Repository eclipse-che/che, pull requests merged in 2018-10, with the labels that each got.

#11392 Fail workspace validation if config contains both ws.next plugins and installers
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceValidator.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceValidatorTest.java
Labels: kind/task, status/code-review

#11409 CHE-11408: Disable probes of Che master when debug is enabled
  deploy/openshift/deploy_che.sh
Labels: kind/enhancement, status/code-review

#11402 Make methods accessible with machine token configurable
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthenticatedResource.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenAccessFilter.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenAccessFilterTest.java
Labels: kind/task, status/code-review

#11404 Include activity tracker extension into default Theia image
  dockerfiles/theia/src/extensions.json
Labels: kind/bug, status/code-review

#11425 Selenium: Correct the method 'checkFindProjectSymbolFeature()' in the 'GolangFileEditingTest'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AssistantFindPanel.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
Labels: kind/task, status/code-review, team/che-qe

#11422 Make Che Server depending on plugin broker image tag instead of latest
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: status/code-review

#11366 Login to oc right after init
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/OpenShiftKeycloakCliCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/OpenShiftCliCommandExecutor.java
Labels: status/code-review

#11427 Rework ConvertToProjectWithPomFileTest test for checking conversion folders to maven multimodule project
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestProjectServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/project/ProjectTemplates.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ConvertToMavenProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ConvertToProjectWithPomFileTest.java
  selenium/che-selenium-test/src/test/resources/projects/java-multimodule/my-webapp/pom.xml
  selenium/che-selenium-test/src/test/resources/projects/simple_Artik_project/test.c
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/project/undefined.json
Labels: kind/task, status/code-review

#11439 Fix regex in PullRequestPluginTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11441 Selenium: Change the timeout in the 'openItemByPath()' from the 'ProjectExplorer'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
Labels: kind/task, status/code-review, team/che-qe

#11432 Fixed `exec`, `terminal` sidecars
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/WorkspaceServiceAccount.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/MachineNameProvisioner.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactoryTest.java
Labels: kind/bug, status/code-review

#11430 Add custom timeout for AbstractTestWorkspaceServiceClient#waitStatus.
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/AbstractTestWorkspaceServiceClient.java
Labels: kind/enhancement, status/code-review

#11448 Adapt "open declaration" tests to behaviour of LSP editors
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0087Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0091Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0093Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0097Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0114Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0115Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0119Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0120Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0121Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0122Test.java
Labels: selenium/failure, target/branch, team/languages

#11410 Make Theia sidecar/stack secure, add an ability to use new JWT auth on a per-workspace basis
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/restartpolicy/RestartPolicyRewriter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/server/ServersConverter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/SecureServerExposerFactoryProvider.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/restartpolicy/RestartPolicyRewriterTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/SecureServerExposerFactoryProviderTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/InternalRuntime.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/InternalRuntimeTest.java
Labels: kind/enhancement, status/code-review

#11413 Set k8s memory request wherever we set limit
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/RamLimitRequestProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Containers.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelperTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/RamLimitRequestProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/ContainersTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolverTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
Labels: kind/task, status/code-review

#11464 Selenium: not check that CHE_MACHINE_NAME variable exists in 'Environment variables' tab
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java
Labels: kind/task, status/code-review, team/che-qe

#11446 Don't stop workspace recovery when error is encountered
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
Labels: kind/bug, status/code-review

#11477 introduce RC version for pre-release testing
  dockerfiles/base/scripts/base/commands/cmd_offline.sh
  dockerfiles/base/scripts/base/startup_03_pre_networking.sh
  dockerfiles/cli/version/6.12.0/images-bootstrap
  dockerfiles/cli/version/6.12.0/images-utilities
  dockerfiles/cli/version/latest/images-bootstrap
  dockerfiles/cli/version/latest/images-utilities
  dockerfiles/cli/version/nightly/images-bootstrap
  dockerfiles/cli/version/nightly/images-utilities
  dockerfiles/cli/version/rc/images
  dockerfiles/cli/version/rc/images-bootstrap
  dockerfiles/cli/version/rc/images-stacks
  dockerfiles/cli/version/rc/images-utilities
  dockerfiles/dev/Dockerfile
Labels: status/code-review, team/che-sd

#11480 fix pg version in rc
  dockerfiles/cli/version/rc/images
Labels: kind/bug, status/code-review

#11301 CHE-10883 migrate from bower to yarn
  dashboard/.bowerrc
  dashboard/Dockerfile
  dashboard/README.md
  dashboard/bower.json
  dashboard/gulp/build.js
  dashboard/gulp/conf.js
  dashboard/gulp/inject.js
  dashboard/gulp/material-design-svgfont.js
  dashboard/gulp/scripts.js
  dashboard/gulp/server.js
  dashboard/gulp/styles.js
  dashboard/gulp/unit-tests.js
  dashboard/gulp/watch.js
  dashboard/karma.conf.js
  dashboard/package.json
  dashboard/pom.xml
  dashboard/src/app/index.module.ts
  dashboard/src/app/index.styl
  dashboard/src/app/stacks/list-stacks/build-stack/recipe-editor/recipe-editor.html
  dashboard/src/app/teams/list/list-teams.controller.ts
  dashboard/src/app/workspaces/workspace-details/environments/environments.html
  dashboard/src/app/workspaces/workspace-details/export-workspace/dialog/export-tab-dialog.html
  dashboard/src/app/workspaces/workspace-details/select-stack/recipe-authoring/workspace-recipe-authoring.html
  dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts
  dashboard/src/components/attribute/attribute-config.ts
  dashboard/src/components/attribute/codemirror/codemirror.directive.ts
  dashboard/src/components/codemirror/codemirror.ts
  dashboard/src/components/components-config.ts
  dashboard/src/components/widget/codemirror/codemirror.styl
  dashboard/src/components/widget/editor/che-editor.controller.ts
  dashboard/src/index.html
  dashboard/src/index.ts
  dashboard/tsconfig.json
  dashboard/yarn.lock
Labels: kind/task, status/code-review

#11313 [root pom] support overriding the version of dashboard
  pom.xml
Labels: status/code-review

#11494 fix dashboard version
  pom.xml
Labels: kind/bug, status/code-review

#11489 Remove outdated actions
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/FactoryExtension.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/FactoryGinModule.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/json/ImportFromConfigAction.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/json/ImportFromConfigPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/json/ImportFromConfigView.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/json/ImportFromConfigViewImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/json/ImportFromConfigViewImpl.ui.xml
Labels: status/code-review

#11498 [Selenium] Fix unexpected fail of "MacrosCommandsEditorTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/MacrosCommandsEditorTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11492 Upgrade the version of jQuery to 3.3.1
  dashboard/package.json
  dashboard/yarn.lock
Labels: status/code-review

#11465 Sidecar container naming using plugin_name + che_container_name
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolverBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingValidator.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/ListenBrokerEvents.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerStatusListener.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolverTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerStatusListenerTest.java
Labels: kind/enhancement, status/code-review

#11456 Limit pool size used to process Json/rpc requests
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/ServerSideRequestProcessor.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/util/ProjectApiUtils.java
  wsagent/che-wsagent-core/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties
Labels: kind/bug, status/code-review

#11518 [Selenium] Get rid of "StaleElementReferenceException" in the "TheiaEditor#getEditorText()" method
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaEditor.java
Labels: kind/bug, status/code-review, team/che-qe

#11523 [Selenium] Fix unexpected fail of "TheiaBuildPluginTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaTerminal.java
Labels: kind/bug, status/code-review, team/che-qe

#11519 [dockerfile] Multi staged build of Theia image
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
  dockerfiles/theia/e2e/src/docker-run.sh
  dockerfiles/theia/src/builder/add-extensions.sh
  dockerfiles/theia/src/builder/assemble-theia.sh
  dockerfiles/theia/src/builder/build-and-publish-theia.sh
  dockerfiles/theia/src/builder/check-github-limit.sh
  dockerfiles/theia/src/builder/setup-nodejs.sh
  dockerfiles/theia/src/config.yaml
  dockerfiles/theia/src/entrypoint.sh
  dockerfiles/theia/src/setup.sh
  dockerfiles/theia/supervisord.conf
Labels: kind/enhancement

#11534 Adapt the "TransitiveDependencyTest" selenium test for changes from "5730_java_ls_poc" branch
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/TransitiveDependencyTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11561 Selenium: quick fix for selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/assistant/CheckFindActionFeatureInCheTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/GenerateEffectivePomTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCeylonWithJavaStackTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/mavenplugin/war-module
Labels: kind/bug, status/code-review, team/che-qe

#11532 Fix webpack config
  dashboard/gulp/scripts.js
Labels: kind/bug

#11550 Fix NPE when no signature help is available
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/signature/SignatureInfoImpl.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#11485 Enhanced error logging in WsAgentURLProvider
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/WsAgentURLProvider.java
Labels: status/code-review

#11483 Fix for rename file operation when using Camel LS
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/RenameItemAction.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/rename/RenamePresenter.java
Labels: kind/bug, status/code-review

#11517 Fix stacks ci tests, allow wait for multiple jdltls resolve msg
  assembly/assembly-wsmaster-war/src/main/resources/che-in-che.json
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Consoles.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromAndroidStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCentosWildFlySwarmStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCeylonWithJavaStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromEclipseCheStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromEclipseVertxStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaCentosStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromSpringBootStackTest.java
Labels: kind/bug, selenium/failure, status/code-review, target/branch, team/languages

#11573 [dockerfile] Update che-theia image
  dockerfiles/theia/Dockerfile
Labels: kind/enhancement, status/code-review

#11567 Remove obsolete 'Welcome' page from preferences
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/FactoryGinModule.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/welcome/preferences/ShowWelcomePreferencePagePresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/welcome/preferences/ShowWelcomePreferencePageView.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/welcome/preferences/ShowWelcomePreferencePageViewImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/welcome/preferences/ShowWelcomePreferencePageViewImpl.ui.xml
Labels: kind/bug, status/code-review

#11566 Fix duplicating the processes in the Commands toolbar
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/command/exec/AbstractExecAgentEventHandler.java
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/command/exec/ExecAgentEventManager.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/execute/JsonRpcExecAgentCommandManager.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/execute/JsonRpcExecAgentEventManager.java
Labels: kind/bug, status/code-review

#11577 Selenium: update expected stacks lists in 'NewWorkspacesPageTest' test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
Labels: kind/task, status/code-review, team/che-qe

#11580 Added exec plugin to Che 7 stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#11542 Store logs of test workspaces created by E2E tests from Dashboard
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestWorkspace.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestWorkspaceProvider.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/CreateWorkspaceHelper.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromZipTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromAndroidStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromBlankStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCamelStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCentosBlankStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCentosGoStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCentosNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCentosWildFlySwarmStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCeylonWithJavaStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCppStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromEclipseCheStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromEclipseVertxStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromGoStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaCentosStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaMySqlCentosStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaDockerStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaOpenshiftStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromKotlinStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromNETStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromPHPStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromPythonStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromRailsStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromSpringBootStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/ImportAndValidateEclipseCheProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithAndroidStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithBlankStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithCppStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNetStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPHPStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPythonStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithRailsStackTest.java
Labels: kind/task, status/code-review, team/che-qe

#11090 Provide better compatibility with alternate OIDC providers
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/keycloak/OIDCKeycloak.js
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/keycloak/oidcCallback.js
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/keycloak/oidcCallbackDashboard.html
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/keycloak/oidcCallbackIde.html
  dashboard/src/app/index.module.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/import-github-project/import-github-project.controller.ts
  dashboard/src/components/api/che-keycloak.factory.ts
  dashboard/src/components/interceptor/keycloak-token-interceptor.ts
  dockerfiles/init/manifests/che.env
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/IDE.html
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.js
  multiuser/keycloak/che-multiuser-keycloak-ide/src/main/java/org/eclipse/che/multiuser/keycloak/ide/Keycloak.java
  multiuser/keycloak/che-multiuser-keycloak-ide/src/main/java/org/eclipse/che/multiuser/keycloak/ide/KeycloakProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakConfigurationService.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakHttpJsonRequestFactory.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakProfileRetriever.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettings.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakUserManager.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/dao/KeycloakProfileDao.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakServletModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-shared/src/main/java/org/eclipse/che/multiuser/keycloak/shared/KeycloakConstants.java
  workspace-loader/src/index.ts
Labels: kind/question, kind/task, status/code-review

#11565 [Selenium] Fix unexpected fail of "AutocompleteFeaturesInEditorTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FileStructure.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
Labels: kind/bug, status/code-review, team/che-qe

#11575 Split editors and plugins, and disable installers, when any plugin is selected
  dashboard/src/app/index.styl
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.html
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.directive.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.html
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.styl
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.html
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.styl
Labels: kind/bug, status/code-review

#11576 CHE-10945: Fix terminal font for some systems.
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/terminal/options/TerminalOptionsJso.java
Labels: kind/bug, status/code-review

#11579 Fix importing a project from Git VCS with a branch that contains slash symbol
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java
  wsagent/che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConnection.java
Labels: kind/bug, status/code-review

#11590 Selenium: Change the 'GitStatusBar' to avoid unexpected 'stale element exception'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/Git.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitStatusBar.java
Labels: kind/task, status/code-review, team/che-qe

#11597 Selenium: quick fix for selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/EditMachineForm.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindUsagesBaseOperationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ResolveDependencyAfterRecreateProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/task, status/code-review, team/che-qe

#11595 [Selenium] Adapt the "TheiaBuildPluginTest" selenium test to changes in the top menu
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProposalForm.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaTerminal.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11599 Selenium: Correct the method 'waitAndSelectItemByName()' in the 'ProjectExplorer'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
Labels: kind/task, status/code-review, team/che-qe

#11602 Add cause information in LoggedRunnable error
  core/commons/che-core-commons-schedule/src/main/java/org/eclipse/che/commons/schedule/executor/LoggedRunnable.java
Labels: kind/enhancement, status/code-review

#11588 Add an ability to use a custom registry for WS.NEXT plugins
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/PluginMetaRetriever.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginFQN.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/wsplugins/ChePluginMetaRetrieverTest.java
Labels: kind/task, status/code-review

#11585 Improve and clean up factory validation exception messages
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryConstants.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/builder/FactoryBuilder.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/builder/FactoryBuilderTest.java
Labels: kind/bug, status/code-review

#11607 [Selenium] Adapt the "TheiaBuildPluginTest" selenium test to the new terminal tab titles
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11610 Selenium: fix unstable selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Consoles.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FileStructure.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/EditMachineForm.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11611 Create a parent /node_modules folder and add setting for yarn to use that parent folder
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/src/docker-run.sh
Labels: status/code-review

#11608 Add an index in thread names
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/ServerSideRequestProcessor.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/watcher/server/impl/FileWatcherService.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/InternalRuntimeTest.java
Labels: kind/enhancement, status/code-review

#11515 Reworked LanguageServerFileWatcher
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerAbstractFileWatcher.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerConfig.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerCreateFileWatcher.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerDeleteFileWatcher.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerFileWatcher.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerModule.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerUpdateFileWatcher.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/RegistryContainer.java
  wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/LanguageServerAbstractFileWatcherTest.java
  wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/LanguageServerFileWatcherTest.java
Labels: status/code-review

#11617 Add an ability to disable discover-ability of a plugin endpoint
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarServicesProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarServicesProvisionerTest.java
Labels: kind/enhancement, status/code-review

#11596 Add workspaceEnv to plugin, populate it on sidecar resolving
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/BrokersResult.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/KubernetesBrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/ListenBrokerEvents.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/WaitBrokerResult.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerStatusListener.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/BrokersResultTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBrokerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerStatusListenerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/wsplugins/brokerphases/OpenshiftBrokerEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginBase.java
Labels: kind/enhancement, status/code-review

#11619 Fix build (invalid stubbing)
  wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/LanguageServerAbstractFileWatcherTest.java
Labels: kind/bug, status/code-review

#11612 Selenium: wait that IDE is ready to use before open project
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/RenamePrivateFieldSmokeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameMethodInInterfaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenamePrivateMethodTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameStaticMethodsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameVirtualMethodsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/CodeAssistAfterMoveItemTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveJavaClassToSubpackageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveJavaFileInNewSourceFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageSmokeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageSpringTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/preview/CheckTreeInRefactorPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/preview/PreviewRefactoringTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/GenericsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/IllegalTypeNameTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestAnnotationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestEnumerationsTest.java
Labels: kind/task, status/code-review, team/che-qe

#11626 Selenuim: execute selenium tests from 'dashboard' package on openshift prod-preview
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/StacksListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheProdPreviewSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#11628 [Selenium] Add catching of the known bug (#11624) to the "TheiaBuildPluginTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaTerminal.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/task, status/code-review, team/che-qe

#11623 Add workspace name and namespace as environment variable
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceNameEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceNamespaceNameEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceNameEnvVarProviderTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceNamespaceEnvVarProviderTest.java
Labels: kind/enhancement, status/code-review

#11633 [docker] Update che theia image
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
Labels: status/code-review

#11613 Cleanup code after removing test LangServer
  agents/pom.xml
  agents/test-ls/pom.xml
  agents/test-ls/src/main/resources/installers/1.0.0/org.eclipse.che.test.ls.json
  agents/test-ls/src/main/resources/installers/1.0.0/org.eclipse.che.test.ls.script.sh
  assembly/assembly-wsagent-war/pom.xml
  assembly/assembly-wsmaster-war/pom.xml
  plugins/plugin-languageserver/che-plugin-test-ls/pom.xml
  plugins/plugin-languageserver/che-plugin-test-ls/src/main/java/org/eclipse/che/plugin/test/ls/inject/TestLSModule.java
  plugins/plugin-languageserver/che-plugin-test-ls/src/main/java/org/eclipse/che/plugin/test/ls/languageserver/TestLanguageServerConfig.java
  plugins/plugin-languageserver/pom.xml
  pom.xml
Labels: status/code-review

#11524 Display notification with proposition to restart ws agent
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/StartWsAgentNotification.java
Labels: kind/bug, status/code-review

#11594 Fixed case when Find References feature displays incorrect line positions
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/location/OpenLocationViewImpl.java
Labels: kind/bug, status/code-review

#11641 [dockerfile] Update che theia image
  dockerfiles/theia/Dockerfile
Labels: status/code-review

#11646 [Selenium] Update launch command in 'TheiaBuildPluginTest' according to changes in #11633
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11656 Change Theia broker image to one hosted in wsskeleton repo
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#11510 Fix of FileWatcherByPathMatcher to properly watch existing files.
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/watcher/server/impl/FileWatcherByPathMatcher.java
  wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/watcher/server/impl/FileWatcherByPathMatcherTest.java
Labels: kind/bug, status/code-review

#11671 [dockerfile] [theia] Fix git
  dockerfiles/theia/Dockerfile
Labels: kind/bug, status/code-review

#11669 Selenium: Delete the 'try-catch' from the test method in the 'GolangFileEditingTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
Labels: kind/task, status/code-review, team/che-qe

#11652 Selenium: Add the 'try-catch' to the 'GitPullTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
Labels: kind/task, status/code-review, team/che-qe

#11658 Prevent exception in case Preview URL not set
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/toolbar/previews/PreviewsPresenter.java
Labels: kind/bug, status/code-review, team/ide

#11022 [WIP]Fix timeunit: set to seconds. Add checking after add to index
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Menu.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesByMultiSelectTest.java
Labels: kind/bug, status/code-review

#11674 Selenium: adapt selenium tests after merging JDT.LS branch in master
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Consoles.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FileStructure.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/EditMachineForm.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureCodeEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ImplementationBaseOperationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCentosWildFlySwarmStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromEclipseVertxStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromSpringBootStackTest.java
Labels: kind/task, status/code-review, team/che-qe

#11678 adds pluginrepo for snapshots, sort poms
  dashboard/pom.xml
  pom.xml
Labels: kind/enhancement, status/code-review

#11673 [Selenium] Rework selenium tests in the "preferences", "autocomplete", "projectexplorer", "dependencies", "editor" packages for adopting to branch changes
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/FileUtil.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FileStructure.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/CheckErrorsWarningsTabTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/TransitiveDependencyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/preferences/embed-code
Labels: kind/bug, status/code-review, team/che-qe

#11680 Selenium: remove info about known #10698 issue
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/TypeScriptEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/php/PhpAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/python/PythonAssistantFeaturesTest.java
Labels: kind/task, status/code-review, team/che-qe

#11687 Che-theia: Temporary using extension branch for che-theia-factory-ext…
  dockerfiles/theia/src/extensions.json
Labels: kind/task, status/code-review, team/ide2

#11651 Add missing java support in Camel stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#11672 Fix improperly editor behavior when in debug mode
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/debug/BreakpointManagerImpl.java
Labels: kind/bug, status/code-review

#11695 Update the theia yeoman generator to the latest version
  dockerfiles/theia/Dockerfile
Labels: kind/enhancement, status/code-review

#11661 Add Theia stack for Kubernetes
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#11700 [Selenium] Fix unexpected fail of "TheiaBuildPluginTest", "AutocompleteFeaturesInEditorTest", "DeletePackageWithOpenedFilesTabTest", "ContextMenuEditorTest", "JavaDocPopupTest" selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteFeaturesInEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/JavaDocPopupTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeletePackageWithOpenedFilesTabTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11708 Selenium: quick fix for selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Refactor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameVirtualMethodsTest.java
  selenium/che-selenium-test/src/test/resources/conf/selenium.properties
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#11702 Use keyclock token in case MultiUser assembly for SSH Key Uploading
  wsagent/che-core-ssh-key-ide/src/main/java/org/eclipse/che/plugin/ssh/key/client/upload/UploadSshKeyPresenter.java
Labels: kind/bug, status/code-review

#11715 Selenium: Adapt selenium tests after merging JDT.LS branch in master
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/RunPlainJavaProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/CodeAssistAfterMoveItemTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveItemsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageTest.java
Labels: kind/task, status/code-review, team/che-qe

#11647 Correct initialize orion hover provider
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionHoverRegistrant.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionServiceRegistrationOverlay.java
Labels: kind/bug, severity/P1, status/code-review, team/ide

#11724 Selenium: quick fix for CheckStoppingWsByTimeoutTest test
  selenium/che-selenium-test/src/test/resources/conf/selenium.properties
Labels: status/code-review, team/che-qe

#11723 [Selenium] Fix unexpected fails of "CheckBasicFunctionalityInCommandsExplorerTest", "CheckOnValidAndInvalidPackageNameTest" and "CheckShowHideHiddenFilesTest" selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsExplorer.java
Labels: kind/bug, status/code-review, team/che-qe

#11711 Selenium: cover creation stacks from recipe by selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/BuildStackFromRecipe.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/stacks/StackDetails.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/stacks/Stacks.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateStackTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#11696 Fix of signature help feature when typing '(' symbol
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/signature/LanguageServerSignatureHelp.java
Labels: kind/bug, status/code-review

#11726 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#11736 [Selenium] Fix unexpected fails of "TheiaBuildPluginTest", "JavaDocPopupTest", "CheckAutocompleteFeaturesInTheTestFolderTest", "ContextMenuEditorTest" selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/CheckAutocompleteFeaturesInTheTestFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/JavaDocPopupTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11698 Display notification with error instead of dialog window
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/ProjectWizard.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardPresenter.java
  ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
  ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projecttype/wizard/ProjectWizardTest.java
Labels: kind/bug, status/code-review

#11691 Switch update project to Json-rpc
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/project/ProjectServiceClient.java
  wsagent/che-core-api-project-shared/src/main/java/org/eclipse/che/api/project/shared/dto/service/UpdateRequestDto.java
Labels: kind/bug

#11737 Selenium: Change the 'waitNode()' method in the 'AssistantFindPanel'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AssistantFindPanel.java
Labels: kind/task, status/code-review, team/che-qe

#11748 [docker] [theia] Factory Extension has been removed in image, fix the test
  dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
Labels: kind/bug, status/code-review

#11405 CHE-9720: Checkout ssh-extension to tag with extension
  dockerfiles/theia/src/extensions.json
Labels: status/code-review

#11751 [Selenium] Fix of unexpected fails of "AutocompleteProposalJavaDocTest", "ShowHintsCommandTest", "DownloadProjectTest", "CheckRestoringSplitEditorTest" selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/ShowHintsCommandTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DownloadProjectTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11752 Send URI instead of path to ls on didChangeWatchedFiles
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerAbstractFileWatcher.java
Labels: kind/bug, status/code-review

#11738 Use styled dialog instead of browser pop-up for goto line in compare widget
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/CompareViewImpl.java
  plugins/plugin-orion/che-plugin-orion-compare/pom.xml
  plugins/plugin-orion/che-plugin-orion-compare/src/main/java/org/eclipse/che/ide/orion/compare/CompareInitializer.java
Labels: kind/bug, status/code-review

#11755 Selenium: Add the 'try-catch' to the 'RenamePackageTest' according to the known issue #11754
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageTest.java
Labels: kind/task, status/code-review, team/che-qe

#11753 [dockerfile] [cli] Fix title in cli backup command to not see codenvy
  dockerfiles/base/scripts/base/commands/cmd_backup.sh
  dockerfiles/cli/tests/cmd_backup_restore_tests.bats
Labels: kind/bug, kind/enhancement, status/code-review

#11762 [Selenium] Remove try/catch block with known #11660 issue from "TransitiveDependencyTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/TransitiveDependencyTest.java
Labels: status/code-review

#11767 Selenium: add info about known #11735 issue to JavaDocPopupTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/JavaDocPopupTest.java
Labels: kind/task, status/code-review, team/che-qe

#11765 [dockerfile] Update to latest tag of Theia + cleanup 1GiB in image
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
  dockerfiles/theia/src/.yarnclean
  dockerfiles/theia/src/builder/production-mode.sh
  dockerfiles/theia/src/cleanup-exact
  dockerfiles/theia/src/cleanup-find
  dockerfiles/theia/src/cleanup.sh
  dockerfiles/theia/src/entrypoint.sh
  dockerfiles/theia/src/package.json
Labels: status/code-review

#11766 Selenium: Add changes to the 'RenameParametersTest' to incease reliability
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/parameters/RenameParametersTest.java
Labels: kind/task, status/code-review, team/che-qe

#11776 Selenium: update info about known issues
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ChangeVariableWithEvaluatingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/InnerClassAndLambdaDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/NodeJsDebugTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/StepIntoStepOverStepReturnWithChangeVariableTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteWithInheritTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/QuickFixAndCodeAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithMultiModuleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerClickCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerUserCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromUiWithKeepDirTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/filewatcher/RemoveFilesWithActiveTabs.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/RenameProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/RenamePrivateFieldTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameVirtualMethodsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginJunit4CheckRunSuitesAndScopesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginJunit4Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginTestNgTest.java
Labels: kind/task, status/code-review, team/che-qe

#11758 Selenium: Delete the 'try-catch' from the 'ImportAndValidateEclipseCheProjectTest'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/MavenPluginStatusBar.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/ImportAndValidateEclipseCheProjectTest.java
Labels: kind/task, status/code-review, team/che-qe

#11771 Fix 'add a new machine' flow
  dashboard/src/components/api/environment/compose-environment-manager.ts
  dashboard/src/components/api/environment/kubernetes-environment-manager.ts
Labels: kind/bug, status/code-review

#11739 Update Che 7 stack to support kube as well
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#11657 Share volumes between containers for ephemeral workspaces
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/EphemeralWorkspaceAdapter.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/EphemeralWorkspaceAdapterTest.java
Labels: kind/bug, status/code-review

#9343 PostgreSQL debug mode
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
  deploy/openshift/templates/multi/postgres-template.yaml
  dockerfiles/postgres/Dockerfile
  dockerfiles/postgres/init-debug.sh
  dockerfiles/postgres/postgresql.conf.debug
Labels: status/code-review

#11784 CHE-11457: switch github-extension to tag
  dockerfiles/theia/src/extensions.json
Labels: kind/task, status/code-review

#11704 Removing offline tokens support (OSIO specific).
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestAuthServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/provider/TestOfflineToAccessTokenExchangeApiEndpointUrlProvider.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/requestfactory/TestUserHttpJsonRequestFactory.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/user/AdminTestUser.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/user/DefaultTestUser.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/user/TestUser.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/user/TestUserFactory.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/user/TestUserImpl.java
  selenium/che-selenium-test/pom.xml
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumMultiUserModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumOpenShiftModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/CheTestAuthServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/AbstractKeycloakTestAuthServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/KeycloakTestAuthServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/OsioKeycloakTestAuthServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/KeycloakCliClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/CheTestOfflineToAccessTokenExchangeApiEndpointUrlProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheAdminTestUserProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheDefaultTestUserProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheTestUserProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/SingleUserCheDefaultTestUserProvider.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java
Labels: status/code-review
