Repository eclipse-che/che, pull requests merged in 2018-06, with the labels that each got.

#9896 Selenium: delete the 'try/catch' from the 'PullRequestPluginTest' according to close issue #9484
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
Labels: kind/task, status/code-review, team/che-qe

#9892 Selenium: delete the 'try/catch' from the 'TestWorkspaceImpl' according to close issue #9556
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceImpl.java
Labels: kind/task, status/code-review, team/che-qe

#9888 Selenium: cover creation of workspaces from organization details page
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/organization/OrganizationPage.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceTest.java
Labels: kind/task, team/che-qe

#9928 updated URL for the Camel LSP binary
  agents/ls-camel/src/main/resources/installers/1.0.0/org.eclipse.che.ls.camel.script.sh
Labels: kind/enhancement, status/code-review

#9636 Support Rename refactoring
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/resources/Container.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/impl/ContainerImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/impl/ResourceManager.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/pom.xml
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/diagnostics/PomDiagnosticsRequestor.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/RefactoringActionDelegate.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewNode.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/StringStreamEditor.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/JavaRefactoringRename.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/RenameRefactoringAction.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenameView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenameViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/similarnames/SimilarNamesConfigurationPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/similarnames/SimilarNamesConfigurationView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/similarnames/SimilarNamesConfigurationViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/service/JavaLanguageExtensionServiceClient.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewPresenterTest.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/JavaRefactoringRenameTest.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenterTest.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/similarnames/SimilarNamesConfigurationPresenterTest.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/similarnames/SimilarNamesConfigurationViewImplTest.java
  plugins/plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/Constants.java
  plugins/plugin-java/che-plugin-java-server/pom.xml
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLSWrapper.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/quickassist/ApplyWorkspaceEditAction.java
Labels: kind/enhancement, status/code-review, target/branch, team/languages

#9932 Watch connection manager never closed when trying to delete a non-existing POD
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
Labels: kind/bug, status/code-review

#9774 Add an ability to try Workspace.Next features
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  core/commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/StringArrayConverter.java
  deploy/kubernetes/kubectl/Deploy Che.md
  deploy/kubernetes/kubectl/che-kubernetes.yaml
  deploy/kubernetes/kubectl/wsnext/feature-api.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsnext/KubernetesWorkspaceNextApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsnext/KubernetesWorkspaceNextApplierTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalMachineConfig.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/WorkspaceNextApplier.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/WorkspaceNextObjectsRetriever.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheFeature.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheFeatureSpec.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheServiceParameter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheServiceReference.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheServiceSpec.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/Command.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/Container.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/EnvVar.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/ObjectMeta.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/ResourceRequirements.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/Server.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/TypeMeta.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/Volume.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/wsnext/WorkspaceNextObjectsRetrieverTest.java
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
Labels: kind/enhancement, status/code-review

#9947 Fix start of Che assembly on non-k8s infras
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
Labels: kind/bug

#9826 Improve wsmaster OpenIdConnect configurability, and helm deployment s…
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  deploy/kubernetes/helm/che/requirements.yaml
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettings.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-shared/src/main/java/org/eclipse/che/multiuser/keycloak/shared/KeycloakConstants.java
Labels: status/code-review

#9793 Update cached children when external file event is coming
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/impl/ResourceManager.java
Labels: kind/bug, severity/P2, status/in-progress, team/ide

#9926 Removed extra dependency
  ide/che-core-ide-api/pom.xml
Labels: status/code-review

#9933 Added back and reworked LS related tests removed by a mistake
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerFileWatcher.java
  wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/LanguageServerFileWatcherTest.java
Labels: kind/enhancement, status/code-review

#9650 Issue 8721 - Update Libraries, etc. based on JDT notifications #8721
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/project/node/ProjectClasspathChangedEvent.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/tree/library/LibrariesNode.java
  plugins/plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/Constants.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ExecuteClientCommandJsonRpcTransmitter.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageClient.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/LanguageServerExtension.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/inject/LanguageServerGinModule.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/ExecuteClientCommandProcessor.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/ExecuteClientCommandReceiver.java
Labels: kind/enhancement, status/code-review, target/branch, team/languages

#9800 [#8040]: Fix Git credentials by creating ~/.ssh in case it is missing
  agents/git-credentials/src/main/resources/installers/1.0.0/org.eclipse.che.git.script.sh
Labels: kind/bug, status/code-review

#9816 Added an ability to interrupt the start of a Kubernetes/OpenShift runtime
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/ReplicationModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/StartSynchronizer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/StartSynchronizerFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapperFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/event/KubernetesRuntimeStoppedEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/event/KubernetesRuntimeStoppingEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/StartSynchronizerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
  multiuser/api/che-multiuser-api-jgroups/pom.xml
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/WorkspaceStopPropagator.java
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/JGroupsWorkspaceStatusCache.java
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/ReplicatedMapNotificationAdapter.java
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/StatusChangeListener.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/RuntimeIdentityImpl.java
Labels: kind/enhancement, status/code-review

#9665 Remove unnecessary pageobjects. Rename MachineTerminal page object to CheTerminal
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CheTerminal.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Ide.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/machineperspective/CreateMachineWidget.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/machineperspective/MachineInformationTab.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/assistant/KeyBindingsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ChangeVariableWithEvaluatingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/StepIntoStepOverStepReturnWithChangeVariableTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/filewatcher/CheckFileWatcherExcludeFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromPreferencesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitChangeMarkersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitColorsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindTextFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ServerRuntimeInfoTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/TerminalTypingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithSplitPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/FailMoveItemTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkspaceFromOfficialUbuntuImageStartTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithAndroidStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithBlankStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithCppStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNetStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPHPStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPythonStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithRailsStackTest.java
Labels: status/code-review

#9969 Implement selenium test for covering LS server for TypeScript language
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteJSFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PhpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/TypeScriptEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/type-script-simple-project/Greeter.ts
  selenium/che-selenium-test/src/test/resources/projects/type-script-simple-project/testPrint.ts
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/eclipse_nodejs.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_nodejs.json
Labels: kind/task, status/code-review

#9981 Add support of Workspace Next to Openshift infrastructure
  deploy/kubernetes/kubectl/wsnext/feature-api.yaml
  deploy/openshift/Readme.md
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/wsnext/feature-api.yaml
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
Labels: kind/enhancement, status/code-review

#9962 Private registries support
  assembly/assembly-wsmaster-war/pom.xml
  infrastructures/docker/docker-auth/pom.xml
  infrastructures/docker/docker-auth/src/main/java/org/eclipse/che/infrastructure/docker/auth/UserSpecificDockerRegistryCredentialsProvider.java
  infrastructures/docker/docker-auth/src/main/java/org/eclipse/che/infrastructure/docker/auth/dto/AuthConfig.java
  infrastructures/docker/docker-auth/src/main/java/org/eclipse/che/infrastructure/docker/auth/dto/AuthConfigs.java
  infrastructures/docker/docker-auth/src/test/java/org/eclipse/che/infrastructure/docker/auth/UserSpecificDockerRegistryCredentialsProviderTest.java
  infrastructures/docker/docker-client/pom.xml
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerRegistryAuthResolver.java
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerRegistryDynamicAuthResolver.java
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/InitialAuthConfig.java
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/NoOpDockerRegistryDynamicAuthResolverImpl.java
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/params/BuildImageParams.java
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/params/PullParams.java
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/params/PushParams.java
  infrastructures/docker/docker-client/src/test/java/org/eclipse/che/infrastructure/docker/client/DockerConnectorTest.java
  infrastructures/docker/docker-client/src/test/java/org/eclipse/che/infrastructure/docker/client/DockerRegistryAuthResolverTest.java
  infrastructures/docker/docker-client/src/test/java/org/eclipse/che/infrastructure/docker/client/InitialAuthConfigTest.java
  infrastructures/docker/docker-client/src/test/java/org/eclipse/che/infrastructure/docker/client/params/BuildImageParamsTest.java
  infrastructures/docker/docker-client/src/test/java/org/eclipse/che/infrastructure/docker/client/params/PullParamsTest.java
  infrastructures/docker/docker-client/src/test/java/org/eclipse/che/infrastructure/docker/client/params/PushParamsTest.java
  infrastructures/docker/infrastructure/pom.xml
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/ParallelDockerImagesBuilder.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/ParallelDockerImagesBuilderTest.java
  infrastructures/docker/pom.xml
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ImagePullSecretProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ImagePullSecretProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
  pom.xml
Labels: kind/enhancement, status/code-review

#9974 Selenium: Create the 'ContributeTabTest'
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestMenuCommandsConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/PanelSelector.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Preferences.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/PullRequestPanel.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromPreferencesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginWithForkTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/SetGitCommitterTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindTextFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/CheckErrorsWarningsTabTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/ContributeTabTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckDisplayingArtifactIdTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#9985 Clean up opening files list
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorAgentImpl.java
Labels: kind/bug

#9996 Set face name for 'Refresh Contribution Branch Name' button to avoid NPE
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/parts/contribute/ContributePartViewImpl.java
Labels: kind/bug

#9982 Create selenium test user in Eclipse Che on OCP remotely
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/DockerUtil.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/process/ProcessAgent.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceLogsReader.java
  selenium/che-selenium-test/README.md
  selenium/che-selenium-test/pom.xml
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumDockerModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumMultiUserModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumOpenshiftModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/KeycloakAdminConsoleClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/KeycloakSettings.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/KeycloakTestAuthServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/KeycloakToken.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/KeycloakTokenContainer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/TestKeycloakSettingsServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/executor/DockerKeycloakCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/executor/KeycloakCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/executor/OpenShiftKeycloakCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/OpenShiftWebConsoleUrlProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheAdminTestUserProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheDefaultTestUserProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheTestUserProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/CheMultiuserAdminDashboard.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/Dashboard.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakFederatedIdentitiesPage.java
Labels: kind/task, status/code-review

#9875 Selenium: cover Clangd LS functionality by selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Wizard.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ClangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PhpFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/console-cpp-simple/hello.cc
  selenium/che-selenium-test/src/test/resources/projects/console-cpp-simple/hello.cpp
  selenium/che-selenium-test/src/test/resources/projects/console-cpp-simple/iseven.cpp
  selenium/che-selenium-test/src/test/resources/projects/console-cpp-simple/iseven.h
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/eclipse_cpp_gcc.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_cpp_gcc.json
Labels: kind/task, status/code-review, team/che-qe

#9988 Add ability to see and copy commit id value from git history dialog
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/AlteredFiles.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/changespanel/ChangesPanelViewImpl.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/changespanel/ChangesPanelViewImpl.ui.xml
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/selectablechangespanel/SelectableChangesPanelViewImpl.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/history/HistoryPresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.properties
Labels: kind/enhancement, status/code-review, team/ide

#10006 Selenium: cover #8674 issue in selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
Labels: kind/task, status/code-review, team/che-qe

#10015 Don't trim stack trace and capture skipped selenium test results
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-test/pom.xml
Labels: status/code-review, team/che-qe

#10017 Selenium: wait until 'Workspace is Created' dialog is fully rendered before creating workspace
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
Labels: kind/bug, status/code-review, team/che-qe

#10016 Selenium: Add the 'Assert.fail()' in the 'ImportWizardFormTest according to the known issue #10012
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
Labels: kind/task, status/code-review, team/che-qe

#9993 [WIP] Do not initialize Contribution Workflow when process of initialization has started
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/ContributionMixinProvider.java
Labels: kind/bug, status/code-review

#9954 Fire ProjectCreatedEvent on importProject
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
Labels: kind/bug, status/code-review

#10023 Fix comment to comply build requirements
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
Labels: kind/bug, status/code-review

#10022 Add option not to start test workspaces after creation
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/InjectTestWorkspace.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceImpl.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceInjector.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceProvider.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceProviderImpl.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/gwt/CheckSimpleGwtAppTest.java
Labels: kind/task, status/code-review, team/che-qe

#10025 add cli bugfix versions
  dockerfiles/cli/version/6.5.2/images
  dockerfiles/cli/version/6.5.2/images-stacks
  dockerfiles/cli/version/6.5.3/images
  dockerfiles/cli/version/6.5.3/images-stacks
  dockerfiles/cli/version/6.6.1/images
  dockerfiles/cli/version/6.6.1/images-stacks
  dockerfiles/cli/version/latest.ver
Labels: kind/bug, status/code-review

#10005 Delete only child projects from project config registry at removing project
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/InmemoryProjectRegistry.java
Labels: kind/bug

#9915 CHE-9563 fix switcher bug for UD
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.controller.ts
Labels: kind/bug, status/code-review

#10010 rh-che #703: Adding support of 'Impersonate-*' headers processing in OpenShift infrastructure
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
Labels: kind/enhancement, status/code-review

#9994 CHE-6840 Fix bug when closing editor by mouse middle key
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.java
Labels: kind/bug, status/code-review

#10003 Increase remove node-loader handler timeout
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/TreeResourceRevealer.java
Labels: kind/bug, status/code-review

#10042 Selenium: fix workspace template for C++ stack
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/eclipse_cpp_gcc.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_cpp_gcc.json
Labels: kind/bug, status/code-review, team/che-qe

#10033 Extract OpenShiftCliCommandExecutor in selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/executor/CommandExecutor.java
  selenium/che-selenium-test/README.md
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumDockerModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumOpenshiftModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/DockerKeycloakCliCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/KeycloakCliClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/KeycloakCliCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/OpenShiftKeycloakCliCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/DockerCliCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/OpenShiftCliCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/OpenShiftWebConsoleUrlProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheAdminTestUserProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheDefaultTestUserProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheTestUserProvider.java
Labels: kind/task, status/code-review, team/che-qe

#10057 Selenium: cover workspace creation from Python stack by selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromPythonStackTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#10029 CHE-8164: Fix error when creating project from archetype
  plugins/plugin-maven/che-plugin-maven-generator-archetype/pom.xml
  plugins/plugin-maven/che-plugin-maven-generator-archetype/src/main/java/org/eclipse/che/plugin/maven/generator/archetype/ArchetypeGenerator.java
  plugins/plugin-maven/che-plugin-maven-generator-archetype/src/test/java/org/eclipse/che/plugin/maven/generator/archetype/ArchetypeGeneratorTest.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/projecttype/handler/ArchetypeGenerationStrategy.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckGeneratingMavenArchetypeTest.java
Labels: kind/bug, status/code-review

#10069 Selenium: Correct the closing 'Preferences' form in the 'AfterMethod' of 'ContributeTabTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/ContributeTabTest.java
Labels: kind/task, status/code-review, team/che-qe

#10073 Fix image-che-flag
  deploy/openshift/ocp.sh
Labels: kind/bug, status/code-review

#9960 Optimize the list of stacks
  assembly/assembly-wsmaster-war/src/main/resources/che-in-che.json
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  ide/che-core-ide-templates/src/main/resources/samples.json
Labels: kind/task, status/code-review

#10104 Selenium: fix StacksListTest selenium test according to stacks list changes
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/StacksListTest.java
Labels: kind/task, status/code-review, team/che-qe

#10091 Implement test for covering rollout update CHE with Recreate strategy
  selenium/che-selenium-test/pom.xml
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/CheTestSystemClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/RecreateUpdateStrategyTest.java
Labels: kind/task, status/code-review

#10108 Add one condition check to 'AfterMethod' in the 'ContributeTabTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/ContributeTabTest.java
Labels: kind/task, status/code-review, team/che-qe

#10102 Lang servers
  agents/ls-csharp/src/main/resources/installers/1.0.1/org.eclipse.che.ls.csharp.script.sh
  plugins/plugin-web/che-plugin-web-ext-server/src/main/java/org/eclipse/che/plugin/web/typescript/TypeScriptLanguageServerConfig.java
Labels: status/code-review

#9976 Track workspace Pods starting for failures
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Constants.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPodsTest.java
Labels: kind/bug, status/code-review

#9997 Selenium: Revise and update "Dashboard" selenium tests in "Workspaces" section ("Workspace List" and "New Workspace" pages).
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/AddOrImportForm.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/CheMultiuserAdminDashboard.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/Dashboard.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/DocumentationPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/ProjectOptions.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceConfig.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromZipTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsComposeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsSingleMachineTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromPythonStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithNodeWsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithAndroidStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithBlankStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithCppStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNetStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPHPStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPythonStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithRailsStackTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/dashboard/expectedWorkspaceConfTemplate.txt
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#10080 Show warning dialog after refactoring operation if something isn't valid
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/JavaRefactoringRename.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/service/JavaLanguageExtensionServiceClient.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameStaticMethodsTest.java
Labels: status/code-review, target/branch, team/languages

#10114 Setup OCP to create objects under the certain user account
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
  deploy/openshift/templates/multi/oauth-client.yaml
Labels: kind/task, status/code-review

#10060 Fix for formatting for python language servers
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/LanguageServerFormatter.java
Labels: kind/bug, status/code-review

#10116 Make theia Docker image be able to use yarn cache on Openshift
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/src/add-extensions.js
Labels: kind/bug, status/code-review

#10028 Simple Java project is not recognized #9526
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#9983 Handle project updated notifications from jdt.ls
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/action/ReimportMavenDependenciesAction.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/ExecuteClientCommandProcessor.java
Labels: kind/task, status/code-review, target/branch, team/languages

#10134 Update style for the save mark in editor tab for FireFox
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.ui.xml
Labels: kind/bug, severity/P2, status/code-review, team/ide

#10096 Basic support of the Eclipse Ceylon language
  assembly/assembly-wsagent-war/pom.xml
  ide/che-ide-full/pom.xml
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/pom.xml
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/java/org/eclipse/che/plugin/ceylon/ide/CeylonExtension.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/java/org/eclipse/che/plugin/ceylon/ide/CeylonLanguageDescriptionProvider.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/java/org/eclipse/che/plugin/ceylon/ide/CeylonLocalizationConstant.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/java/org/eclipse/che/plugin/ceylon/ide/CeylonResources.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/java/org/eclipse/che/plugin/ceylon/ide/action/CreateCeylonFileAction.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/java/org/eclipse/che/plugin/ceylon/ide/inject/CeylonGinModule.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/java/org/eclipse/che/plugin/ceylon/ide/project/CeylonProjectWizardRegistrar.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/module.gwt.xml
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/resources/org/eclipse/che/plugin/ceylon/ide/json/highlighting.json
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/resources/org/eclipse/che/plugin/ceylon/ide/svg/ceylon.svg
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/pom.xml
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/java/org/eclipse/che/plugin/ceylon/inject/CeylonModule.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/java/org/eclipse/che/plugin/ceylon/projecttype/CeylonProjectType.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/java/org/eclipse/che/plugin/ceylon/projecttype/CreateCeylonProjectHandler.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/resources/project/.ceylon/bootstrap/ceylon-bootstrap.properties
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/resources/project/.ceylon/config
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/resources/project/.ceylon/ide-config
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/resources/project/ceylonb
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/resources/project/ceylonb.bat
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/resources/project/source/run.ceylon
  plugins/plugin-ceylon/che-plugin-ceylon-lang-shared/pom.xml
  plugins/plugin-ceylon/che-plugin-ceylon-lang-shared/src/main/java/org/eclipse/che/plugin/ceylon/shared/Constants.java
  plugins/plugin-ceylon/pom.xml
  plugins/pom.xml
  pom.xml
Labels: status/code-review

#10146 Fix start of workspaces of Eclipse Che Singleuser on OCP
  deploy/openshift/deploy_che.sh
Labels: kind/bug, status/code-review

#10147 Selenium: move WorkingWithJavaMySqlStackTest and WorkingWithNodeWsTest selenium tests to stack package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/WorkingWithJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/WorkingWithNodeWsTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#10145 Selenium: cover workspace creation from Blank stack by selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromBlankStackTest.java
Labels: kind/task, status/code-review, team/che-qe

#10149 Selenium: cover Python language server format feature by selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/project/ProjectTemplates.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PythonFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/console-python3-simple/calc.py
  selenium/che-selenium-test/src/test/resources/projects/console-python3-simple/main.py
  selenium/che-selenium-test/src/test/resources/projects/console-python3-simple/module.py
  selenium/che-selenium-test/src/test/resources/projects/console-python3-simple/towers.py
  selenium/che-selenium-test/src/test/resources/templates/project/python.json
Labels: kind/task, status/code-review, team/che-qe

#10157 Selenium: set the GitHub username to lowercase when compared to the value 'Federated Identity'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromPreferencesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
Labels: kind/task, status/code-review, team/che-qe

#10153 Use location instead of Eclipse workspace path for classpath
  agents/ls-java/src/main/resources/installers/1.0.1/org.eclipse.che.ls.java.script.sh
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/pom.xml
  plugins/plugin-java/che-plugin-java-ext-lang-server/pom.xml
  plugins/plugin-java/che-plugin-java-ext-lang-shared/pom.xml
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/ConfigureClasspathBaseTest.java
Labels: kind/bug, status/code-review, target/branch

#10155 che #9946: Better handling of unrecoverable events for k8s & openshift infra (processing both 'container' and 'pod' events)
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/event/PodEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/event/PodEventHandler.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/PodEvents.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/PodEventsTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
Labels: kind/bug, status/code-review

#10158 Add selenium test of login with OpenShift account
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/PageObjectsInjectorImpl.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ocp/AuthorizeOpenShiftAccessPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ocp/OpenShiftLoginPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ocp/OpenShiftProjectCatalogPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/site/CheLoginPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/site/FirstBrokerProfilePage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/site/ProfilePage.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java
Labels: kind/task, status/code-review, team/che-qe

#10177 Fix a bug in the Che GWT maven plugin that prevents RhChe to build with upstream `master`
  core/che-core-gwt-maven-plugin/src/main/java/org/eclipse/che/plugin/gwt/ProcessExcludesMojo.java
Labels: kind/bug, status/code-review

#10166 Adapt the CSharpFileEditingTest after latest changes in Csharp language server
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CSharpFileEditingTest.java
Labels: kind/task, status/code-review

#10198 Add Html Sanitization for workspace name for preventing XSS
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/context/BrowserAddress.java
Labels: kind/enhancement, status/code-review

#10176 Selenium: Create E2E test for checking Hot update feature for wsmaster
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/recreate/RecreateUpdateStrategyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithWorkspacesStartStopTest.java
Labels: kind/task, status/code-review

#10118 Selenium: Fix of unexpected fail of "AddOrImportProjectFormTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/AddOrImportForm.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10148 Merge wiptheia dockerfile with Che Theia IDE dockerfile
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/src/add-extensions.js
  dockerfiles/theia/src/main.js
  dockerfiles/theia/src/package.json
  dockerfiles/theia/src/start.sh
  dockerfiles/theia/src/versions.sh
  dockerfiles/theia/supervisord.conf
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/task, status/code-review

#10197 Make Authorization header value more uniform and use 'Bearer' prefix
  multiuser/machine-auth/che-multiuser-machine-authentication-ide/src/main/java/org/eclipse/che/multiuser/machine/authentication/ide/MachineAsyncRequest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/server/WsAgentServerLivenessProbeConfigFactory.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/probe/WorkspaceProbesFactoryTest.java
Labels: kind/bug, status/code-review

#10212 Selenium: Fix of unexpected fail of "RollingUpdateStrategyWithWorkspacesStartStopTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithEditorTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10224 Consume Progress and Status DTO's from
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressMessagesHandler.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressMonitorPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressorJsonRpcHandler.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/background/BackgroundLoaderPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/dto/progressor/ProgressReportDto.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageClient.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProcessorJsonRpcCommunication.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProgressReport.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/StatusReport.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#10228 #10229 Publish all workspace pod events to the machine logs
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
Labels: kind/enhancement, status/code-review
