Repository eclipse-che/che, pull requests merged in 2018-12, with the labels that each got.

#12081 Copy yarn.lock before yarn install
  dashboard/Dockerfile
Labels: status/code-review

#12087 Temporary disable refactoring rename operation in go extension
  plugins/plugin-golang/che-plugin-golang-lang-ide/pom.xml
  plugins/plugin-golang/che-plugin-golang-lang-ide/src/main/java/org/eclipse/che/plugin/golang/ide/GolangExtension.java
Labels: kind/task, status/code-review, team/ide

#12046 Add ability to change CORS configuration on Che Server through env vars
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterServletModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/cors/CheCorsFilter.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/cors/CheCorsFilterConfig.java
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/openshift/templates/che-server-template.yaml
  wsagent/che-wsagent-core/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsAllowedOriginsEnvVarProvider.java
Labels: kind/enhancement, status/code-review

#12049 Introducing Jaeger tracing support to the Che Helm chart.
  deploy/kubernetes/helm/che/charts/che-jaeger/.helmignore
  deploy/kubernetes/helm/che/charts/che-jaeger/Chart.yaml
  deploy/kubernetes/helm/che/charts/che-jaeger/templates/deployment.yaml
  deploy/kubernetes/helm/che/charts/che-jaeger/templates/ingress.yaml
  deploy/kubernetes/helm/che/charts/che-jaeger/templates/service-agent.yaml
  deploy/kubernetes/helm/che/charts/che-jaeger/templates/service-collector.yaml
  deploy/kubernetes/helm/che/charts/che-jaeger/templates/service-query.yaml
  deploy/kubernetes/helm/che/charts/che-jaeger/values.yaml
  deploy/kubernetes/helm/che/requirements.lock
  deploy/kubernetes/helm/che/requirements.yaml
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/task, status/code-review

#12113 use latest tag of che-ls-jdt
  pom.xml
Labels: status/code-review

#12088 Add prometheus and grafana to the Helm chart
  .gitignore
  deploy/kubernetes/helm/che/.gitignore
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/.helmignore
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/Chart.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/ingress.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/service-agent.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/service-collector.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/service-query.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/values.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/.helmignore
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/Chart.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/endpoints-monitor-role.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/endpoints-monitor-rolebinding.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/ingress.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/keycloak-data-claim.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/keycloak-log-claim.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/keycloak-serviceaccount.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/service.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/values.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/.helmignore
  deploy/kubernetes/helm/che/custom-charts/che-postgres/Chart.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/postgres-data-claim.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/service.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/values.yaml
  deploy/kubernetes/helm/che/requirements.lock
  deploy/kubernetes/helm/che/requirements.yaml
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/templates/metrics-ingress.yaml
  deploy/kubernetes/helm/che/templates/service.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/task, status/code-review

#11170 Added 'centos-php' tag to web-php-simple sample.
  ide/che-core-ide-templates/src/main/resources/samples.json
Labels: kind/enhancement, status/code-review

#12112 Different small changes for Che with SSL enabled
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/multi/keycloak-template.yaml
  deploy/openshift/templates/multi/openshift-certificate-secret.yaml
  dockerfiles/che/entrypoint.sh
  dockerfiles/keycloak/kc_realm_user.sh
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  selenium/che-selenium-test/src/test/resources/projects/nodejs-with-yaml/deployment.yaml
Labels: kind/enhancement, status/code-review

#12133 Increase java heap memory for commands in Vert.x and Spring Boot predefined stacks
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/task, status/code-review

#11998 Devfile local features implenentation with schema validation and automated model build.
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/Command.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  multiuser/permission/che-multiuser-permission-devfile/pom.xml
  multiuser/permission/che-multiuser-permission-devfile/src/main/java/org/eclipse/che/multiuser/permission/devfile/DevfilePermissionsFilter.java
  multiuser/permission/che-multiuser-permission-devfile/src/test/java/org/eclipse/che/multiuser/permissions/devfile/DevfilePermissionsFilterTest.java
  multiuser/permission/che-multiuser-permission-devfile/src/test/resources/logback-test.xml
  multiuser/permission/pom.xml
  pom.xml
  wsmaster/che-core-api-devfile/pom.xml
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/Constants.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileConverter.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileFormatException.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileSchemaProvider.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileSchemaValidator.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileService.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/WorkspaceExportException.java
  wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileConverterTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileServiceTest.java
  wsmaster/che-core-api-devfile/src/test/resources/devfile.yaml
  wsmaster/che-core-api-devfile/src/test/resources/devfile_bad.yaml
  wsmaster/che-core-api-devfile/src/test/resources/logback-test.xml
  wsmaster/che-core-api-devfile/src/test/resources/workspace_config.json
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceKeyValidator.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/pom.xml
Labels: kind/task, status/code-review

#12138 bump parent version
  pom.xml
Labels: status/code-review

#12143 Increase workspace config attributes values field length in database.
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.16.0/1__increase_workspace_config_attributes_values_length.sql
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.16.0/mysql/1__increase_workspace_config_attributes_values_length.sql
Labels: kind/bug, status/code-review

#11983 Update nodejs-hello-world run command
  ide/che-core-ide-templates/src/main/resources/samples.json
Labels: kind/bug, status/code-review

#12126 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#12152 switch email from wish@codenvy.com to che-dev@eclipse.org
  dashboard/src/assets/branding/product.json
Labels: kind/question, status/code-review

#12082 [dockerfiles] [theia] Update to theia 0.3.17
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
  dockerfiles/theia/e2e/src/yarn.lock
  dockerfiles/theia/src/builder/clone.sh
Labels: status/code-review

#12156 Selenium: fix unstable selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/DocumentationPage.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/RunToCursorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckOnValidAndInvalidPackageNameTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCamelStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/task, selenium/failure, status/in-progress, team/che-qe

#12104 Add new postgres nodejs stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#12141 Use latest plugin brokers
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/ServerServiceBuilder.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
Labels: kind/task, status/code-review

#12148 Add attributes to Che 7 plugin meta; make URL field not mandatory
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/PluginMetaRetriever.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginMeta.java
Labels: kind/enhancement, status/code-review

#12154 FIX Typo "doesn't exists" -> "doesn't exist"
  deploy/openshift/ocp.sh
  dockerfiles/lib/src/internal/dir/che-dir-constant.properties
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/resources/Container.java
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/resources/VirtualFile.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/editor/page/goal/GoalPage.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/debug/BreakpointStorageImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/impl/InMemoryResourceStore.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/search/FullTextSearchPresenter.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/Tree.java
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerConnectorConfiguration.java
  wsagent/che-core-api-git/src/test/java/org/eclipse/che/api/git/GitConfigurationCheckerTest.java
Labels: kind/bug, status/code-review

#12085 [dockerfiles] [theia] Add eclipse/theia-dev image
  dockerfiles/pom.xml
  dockerfiles/theia-dev/Dockerfile
  dockerfiles/theia-dev/build.sh
  dockerfiles/theia-dev/e2e/Dockerfile
  dockerfiles/theia-dev/e2e/build.sh
  dockerfiles/theia-dev/pom.xml
  dockerfiles/theia-dev/src/entrypoint.sh
Labels: status/code-review

#11944 Upgrade dependencies
  assembly/assembly-wsmaster-war/pom.xml
  core/che-core-api-core/pom.xml
  core/che-core-metrics-core/pom.xml
  core/commons/che-core-commons-inject/pom.xml
  ide/che-ide-core/pom.xml
  infrastructures/docker/environment/pom.xml
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/CommandDeserializerTest.java
  infrastructures/docker/infrastructure/pom.xml
  infrastructures/kubernetes/pom.xml
  infrastructures/openshift/pom.xml
  multiuser/api/che-multiuser-api-organization/pom.xml
  multiuser/api/che-multiuser-api-permission/pom.xml
  multiuser/api/che-multiuser-api-resource/pom.xml
  multiuser/integration-tests/che-multiuser-cascade-removal/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml
  multiuser/permission/che-multiuser-permission-workspace/pom.xml
  multiuser/personal-account/pom.xml
  plugins/plugin-camel/che-plugin-camel-server/pom.xml
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/pom.xml
  plugins/plugin-clangd/che-plugin-clangd-lang-server/pom.xml
  plugins/plugin-composer/che-plugin-composer-server/pom.xml
  plugins/plugin-cpp/che-plugin-cpp-lang-server/pom.xml
  plugins/plugin-csharp/che-plugin-csharp-lang-server/pom.xml
  plugins/plugin-gdb/che-plugin-gdb-server/pom.xml
  plugins/plugin-github/che-plugin-github-oauth2/pom.xml
  plugins/plugin-github/che-plugin-github-provider-github/pom.xml
  plugins/plugin-github/che-plugin-github-server/pom.xml
  plugins/plugin-golang/che-plugin-golang-lang-server/pom.xml
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/pom.xml
  plugins/plugin-java/che-plugin-java-ext-lang-server/pom.xml
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/pom.xml
  plugins/plugin-java/che-plugin-java-server/pom.xml
  plugins/plugin-json/che-plugin-json-server/pom.xml
  plugins/plugin-maven/che-plugin-maven-server/pom.xml
  plugins/plugin-nodejs-debugger/che-plugin-nodejs-debugger-server/pom.xml
  plugins/plugin-nodejs/che-plugin-nodejs-lang-server/pom.xml
  plugins/plugin-php/che-plugin-php-lang-server/pom.xml
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-server/pom.xml
  plugins/plugin-python/che-plugin-python-lang-server/pom.xml
  plugins/plugin-testing-java/plugin-testing-junit/che-plugin-testing-junit-server/pom.xml
  plugins/plugin-testing-java/plugin-testing-testng/che-plugin-testing-testng-server/pom.xml
  plugins/plugin-testing-php/plugin-testing-phpunit/che-plugin-testing-phpunit-server/pom.xml
  plugins/plugin-web/che-plugin-web-ext-server/pom.xml
  plugins/plugin-yaml/che-plugin-yaml-server/pom.xml
  plugins/plugin-zend-debugger/che-plugin-zend-debugger-server/pom.xml
  wsagent/che-core-api-debug/pom.xml
  wsagent/che-core-api-git/pom.xml
  wsagent/che-core-api-languageserver/pom.xml
  wsagent/che-core-api-project/pom.xml
  wsagent/che-core-api-testing/pom.xml
  wsagent/che-core-git-impl-jgit/pom.xml
  wsagent/che-core-ssh-key-server/pom.xml
  wsmaster/che-core-api-system/pom.xml
Labels: kind/task, status/code-review

#12157 Increase java heap memory for 'mvn clean install' command in predefined 'Spring Boot' stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: status/code-review, team/che-qe

#12089 Add an ability to run Che with https endpoints with self-signed certificates
  agents/exec/installer/src/main/resources/installers/1.0.0/org.eclipse.che.exec.script.sh
  agents/exec/installer/src/main/resources/installers/1.0.1/org.eclipse.che.exec.script.sh
  agents/go-agents/Gopkg.lock
  agents/go-agents/Gopkg.toml
  agents/go-agents/bootstrapper/cfg/cfg.go
  agents/go-agents/bootstrapper/main.go
  agents/go-agents/vendor/github.com/eclipse/che-go-jsonrpc/README.md
  agents/go-agents/vendor/github.com/eclipse/che-go-jsonrpc/jsonrpcws/jsonrpc_impl.go
  agents/ls-java/src/main/resources/installers/1.0.1/org.eclipse.che.ls.java.script.sh
  agents/terminal/src/main/resources/installers/1.0.0/org.eclipse.che.terminal.script.sh
  agents/terminal/src/main/resources/installers/1.0.1/org.eclipse.che.terminal.script.sh
  assembly/assembly-wsagent-server/src/assembly/setenv.sh
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/CertificateProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/CertificateProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
  wsagent/agent/src/main/resources/installers/1.0.0/org.eclipse.che.ws-agent.script.sh
  wsagent/agent/src/main/resources/installers/1.0.1/org.eclipse.che.ws-agent.script.sh
  wsagent/agent/src/main/resources/installers/1.0.2/org.eclipse.che.ws-agent.script.sh
  wsagent/agent/src/main/resources/installers/1.0.3/org.eclipse.che.ws-agent.script.sh
Labels: kind/enhancement, status/code-review

#12166 Made changes needed for deploying secure Che with OAuth provider configured on Minishift
  deploy/openshift/deploy_che.sh
Labels: kind/task, status/code-review

#12173 Add integrity validations for devfile service
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/Constants.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileConverter.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileIntegrityValidator.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileService.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileIntegrityValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileServiceTest.java
Labels: kind/task, status/code-review

#12171 [docker] [theia] Use of theia-dev image in theia image
  dockerfiles/theia-dev/Dockerfile
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/pom.xml
  dockerfiles/theia/src/builder/check-github-limit.sh
  dockerfiles/theia/src/builder/clone.sh
  dockerfiles/theia/src/builder/production-mode.sh
  pom.xml
Labels: status/code-review

#12178 Move Che Theia to 3100 port
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
  dockerfiles/theia/src/entrypoint.sh
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: status/code-review

#12189 Selenium: stabilize selenium tests, adapt NewWorkspacePageTest test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewPackageFromContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCamelStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginJunit4Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#12192 Only deploy metrics ingress if metrics are enabled.
  deploy/kubernetes/helm/che/templates/metrics-ingress.yaml
Labels: kind/bug, status/code-review

#12176 Added PerWorkspace PVC strategy
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/EphemeralWorkspaceAdapter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategyTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
Labels: kind/enhancement, status/code-review

#12197 Fix of conflict of seleniumhq 3.0.1 with guava 27.0.1-jre
  selenium/pom.xml
Labels: kind/bug, status/code-review, team/che-qe

#12210 Selenium: Delete the 'try-catch' expression from 'refactor.parameters' tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/parameters/FailParametersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/parameters/RenameParametersTest.java
Labels: kind/task, status/code-review, team/che-qe

#12206 [Selenium] Change selenium tests from 'projectexplorer' package to wait that jdtls is fully initialized before working with project
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckAutoSaveForFileWhichAlreadyExistTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckCollapseAllNodesProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckCopyCutFeaturesForFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckDisplayingArtifactIdTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckErrorMessageWhenCreationDuplicateFolderOrFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckHiddenFolderAndFileCreatedFromCommandTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckOnValidAndInvalidClassNameTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckOnValidAndInvalidPackageNameTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckRecentFilesAndRevealResourceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckRefreshProjectTreeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckTreeStructureAfterCloseTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/ClosingSeveralOpenFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewFoldersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewJavaFilesFromContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewJavaFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewNotJavaFilesFromContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewNotJavaFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewPackagesWithHelpCreationJavaClassTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateProjectInSelectedFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateProjectsForArtikPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeleteFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeletePackageFromContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeletePackageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeletePackageWithOpenedFilesTabTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/FileNotExistIntoEditorAfterDeleteTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/FileOpenedAfterCreationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/JustCreatedFileNotExistIntoEditorAfterDeleteTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/NavigationByKeyboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/OpenFileWithHelpContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/PreviewHtmlFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/RenameJustCreatedNotJavaFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/RenameProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/RenamedAlreadyCreatedNotJavaFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/ShowFileReferenceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/UploadIntoProjectTest.java
Labels: kind/task, status/code-review, team/che-qe

#12198 Add sample for nodejs postgres stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  ide/che-core-ide-templates/src/main/resources/samples.json
Labels: kind/bug, status/code-review

#12214 Selenium: Delete the 'try-catch' expression from the 'CodeAssistAfterMoveItemTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/CodeAssistAfterMoveItemTest.java
Labels: kind/task, status/code-review, team/che-qe

#12213 Selenium: stabilize selenium tests, add tests to UNDER_REPAIR group
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaHostedPluginSelectPathForm.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaDockerStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaOpenshiftStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginJunit4CheckRunSuitesAndScopesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginJunit4Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginTestNgTest.java
Labels: status/code-review, team/che-qe

#12226 [dockerfiles] [theia] Add patch for git clone operation for theia 0.3.17
  dockerfiles/theia/src/patches/0.3.17/001-args.patch
Labels: kind/bug, status/code-review

#12221 Handle selenium tests extension
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumClassModule.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
Labels: kind/task, status/code-review, team/che-qe

#12219 Selenium: Add corrections to the tests from 'git' package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AddFilesToIndexTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/BranchTest.java
Labels: kind/task, status/code-review, team/che-qe

#12201 Gwt ide as sidecar Docker image
  dockerfiles/gwt-ide/Dockerfile
  dockerfiles/gwt-ide/build.sh
  dockerfiles/gwt-ide/entrypoint.sh
  dockerfiles/gwt-ide/supervisord.conf
  dockerfiles/gwt-ide/traefik.toml
  dockerfiles/gwt-ide/traefik_conf.sh
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/IDE.html
Labels: kind/task, status/code-review

#12240 [dockerfiles] [theia] Fix theia 0.3.17
  dockerfiles/theia/src/patches/0.3.17/001-args.patch
Labels: kind/bug, status/code-review

#12236 Selenium: Add corrections to the 'ConfigureSomeSourceFoldersTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/ConfigureSomeSourceFoldersTest.java
Labels: kind/task, status/code-review, team/che-qe

#12247 Selenium: stabilize selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ClangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/JsonFileEditingTest.java
Labels: status/code-review, team/che-qe

#12231 Save selection when process tree updates
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/panel/ProcessesPanelPresenter.java
Labels: kind/bug, status/code-review, team/ide

#12235 Remove maven server
  assembly/assembly-wsagent-server/src/assembly/assembly.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/resources/che-in-che.json
  dockerfiles/init/manifests/che.env
  plugins/plugin-maven/che-plugin-maven-ide/pom.xml
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/MavenLanguageDescriptionProvider.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/TestLSLanguageDescriptionProvider.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/inject/MavenGinModule.java
  plugins/plugin-maven/che-plugin-maven-server/pom.xml
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/lsp/MavenLanguageServer.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/lsp/MavenLanguageServerConfig.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/lsp/MavenTextDocumentService.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/inject/MavenModule.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/rmi/Ref.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/rmi/RmiClient.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/rmi/RmiObjectWrapper.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/MavenAttributes.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/MessageType.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/dto/MavenOutputEventDto.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/dto/MavenProblem.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/dto/NotificationMessage.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/dto/PercentMessageDto.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/dto/PercentUndefinedMessageDto.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/dto/ProjectsUpdateMessage.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/dto/StartStopNotification.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/dto/TextMessageDto.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/event/MavenOutputEvent.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/event/MavenPercentMessageEvent.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/event/MavenPercentUndefinedEvent.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/event/MavenStartStopEvent.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/event/MavenTextMessageEvent.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/event/MavenUpdateEvent.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/impl/MavenOutputEventImpl.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/impl/MavenPercentEventImpl.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/impl/MavenPercentUndefinedEventImpl.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/impl/MavenStartStopEventImpl.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/impl/MavenTextMessageEventImpl.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/impl/MavenUpdateEventImpl.java
  plugins/plugin-maven/maven-server/maven-server-api/pom.xml
  plugins/plugin-maven/maven-server/maven-server-impl/pom.xml
  plugins/plugin-maven/maven-server/pom.xml
  plugins/plugin-maven/pom.xml
  wsagent/che-wsagent-core/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceMavenServerJavaOptsEnvVariableProvider.java
Labels: kind/task, status/code-review, team/languages

#12256 Selenium: check that refactoring rename operation for Golang LS not exists
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
Labels: kind/task, status/code-review, team/che-qe

#12177 Workspace activity metrics
  assembly/assembly-wsmaster-war/src/main/resources/META-INF/persistence.xml
  multiuser/api/che-multiuser-api-permission/src/main/java/org/eclipse/che/multiuser/api/permission/server/SystemDomain.java
  multiuser/api/che-multiuser-api-workspace-activity/src/test/java/org/eclipse/che/multiuser/api/workspace/activity/MultiUserWorkspaceActivityManagerTest.java
  multiuser/integration-tests/che-multiuser-mysql-tck/pom.xml
  multiuser/permission/che-multiuser-permission-workspace-activity/pom.xml
  multiuser/permission/che-multiuser-permission-workspace-activity/src/main/java/org/eclipse/che/multiuser/permission/workspace/activity/ActivityPermissionsFilter.java
  multiuser/permission/che-multiuser-permission-workspace-activity/src/test/java/org/eclipse/che/multiuser/permission/workspace/activity/ActivityPermissionsFilterTest.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/InmemoryWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/JpaWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivity.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManager.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityService.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceExpiration.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/inject/WorkspaceActivityModule.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManagerTest.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityServiceTest.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/jpa/WorkspaceActivityTckModule.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/spi/tck/WorkspaceActivityDaoTest.java
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.16.0/2__create_workspace_activity_table.sql
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.16.0/3__bootstrap_ws_activity_data.sql
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.16.0/mysql/3__bootstrap_ws_activity_data.sql
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
  wsmaster/integration-tests/mysql-tck/pom.xml
  wsmaster/integration-tests/mysql-tck/src/test/java/MySqlTckModule.java
  wsmaster/integration-tests/postgresql-tck/src/test/java/PostgreSqlTckModule.java
Labels: kind/task, status/code-review

#12265 Fix WS Agent not setting appropriate CORS allowed origin on Docker
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/cors/CheWsAgentCorsAllowedOriginsProvider.java
Labels: kind/bug, status/code-review

#12271 Fix the output of the GET /activity to just contain the array of ws ids
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityService.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityServiceTest.java
Labels: kind/bug, status/code-review, team/platform

#12250 Add '.d.ts' DTO generator
  core/che-core-typescript-dto-maven-plugin/pom.xml
  core/che-core-typescript-dto-maven-plugin/src/it/java/org/eclipse/che/plugin/typescript/dto/TypeScriptDTOGeneratorMojoITest.java
  core/che-core-typescript-dto-maven-plugin/src/it/resources/dto.spec.ts
  core/che-core-typescript-dto-maven-plugin/src/main/java/org/eclipse/che/plugin/typescript/dto/DTOHelper.java
  core/che-core-typescript-dto-maven-plugin/src/main/java/org/eclipse/che/plugin/typescript/dto/TypeScriptDTOGeneratorMojo.java
  core/che-core-typescript-dto-maven-plugin/src/main/java/org/eclipse/che/plugin/typescript/dto/TypeScriptDtoDTSGenerator.java
  core/che-core-typescript-dto-maven-plugin/src/main/java/org/eclipse/che/plugin/typescript/dto/model/DtoModel.java
  core/che-core-typescript-dto-maven-plugin/src/main/java/org/eclipse/che/plugin/typescript/dto/model/DtoNamespace.java
  core/che-core-typescript-dto-maven-plugin/src/main/java/org/eclipse/che/plugin/typescript/dto/model/FieldAttributeModel.java
  core/che-core-typescript-dto-maven-plugin/src/main/java/org/eclipse/che/plugin/typescript/dto/model/MethodModel.java
  core/che-core-typescript-dto-maven-plugin/src/main/resources/org/eclipse/che/plugin/typescript/dto/typescript.d.ts.template
  core/che-core-typescript-dto-maven-plugin/src/main/resources/org/eclipse/che/plugin/typescript/dto/typescript.template
  core/che-core-typescript-dto-maven-plugin/src/test/java/org/eclipse/che/plugin/typescript/dto/MyCustomDTO.java
  core/che-core-typescript-dto-maven-plugin/src/test/java/org/eclipse/che/plugin/typescript/dto/TypeScriptDTOGeneratorMojoTest.java
  core/che-core-typescript-dto-maven-plugin/src/test/java/org/eclipse/che/plugin/typescript/dto/internal/InternalDto.java
  core/che-core-typescript-dto-maven-plugin/src/test/projects/project-d-ts/pom.xml
Labels: kind/enhancement, status/code-review

#12163 Use init broker to remove plugins files on brokering
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesBrokerInitContainerApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/KubernetesBrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/wsplugins/brokerphases/OpenshiftBrokerEnvironmentFactory.java
Labels: status/code-review

#12232 Factory support of devfile
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
  plugins/plugin-github/che-plugin-github-factory-resolver/pom.xml
  plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/GitHubFactoryModule.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/GithubFactoryParametersResolver.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/GithubSourceStorageBuilder.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/GithubURLParser.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/GithubURLParserImpl.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/GithubUrl.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/LegacyGithubURLParser.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/test/java/org/eclipse/che/plugin/github/factory/resolver/GithubFactoryParametersResolverTest.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/test/java/org/eclipse/che/plugin/github/factory/resolver/GithubURLParserTest.java
  plugins/plugin-github/che-plugin-github-factory-resolver/src/test/java/org/eclipse/che/plugin/github/factory/resolver/GithubUrlTest.java
  plugins/plugin-urlfactory/pom.xml
  plugins/plugin-urlfactory/src/main/java/org/eclipse/che/plugin/urlfactory/URLFactoryBuilder.java
  plugins/plugin-urlfactory/src/test/java/org/eclipse/che/plugin/urlfactory/URLFactoryBuilderTest.java
  plugins/plugin-urlfactory/src/test/resources/logback-test.xml
  plugins/pom.xml
  pom.xml
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileManager.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileService.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/schema/DevfileSchemaProvider.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/validator/DevfileIntegrityValidator.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidator.java
  wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileManagerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileServiceTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileIntegrityValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/Constants.java
  wsmaster/che-core-api-factory/pom.xml
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolver.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryManager.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryParametersResolver.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/ValueHelper.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/jpa/JpaFactoryDao.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/spi/FactoryDao.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/ProjectConfigDtoMerger.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLChecker.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFetcher.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/FactoryServiceTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/builder/FactoryBuilderTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/spi/tck/FactoryDaoTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/ProjectConfigDtoMergerTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLCheckerTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFetcherTest.java
  wsmaster/che-core-api-factory/src/test/resources/.che.json
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/ProjectConfigDto.java
Labels: kind/task, status/code-review

#12281 Selenium: add selenium tests to UNDER_REPAIR group
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCentosNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromNodeStackTest.java
Labels: status/code-review, team/che-qe

#12275 Selenium: Correct some selenium tests to increase reliability
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AddFilesToIndexTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AmendCommitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutReferenceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/InitializeAndDeleteLocalRepositoryTest.java
Labels: kind/task, status/code-review, team/che-qe

#12283 Fixed logged messages in commons schedule module
  core/commons/che-core-commons-schedule/src/main/java/org/eclipse/che/commons/schedule/executor/LoggedRunnable.java
Labels: kind/task

#12300 Selenium: Refactor some tests from the 'debugger' package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/CppProjectDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/PhpProjectDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/StepIntoStepOverStepReturnWithChangeVariableTest.java
Labels: kind/task, status/code-review, team/che-qe

#12257 Add periodical job that stops Runtimes without existing pods
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/InconsistentRuntimesDetector.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/RuntimeHangingDetector.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/InconsistentRuntimesDetectorTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/provision/OpenShiftUniqueNamesProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTermination.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/InternalRuntime.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTerminationTest.java
Labels: kind/enhancement, status/code-review

#12279 Remove redundant Eclipse Che 'user' role
  dockerfiles/init/modules/keycloak/templates/che-realm.json.erb
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/KeycloakCliClient.java
Labels: kind/task, team/che-qe

#12294 Make documentation links configurable
  dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.ts
  dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
  dashboard/src/app/factories/list-factories/list-factories.html
  dashboard/src/app/organizations/organizations.html
  dashboard/src/assets/branding/product.json
  dashboard/src/components/branding/che-branding.factory.ts
  dashboard/src/components/widget/footer/che-footer.directive.ts
  dashboard/src/components/widget/footer/che-footer.html
  dashboard/src/index.html
Labels: kind/enhancement, status/code-review

#12286 Upgrade version of selenium chrome-node to 3.141.59-dubnium
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/docker-compose.yml
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/DashboardAccount.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
Labels: kind/task, team/che-qe

#12314 Selenium: add info about known issues, stabilize tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsComposeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckOpenFileFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithKeepDirectoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckGeneratingMavenArchetypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckMavenPluginTest.java
Labels: selenium/failure, status/code-review, team/che-qe

#12316 Selenium: add info about known #12315 issue to TheiaBuildPluginTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: status/code-review, team/che-qe

#12318 Fix LoginNewUserWithOpenShiftOAuthTest selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
Labels: team/che-qe

#12313 Selenium: Refactor some tests from the 'editor' package
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/SplitEditorFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
Labels: kind/task, status/code-review, team/che-qe
