Repository eclipse-che/che, pull requests merged in 2018-04, with the labels that each got.

#9297 Selenium: improve and rework the 'PullRequestPluginTest' test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
Labels: kind/task, status/code-review, team/che-qe

#9308 Add auxiliary test github user repository
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
Labels: kind/task, status/code-review, team/che-qe

#9307 Add exec with error output processing
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesMachine.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/bootstrap/AbstractBootstrapper.java
Labels: kind/task, status/code-review

#9300 Add ability to manage the list of Theia plugins in UD
  dashboard/src/app/ide/ide.controller.ts
  dashboard/src/app/index.module.ts
  dashboard/src/app/profile/profile.controller.ts
  dashboard/src/app/workspaces/create-workspace/namespace-selector/namespace-selector.service.ts
  dashboard/src/app/workspaces/workspace-details/machine-selector/machine-selector.controller.ts
  dashboard/src/app/workspaces/workspace-details/machine-selector/machine-selector.directive.ts
  dashboard/src/app/workspaces/workspace-details/machine-selector/machine-selector.html
  dashboard/src/app/workspaces/workspace-details/workspace-details-config.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.html
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-details-tools.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-details-tools.directive.ts
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-details-tools.html
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-details-tools.styl
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-config.ts
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/add-package-popover.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/add-package-popover.directive.ts
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/add-package-popover.html
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/add-package-popover.styl
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/workspace-tools-ide.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/workspace-tools-ide.directive.ts
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/workspace-tools-ide.html
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/workspace-tools-ide.styl
  dashboard/src/components/api/che-api-config.ts
  dashboard/src/components/api/json-rpc/che-json-rpc-api-service.ts
  dashboard/src/components/api/npm-registry.factory.ts
  dashboard/src/components/attribute/format-output/che-format-output.directive.ts
Labels: kind/enhancement, status/code-review

#8983 Enable single-level DNS domains (*.domain.tld) in SINGLE_PORT mode to simplify HTTPS setup
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  dockerfiles/init/manifests/che.env
  dockerfiles/init/manifests/che.pp
  dockerfiles/init/modules/che/templates/che.env.erb
  dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/provisioner/labels/SinglePortLabelsProvisioner.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/server/mapping/SinglePortHostnameBuilder.java
Labels: kind/enhancement, status/code-review

#9312 Selenium: improve and rework the 'PullRequestPluginWithForkTest' test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginWithForkTest.java
Labels: kind/task, status/code-review, team/che-qe

#9280 Fix recreation of user in Che DB, when it has been recreated on Keycloak
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakUserManager.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/dao/KeycloakProfileDao.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakUserManagerTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/resources/logback-test.xml
  wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/UserManager.java
Labels: kind/bug, status/code-review

#9320 Fix failing tests in docker infrastructure
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/server/mapping/SinglePortUrlBuilderTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/server/mapping/SinglePortUrlRewriterTest.java
Labels: kind/enhancement, status/code-review

#9309 Selenium: Rework the 'CheckoutToRemoteBranchWhichAlreadyHasLinkedLocalBranchTest to run in the multi-threaded mode
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchWhichAlreadyHasLinkedLocalBranchTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#9302 CHE-9066: Fix wrong author name of revert commit
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/RevertCommitTest.java
  wsagent/che-core-api-git/src/test/java/org/eclipse/che/git/impl/RevertTest.java
  wsagent/che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConnection.java
Labels: kind/bug, status/code-review

#9327 Selenium: fix github user name in PullRequestPluginWithForkTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginWithForkTest.java
Labels: kind/bug, status/code-review, team/che-qe

#9262 Selenium: add method for switching from Dashboard to IDE frame in SeleniumWebDriverHelper class
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Preferences.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/AccountTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromZipTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspaceDetailsComposeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithMultiModuleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerClickCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerUserCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithUntilPolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckOpenFileFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckRunCommandFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckWelcomePanelOnCodenvyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromUiWithKeepDirTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateNamedFactoryFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromImportTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromPreferencesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/PreviewUrlIntoCommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/PreviewHtmlFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithNodeWsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithAndroidStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithBlankStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithCppStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNetStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPHPStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPythonStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithRailsStackTest.java
Labels: kind/task, status/code-review, team/che-qe

#9337 Fix GitHub optional properties binding to selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubKeyUploader.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/CheTestOfflineToAccessTokenExchangeApiEndpointUrlProvider.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithMultiModuleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithSparseCheckoutTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithKeepDirectoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AddFilesToIndexTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AmendCommitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromImportTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromPreferencesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/BranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutReferenceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesByMultiSelectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CreateAndDeleteLocalBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/FetchAndMergeRemoteBranchIntoLocalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitChangeMarkersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitColorsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitCompareTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportProjectIntoSpecifiedBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportRecursiveSubmoduleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/InitializeAndDeleteLocalRepositoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/KeepDirectoryGitImportTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PushChangeNotUpdatedRepoTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PushingChangesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/RevertCommitTest.java
  selenium/che-selenium-test/src/test/resources/conf/selenium.properties
Labels: kind/bug, status/code-review, team/che-qe

#9341 Fix go stack version.
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review

#9322 CHE-9299 remove the dev machine validation for UD
  dashboard/src/app/stacks/list-stacks/build-stack/build-stack.component.spec.ts
  dashboard/src/app/stacks/list-stacks/build-stack/build-stack.controller.ts
  dashboard/src/app/stacks/stack-details/stack-validation.service.ts
  dashboard/src/app/workspaces/workspace-details/environments/environments.controller.ts
  dashboard/src/app/workspaces/workspace-details/environments/environments.html
  dashboard/src/app/workspaces/workspace-details/environments/list-agents/list-agents.controller.ts
  dashboard/src/app/workspaces/workspace-details/environments/machine-config/machine-config.html
  dashboard/src/app/workspaces/workspace-details/machine-selector/machine-selector.html
  dashboard/src/app/workspaces/workspace-details/machine-selector/machine-selector.styl
  dashboard/src/app/workspaces/workspace-details/workspace-details-config.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/change-dev-machine-dialog/change-dev-machine-dialog.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/change-dev-machine-dialog/change-dev-machine-dialog.html
  dashboard/src/app/workspaces/workspace-details/workspace-machines/change-dev-machine-dialog/change-dev-machine-dialog.styl
  dashboard/src/app/workspaces/workspace-details/workspace-machines/machine-item/workspace-machine-item.directive.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/machine-item/workspace-machine-item.html
  dashboard/src/app/workspaces/workspace-details/workspace-machines/workspace-machines.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/workspace-machines.html
  dashboard/src/components/api/environment/environment-manager.ts
Labels: kind/bug

#9296 Add setting of an environment variable to configure master logs encoding
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/kubectl/che-kubernetes.yaml
  deploy/openshift/che-config
  dockerfiles/init/manifests/che.env
Labels: kind/enhancement, status/code-review

#9350 Selenium: not check Workspace API installer changeability in WorkspaceDetailsSingleMachineTest test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceInstallers.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspaceDetailsSingleMachineTest.java
Labels: selenium/failure, team/che-qe

#9329 k8s-infra: routing, TLS (rebased)
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/deployment.yaml
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/endpoints-monitor-role.yaml
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/endpoints-monitor-rolebinding.yaml
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/ingress.yaml
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/keycloak-configure-job.yaml
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/keycloak-serviceaccount.yaml
  deploy/kubernetes/helm/che/charts/che-postgres/templates/deployment.yaml
  deploy/kubernetes/helm/che/readme.md
  deploy/kubernetes/helm/che/templates/_hostHelper.tpl
  deploy/kubernetes/helm/che/templates/_keycloakAuthUrlHelper.tpl
  deploy/kubernetes/helm/che/templates/_keycloakHostHelper.tpl
  deploy/kubernetes/helm/che/templates/cert-issuer.yaml
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/templates/ingress.yaml
  deploy/kubernetes/helm/che/templates/staging-cert-issuer.yaml
  deploy/kubernetes/helm/che/values.yaml
  deploy/kubernetes/helm/che/values/default-host.yaml
  deploy/kubernetes/helm/che/values/multi-user.yaml
  deploy/kubernetes/helm/che/values/tls.yaml
  dockerfiles/init/manifests/che.env
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/IngressTlsProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/server/ServersConverter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/AbstractIngressExternalServerExposerStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/DefaultHostIngressExternalServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/ExternalServerExposerStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/ExternalServerExposerStrategyProvider.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/ExternalServerIngressBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/IngressAnnotationsProvider.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/MultiHostIngressExternalServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/SingleHostIngressExternalServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/IngressTlsProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/DefaultHostIngressExternalServerExposerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/ExternalServerIngressBuilderTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/MultiHostIngressExternalServerExposerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/provision/OpenShiftServersConverter.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/provision/RouteTlsProvisioner.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftExternalServerExposer.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftServerResolver.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftServerExposerTest.java
Labels: kind/enhancement, status/code-review

#9328 Improve and rework the PushingChangesTest using kohsuke library
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/Git.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PushingChangesTest.java
Labels: kind/task, status/code-review

#9364 Selenium: change url of known issue to #8293 instead of #8465 in NavigateToFileTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
Labels: kind/bug, status/code-review, team/che-qe

#9366 Fix Openshift infrastructure
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/server/ServersConverter.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
Labels: kind/enhancement, status/code-review

#9363 Update content from the resource for CheckGeneratingMavenArchetypeTest file to actual state
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckGeneratingMavenArchetypeTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/mavenplugin/pom-quick-start-archetype-context
Labels: kind/enhancement, status/code-review

#9342 Use workspace limit idle timeout value in WorkspaceActivityManager
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties
  dockerfiles/init/manifests/che.env
  wsmaster/che-core-api-workspace-activity/pom.xml
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManager.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManagerTest.java
Labels: kind/bug, status/code-review

#9371 Make exec agent not to use setsid for other than Linux OSes
  agents/go-agents/core/process/process.go
Labels: kind/task, status/code-review

#9368 Selenium: Rework the 'CheckoutReferenceTest' to run in the multi-thread mode
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitHistory.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutReferenceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#8982 Configure JPA L2 cache coordination between instances on Openshift® / Kubernetes
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/jgroups/che-tcp.xml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/kubectl/che-kubernetes.yaml
  deploy/openshift/che-openshift.yml
Labels: kind/task, status/code-review

#9196 Change way of storing IDE state data
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/statepersistance/AppStateServiceClient.java
  ide/che-core-ide-app/pom.xml
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/DefaultIdeInitializationStrategy.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/FactoryIdeInitializationStrategy.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/context/AppContextImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateBackwardCompatibility.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateConstants.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateManager.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateServiceClientImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateSyncWriter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateTracker.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/PersistenceApiModule.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/StopWorkspaceAction.java
  ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/statepersistance/AppStateManagerTest.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceVcsStatusInjector.java
  wsagent/che-wsagent-core/pom.xml
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/CheWsAgentModule.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/appstate/AppStateManager.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/appstate/AppStateService.java
  wsagent/che-wsagent-core/src/test/java/org/eclipse/che/wsagent/server/appstate/AppStateManagerTest.java
  wsagent/che-wsagent-core/src/test/java/org/eclipse/che/wsagent/server/appstate/AppStateServiceTest.java
Labels: kind/bug, status/code-review

#9369 Correct handle of input events in navigate to file dialogue
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/navigation/NavigateToFilePresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/navigation/NavigateToFileView.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/navigation/NavigateToFileViewImpl.java
Labels: kind/bug, selenium/failure, severity/P1, status/code-review, target/che6, team/ide

#9375 Selenium: move SeleniumWebDriverHelper class to org.eclipse.che.selenium.core package
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/factory/TestFactory.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/factory/TestFactoryInitializer.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/WebDriverWaitFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Preferences.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/DashboardFactories.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/DashboardAccount.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakAccountPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakFederatedIdentitiesPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakHeaderButtons.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakPasswordPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceShare.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceSsh.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspacesVolumes.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/debug/DebugPanel.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitHistory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitRevertCommit.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/AccountTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromZipTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspaceDetailsComposeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithMultiModuleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerClickCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerUserCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithUntilPolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckOpenFileFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckRunCommandFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckWelcomePanelOnCodenvyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromUiWithKeepDirTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateNamedFactoryFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromImportTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromPreferencesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/KeepDirectoryGitImportTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/PreviewUrlIntoCommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/PreviewHtmlFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/TransitiveDependencyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithNodeWsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithAndroidStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithBlankStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithCppStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNetStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPHPStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithPythonStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/notjavastack/CreateWorkspaceWithRailsStackTest.java
Labels: kind/bug, status/code-review, team/che-qe

#9380 Fix move sign key binding to auth module
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/CheWsAgentModule.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/WsAgentAuthModule.java
Labels: kind/bug, status/code-review

#9382 che #9376 Setting default postgres image for 'deploy_postgres_only.sh' instead of failing if 'IMAGE_POSTGRES' env var is not set
  deploy/openshift/multi-user/deploy_postgres_only.sh
Labels: kind/question, status/code-review

#9370 Fix workspace loader which should pass its query strings to the underlying alternate IDE
  workspace-loader/src/index.ts
  workspace-loader/test/test.spec.ts
Labels: kind/bug, status/code-review

#9396 Add catching of known bug #9393
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/RenameProjectTest.java
Labels: kind/task, status/code-review

#9301 Implemented recovery functionality for Kubernetes/OpenShift infrastructures
  assembly/assembly-wsmaster-war/src/main/resources/META-INF/persistence.xml
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesMachine.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesRuntimeContext.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapperFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/KubernetesMachineCache.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/KubernetesRuntimeStateCache.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesMachineCache.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesRuntimeStateCache.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/model/KubernetesMachineImpl.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/model/KubernetesRuntimeState.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/model/KubernetesServerImpl.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaTckModule.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/KubernetesMachinesCacheTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/KubernetesRuntimeStateCacheTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/TestObjects.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/kubernetes/src/test/resources/META-INF/services/org.eclipse.che.commons.test.tck.TckModule
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfrastructure.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftRuntimeContext.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectTest.java
  pom.xml
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.4.0/3__add_k8s_runtimes.sql
  wsmaster/integration-tests/postgresql-tck/pom.xml
  wsmaster/integration-tests/postgresql-tck/src/test/java/PostgreSqlTckModule.java
Labels: kind/enhancement, status/code-review

#9389 Selenium: wait that Restart button in ToastLoader is clickable
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/NotificationsPopupPanel.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ToastLoader.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckRestoringWorkspaceAfterStoppingWsAgentProcessTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStopStartWsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStoppingWsByTimeoutTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/bug, status/code-review, team/che-qe

#9372 Selenium: Create one test from "ImportRecursiveSubmoduleTest", "ImportProjectIntoSpecifiedBranchTest", and "KeepDirectoryGitImportTest" selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromImportTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportProjectIntoSpecifiedBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportRecursiveSubmoduleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/KeepDirectoryGitImportTest.java
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/.gitignore
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/README.md
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/pom.xml
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/src/main/java/com/codenvy/example/spring/GreetingController.java
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/src/main/java/com/codenvy/example/spring/HelloWorld.java
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/src/main/webapp/WEB-INF/jsp/hello_view.jsp
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/src/main/webapp/WEB-INF/spring-servlet.xml
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/src/main/webapp/WEB-INF/web.xml
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test/src/main/webapp/index.jsp
  selenium/che-selenium-test/src/test/resources/projects/Repo_For_Test_branch1/AppController.java
  selenium/che-selenium-test/src/test/resources/projects/testRepo/README.md
  selenium/che-selenium-test/src/test/resources/projects/testRepo/README2.md
  selenium/che-selenium-test/src/test/resources/projects/testRepo/pom.xml
  selenium/che-selenium-test/src/test/resources/projects/testRepo/src/main/java/com/company/example/A.java
  selenium/che-selenium-test/src/test/resources/projects/testRepo/src/main/webapp/WEB-INF/jsp/hello_view.jsp
  selenium/che-selenium-test/src/test/resources/projects/testRepo/src/main/webapp/WEB-INF/spring-servlet.xml
  selenium/che-selenium-test/src/test/resources/projects/testRepo/src/main/webapp/index.jsp
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review

#9392 Added initialization for FileTreeWalker
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/watcher/server/impl/FileTreeWalker.java
  wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/watcher/server/impl/FileTreeWalkerTest.java
Labels: kind/enhancement, status/code-review

#9407 Selenium: Remove catching issue #7551 in the selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ConvertToProjectWithPomFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java
Labels: kind/task, status/code-review

#9395 Use workspace limit idle timeout value in WorkspaceActivityManager
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties
  dockerfiles/init/manifests/che.env
  multiuser/api/che-multiuser-api-workspace-activity/pom.xml
  multiuser/api/che-multiuser-api-workspace-activity/src/main/java/org/eclipse/che/multiuser/api/workspace/activity/MultiUserWorkspaceActivityManager.java
  multiuser/api/che-multiuser-api-workspace-activity/src/main/java/org/eclipse/che/multiuser/api/workspace/activity/MultiUserWorkspaceActivityModule.java
  multiuser/api/che-multiuser-api-workspace-activity/src/test/java/org/eclipse/che/multiuser/api/workspace/activity/MultiUserWorkspaceActivityManagerTest.java
  multiuser/api/pom.xml
  pom.xml
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManager.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManagerTest.java
Labels: kind/bug, status/code-review

#9420 Selenium: Resolve unexpected fail of UpdateListOfLibraryTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/UpdateListOfLibraryTest.java
Labels: kind/bug, status/code-review

#9422 Make IDE use projects folder configured in a workspace instead of hardcoded /projects
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/app/AppContext.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/context/AppContextImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/CurrentWorkspaceManager.java
Labels: status/code-review

#9437 Fixed removing of PVCs when OpenShift project name is predefined
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPersistentVolumeClaims.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleaner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleanerTest.java
Labels: kind/bug, status/code-review

#9440 Fix calculation Projects Root so it wont cause NPE if there are no 'project' volume defined
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/workspace/model/MachineConfigImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/context/AppContextImpl.java
Labels: kind/bug, status/code-review

#9405 Notify other browsers when project is created in one session
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/ProjectTreeChangeHandler.java
  ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
Labels: kind/bug, severity/P2, status/code-review, team/ide

#9457 Selenium: Add catching issue #9456
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestUserPreferencesServiceClient.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
Labels: kind/bug

#9190 Use templates only to deploy Che to OpenShift
  deploy/openshift/ocp.sh
  deploy/openshift/templates/README.md
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/https/che-route-tls.yaml
  deploy/openshift/templates/https/keycloak-route-tls.yaml
  deploy/openshift/templates/multi/keycloak-template.yaml
  deploy/openshift/templates/multi/postgres-template.yaml
  deploy/openshift/templates/pvc/che-server-pvc.yaml
  dockerfiles/keycloak/kc_realm_user.sh
Labels: kind/enhancement, status/code-review

#9460 Selenium: Remove workaround in "MacrosCommandsEditorTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/MacrosCommandsEditorTest.java
Labels: kind/task, status/code-review, team/che-qe

#9468 Fixed command for launching minikube with RBAC in helm chart readme
  deploy/kubernetes/helm/che/readme.md
Labels: kind/bug, status/code-review

#9446 CHE-9428: fix kubernetes infra after a merge of not checked PR
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/kubectl/che-kubernetes.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/ExternalServerExposerStrategyProvider.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/MultiHostIngressExternalServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/SingleHostIngressExternalServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/MultiHostIngressExternalServerExposerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
Labels: kind/bug, status/code-review

#9474 Fix error of selenium tests when admin credentials is incorrect
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/CheTestAuthServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/KeycloakAdminConsoleClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/user/MultiUserCheAdminTestUserProvider.java
Labels: kind/bug, status/code-review, team/che-qe

#9478 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#9483 Add dependencies for terminations
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientTermination.java
  wsmaster/che-core-api-system/src/main/java/org/eclipse/che/api/system/server/ServiceTermination.java
  wsmaster/che-core-api-system/src/main/java/org/eclipse/che/api/system/server/ServiceTerminator.java
  wsmaster/che-core-api-system/src/test/java/org/eclipse/che/api/system/server/SystemTerminatorTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTermination.java
Labels: kind/enhancement, status/code-review, target/branch

#9492 Added starting servers checkers after recovering only for RUNNING workspaces
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesRuntimeContext.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesMachineCache.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesRuntimeStateCache.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/KubernetesMachinesCacheTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/KubernetesRuntimeStateCacheTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftRuntimeContext.java
Labels: kind/bug, status/code-review

#9463 Kubernetes client shutdown via termination
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientTermination.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  wsmaster/che-core-api-system/src/main/java/org/eclipse/che/api/system/server/ServiceTermination.java
  wsmaster/che-core-api-system/src/main/java/org/eclipse/che/api/system/server/ServiceTerminator.java
  wsmaster/che-core-api-system/src/test/java/org/eclipse/che/api/system/server/SystemTerminatorTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTermination.java
Labels: kind/bug, status/code-review, target/branch

#9490 Make Keycloak Admin configurable
  deploy/openshift/templates/multi/keycloak-template.yaml
  dockerfiles/keycloak/kc_realm_user.sh
Labels: kind/question, status/code-review

#9493 Fixes to ocp script
  deploy/openshift/ocp.sh
Labels: kind/bug, status/code-review

#9495 Fix Github oAuth in dashboard
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/import-github-project/import-github-project.controller.ts
Labels: kind/bug, status/code-review

#9497 Use -gt as comparison operator
  deploy/openshift/ocp.sh
Labels: status/code-review

#9499 Fix injection of default user in selenium tests of SingleUser Che
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/CheTestAuthServiceClient.java
Labels: kind/bug, status/code-review, team/che-qe

#9503 Selenium: Covers more steps of the "RenameProjectTest" selenium test by catching issue #9393
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/RenameProjectTest.java
Labels: kind/task, status/code-review

#9504 Fix bootstrapping fast failed when URL is invalid
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
Labels: kind/bug, status/code-review

#9514 Fix handling of outdated local Chrome version when create webdriver
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/SeleniumWebDriver.java
Labels: kind/task, status/code-review, team/che-qe

#9448 Selenium: adapt dashboard selenium tests for OSIO
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/TestGroup.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ToastLoader.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteRunningWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteStoppingWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/FactoriesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromZipTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspaceDetailsComposeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspaceDetailsSingleMachineTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspacesListTest.java
Labels: kind/task, status/code-review, team/che-qe

#9515 Remove duplicated declaration of artifact
  multiuser/api/che-multiuser-api-workspace-activity/pom.xml
Labels: status/code-review

#9509 Update OpenShift Origin version to 3.9
  deploy/openshift/ocp.sh
Labels: kind/enhancement, status/code-review

#9521 Upgrade php ls
  agents/ls-php/src/main/resources/installers/5.4.0/org.eclipse.che.ls.php.json
  agents/ls-php/src/main/resources/installers/5.4.0/org.eclipse.che.ls.php.script.sh
Labels: kind/enhancement, status/code-review

#9471 Add GitResetTest for covering git soft/mixed/hard reset feature
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/WorkspaceTemplate.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/Git.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitReset.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitResetTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/default_with_github_projects.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/default_with_github_projects.json
Labels: kind/enhancement, status/code-review

#9532 Rework organization-related tests to be executed in multi-thread mode
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestOrganizationServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestOrganizationServiceClientFactory.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/organization/TestOrganizationInjector.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumMultiUserModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/CheTestAdminOrganizationServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/CheTestDefaultOrganizationServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/requestfactory/CheTestDefaultHttpJsonRequestFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Swagger.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/Account.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AdminOfParentOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AdminOfSubOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/CreateRootOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationByBulkTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationInListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/FilterOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/MemberOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/OrganizationMembersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/RenameOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/SystemAdminOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/UserEmptyOrganizationTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#9533 Remove Keycloak job, use the right entrypoint, add envs the script re…
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/deployment.yaml
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/keycloak-configure-job.yaml
Labels: kind/question, status/code-review

#9529 CHE-9442: Fix Git exception when editing untracked or new file.
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitChangesDetector.java
Labels: kind/bug, status/code-review

#9522 Do not display hidden items in root of project tree
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/watcher/server/detectors/ProjectTreeTracker.java
Labels: kind/bug, status/code-review

#9558 Add info about bug #9548 into the PullRequestPluginWithForkTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginWithForkTest.java
Labels: kind/task, status/code-review, team/che-qe

#9524 Selenium: Rework the 'GitCompareTest' by use the 'kohsuke Github' library
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitCompare.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitCompareTest.java
Labels: kind/task, status/code-review, team/che-qe

#9575 README: Reference to roadmap and meetings
  README.md
Labels: kind/docs, status/code-review
