Repository eclipse-che/che, pull requests merged in 2018-07, with the labels that each got.

#10088 NPEs on workspace start-up #10083
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcError.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcErrorTransmitter.java
Labels: status/code-review

#10235 Fix version of jdtls runner
  agents/ls-java/src/main/resources/installers/1.0.1/org.eclipse.che.ls.java.script.sh
Labels: kind/bug, status/code-review, target/branch

#10165 Update Keycloak to 3.4.3.Final version
  dockerfiles/cli/images.template
  dockerfiles/cli/version/latest/images
  dockerfiles/cli/version/nightly/images
  dockerfiles/init/modules/keycloak/files/che/login/login-reset-password.ftl
  dockerfiles/init/modules/keycloak/files/che/login/login.ftl
  dockerfiles/init/modules/keycloak/files/che/login/register.ftl
  dockerfiles/keycloak/Dockerfile
Labels: kind/task, status/code-review

#10238 CHE-10215 fix factory templates
  dashboard/src/components/api/che-factory-template.factory.ts
  dashboard/src/components/api/factory-templates.ts
Labels: kind/bug, status/code-review

#10220 Selenium: Change the wait timeout in the 'Menu' to increase stability selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Menu.java
Labels: kind/task, status/code-review, team/che-qe

#10021 Use Deployments instead of Pods in Kubernetes/OpenShift infra
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelperTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectTest.java
Labels: kind/enhancement, status/code-review

#10237 Make it possible for Go agents to use auth tokens from HTTP header
  agents/go-agents/core/auth/auth.go
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/HttpConnectionServerChecker.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/ServersChecker.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/TerminalHttpConnectionServerChecker.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/HttpConnectionServerCheckerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/ServersCheckerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/TerminalHttpConnectionServerCheckerTest.java
Labels: status/code-review

#10245 Added doc for CHE_LOGGER_CONFIG in che.env file
  dockerfiles/init/manifests/che.env
Labels: kind/enhancement, status/code-review

#10221 Adapt selenium tests relaited to java refactoring
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/ChangePreview.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewNode.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewViewImpl.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/pom.xml
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/quickassist/ApplyWorkspaceEditAction.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/RenamePrivateFieldTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameMethodInInterfaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/preview/CheckTreeInRefactorPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/preview/PreviewRefactoringTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/refactor/move/test7/out/A.java
  selenium/che-selenium-test/src/test/resources/projects/rename-non-private-field/pom.xml
  selenium/che-selenium-test/src/test/resources/projects/rename-parameters/pom.xml
  selenium/che-selenium-test/src/test/resources/projects/rename-private-field/pom.xml
Labels: kind/bug, status/code-review, target/branch, team/languages

#10214 Selenium: cover workspace creation from Java stack by selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/HttpUtil.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestBuildConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestCommandsConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestIntelligentCommandsConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestProjectExplorerContextMenuConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Consoles.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Ide.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/CreateWorkspaceHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/plugins/JavaTestRunnerPluginConsole.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/PhpProjectDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/StepIntoStepOverStepReturnWithChangeVariableTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/gwt/CheckSimpleGwtAppTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckMacrosFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckRestoringWorkspaceAfterStoppingWsAgentProcessTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithSplitPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckHiddenFolderAndFileCreatedFromCommandTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromPythonStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/WorkingWithJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/WorkingWithNodeWsTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#10244 Added cascade removing of Kubernetes runtime state when a workspace is removed
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/BeforeKubernetesRuntimeStateRemovedEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesMachineCache.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesRuntimeCacheModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesRuntimeStateCache.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/model/KubernetesRuntimeState.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  wsmaster/integration-tests/cascade-removal/pom.xml
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/TestObjectsFactory.java
  wsmaster/integration-tests/postgresql-tck/src/test/java/PostgreSqlTckModule.java
Labels: kind/bug, status/code-review

#10196 Fixed absence of internal servers in WorkspaceProjectSynchronizer
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/WorkspaceProjectSynchronizer.java
Labels: kind/bug, status/code-review

#10249 Fix machine auth by using own user token instead of workspace owner token.
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/AgentHttpJsonRequestFactory.java
Labels: kind/bug, status/code-review

#10254 Fixed maven build without test sources compiling
  infrastructures/docker/environment/pom.xml
  infrastructures/openshift/pom.xml
  multiuser/api/che-multiuser-api-authorization-impl/pom.xml
  multiuser/api/che-multiuser-api-authorization/pom.xml
  multiuser/api/che-multiuser-api-permission/pom.xml
  multiuser/api/che-multiuser-api-resource/pom.xml
  multiuser/api/che-multiuser-api-workspace-activity/pom.xml
  multiuser/integration-tests/che-multiuser-cascade-removal/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication-agent/pom.xml
  multiuser/permission/che-multiuser-permission-factory/pom.xml
  multiuser/permission/che-multiuser-permission-installer/pom.xml
  multiuser/permission/che-multiuser-permission-logger/pom.xml
  multiuser/permission/che-multiuser-permission-resource/pom.xml
  multiuser/permission/che-multiuser-permission-system/pom.xml
  multiuser/permission/che-multiuser-permission-user/pom.xml
  multiuser/permission/che-multiuser-permission-workspace-activity/pom.xml
  multiuser/permission/che-multiuser-permission-workspace/pom.xml
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/pom.xml
  plugins/plugin-machine/che-plugin-machine-ext-server/pom.xml
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-server/pom.xml
  selenium/che-selenium-test/pom.xml
  wsmaster/che-core-api-factory/pom.xml
  wsmaster/che-core-api-logger/pom.xml
  wsmaster/che-core-api-user/pom.xml
  wsmaster/che-core-api-workspace-activity/pom.xml
  wsmaster/che-core-api-workspace/pom.xml
Labels: kind/bug, status/code-review

#10191 Creating selenium framework tests (abstraction for rh-che)
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/AbstractTestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/CheTestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/entrance/Entrance.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/AbstractTestWorkspaceProvider.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestWorkspaceProvider.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspace.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceImpl.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/entrance/CookieEntrance.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/entrance/LoginPageEntrance.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/CheTestWorkspaceAgentApiEndpointUrlProvider.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
Labels: status/code-review

#10267 Fix namespace for deployment under OCP user account
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
Labels: kind/bug, status/code-review

#10246 Adjust Workspace.Next model classes to latest updates in the Workspace.Next vision
  deploy/kubernetes/kubectl/Deploy Che.md
  deploy/kubernetes/kubectl/che-kubernetes.yaml
  deploy/kubernetes/kubectl/wsnext/Dockerfile
  deploy/kubernetes/kubectl/wsnext/Readme.md
  deploy/kubernetes/kubectl/wsnext/feature-api.yaml
  deploy/openshift/templates/README.md
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/wsnext/feature-api.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsnext/KubernetesWorkspaceNextApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsnext/KubernetesWorkspaceNextApplierTest.java
  wsmaster/che-core-api-workspace/pom.xml
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/ServerChecker.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/ServersChecker.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/WorkspaceNextApplier.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/WorkspaceNextObjectsRetriever.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheContainer.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheContainerPort.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheFeatureSpec.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/ChePlugin.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/ChePluginEndpoint.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/ChePluginParameter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/ChePluginReference.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheServiceParameter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheServiceReference.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/Container.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/Server.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/wsnext/WorkspaceNextObjectsRetrieverTest.java
Labels: kind/enhancement, status/code-review

#10279 Fix failing test & check formatting
  agents/go-agents/core/auth/auth.go
  agents/go-agents/core/auth/auth_test.go
  agents/go-agents/core/auth/sign_key.go
Labels: kind/bug, status/code-review

#10239 Fix logic error in CSharpFileEditingTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CSharpFileEditingTest.java
Labels: kind/bug, status/code-review

#10172 CHE-9418: Fix Git status message if the repository is checkouted to tag or commit.
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerViewImpl.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/vcs/GitVcsService.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutReferenceTest.java
  wsagent/che-core-api-git-shared/src/main/java/org/eclipse/che/api/git/shared/Status.java
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitConnection.java
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitValueProviderFactory.java
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/Reference.java
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/ReferenceType.java
  wsagent/che-core-api-git/src/test/java/org/eclipse/che/git/impl/StatusTest.java
  wsagent/che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConnection.java
  wsagent/che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitStatusImpl.java
  wsagent/che-core-git-impl-jgit/src/test/java/org/eclipse/che/git/impl/jgit/JGitConnectionTest.java
Labels: kind/bug, status/code-review

#10253 Disables format action in menu when formatting is not supported
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/editor/formatter/ContentFormatter.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorPresenter.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/LanguageServerFormatter.java
Labels: kind/bug, status/code-review, team/ide

#10152 Fix Routing Strategy Docs
  deploy/kubernetes/helm/che/readme.md
Labels: kind/enhancement, status/code-review

#10289 Selenium: fix locators for Keycloak Federated Identities page
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakFederatedIdentitiesPage.java
Labels: kind/bug, status/code-review, team/che-qe

#10269 Selenium: Fix reason of failing the "RollingUpdateStrategyWithEditorTest" selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/WebDriverWaitFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/hotupdate/HotUpdateUtil.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/recreate/RecreateUpdateStrategyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithWorkspacesStartStopTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10266 Refactored external servers exposition in K8s/OS infrastructures
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/server/ServersConverter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/AbstractIngressExternalServerExposerStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/ServerServiceBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/DefaultHostIngressExternalServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServerExposerStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServerExposerStrategyProvider.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServerIngressBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/MultiHostIngressExternalServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/SingleHostIngressExternalServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/IngressTlsProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/DefaultHostIngressExternalServerExposerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServerIngressBuilderTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/MultiHostIngressExternalServerExposerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftExternalServerExposer.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftServerExposerTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftExternalServerExposerTest.java
Labels: kind/enhancement, status/code-review

#10233 Optimizing che-theia-factory loading sequence by adding it to the def…
  dockerfiles/theia/src/package.json
Labels: kind/enhancement, status/code-review

#10218 CHE-9052: Fix bug when file was deleted after move
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/impl/CopyPasteManager.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/impl/ResourceManager.java
  ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestProjectExplorerContextMenuConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ChoiceDialog.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckCopyCutFeaturesForFilesTest.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/ValidatingFsManager.java
Labels: kind/bug, status/code-review

#10297 Selenium: Fix unexpected fail of "NewWorkspacePageTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10304 Selenium: Remove catching of known issue #8122
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewPackagesWithHelpCreationJavaClassTest.java
Labels: kind/task, status/code-review, team/che-qe

#10301 Refine code ownership
  .github/CODEOWNERS
Labels: status/code-review

#9616 Custom socket provider and java language server in sidecar
  agents/ls-java/src/main/resources/installers/1.0.1/org.eclipse.che.ls.java.script.sh
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/WorkspaceConfigProvider.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#10293 Fixed offset and range calculation for full text and range formatting.
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/LanguageServerFormatter.java
Labels: kind/bug, status/code-review, team/ide

#10315 Fixed error logging for Go LS when going to definition
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/che/jdt/javaeditor/JavaReconciler.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/editor/server/impl/EditorWorkingCopyManager.java
Labels: kind/bug, status/code-review, team/ide

#10173 CHE-9154: Fix authorization message
  plugins/plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.properties
Labels: kind/bug, status/code-review

#10320 Selenium: Implement usecase which covers opening a file from libraries after refreshing
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/OpenExternalLibraryFileAfterRefreshTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#10263 Change the loading flow by always wait the runtime before open IDE
  workspace-loader/src/index.ts
  workspace-loader/src/loader/loader.ts
  workspace-loader/src/style.css
  workspace-loader/test/test.spec.ts
Labels: kind/bug, status/code-review

#10179 Correct revert unsaved preference changes
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/ThemeAgent.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/DefaultIdeInitializationStrategy.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/FactoryIdeInitializationStrategy.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/welcome/preferences/ShowWelcomePreferencePagePresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/preferences/PreferencesPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/preferences/pages/general/IdeGeneralPreferencesPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/ThemeAgentImpl.java
  plugins/plugin-debugger/che-plugin-debugger-ide/src/main/java/org/eclipse/che/plugin/debugger/ide/DebuggerExtension.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/ContributionExtension.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Preferences.java
Labels: kind/bug, severity/P2, status/code-review, team/ide

#10310 Tune a list of owners for infrastructure and multi-user modules
  .github/CODEOWNERS
Labels: status/code-review

#10344 Selenium: fix testing code assistant feature in PhpFileEditingTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PhpFileEditingTest.java
Labels: kind/bug, selenium/failure, status/code-review, team/che-qe

#10317 "Minor typographical improvements to localization file" by zv-io
  ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestProjectExplorerContextMenuConstants.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/assistant/KeyBindingsTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/assistant/key-bindings.txt
Labels: status/code-review

#10362 Clean cached classpath on error
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/command/ClasspathContainer.java
Labels: kind/bug, team/languages

#10353 Selenium: Update the 'CreateFactoryTest' according to the test plan
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/DashboardFactories.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/factories/CreateFactoryPage.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/dashboard/config-ws.json
Labels: kind/task, status/code-review, team/che-qe

#10339 Fix Simple Java Project Creation
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/generator/PlainJavaProjectGenerator.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/resources/org/eclipse/che/plugin/java/plain/server/generator/Main.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/resources/org/eclipse/che/plugin/java/plain/server/generator/classpath
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/resources/org/eclipse/che/plugin/java/plain/server/generator/project
Labels: kind/bug, status/code-review, target/branch, team/languages

#10271 Selenium: cover workspace creation from Ubuntu stacks by selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestBuildConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestCommandsConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestIntelligentCommandsConstants.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCppStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromEclipseCheStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromGoStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaDockerStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaOpenshiftStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromKotlinStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromNETStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromNodeStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromPHPStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromRailsStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/WorkingWithJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#10363 Send and handle ProjectCreatedEvent
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProjectsListener.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
Labels: kind/bug, team/languages

#10377 Fix sequence of selenium test package execution
  selenium/che-selenium-test/pom.xml
Labels: kind/bug, team/che-qe

#10268 Different Quickfix Behaviour Java vs. LSP #10112
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/quickassist/LanguageServerQuickAssistProcessor.java
Labels: kind/bug, status/code-review, team/languages

#10382 Selenum: fix 'start apache' command in CreateWorkspaceFromPHPStackTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromPHPStackTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10383 Delete the 'try/catch' from the 'ContributeTabTest' according to resolving issues #9959 #10019
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/ContributeTabTest.java
Labels: kind/task, status/code-review, team/che-qe

#10391 clean up k8s config map
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: status/code-review

#10354 Selenium: Create selenium test for covering issue #9620 "In case ws-agent stopped unexpectedly all editors should become in readonly mode or close them"
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckRestoringWorkspaceAfterStoppingWsAgentProcessTest.java
Labels: kind/task, status/code-review, team/che-qe

#10389 Make sure dot-files don't exist before creating them.
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestProjectServiceClient.java
Labels: kind/bug, selenium/failure, status/code-review, target/branch, team/languages

#10397 Check when ws-edit changes were applied
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/FailMoveItemTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveItemsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveJavaClassToSubpackageTest.java
Labels: status/code-review, target/branch, team/languages

#10376 Selenium: cover Apache Camel language server functionality by selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/WorkspaceTemplate.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ApacheCamelFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/project-for-camel-ls/camel.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/ubuntu_jdk8_with_camel_ls.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_jdk8_with_camel_ls.json
Labels: kind/task, status/code-review, team/che-qe

#10379 Update regex for c-based file extensions
  plugins/plugin-clangd/che-plugin-clangd-lang-server/src/main/java/org/eclipse/plugin/clangd/languageserver/ClangDLanguageServerConfig.java
Labels: kind/bug, severity/P2, status/code-review, team/ide

#10407 Fixed binding of jwt proxy secure servers for Che on K8s/OS
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/SecureServerExposerFactoryProvider.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/SecureServerExposerFactoryProviderTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
Labels: kind/bug, status/code-review

#10401 Selenium: Update priorities of the test methods in the 'ImportWizardFormTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
Labels: kind/task, status/code-review, team/che-qe

#10411 Announce code assist snippet support
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/InitializeParamsProvider.java
Labels: kind/bug, selenium/failure, status/code-review, target/branch, team/languages

#10385 Validate infrastructure related configuration only on start workspace
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceValidator.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceValidatorTest.java
Labels: status/code-review

#10418 Fix selenium tests
  plugins/plugin-java-debugger/che-plugin-java-debugger-ide/src/main/java/org/eclipse/che/plugin/jdb/ide/debug/ExternalResourceLocationHandler.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/tree/library/JarFileNode.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ConditionalBreakpointsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/DebugExternalClassTest.java
Labels: kind/bug, status/code-review, target/branch

#10433 Selenium: fix 'run' command in 'CentOS WildFly Swarm' predefined stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCentosWildFlySwarmStackTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10432 Small fixups for git package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitChangeMarkersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/RevertCommitTest.java
Labels: kind/task, status/code-review, target/branch

#10414 10413 address lsp doc popup
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/ContentAssistWidget.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
Labels: kind/bug, selenium/failure, status/code-review, target/branch, team/languages

#10328 Added go test and go build
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#10450 Selenium: remove selenium tests from OSIO test group
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteRunningWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteStoppingWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromZipTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsComposeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsSingleMachineTest.java
Labels: kind/task, status/code-review, team/che-qe

#10421 Update regex for initializing C# language server
  plugins/plugin-csharp/che-plugin-csharp-lang-server/src/main/java/org/eclipse/che/plugin/csharp/languageserver/CSharpLanguageServerConfig.java
Labels: kind/bug, status/code-review

#10434 Selenium: cover JSON language server functionality by selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/WorkspaceTemplate.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Wizard.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/JsonFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/nodejs_with_json_ls.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/nodejs_with_json_ls.json
Labels: kind/task, status/code-review, team/che-qe

#10453 Selenium: Increase stability of the "CheckIntelligenceCommandFromToolbarTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsToolbar.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10440 CHE-10286: Switch import rest methods to Json-rpc
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/project/ProjectServiceClient.java
  ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/project/ProjectServiceClientTest.java
  ide/commons-gwt/pom.xml
  ide/commons-gwt/src/main/java/org/eclipse/che/ide/jsonrpc/JsonRpcErrorUtils.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/LanguageServerServiceClient.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/TextDocumentServiceClient.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/WorkspaceServiceClient.java
  wsagent/che-core-api-project-shared/src/main/java/org/eclipse/che/api/project/shared/Constants.java
  wsagent/che-core-api-project-shared/src/main/java/org/eclipse/che/api/project/shared/dto/service/CreateBatchProjectsRequestDto.java
  wsagent/che-core-api-project-shared/src/main/java/org/eclipse/che/api/project/shared/dto/service/ImportRequestDto.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectApiModule.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectJsonRpcServiceConfigurator.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectJsonRpcServiceBackEnd.java
Labels: kind/bug, status/code-review

#10422 Open folder in terminal
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/OpenInTerminalAction.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/panel/ProcessesPanelPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/terminal/TerminalOptionsJso.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/terminal/TerminalPresenter.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestProjectExplorerContextMenuConstants.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/OpenInTerminalTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/enhancement, status/code-review

#10468 Selenium: adapt selenium tests according to changes in the flow for adding a new stack
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/stacks/Stacks.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/StacksListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
Labels: kind/task, status/code-review, team/che-qe

#10471 Fix selenium tests in editor package
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/LanguageServerExtension.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
Labels: kind/task, status/code-review, target/branch

#10452 Fix selenium tests in projectexplorer package
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorAgentImpl.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckShowHideHiddenFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DownloadProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/NavigationByKeyboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/UploadIntoProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/OpenExternalLibraryFileAfterRefreshTest.java
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/.codenvy/misc.xml
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/.codenvy/project.json
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/pom.xml
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/com/codenvy/example/spring/GreetingController.java
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/com/codenvy/example/spring/SomeLess.less
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/com/codenvy/example/spring/SqlFile.sql
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/com/codenvy/example/spring/some
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/com/codenvy/example/test/Test1.java
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/com/codenvy/example/test/Test2.java
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/com/codenvy/example/test/Test3.java
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/com/codenvy/example/test/Test4.java
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/java/org/eclipse/qa/examples/AppController.java
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/webapp/WEB-INF/DefaultCss.css
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/webapp/WEB-INF/SomeHtml.html
  selenium/che-selenium-test/src/test/resources/projects/ProjectWithDifferentTypeOfFiles2/src/main/webapp/WEB-INF/someJS.js
Labels: kind/task, status/code-review, target/branch, team/languages

#10467 Simplify the theia stack from 2 machines to 1 with Theia only
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: status/code-review

#10478 allow to not define GITHUB_TOKEN to build.sh if api rate limit on github is enough
  dockerfiles/theia/Dockerfile
Labels: kind/enhancement, status/code-review

#10485 Selenium: check workspace action buttons on Workspaces list page
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/dashboard/expectedWorkspaceConfTemplate.txt
Labels: status/code-review, team/che-qe

#10483 [docker] [theia] Enable the theia plug-in generator in theia image
  dockerfiles/theia/Dockerfile
Labels: status/code-review

#10367 CHE-10097, CHE-10098, CHE-256: fix bugs related to installers on Stack Details page
  dashboard/src/app/stacks/stack-details/stack.controller.ts
  dashboard/src/app/stacks/stack-details/stack.spec.ts
  dashboard/src/app/workspaces/workspace-details/environments/environments.html
  dashboard/src/app/workspaces/workspace-details/environments/machine-config/machine-config.controller.ts
  dashboard/src/app/workspaces/workspace-details/environments/machine-config/machine-config.directive.ts
  dashboard/src/app/workspaces/workspace-details/environments/machine-config/machine-config.html
  dashboard/src/app/workspaces/workspace-details/machine-selector/machine-selector.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.html
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.directive.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-agents/machine-agents.html
  dashboard/src/components/api/builder/che-agent-builder.ts
  dashboard/src/components/api/che-agent.factory.ts
  dashboard/src/components/api/test/che-http-backend.ts
Labels: kind/bug, status/code-review

#10482 Added page which set up authentication cookie via jwtproxy
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.html
Labels: kind/task, status/code-review, target/branch

#10498 Selenium: adapt selenium tests that work with Theia stack
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaDockerStackTest.java
Labels: kind/task, team/che-qe

#10475 Selenium: Finish creating the test methods in the 'UploadIntoProjectTest'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/upload/AbstractUploadDialogPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/upload/UploadDirectoryDialogPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/upload/UploadFileDialogPage.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/UploadIntoProjectTest.java
Labels: kind/task, status/code-review, team/che-qe

#10164 Generate yarn cache with THEIA_VERSION. Generate resolutions to use strict Theia dependencies
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/README.md
  dockerfiles/theia/src/add-extensions.js
  dockerfiles/theia/src/extensions.json
  dockerfiles/theia/src/resolutions-provider.js
Labels: status/code-review

#10492 Improve java debug performance to fetch list of threads/frames/variables
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/debug/DebuggerServiceClient.java
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/debug/DebuggerServiceClientImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/debug/Debugger.java
  plugins/plugin-debugger/che-plugin-debugger-ide/src/main/java/org/eclipse/che/plugin/debugger/ide/debug/AbstractDebugger.java
  plugins/plugin-debugger/che-plugin-debugger-ide/src/main/java/org/eclipse/che/plugin/debugger/ide/debug/DebuggerPresenter.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/main/java/org/eclipse/che/plugin/jdb/server/JavaDebugger.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/main/java/org/eclipse/che/plugin/jdb/server/model/JdbLocation.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/main/java/org/eclipse/che/plugin/jdb/server/model/JdbStackFrame.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/StackFrameDumpTest1.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/ThreadDumpTest1.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ThreadDumpTest.java
  wsagent/che-core-api-debug/src/main/java/org/eclipse/che/api/debugger/server/Debugger.java
  wsagent/che-core-api-debug/src/main/java/org/eclipse/che/api/debugger/server/DebuggerService.java
Labels: kind/bug, status/code-review, team/languages

#10511 Parse THEIA_PORT environment variable
  dockerfiles/theia/src/start.sh
Labels: kind/question, status/code-review

#10463 Add exclusions mechanism into jwtproxy config builder & exlude liveness probes from auth
  agents/exec/installer/src/main/resources/installers/1.0.0/org.eclipse.che.exec.json
  agents/exec/installer/src/main/resources/installers/1.0.1/org.eclipse.che.exec.json
  agents/terminal/src/main/resources/installers/1.0.0/org.eclipse.che.terminal.json
  agents/terminal/src/main/resources/installers/1.0.1/org.eclipse.che.terminal.json
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/ServerConfig.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateSyncWriter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyConfigBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyConfigBuilderTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposerTest.java
  infrastructures/kubernetes/src/test/resources/jwtproxy-confg.yaml
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenRegistry.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestProjectServiceClient.java
  wsagent/agent/src/main/resources/installers/1.0.0/org.eclipse.che.ws-agent.json
  wsagent/agent/src/main/resources/installers/1.0.1/org.eclipse.che.ws-agent.json
  wsagent/agent/src/main/resources/installers/1.0.2/org.eclipse.che.ws-agent.json
  wsagent/agent/src/main/resources/installers/1.0.3/org.eclipse.che.ws-agent.json
Labels: kind/task, status/code-review

#10526 Add the re-selection of the project in the test 'AmendCommitTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AmendCommitTest.java
Labels: kind/task, status/code-review, team/che-qe

#10528 Add service discovery of ChePluginEndpoint of sidecar tooling container on k8s/OS infras
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsnext/KubernetesWorkspaceNextApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsnext/KubernetesWorkspaceNextApplierTest.java
Labels: kind/question, status/code-review

#10405 Restore the dependencies on creating a C# project
  plugins/plugin-csharp/che-plugin-csharp-lang-server/pom.xml
  plugins/plugin-csharp/che-plugin-csharp-lang-server/src/main/java/org/eclipse/che/plugin/csharp/languageserver/CSharpLanguageServerConfig.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerInitializedEvent.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerInitializer.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerService.java
Labels: kind/enhancement, status/code-review

#10525 Selenium: cover Yaml language server functionality by selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/WorkspaceTemplate.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Preferences.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/YamlFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/nodejs-with-yaml/deployment.yaml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/eclipse_nodejs_with_yaml_ls.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_nodejs_with_yaml_ls.json
Labels: kind/task, status/code-review, team/che-qe

#10513 Fix start of a workspace with Theia on k8s infra
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review

#10546 che #10444: Fixing NumberFormatException occurences during the 'watchEvents' calls on k8s infrastructure
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/PodEvents.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/PodEventsTest.java
Labels: kind/bug, status/code-review

#10534 Set vcs status marker only for resource related editor tabs
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/EditorPartStackPresenter.java
Labels: kind/bug, status/code-review

#10527 Fix exceptions at opening an editor that does not correspond to an existing resource
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/FileOpenCloseEventListener.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/core/reconcile/PomReconciler.java
  plugins/plugin-testing-java/plugin-testing-testng/che-plugin-testing-testng-server/src/main/java/org/eclipse/che/plugin/testing/testng/server/TestNGRunner.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/editor/server/impl/EditorWorkingCopyManager.java
Labels: kind/bug, status/code-review

#10503 Add notifier about low disk space
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/CoreGinModule.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/FreeDiskSpaceNotifier.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/FreeDiskSpaceStatusBarAction.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java
  ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/FreeDiskSpaceChecker.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/FreeDiskSpaceCheckerCommunication.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/WsAgentModule.java
Labels: kind/enhancement, severity/P2, status/code-review, team/ide

#10558 Selenium: Create test 'ImportAndValidateEclipseCheProjectTest'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/InformationDialog.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/MavenPluginStatusBar.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/ImportAndValidateEclipseCheProjectTest.java
Labels: kind/task, status/code-review, team/che-qe

#10443 Added more information in error output
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
Labels: kind/enhancement, status/code-review

#10575 Added page which set up authentication cookie via jwtproxy
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.html
Labels: kind/task, status/code-review

#10578 Fix workspace-loader application build
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.html
  workspace-loader/.gitignore
  workspace-loader/package-lock.json
  workspace-loader/package.json
Labels: kind/bug, status/code-review, target/branch, team/languages

#10552 [ Theia Docker image] Updates
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/src/add-extensions.js
  dockerfiles/theia/src/extensions.json
  dockerfiles/theia/src/package.json
  dockerfiles/theia/src/patches/0.3.12/001-regexp.patch
  dockerfiles/theia/src/setup.sh
  dockerfiles/theia/src/versions.sh
Labels: kind/enhancement, status/code-review

#10533 CHE-10365: Add websocket reconnection feature to workspace loader app
  workspace-loader/package.json
  workspace-loader/src/index.ts
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/json-rpc/json-rpc-client.ts
  workspace-loader/src/json-rpc/websocket-client.ts
Labels: kind/task, status/code-review

#10598 Selenium: Update license header in 'MachinesAsynchronousStartTest' selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/MachinesAsynchronousStartTest.java
Labels: kind/bug, status/code-review

#10387 Add Proxy env variables for workspace containers in Openshift and Kub…
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
  deploy/openshift/templates/che-server-template.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ProxySettingsProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
Labels: kind/enhancement, status/code-review
