Repository eclipse-che/che, pull requests merged in 2018-02, with the labels that each got.

#8709 Increase postgres claim for OpenShift to be 1gb
  dockerfiles/init/modules/openshift/files/scripts/multi-user/keycloak/keycloak-data-claim.yaml
  dockerfiles/init/modules/openshift/files/scripts/multi-user/keycloak/keycloak-log-claim.yaml
  dockerfiles/init/modules/openshift/files/scripts/multi-user/postgres/postgres-data-claim.yaml
Labels: status/code-review

#8685 Selenium: Create new class 'WebDriverWaitFactory'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/WebDriverWaitFactory.java
Labels: kind/task, status/code-review

#8714 UI for workspace-loader
  wokspace-loader/src/index.html
  wokspace-loader/src/index.ts
  wokspace-loader/src/loader/loader.ts
  wokspace-loader/src/style.css
  wokspace-loader/tsconfig.json
  wokspace-loader/webpack.common.js
  wokspace-loader/webpack.dev.js
  wokspace-loader/webpack.prod.js
Labels: kind/enhancement, status/code-review, target/branch

#8718 Fix name of workspace-loader directory
  pom.xml
  workspace-loader/.gitignore
  workspace-loader/assembly.xml
  workspace-loader/package-lock.json
  workspace-loader/package.json
  workspace-loader/pom.xml
  workspace-loader/src/custom.d.ts
  workspace-loader/src/index.html
  workspace-loader/src/index.ts
  workspace-loader/src/json-rpc/che-json-rpc-api-service.ts
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/json-rpc/json-rpc-client.ts
  workspace-loader/src/json-rpc/util.ts
  workspace-loader/src/json-rpc/websocket-client.ts
  workspace-loader/src/rest.ts
  workspace-loader/src/style.css
  workspace-loader/src/workspace.ts
  workspace-loader/tsconfig.json
  workspace-loader/tslint.json
  workspace-loader/webpack.common.js
  workspace-loader/webpack.dev.js
  workspace-loader/webpack.prod.js
Labels: kind/bug, status/code-review, target/branch

#8722 Selenium: Update CheckErrorMessageWhenCreationDuplicateFolderOrFileTest for increasing stability
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckErrorMessageWhenCreationDuplicateFolderOrFileTest.java
Labels: kind/bug, status/code-review

#8686 [WIP] CHE-8365: Fix opening empty files when soft wrap options is activated in editor
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorPresenter.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorWidget.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionTextViewOverlay.java
Labels: kind/bug, status/code-review

#8664 Fix perspective initialization in case switching perspective
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/perspectives/project/ProjectPerspective.java
Labels: kind/bug, status/code-review

#8726 Disable pre-creating of PVC subpaths on minikube
  dockerfiles/init/modules/kubernetes/files/che-kubernetes.yaml
Labels: kind/task, status/code-review

#8730 Fix formatting issue
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/perspectives/project/ProjectPerspective.java
Labels: kind/bug, status/code-review, team/ide

#8610 Directory created from terminal doesn't appear in project explorer root
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectApiModule.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/OnWorkspaceStartProjectInitializer.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectConfigRegistry.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/RootDirCreationHandler.java
Labels: kind/bug, status/code-review

#8723 Fix keyboard filter in File Structure dialog
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/filestructure/FileStructureWindow.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/filestructure/FileStructureView.java
Labels: kind/bug, status/code-review, target/branch

#8725 Selenium: wait opened workspace is ready to use
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromZipTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspaceDetailsComposeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckCreatingProjectInEmptyWsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckMacrosFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckRestoringWorkspaceAfterStoppingWsAgentProcess.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ConvertToProjectFromConfigurationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ConvertToProjectWithPomFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/DialogAboutTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureBaseOperationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureByKeyboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureCodeEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureNodesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindTextFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindUsagesBaseOperationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ImplementationBaseOperationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ResolveDependencyAfterRecreateProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ServerRuntimeInfoTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithSplitPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithJavaMySqlStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkingWithNodeWsTest.java
Labels: kind/task, status/code-review, team/che-qe

#8734 CHE-8414: Fix selenium test according to new behaviour of JDT LS
  selenium/che-selenium-test/pom.xml
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportProjectIntoSpecifiedBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckGeneratingMavenArchetypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureBaseOperationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureByKeyboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureCodeEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureNodesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindUsagesBaseOperationTest.java
  selenium/che-selenium-test/src/test/resources/projects/checkoutSpringSimple/.gitignore
  selenium/che-selenium-test/src/test/resources/projects/create-local-branch-project/.gitignore
  selenium/che-selenium-test/src/test/resources/projects/default-spring-project/.gitignore
  selenium/che-selenium-test/src/test/resources/projects/java-project-for-multiselect/.gitignore
  selenium/che-selenium-test/src/test/resources/projects/simple-java-project/.gitignore
Labels: kind/task, status/code-review, target/branch

#8612 CHE-7278 Properly handle restarting the workspace
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/jsonrpc/WsMasterJsonRpcInitializer.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/loading/ShowWorkspaceStatusAction.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/loading/WorkspaceLoadingTrackerImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/loading/WorkspaceLoadingTrackerView.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/loading/WorkspaceLoadingTrackerViewImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/loading/WorkspaceLoadingTrackerViewImpl.ui.xml
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/StartWorkspaceAction.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/events/WorkspaceStatusEventHandler.java
  ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
  ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/command/toolbar/processes/styles.css
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/ContributionMixinProvider.java
Labels: kind/bug, status/code-review

#8736 Selenium: change a way for selecting an element from suggestions list
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/NavigateToFile.java
Labels: kind/task, status/code-review, team/che-qe

#8743 CHE-8414: Fix selenium test according to new behaviour of JDT LS
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportProjectIntoSpecifiedBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0087Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0091Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0093Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0097Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0114Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0115Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0119Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0120Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0121Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0122Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/RunPlainJavaProjectTest.java
Labels: kind/task, status/code-review, target/branch

#8656 CHE-8580: Use URI for Classfiles in Java Debugger
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/tree/library/JarFileNode.java
Labels: kind/enhancement, status/code-review, target/branch

#8754 Support enter press in refactoring rename form
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenameViewImpl.java
Labels: kind/enhancement, status/code-review, team/ide

#8755 Selenium: increase timeout to check that a menu item is enabled
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Menu.java
Labels: status/code-review, team/che-qe

#8746 Selenium: Add most common methods to the "SeleniumWebDriverHelper"
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Preferences.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/DashboardAccount.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakAccountPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakFederatedIdentitiesPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakHeaderButtons.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakPasswordPage.java
Labels: kind/task, status/code-review, team/che-qe

#8757 Add different style for focusable element
  ide/commons-gwt/src/main/resources/org/eclipse/che/ide/ui/listbox/ListBox.css
Labels: kind/bug, status/code-review, target/che6, team/ide

#8760 Fix displaying pull request panel
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/ContributionMixinProvider.java
Labels: kind/bug, status/code-review

#8772 Selenium: Catch issue #7161 in 'ShowHintsCommandTest' selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/ShowHintsCommandTest.java
Labels: kind/bug, status/code-review

#8491 Bug with closing tabs in processes panel
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/multisplitpanel/panel/SubPanelViewImpl.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithSplitPanelTest.java
Labels: kind/bug, status/code-review, team/plugin

#8762 Workspace loader dashboard
  dashboard/gulp/proxy.js
  dashboard/src/app/ide/ide.service.ts
  dashboard/src/components/api/che-organizations.factory.ts
  dashboard/src/components/api/test/che-http-backend.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  workspace-loader/src/index.ts
Labels: status/code-review, target/branch

#8764 Add back primary style for start workspace button
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/StartWorkspaceNotification.java
Labels: kind/bug, severity/P2, status/code-review, team/ide

#8780 Selenium: Add catch browser logs in the selenium tests from 'opendeclaration' package for investigating "#8122" bug
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteWithInheritTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/ShowHintsCommandTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0093Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0115Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0121Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewPackagesWithHelpCreationJavaClassTest.java
Labels: kind/bug, status/code-review

#8753 Fix orion document changing event getting text from native orion event instead of guessing it
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionDocument.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/ModelChangedEventOverlay.java
Labels: kind/bug, status/code-review

#8767 Thread-unsafe collections used for subscription contexts
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/RemoteSubscriptionManager.java
Labels: kind/bug, status/code-review, team/ide

#8710 Fix machine token generation on workspace start
  multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenInterceptor.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenProviderImpl.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenRegistry.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenInterceptorTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenRegistryTest.java
Labels: kind/bug, status/code-review

#8796 Selenium: remove unnecessary steps from CreateWorkspaceOnDashboardTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
Labels: status/code-review, team/che-qe

#8794 Selenium: add info about known issue
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjects.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ResolveDependencyAfterRecreateProjectTest.java
Labels: kind/bug, status/code-review, team/che-qe

#8795 Fix incorrect usage of k8s property in openshift infra
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
Labels: kind/bug

#8731 Show information about methods' signatures
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/popup/PopupResources.java
  ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/popup/popup.css
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/EditorInitializePromiseHolder.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorPresenter.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorWidget.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/inject/OrionEditorGinModule.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/signature/SignatureHelpResources.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/signature/SignatureHelpView.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/signature/SignatureWidget.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/signature/SignatureWidgetFactory.java
  ide/che-core-orion-editor/src/main/resources/org/eclipse/che/ide/editor/orion/client/signature/SignatureHelp.css
  ide/che-core-orion-editor/src/main/resources/org/eclipse/che/ide/editor/orion/client/signature/arrow.svg
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaExtension.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/action/ParametersHintsAction.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/paraminfo/ParametersHintsPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/paraminfo/ParametersHintsView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/paraminfo/ParametersHintsViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/paraminfo/ParametersHintsViewImpl.ui.xml
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/service/JavaNavigationService.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/service/JavaNavigationServiceImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/plugin/java/server/ParametersHints.java
  plugins/plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/plugin/java/server/rest/JavaNavigationService.java
  plugins/plugin-keybinding-eclipse/plugin-keybinding-eclipse-ide/src/main/java/org/eclipse/che/plugin/keybinding/EclipseKeyBinding.java
Labels: kind/enhancement, status/code-review, target/branch

#8804 Fix displaying the editor annotations for the corresponding diagnostics notifications
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorAgentImpl.java
Labels: status/code-review

#8803 Save meaningful logs of failed tests workspaces in the target directory
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/pom.xml
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestOrganizationServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/user/TestUserImpl.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/DockerUtil.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/FileUtil.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/UrlUtil.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/process/ProcessAgent.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/process/ProcessAgentException.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceLogsReader.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceLogsReaderTest.java
  selenium/che-selenium-test/pom.xml
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumDockerModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumOpenshiftModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/CheTestApiEndpointUrlProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/CheTestDashboardUrlProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/CheTestIdeUrlProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/requestfactory/CheTestAdminHttpJsonRequestFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestDockerWorkspaceLogsReader.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestOpenshiftWorkspaceLogsReader.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/account/KeycloakHeaderButtons.java
  selenium/che-selenium-test/src/test/resources/conf/selenium.properties
Labels: kind/task, status/code-review, team/che-qe

#8801 Add ability found artifacts in repositories described in pom.xml
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/core/classpath/ClasspathManager.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/core/project/MavenProject.java
  plugins/plugin-maven/maven-server/maven-server-impl/src/test/java/org/eclipse/che/maven/server/ProjectResolverTest.java
  plugins/plugin-maven/maven-server/maven-server-impl/src/test/resources/with-remote-repository/pom.xml
Labels: kind/bug, status/code-review, team/ide

#8715 Initial support for deploying Che to Kubernetes using Helm charts
  dockerfiles/init/modules/che-kubernetes-helm/.helmignore
  dockerfiles/init/modules/che-kubernetes-helm/Chart.yaml
  dockerfiles/init/modules/che-kubernetes-helm/readme.md
  dockerfiles/init/modules/che-kubernetes-helm/templates/_hostHelper.tpl
  dockerfiles/init/modules/che-kubernetes-helm/templates/_secretHelper.tpl
  dockerfiles/init/modules/che-kubernetes-helm/templates/cert-issuer.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/certificate.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/cluster-role-binding.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/configmap.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/deployment.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/ingress.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/pvc.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/registry-pull-secret.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/service.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/serviceaccount.yaml
  dockerfiles/init/modules/che-kubernetes-helm/templates/staging-cert-issuer.yaml
  dockerfiles/init/modules/che-kubernetes-helm/tiller-rbac.yaml
  dockerfiles/init/modules/che-kubernetes-helm/values.yaml
Labels: kind/enhancement, kind/epic, status/code-review

#8758 CHE-8575: Do not show .che folder in project explorer
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/OnWorkspaceStartProjectInitializer.java
Labels: kind/bug, status/code-review

#8818 fix CLI ENV vars setting / overriding
  dockerfiles/base/scripts/base/commands/cmd_config.sh
  dockerfiles/base/scripts/base/startup_04_pre_cli_init.sh
Labels: kind/bug, status/code-review

#8748 Enabe parallel pull of images in docker infra
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/DockerInfraModule.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/DockerInternalRuntime.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/DockerMachineStarter.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/ParallelDockerImagesBuilder.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/ParallelDockerImagesBuilderFactory.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/DockerInternalRuntimeTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/ParallelDockerImagesBuilderTest.java
Labels: kind/enhancement, status/code-review

#8717 Remove exec/terminal agents from dependencies of ws-agent
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspaceDetailsSingleMachineTest.java
  selenium/che-selenium-test/src/test/resources/templates/factory/docker/minimal.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/default.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/eclipse_cpp_gcc.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/eclipse_nodejs.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/eclipse_php.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/ubuntu.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/ubuntu_jdk8.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/ubuntu_with_c_sharp_lsp.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/centos_jdk8_openshift_recipe.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/default.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_cpp_gcc.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_nodejs.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_php.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_jdk8.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_with_c_sharp_lsp.json
  wsagent/agent/src/main/resources/installers/1.0.3/org.eclipse.che.ws-agent.json
Labels: kind/task, status/code-review

#8814 Set up default file encoding to utf8 in workspace agent configuration
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  dockerfiles/init/manifests/che.env
Labels: kind/bug, status/code-review, team/ide

#8834 CHE CLI: Space in NO_PROXY leads to failed startup
  dockerfiles/init/modules/che/templates/che.env.erb
Labels: kind/bug, status/code-review

#8833 Selenium: change method to get a number of root organizations
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestOrganizationServiceClient.java
Labels: kind/bug, status/code-review, team/che-qe

#8661 CHE-8510: Recognize multi-module projects
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/settings/compiler/JavaCompilerPreferencePresenter.java
  plugins/plugin-java/che-plugin-java-server/pom.xml
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProjectsListener.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProjectsSynchronizer.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/hover/HoverProvider.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/MavenExtension.java
  plugins/plugin-maven/che-plugin-maven-server/pom.xml
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/PomModificationDetector.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/core/MavenWorkspace.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/core/project/PomChangeListener.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/inject/MavenModule.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/service/LanguageServiceUtils.java
Labels: status/code-review, target/branch

#8837 Support Compose memory limit byte units
  infrastructures/docker/environment/pom.xml
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/deserializer/MemLimitDeserializer.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/model/ComposeService.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/MemLimitDeserializerTest.java
Labels: kind/bug

#8835 Selenium: Rework "ProjectExplorer#openItemByPath()" method for working with already expanded project explorer tree and fix related selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesByMultiSelectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportRecursiveSubmoduleTest.java
Labels: kind/task, status/code-review

#8851 Selenium: change method for expanding test projects in ResolveDependencyAfterRecreateProjectTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ResolveDependencyAfterRecreateProjectTest.java
Labels: kind/bug, status/code-review, team/che-qe

#8842 Selenium: add selenium test to cover creating of workspaces for organizations
  dashboard/src/app/workspaces/create-workspace/namespace-selector/namespace-selector.html
  dashboard/src/app/workspaces/list-workspaces/workspace-item/workspace-item.html
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.html
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/Dashboard.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/organization/OrganizationListPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
Labels: kind/task, status/code-review, team/che-qe

#8855 Selenium: add AddWorkspaceToOrganizationTest selenium test to tests suite
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
Labels: status/code-review, team/che-qe

#8862 Selenium: add info about known issue to WorkingWithTerminalTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
Labels: kind/bug, status/code-review, team/che-qe

#8614 Support alternate OIDC providers, to prepare for the switch from Keycloak to `fabric8_auth`
  assembly-multiuser/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  assembly-multiuser/assembly-wsmaster-war/src/main/webapp/keycloak/OIDCKeycloak.js
  dashboard/src/app/index.module.ts
  dashboard/src/app/profile/profile.controller.ts
  dashboard/src/app/profile/profile.html
  multiuser/keycloak/che-multiuser-keycloak-ide/src/main/java/org/eclipse/che/multiuser/keycloak/ide/Keycloak.java
  multiuser/keycloak/che-multiuser-keycloak-ide/src/main/java/org/eclipse/che/multiuser/keycloak/ide/KeycloakProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/AbstractKeycloakFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakAuthenticationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettings.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/dao/KeycloakProfileDao.java
  multiuser/keycloak/che-multiuser-keycloak-shared/src/main/java/org/eclipse/che/multiuser/keycloak/shared/KeycloakConstants.java
  pom.xml
Labels: status/code-review, target/branch

#8860 Selenium: Change the #8031 on the #8856 in the 'try/catch' block
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceImpl.java
Labels: kind/task, status/code-review, team/che-qe

#8878 Fix creation of test users for selenium testing
  selenium/che-selenium-core/bin/webdriver.sh
Labels: kind/task, status/code-review, team/che-qe

#8869 Selenium: add AddWorkspaceToOrganizationTest selenium test to MULTIUSER tests group
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
Labels: status/code-review, team/che-qe

#8560 Implement matching of a machine to OpenShift container by pod annotations
  dashboard/src/app/workspaces/workspace-details/workspace-machines/edit-machine-dialog/edit-machine-dialog.controller.ts
  dashboard/src/components/api/environment/openshift-environment-manager.spec.ts
  dashboard/src/components/api/environment/openshift-environment-manager.ts
  dashboard/src/components/api/environment/openshift-machine-recipe-parser.ts
Labels: kind/task

#8887 set correct version for image traefik in 6.2.0
  dockerfiles/cli/version/6.2.0/images
Labels: status/code-review

#8883 Print selenium test statistics in log during execution
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestStatistics.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/inject/SeleniumTestStatisticsTest.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceLogsReaderTest.java
Labels: kind/task, status/code-review, team/che-qe

#8893 fix new images build outside it's directory
  dockerfiles/keycloak-util/build.sh
  dockerfiles/keycloak/build.sh
  dockerfiles/postgres/build.sh
Labels: kind/bug, status/code-review

#8894 Remove odd import from the TestWorkspaceLogsReaderTest
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceLogsReaderTest.java
Labels: kind/bug, team/che-qe

#8896 eliminate kc-util image
  dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh
  dockerfiles/init/modules/openshift/files/scripts/multi-user/configure_keycloak.sh
  dockerfiles/init/modules/openshift/files/scripts/multi-user/deploy_postgres_only.sh
  dockerfiles/init/modules/openshift/files/scripts/multi-user/keycloak/config/keycloak-config-pod-deployment.yaml
  dockerfiles/keycloak-util/Dockerfile
  dockerfiles/keycloak-util/build.sh
  dockerfiles/keycloak/Dockerfile
  dockerfiles/keycloak/build.sh
  dockerfiles/keycloak/keycloak_config.sh
Labels: kind/enhancement, status/code-review

#8879 Reset showInheritedMembers flag on each action calls
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/filestructure/FileStructurePresenter.java
Labels: kind/bug, status/code-review

#8895 Fix switching parts layout
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/toolbar/selector/PanelSelectorPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/multipart/EditorMultiPartStackPresenter.java
Labels: kind/bug, status/code-review

#8827 Fix for workspace symbols not opening the file
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/navigation/workspace/FindSymbolAction.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/navigation/workspace/SymbolEntry.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/quickopen/EditorQuickOpenEntry.java
Labels: kind/bug, status/code-review, target/branch

#8800 Uploading zip file corrupts file
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/FsOperations.java
  wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/fs/server/impl/FsOperationsTest.java
Labels: kind/bug, status/code-review, team/ide

#8836 Make start of OpenShift machines parallel
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/DockerInternalRuntime.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/bootstrap/DockerBootstrapper.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/DockerInternalRuntimeTest.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesMachine.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/KubernetesSharedPool.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/RuntimeEventsPublisher.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenProviderImpl.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/bootstrap/AbstractBootstrapper.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/ServersChecker.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/WorkspaceProbesFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/server/ExecServerLivenessProbeConfigFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/server/HttpProbeConfigFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/server/TerminalServerLivenessProbeConfigFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/server/WsAgentServerLivenessProbeConfigFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/MachineTokenEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/token/MachineTokenProvider.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/ServersCheckerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/probe/WorkspaceProbesFactoryTest.java
Labels: kind/task, status/code-review

#8908 Remove unsupported ls on Mac
  dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh
  dockerfiles/init/modules/openshift/files/scripts/multi-user/configure_keycloak.sh
  dockerfiles/init/modules/openshift/files/scripts/multi-user/deploy_postgres_and_keycloak.sh
  dockerfiles/init/modules/openshift/files/scripts/multi-user/keycloak-config/keycloak-config-pod-deployment.yaml
Labels: status/code-review

#8912 replace duplicate env var with check if it's defined
  dockerfiles/init/modules/openshift/files/scripts/multi-user/deploy_postgres_and_keycloak.sh
Labels: kind/bug, status/code-review

#8911 Remove outdated plugin
  plugins/plugin-traefik/pom.xml
Labels: status/code-review

#8892 Allow configuring the dispatcher and connection pool of the `KubernetesClient` shared underlying http client.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
Labels: status/code-review

#8901 Fix key press handling in some cases
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/navigation/NavigateToFileViewImpl.java
Labels: kind/bug, status/code-review

#8882 Selenium: Rework the 'WorkingWithPullConflictsTest' related to #8832
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitCompareTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/WorkingWithPullConflictsTest.java
  selenium/che-selenium-test/src/test/resources/projects/default-spring-project/README.md
  selenium/che-selenium-test/src/test/resources/projects/default-spring-project/src/main/webapp/index.jsp
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/SmokeTestsSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#8927 Avoid not needed encoding
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/navigation/NavigateToFilePresenter.java
  wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/search/SearcherTest.java
Labels: kind/bug, status/code-review

#8866 Fixed missing header file extensions for C and C++ languages
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/registry/DefaultLanguages.java
Labels: kind/bug, status/code-review

#8919 CHE-8909 fix bug with adding a new machine with the needed name
  dashboard/src/app/workspaces/workspace-details/workspace-machines/edit-machine-dialog/edit-machine-dialog.controller.ts
Labels: kind/bug, status/code-review

#8916 CHE-8544 fix user's workspaces visibility
  dashboard/src/app/organizations/organization-details/organization-details.controller.ts
  dashboard/src/app/organizations/organization-details/organization-details.html
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.controller.ts
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.directive.ts
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.html
  dashboard/src/app/organizations/organizations-config.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
Labels: kind/bug, status/code-review

#8918 Selenium: test Navigate To File feature using '*' and '?' characters in search bar
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/NavigateToFile.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
Labels: kind/task, status/code-review, team/che-qe

#8932 Selenium: add info about known issue #8931 in WorkspaceProjects page object
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjects.java
Labels: status/code-review, team/che-qe

#8905 Fix displaying Pull Request Panel
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/perspectives/general/AbstractPerspective.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateConstants.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateManager.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/WorkspacePresenter.java
  ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/statepersistance/AppStateManagerTest.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/pom.xml
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/ContributionMixinProvider.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/actions/ContributePartDisplayingModeAction.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/parts/contribute/ContributePartPresenter.java
Labels: kind/bug, status/code-review

#8917 Selenium: cover working with factories on the Dashboard by selenium tests
  dashboard/src/app/factories/create-factory/config-file-tab/factory-from-file.html
  dashboard/src/app/factories/create-factory/create-factory.html
  dashboard/src/app/factories/create-factory/git/create-factory-git.html
  dashboard/src/app/factories/create-factory/template-tab/factory-from-template.html
  dashboard/src/app/factories/create-factory/workspaces-tab/factory-from-workspace.html
  dashboard/src/app/factories/list-factories/factory-item/factory-item.html
  dashboard/src/app/factories/list-factories/list-factories.html
  dashboard/src/components/service/confirm-dialog/che-confirm-dialog.html
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/DashboardFactories.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/factories/CreateFactoryPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/factories/FactoryDetails.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/FactoriesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckOpenFileFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckRunCommandFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateNamedFactoryFromDashBoard.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#8924 Fix context propagation for bootstrap and server checks
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
Labels: kind/bug, status/code-review

#8930 Selenium: remove project state checking after workspace restarting from ProjectStateAfterRefreshTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java
Labels: kind/task, status/code-review, team/che-qe

#8934 Fix unexpected removal/stop of test workspace in factory-related selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateNamedFactoryFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithKeepDirectoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/SmokeTestsSuite.xml
Labels: kind/bug, status/code-review, team/che-qe

#8913 Fix che.workspace.auto_start property not returning from workspace service
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/bug, status/code-review

#8949 Selenium: fix expected values list in NavigateToFileTest test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/NavigateToFile.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
Labels: kind/bug, status/code-review, team/che-qe

#8872 Remove declaration of unused properties & environment variables
  dockerfiles/init/manifests/che.env
Labels: kind/task, status/code-review

#8948 Rename docker connector configuration properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties
  dockerfiles/init/manifests/che.env
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerConnectorConfiguration.java
Labels: kind/bug, status/code-review
