Repository eclipse-che/che, pull requests merged in 2018-05, with the labels that each got.

#9561 Add missing maven-server binaries for Che-in-Che deployment
  assembly/assembly-wsmaster-war/src/main/resources/che-in-che.json
Labels: kind/bug, status/code-review

#9571 Skip downloading binaries if node_modules exist
  agents/ls-csharp/src/main/resources/installers/1.0.1/org.eclipse.che.ls.csharp.script.sh
Labels: status/code-review

#9570 Do not download LS binaries if LS dir is found in a container
  agents/ls-php/src/main/resources/installers/5.4.0/org.eclipse.che.ls.php.script.sh
Labels: status/code-review

#9569 Add new Python Language server
  agents/ls-python/src/main/resources/installers/1.0.4/org.eclipse.che.ls.python.json
  agents/ls-python/src/main/resources/installers/1.0.4/org.eclipse.che.ls.python.script.sh
Labels: kind/enhancement, status/code-review

#9560 Fixed removal of remote subscriptions in manager
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/RemoteSubscriptionManager.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/RemoteSubscriptionStorage.java
  multiuser/api/che-multiuser-api-remote-subscription/src/main/java/org/eclipse/che/multiuser/api/subscription/DistributedRemoteSubscriptionStorage.java
Labels: kind/bug, status/code-review

#9585 Selenium: change url of known issue to #8465 instead of #8293 in NavigateToFileTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
Labels: kind/bug, status/code-review, team/che-qe

#9553 Remove cleaning up of CHE_DATA/lib folder in entrypoint.sh
  dockerfiles/che/entrypoint.sh
Labels: kind/enhancement, status/code-review

#9586 CHE-8931: fix black screen on project details page
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/project-details.controller.ts
Labels: kind/bug, status/code-review

#9594 Fix check for a directory
  agents/ls-php/src/main/resources/installers/5.4.0/org.eclipse.che.ls.php.script.sh
Labels: kind/bug, status/code-review

#9600 Include workspace activity times into cascade removals;
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/JpaWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/inject/WorkspaceActivityModule.java
  wsmaster/integration-tests/cascade-removal/pom.xml
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
Labels: kind/bug, status/code-review

#9513 Update deploy_che script
  deploy/openshift/che-config
  deploy/openshift/che-openshift.yml
  deploy/openshift/deploy_che.sh
  deploy/openshift/multi-user/configure_keycloak.sh
  deploy/openshift/multi-user/deploy_postgres_and_keycloak.sh
  deploy/openshift/multi-user/deploy_postgres_only.sh
  deploy/openshift/multi-user/keycloak-config/keycloak-config-pod-deployment.yaml
  deploy/openshift/multi-user/keycloak/deployment-config.yaml
  deploy/openshift/multi-user/keycloak/keycloak-data-claim.yaml
  deploy/openshift/multi-user/keycloak/keycloak-log-claim.yaml
  deploy/openshift/multi-user/keycloak/route.yaml
  deploy/openshift/multi-user/keycloak/service.yaml
  deploy/openshift/multi-user/postgres/deployment-config.yaml
  deploy/openshift/multi-user/postgres/postgres-data-claim.yaml
  deploy/openshift/multi-user/postgres/service.yaml
  deploy/openshift/multi-user/wait_until_keycloak_is_available.sh
  deploy/openshift/multi-user/wait_until_postgres_is_available.sh
  deploy/openshift/ocp.sh
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/https/keycloak-route-tls.yaml
  deploy/openshift/templates/multi/keycloak-template.yaml
Labels: kind/enhancement, status/code-review

#9400 Changed absolute paths to relative paths for zipped content
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/ZipArchiver.java
Labels: kind/enhancement, status/code-review

#9583 Add supervisor into Theia image to reap zombie processes
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/supervisord.conf
Labels: kind/task, status/code-review

#9627 Fix Eclipse Che deployment on OCP
  deploy/openshift/ocp.sh
Labels: kind/bug, team/che-sd

#9608 Allow adding Theia extension on image build from within container
  dashboard/src/app/workspaces/workspace-details/workspace-tools/workspace-tools-ide/workspace-tools-ide.controller.ts
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/src/add-extensions.js
  dockerfiles/theia/src/add-native-plugins.js
Labels: status/code-review

#9629 Selenium: wait for Project Explorer after starting IDE in tests from refactor.types package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/GenericsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/IllegalTypeNameTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestAnnotationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestEnumerationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestFailTest.java
Labels: kind/bug, status/code-review, team/che-qe

#9602 Selenium: Rework the 'RunPlainJavaProjectTest' to use the 'kohsuke Github' library
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PushChangeNotUpdatedRepoTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/RunPlainJavaProjectTest.java
  selenium/che-selenium-test/src/test/resources/projects/run-plain-java-project/src/com/company/nba/MainClass.java
  selenium/che-selenium-test/src/test/resources/projects/run-plain-java-project/store/mockito-all-1.10.19.jar
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/SmokeTestsSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#9619 Add logging of Kubernetes/OpenShift unrecoverable events
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
Labels: kind/bug, status/code-review

#9622 Skip selenium tests which depends on failed tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-test/README.md
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginWithForkTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/FailNotPrivateFieldTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/FailPrivateFieldTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/RenameNotPrivateFieldTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/RenamePrivateFieldTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenamePrivateMethodTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameStaticMethodsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameVirtualMethodsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveItemsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/parameters/RenameParametersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
Labels: kind/task, status/code-review, team/che-qe

#9634 Rework PlainJava project type and Deprecate SettableValueProvider
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/workspace/model/WorkspaceImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/plugin/java/server/projecttype/JavaProjectType.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-ide/src/main/java/org/eclipse/che/plugin/java/plain/client/wizard/PlainJavaPagePresenter.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-ide/src/main/java/org/eclipse/che/plugin/java/plain/client/wizard/PlainJavaPageView.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-ide/src/main/java/org/eclipse/che/plugin/java/plain/client/wizard/PlainJavaPageViewImpl.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-ide/src/main/java/org/eclipse/che/plugin/java/plain/client/wizard/PlainJavaPageViewImpl.ui.xml
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/projecttype/PlainJavaProjectType.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/projecttype/PlainJavaValueProviderFactory.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/test/java/org/eclipse/che/plugin/java/plain/server/projecttype/PlainJavaValueProviderFactoryTest.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/projecttype/MavenProjectType.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestMenuCommandsConstants.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/RunPlainJavaProjectTest.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/type/SettableValueProvider.java
Labels: status/code-review

#9612 CHE-9449: Adapt Node Js debugger to node version 8
  plugins/plugin-nodejs-debugger/che-plugin-nodejs-debugger-server/pom.xml
  plugins/plugin-nodejs-debugger/che-plugin-nodejs-debugger-server/src/main/java/org/eclipse/che/plugin/nodejsdbg/server/NodeJsDebugProcess.java
  plugins/plugin-nodejs-debugger/che-plugin-nodejs-debugger-server/src/main/java/org/eclipse/che/plugin/nodejsdbg/server/command/NodeJsDebugCommandsLibrary.java
  plugins/plugin-nodejs-debugger/che-plugin-nodejs-debugger-server/src/main/java/org/eclipse/che/plugin/nodejsdbg/server/parser/NodeJsBreakpointsParser.java
  plugins/plugin-nodejs-debugger/che-plugin-nodejs-debugger-server/src/test/java/org/eclipse/che/plugin/nodejsdbg/server/parser/NodeJsBreakpointsParserTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/NodeJsDebugTest.java
Labels: kind/bug, status/code-review

#9601 Selenium: cover the Stacks list by selenium test
  dashboard/src/app/stacks/list-stacks/list-stacks.html
  dashboard/src/app/stacks/list-stacks/stack-item/stack-item.html
  dashboard/src/components/widget/list/che-list-header.html
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/stacks/StackDetails.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/stacks/Stacks.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/StacksListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#9508 Fixed quick documentation
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorWidget.java
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionEditorViewOverlay.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/documentation/QuickDocPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/documentation/QuickDocView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/documentation/QuickDocViewImpl.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/hover/HoverProvider.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/JavaDocPopupLinkTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/JavaDocPopupTest.java
Labels: kind/bug, status/code-review, target/branch

#9662 Change issue reference
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerUserCreatePolicyTest.java
Labels: kind/enhancement, status/code-review

#9661 CHE-9542: Disable unrecoverable k8s events handling
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
Labels: kind/bug, status/code-review

#9667 Selenium: change url of known issue to #9523 instead of #9648 in StacksListTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/StacksListTest.java
Labels: kind/task, status/code-review, team/che-qe

#9672 Selenium: Replace the known issue #8856 on the #9556 in the try/catch block in the TestWorkspaceImpl
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceImpl.java
Labels: kind/task, status/code-review, team/che-qe

#9604 To white label dashboard, make it possible to override dashboard fonts
  dashboard/src/assets/branding/branding.css
  dashboard/src/index.html
Labels: kind/enhancement, status/code-review

#9686 Selenium: Restore order of the test methods launch in the "ContextMenuEditorTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
Labels: kind/task, status/code-review

#9659 Adding error from machine startup and installers to slf4j log
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  wsmaster/che-core-api-logger/pom.xml
  wsmaster/che-core-api-logger/src/main/java/org/eclipse/che/api/logger/ErrorInstallerLogEventLogger.java
  wsmaster/che-core-api-logger/src/main/java/org/eclipse/che/api/logger/ErrorMachineLogEventLogger.java
  wsmaster/che-core-api-logger/src/main/java/org/eclipse/che/api/logger/deploy/LoggerModule.java
  wsmaster/che-core-api-logger/src/test/java/org/eclipse/che/api/logger/LoggerServiceTest.java
  wsmaster/che-core-api-logger/src/test/resources/logback-test.xml
Labels: kind/planning, status/code-review

#9688 Selenium: Add the 'try/catch' to the 'PullRequestPluginTest' according to the known issue #9484
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
Labels: kind/task, status/code-review, team/che-qe

#9685 Added an ability to schedule servers checkers for STARTING K8s/OS runtime
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesRuntimeContext.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftRuntimeContext.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/ProbeScheduler.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/WorkspaceProbesFactory.java
Labels: kind/bug, status/code-review

#9640 Add ability to configure OAuth type in Multi User Che
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/OAuthAPIProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/oauth2/DelegatedOAuthAPI.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAPI.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticationService.java
  wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPITest.java
  wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth/OAuthAuthenticationServiceTest.java
Labels: kind/task, status/code-review

#9687 Fixed removing of temporary workspaces on server startup and shutdown
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/TemporaryWorkspaceRemover.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/TemporaryWorkspaceRemoverTest.java
Labels: kind/bug, status/code-review

#9683 Add DB termination component on application shutdown
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/che-core-db/pom.xml
  core/che-core-db/src/main/java/org/eclipse/che/core/db/DBTermination.java
  wsmaster/che-core-api-system/pom.xml
  wsmaster/che-core-api-system/src/main/java/org/eclipse/che/api/system/server/SystemManager.java
  wsmaster/che-core-api-system/src/test/java/org/eclipse/che/api/system/server/SystemManagerTest.java
Labels: status/code-review

#9693 CHE-9523 fix flow to creating a new OpenShift/K8S stack
  dashboard/src/app/stacks/stack-details/import-stack.controller.ts
  dashboard/src/app/stacks/stack-details/stack.controller.ts
  dashboard/src/app/stacks/stack-details/stack.html
  dashboard/src/app/stacks/stacks-config.ts
  dashboard/src/app/workspaces/workspace-details/che-recipe.service.ts
  dashboard/src/components/api/che-stack.factory.ts
Labels: kind/bug, status/code-review

#9689 Notify consumers about file is opened at restoring IDE state
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorAgentImpl.java
Labels: kind/bug, status/code-review

#9582 Correct process situation when project has been renamed
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/impl/ResourceManager.java
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/jdt/internal/core/JavaProject.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/core/MavenWorkspace.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ExecutiveProjectManager.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/RootDirRemovalHandler.java
Labels: kind/bug, severity/P2, status/code-review, team/ide

#9696 Fixed wrong logger output
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
Labels: kind/bug, status/code-review

#9704 che-9234: fix diagnostics by reworking websocket usage to jsonrpc
  dashboard/src/app/diagnostics/diagnostic-callback.ts
  dashboard/src/app/diagnostics/diagnostics.controller.ts
  dashboard/src/app/diagnostics/test/diagnostics-websocket-wsmaster.factory.ts
  dashboard/src/app/diagnostics/test/diagnostics-workspace-check-workspace.factory.ts
  dashboard/src/app/diagnostics/test/diagnostics-workspace-start-check.factory.ts
  dashboard/src/components/api/json-rpc/che-json-rpc-api.factory.ts
  dashboard/src/components/api/json-rpc/websocket-client.ts
Labels: kind/bug, status/code-review

#9701 Added JGroups based status cache and lock service
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/ReplicationModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/che-core-db/src/main/java/org/eclipse/che/core/db/DBTermination.java
  deploy/openshift/deploy_che.sh
  deploy/openshift/templates/che-server-template.yaml
  multiuser/api/che-multiuser-api-jgroups/pom.xml
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/JGroupsServiceTermination.java
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/JGroupsWorkspaceStatusCache.java
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/lock/JGroupsWorkspaceLockService.java
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/subscription/DistributedRemoteSubscriptionStorage.java
  multiuser/api/che-multiuser-api-jgroups/src/test/resources/logback-test.xml
  multiuser/api/pom.xml
  pom.xml
  wsmaster/che-core-api-system/pom.xml
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
Labels: kind/enhancement, status/code-review

#9708 Send request with activity on ws-agent in a separate thread
  wsagent/che-core-workspace-activity-server/src/main/java/org/eclipse/che/workspace/activity/WorkspaceActivityNotifier.java
Labels: kind/bug, status/code-review

#9611 Adding `-Dvertx.disableDnsResolver=true` to vert.x run / debug commands
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#9736 Added an error when keycloak container is not found
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/KeycloakAdminConsoleClient.java
Labels: kind/enhancement, status/code-review

#9738 Make client id and secret configurable from command line
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: status/code-review

#9703 #9542 Proper handling of unrecoverable events. Processing only events which are related to current workspace pods
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/event/ContainerEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/ContainerEvents.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/ContainerEventsTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
Labels: kind/bug, status/code-review

#9745 Fix AskDialog page object of selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AskDialog.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/NotificationsPopupPanel.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitCompare.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitHistory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsEditor.java
Labels: kind/task, status/code-review

#9746 Selenium: Change the name of the test library in the resources
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/RunPlainJavaProjectTest.java
  selenium/che-selenium-test/src/test/resources/projects/run-plain-java-project/store/testLibrary.jar
Labels: kind/task, status/code-review, team/che-qe

#9742 Selenium: Rework the 'ImportWizardFormTest' to add test repo on Github using the 'kohsuke GitHub' library
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
Labels: kind/task, status/code-review, team/che-qe

#9757 Fix wsagent clientId passing, fix diagnostics recipe to work both on ocp and docker
  dashboard/src/app/diagnostics/test/diagnostics-workspace-start-check.factory.ts
  dashboard/src/components/api/json-rpc/che-json-rpc-wsagent-api.ts
Labels: kind/bug, status/code-review

#9671 CHE-6109: Enable Update project configuration from any project level
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/ProjectConfigurationAction.java
Labels: kind/bug, status/code-review

#9747 If node is already visible in project tree, then select it instead of reload
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/TreeResourceRevealer.java
Labels: kind/bug, status/code-review, team/ide

#9743 Provide machine name as a machine's environment variable
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactoryTest.java
Labels: kind/enhancement, status/code-review

#9737 Move building of postgresql-tck module to integration build profile
  wsmaster/integration-tests/pom.xml
  wsmaster/integration-tests/postgresql-tck/pom.xml
Labels: status/code-review

#9754 Delete child projects only from project config registry at removing project
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectConfigRegistry.java
Labels: kind/bug

#9763 Rework the 'ImportMavenProjectFromGitTest' to add test repo on Github using the 'kohsuke Github' library
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
Labels: kind/task, status/code-review, team/che-qe

#9773 Rework the 'ImportProjectFromZipTest' to add test repo on Github using the 'kohsuke GitHub' library
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromZipTest.java
Labels: kind/task, status/code-review, team/che-qe

#9772 che #9542 Processing only the events that happened after `watchContainers` initialization
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
Labels: kind/bug, status/code-review

#9771 CHE-8931: fix blank screen on project details page
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/project-details.controller.ts
  dashboard/src/components/api/json-rpc/che-json-rpc-api.factory.ts
  dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts
Labels: kind/bug, status/code-review

#9776 Send initialized event, after initialization
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerInitializer.java
Labels: status/code-review

#9762 Selenium: Rework the 'ImportProjectFromGitHubTest' to add test repo on Github using the 'kohsuke Github' library
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
Labels: kind/task, status/code-review, team/che-qe

#9782 fix formating
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerInitializer.java
Labels: kind/bug, status/code-review

#9751 CHE-9716: Use the fixed version of Theia in eclipse/che-theia image
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/README.md
  dockerfiles/theia/src/add-extensions.js
  dockerfiles/theia/src/main.js
  dockerfiles/theia/supervisord.conf
  dockerfiles/theia/theia-default-package.json
  dockerfiles/theia/versions.sh
Labels: kind/task, status/code-review

#9783 Wait until Che is available when deploying it on OCP
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
Labels: kind/enhancement, status/code-review

#9799 add bugfix versions to cli
  dockerfiles/cli/version/6.4.1/images
  dockerfiles/cli/version/6.4.1/images-stacks
  dockerfiles/cli/version/6.5.1/images
  dockerfiles/cli/version/6.5.1/images-stacks
  dockerfiles/cli/version/latest.ver
Labels: kind/bug, status/code-review

#9759 Selenium: cover Python LS functionality by selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/WorkspaceTemplate.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestMenuCommandsConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Wizard.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/ProjectSourcePage.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CheckMainFeatureForPythonLanguageTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/ubuntu_python.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_python.json
Labels: kind/task, status/code-review, team/che-qe

#9779 Fix injection if any implementation of LanguageDescription found
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/inject/LanguageServerGinModule.java
Labels: kind/bug, status/code-review

#9780 There are possible places of failure due to not closing InputStreams
  plugins/plugin-composer/che-plugin-composer-server/src/main/java/org/eclipse/che/plugin/composer/server/projecttype/ComposerValueProviderFactory.java
  plugins/plugin-cpp/che-plugin-cpp-lang-server/src/main/java/org/eclipse/che/plugin/cpp/generator/CProjectGenerator.java
  plugins/plugin-cpp/che-plugin-cpp-lang-server/src/main/java/org/eclipse/che/plugin/cpp/generator/CppProjectGenerator.java
  plugins/plugin-csharp/che-plugin-csharp-lang-server/src/main/java/org/eclipse/che/plugin/csharp/projecttype/CreateNetCoreProjectHandler.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/generator/PlainJavaProjectGenerator.java
  plugins/plugin-nodejs/che-plugin-nodejs-lang-server/src/main/java/org/eclipse/che/plugin/nodejs/generator/NodeJsProjectGenerator.java
  plugins/plugin-php/che-plugin-php-lang-server/src/main/java/org/eclipse/che/plugin/php/projecttype/PhpProjectGenerator.java
  plugins/plugin-python/che-plugin-python-lang-server/src/main/java/org/eclipse/che/plugin/python/generator/PythonProjectGenerator.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/CreateBaseProjectTypeHandler.java
Labels: status/code-review

#9805 Implement selenium test for covering LS server for PHP language
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CSharpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PhpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PythonFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review

#9577 Allow creating OpenShift objects under the current user account on OCP
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  dashboard/src/app/navbar/recent-workspaces/recent-workspaces.controller.ts
  deploy/openshift/templates/README.md
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/multi/keycloak-template.yaml
  deploy/openshift/templates/multi/openshift-certificate-secret.yaml
  dockerfiles/keycloak/Dockerfile
  dockerfiles/keycloak/cli/add_openshift_certificate.cli
  dockerfiles/keycloak/kc_realm_user.sh
  infrastructures/openshift/pom.xml
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientConfigFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/IdentityProviderConfigFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/IdentityProviderConfigBuilderTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClient.java
Labels: kind/task, status/code-review

#9850 fix build.sh for theia image
  dockerfiles/build.include
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/README.md
Labels: kind/bug, status/code-review

#9806 Fix contribute part displaying at project selection
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/PartStack.java
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/PartStackStateChangedEvent.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/common/HidePartAction.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/PartStackPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateManager.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/pom.xml
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/ContributeMessages.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/ContributionMixinProvider.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/actions/ContributePartDisplayingModeAction.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/inject/PullRequestGinModule.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/preference/ContributePreferencePresenter.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/preference/ContributePreferenceView.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/preference/ContributePreferenceViewImpl.java
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/java/org/eclipse/che/plugin/pullrequest/client/preference/ContributePreferenceViewImpl.ui.xml
  plugins/plugin-pullrequest-parent/che-plugin-pullrequest-ide/src/main/resources/org/eclipse/che/plugin/pullrequest/client/ContributeMessages.properties
Labels: kind/bug, status/code-review

#9812 Selenium: Rework "NewWorkspace" selenium page object by "SeleniumWebDriverHelper" class
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/constant/TestTimeoutsConstants.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
Labels: kind/task, status/code-review, team/che-qe

#9777 Fix initialization of servers statuses by DockerInfrastructure
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/server/mapping/ServersMapper.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/server/mapping/ServersMapperTest.java
Labels: kind/bug, status/code-review

#9893 Fix version for eclipse/che-theia image
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review
