Repository eclipse-che/che, pull requests merged in 2018-09, with the labels that each got.

#10740 Move WS.NEXT flow to k8s infra implementation, rework it to use plugin broker
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/kubectl/che-kubernetes.yaml
  deploy/openshift/deploy_che.sh
  deploy/openshift/templates/che-server-template.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesConfigsMaps.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarToolingProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerPhase.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeliverMetas.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/ListenBrokerEvents.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/PrepareStorage.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/WaitBrokerResult.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerResultListener.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerService.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfrastructure.java
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
  selenium/che-selenium-test/src/test/resources/projects/nodejs-with-yaml/deployment.yaml
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/BrokerResultEvent.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/BrokerStatus.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironment.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/WorkspaceNextObjectsRetriever.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/CheFeatureSpec.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/ChePluginParameter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/EnvVar.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/ObjectMeta.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/TypeMeta.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsnext/model/Volume.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/ChePluginsApplier.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/PluginMetaRetriever.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheContainer.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheContainerPort.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheEditor.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/ChePlugin.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/ChePluginEndpoint.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/Command.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/EditorCompatibility.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/EnvVar.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginBase.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginMeta.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/Volume.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/wsnext/WorkspaceNextObjectsRetrieverTest.java
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
Labels: kind/task, status/code-review

#10953 CHE-10730: Change log level from Error to Debug when failed to parse xml file
  plugins/plugin-testing-java/plugin-testing-testng/che-plugin-testing-testng-server/src/main/java/org/eclipse/che/plugin/testing/testng/server/TestNGRunner.java
Labels: kind/enhancement, status/code-review

#11014 Waiting for editor activation in FindUsagesBaseOperationTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindUsagesBaseOperationTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#10990 Make tests stable in projectexplorer package
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckOnValidAndInvalidClassNameTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewJavaFilesFromContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/TransitiveDependencyTest.java
Labels: status/code-review, target/branch, team/languages

#10971 Add Open on GitHub feature with E2E test
  plugins/plugin-github/che-plugin-github-ide/pom.xml
  plugins/plugin-github/che-plugin-github-ide/src/main/java/org/eclipse/che/plugin/github/ide/GitHubExtension.java
  plugins/plugin-github/che-plugin-github-ide/src/main/java/org/eclipse/che/plugin/github/ide/GitHubLocalizationConstant.java
  plugins/plugin-github/che-plugin-github-ide/src/main/java/org/eclipse/che/plugin/github/ide/action/OpenOnGitHubAction.java
  plugins/plugin-github/che-plugin-github-shared/pom.xml
  plugins/plugin-github/che-plugin-github-shared/src/main/java/org/eclipse/che/plugin/github/shared/GitHubUrlUtils.java
  plugins/plugin-github/che-plugin-github-shared/src/test/java/org/eclipse/che/plugin/github/GitHUbUrlUtilsTest.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestProjectServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestProjectExplorerContextMenuConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/OpenOnGitHubTest.java
Labels: kind/enhancement, status/code-review

#10739 Selenium: Cover "Dashboard / Workspace Details / Machines" part of test plan by selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/EditMachineForm.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetailsMachines.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsMachinesRamTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#11025 Multiple changes to deploy scripts
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
Labels: status/code-review

#11005 Fix selenium tests in languageserver package
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProjectsListener.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ApacheCamelFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CSharpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ClangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/JsonFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PhpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PythonFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/TypeScriptEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/YamlFileEditingTest.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerConfigInitializer.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#11034 Fix NavigateToFileTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/AutocompleteCommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/PreviewUrlIntoCommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#11041 Fix selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaStackTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#11046 Selenium: add info about known issues, fix unstable selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckOpenFileFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11052 Fix waiting message in NavigateToFileTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
Labels: kind/bug, target/branch, team/languages

#11015 Add che.workspace.plugin_registry_url information to workspace/settings Rest method
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/openshift/deploy_che.sh
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/task, status/code-review

#10934 Added authorization for JsonRpc methods
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcMethodInvokerFilter.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/RequestHandlerManager.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/RemoteSubscriptionManager.java
  multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/OrganizationApiModule.java
  multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/listener/OrganizationEventsWebsocketBroadcaster.java
  multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/permissions/OrganizationRemoteSubscriptionPermissionsChecks.java
  multiuser/api/che-multiuser-api-organization/src/test/java/org/eclipse/che/multiuser/organization/api/permissions/OrganizationRemoteSubscriptionPermissionsChecksTest.java
  multiuser/api/che-multiuser-api-permission/src/main/java/org/eclipse/che/multiuser/api/permission/server/PermissionsModule.java
  multiuser/api/che-multiuser-api-permission/src/main/java/org/eclipse/che/multiuser/api/permission/server/jsonrpc/JsonRpcPermissionsFilterAdapter.java
  multiuser/api/che-multiuser-api-permission/src/main/java/org/eclipse/che/multiuser/api/permission/server/jsonrpc/RemoteSubscriptionPermissionCheck.java
  multiuser/api/che-multiuser-api-permission/src/main/java/org/eclipse/che/multiuser/api/permission/server/jsonrpc/RemoteSubscriptionPermissionManager.java
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml
  multiuser/permission/che-multiuser-permission-system/pom.xml
  multiuser/permission/che-multiuser-permission-system/src/main/java/org/eclipse/che/multiuser/permission/system/SystemEventsSubscriptionPermissionsCheck.java
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/WorkspaceApiPermissionsModule.java
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/filters/InstallerServicePermissionFilter.java
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspaceRemoteSubscriptionPermissionFilter.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspaceRemoteSubscriptionPermissionFilterTest.java
Labels: kind/task, status/code-review

#11056 Fixed helm deployment with default value of loggerConfig
  deploy/kubernetes/helm/che/templates/configmap.yaml
Labels: kind/bug, status/code-review

#11062 Fix selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitChangeMarkersTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#11063 Fix selenium tests
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProjectsListener.java
Labels: kind/task, status/code-review, target/branch, team/languages

#11049 Various changes of Eclipse Che selenium tests result handling
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceLogsReader.java
Labels: kind/bug, status/code-review, team/che-qe

#11006 Create new test for covering Refactoring ->Rename feature for DotNet LS
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/project/ProjectTemplates.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestCommandsConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestMenuCommandsConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpClassRenamingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/CSharpHelloWorld/Hello.cs
  selenium/che-selenium-test/src/test/resources/projects/CSharpHelloWorld/projects.csproj
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/project/dotNet.json
Labels: kind/task, status/in-progress

#11051 [WIP] Replace outdated images in configuration
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/default.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/default_with_github_projects.json
Labels: kind/enhancement, status/code-review

#11073 [docker images] Switch to Theia 0.3.14
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
  dockerfiles/theia/e2e/cypress/support/commands.ts
  dockerfiles/theia/src/setup.sh
Labels: kind/enhancement, status/code-review

#11037 Prevent XSS attacks
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/toolbar/processes/ProcessWidget.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dialogs/choice/ChoiceDialogPresenter.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dialogs/confirm/ConfirmDialogPresenter.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dialogs/message/MessageDialogPresenter.java
  plugins/plugin-github/che-plugin-github-ide/src/main/java/org/eclipse/che/plugin/github/ide/authenticator/GitHubAuthenticatorViewImpl.java
Labels: kind/task, status/code-review, team/ide

#10869 Update selenium chrome-node to 3.14.0
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/SeleniumWebDriver.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/DownloadedIntoGridFileUtil.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverFactory.java
  selenium/che-selenium-test/docker-compose.yml
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/NotificationsPopupPanel.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ConditionalBreakpointsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/CppProjectDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/DebugExternalClassTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/InnerClassAndLambdaDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/MultimoduleProjectDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/NodeJsDebugTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/PhpProjectDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/RunToCursorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ThreadDumpTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithMultiModuleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerClickCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerUserCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckGeneratingMavenArchetypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckRestoringWorkspaceAfterStoppingWsAgentProcessTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindUsagesBaseOperationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/ContributeTabTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckErrorMessageWhenCreationDuplicateFolderOrFileTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginJunit4CheckRunSuitesAndScopesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginJunit4Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginTestNgTest.java
Labels: kind/task, status/code-review, team/che-qe

#11066 Remove duplicated properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: status/code-review

#10893 New folders do not register in the jdt.ls workspace #10115
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/pom.xml
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/inject/PlainJavaProjectModule.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/inject/PlainJavaProjectSourceFolderWatcher.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/PlainJavaProjectConfigureClasspathTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#11076 CHE-10756: Use regular user instead of root in theia image
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/Dockerfile
  dockerfiles/theia/src/resolutions-provider.js
  dockerfiles/theia/src/setup.sh
  dockerfiles/theia/src/start.sh
Labels: kind/bug, status/code-review

#11057 Use notifications instead of client commands
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/util/JavaLanguageServerExtensionStub.java
  plugins/plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/Constants.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/rest/ClasspathUpdaterService.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/inject/JavaModule.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageClient.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/NotifyJsonRpcTransmitter.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/LanguageServerExtension.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/inject/LanguageServerGinModule.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/CustomNotificationReceiver.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/ExecuteClientCommandProcessor.java
Labels: kind/bug, sprint/current-sprint, status/code-review, target/branch, team/languages

#11061 Moved plugin broker to runtime start phase instead of context preparing
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesRuntimeContext.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesRuntimeFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfrastructure.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftRuntimeContext.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftRuntimeFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
Labels: kind/task, status/code-review

#11085 [stack] Use of new Theia 0.3.14
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: status/code-review

#10673 Make Resource memory request configurable for k8s and OpenShift
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/MachineConfig.java
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
  dockerfiles/init/manifests/che.env
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/ComposeEnvironmentFactory.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/ComposeEnvironmentValidator.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/deserializer/MemAttributeDeserializer.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/model/ComposeService.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerfile/DockerfileEnvironmentFactory.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerimage/DockerImageEnvironmentFactory.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/BuildContextTest.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/CommandDeserializerTest.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/ComposeEnvironmentFactoryTest.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/ComposeEnvironmentValidatorTest.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/ComposeEnvironmentVariableTest.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/MemAttributeDeserializerTest.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerfile/DockerfileEnvironmentFactoryTest.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerimage/DockerImageEnvironmentFactoryTest.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Containers.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactoryTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactoryTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceValidator.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/MachineConfigsValidator.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/MemoryAttributeProvisioner.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/MachineConfigsValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/MemoryAttributeProvisionerTest.java
Labels: status/code-review

#11100 Fix selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/EditMachineForm.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpClassRenamingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpFileEditingTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#11088 [walking skeleton] Introduce ws.next stacks
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/task, status/code-review

#10576 Selenium: Add method to the "WaitUtils" class for waiting specified condition happens without using of "WebDriverWait"
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/WaitUtils.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/utils/WaitSuccessConditionTest.java
Labels: kind/task, status/code-review, team/che-qe

#11098 Added injecting of auth related env vars into Plugin Broker Pod
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
Labels: kind/task, status/code-review

#11092 Added authorization checks for BrokerService's JSON RPC methods
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerService.java
  multiuser/permission/che-multiuser-permission-infra-kubernetes/pom.xml
  multiuser/permission/che-multiuser-permission-infra-kubernetes/src/main/java/org/eclipse/che/multiuser/permission/workspace/infra/kubernetes/BrokerServicePermissionFilter.java
  multiuser/permission/che-multiuser-permission-infra-kubernetes/src/test/java/org/eclipse/che/multiuser/permission/workspace/infra/kubernetes/BrokerServicePermissionFilterTest.java
  multiuser/permission/che-multiuser-permission-infra-kubernetes/src/test/resources/logback-test.xml
  multiuser/permission/pom.xml
  pom.xml
Labels: kind/task, status/code-review

#11099 [ Selenium ] Fix unexpected fail of "CheckErrorsWarningsTabTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/CheckErrorsWarningsTabTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11103 [dockerfiles] [theia] [e2e] Cleanup videos folder on each new run
  dockerfiles/theia/e2e/.dockerignore
  dockerfiles/theia/e2e/src/docker-run.sh
Labels: status/code-review

#11109 Fix for PlainJavaProjectConfigureClasspathTest
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/classpath/valueproviders/selectnode/SelectNodePresenter.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/PlainJavaProjectConfigureClasspathTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#11122 Selenium: increase timeout for checking that Wizard form is closed
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Wizard.java
Labels: kind/bug, status/code-review, team/che-qe

#11125 Fix selenium tests in 'git' package to increase reliability
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AmendCommitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesByMultiSelectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
Labels: kind/task, status/code-review, team/che-qe

#11108 Tune a list of owners for multi-user modules
  .github/CODEOWNERS
Labels: status/code-review

#11043 Add icons to project explorer tree for files with ".ts", ".jsx" and ".es6" extensions
  plugins/plugin-web/che-plugin-web-ext-web/src/main/java/org/eclipse/che/plugin/web/client/WebExtensionResource.java
  plugins/plugin-web/che-plugin-web-ext-web/src/main/java/org/eclipse/che/plugin/web/client/inject/WebModule.java
  plugins/plugin-web/che-plugin-web-ext-web/src/main/resources/org/eclipse/che/plugin/web/client/es6.svg
  plugins/plugin-web/che-plugin-web-ext-web/src/main/resources/org/eclipse/che/plugin/web/client/jsx.svg
  plugins/plugin-web/che-plugin-web-ext-web/src/main/resources/org/eclipse/che/plugin/web/client/ts.svg
Labels: kind/enhancement, status/code-review

#11102 [Selenium] Fix unexpected fail of "WorkspaceDetailsMachineActionsTest" selenium test on docker infrastructure
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11114 Fix NPE and NumberFormatException in some cases
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/RamLimitProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Containers.java
Labels: kind/bug, status/code-review

#11113 Add migration to fix signature keys inconsistency
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.11.0/1__add_signature_key_constraints.sql
Labels: kind/bug, status/code-review

#11127 Apply WaitUtils.waitSuccessCondition() method to HotUpdateUtil
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/hotupdate/HotUpdateUtil.java
Labels: kind/task, status/code-review, team/che-qe

#11126 Remove instructions to fork test repos
  selenium/che-selenium-test/README.md
Labels: kind/docs, status/code-review, team/che-qe

#11150 Selenium: update NewWorkspacePageTest selenium test according to the addition of new stacks
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
Labels: kind/bug, selenium/failure, status/code-review, team/che-qe

#11104 Add functional test for checking factory with skipFirstLevel parameter
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckSkipRootFolderTest.java
Labels: kind/task, status/code-review

#11156 Added authorization checks for all factory service's methods
  multiuser/permission/che-multiuser-permission-factory/pom.xml
  multiuser/permission/che-multiuser-permission-factory/src/main/java/org/eclipse/che/multiuser/permission/factory/FactoryPermissionsFilter.java
  multiuser/permission/che-multiuser-permission-factory/src/test/java/org/eclipse/che/multiuser/permission/factory/FactoryPermissionsFilterTest.java
Labels: kind/bug, status/code-review

#11159 Use correct constant
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Wizard.java
Labels: kind/task, team/ide

#11153 Add actual values of web element in SeleniumWebDriver error message
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/WebDriverWaitFactory.java
Labels: kind/task, status/code-review, team/che-qe

#11136 Fix 'onOpen' websocket handlers
  dashboard/src/components/api/json-rpc/websocket-client.ts
Labels: kind/bug, status/code-review

#11119 Rework plugin brokering to reuse PVC strategies code
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarToolingProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeliverMetas.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/KubernetesBrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/PrepareStorage.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/wsplugins/brokerphases/OpenshiftBrokerEnvironmentFactory.java
Labels: kind/task, status/code-review

#11167 [Selenium] Update the "MachinesAsynchronousStartTest" selenium test according to the new expected behavior
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/EditMachineForm.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/MachinesAsynchronousStartTest.java
Labels: kind/task, status/code-review

#11165 Set stable version of selenium chrome-node 3.14.0-curium
  selenium/che-selenium-test/docker-compose.yml
Labels: kind/task, status/code-review, team/che-qe

#11176 CHE-11173: Fix Unsupported operation exception
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/CachedGitStatusProvider.java
Labels: kind/bug, status/code-review

#11143 Manage the list of plugins from Che plugins registry
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.html
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins-config.ts
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.directive.ts
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.html
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.styl
  dashboard/src/app/workspaces/workspaces-config.ts
  dashboard/src/components/api/che-api-config.ts
  dashboard/src/components/api/plugin-registry.factory.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
Labels: status/code-review

#11177 Use edit role for Che SA
  deploy/openshift/templates/che-server-template.yaml
Labels: kind/enhancement, status/code-review

#11178 Added an ability to specify service account to be bound to workspaces pods
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  core/che-core-api-core/src/main/java/org/eclipse/che/everrest/CheMethodInvokerFilter.java
  deploy/kubernetes/helm/che/templates/_workspaceServiceAccountNameHelper.tpl
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/templates/exec-role.yaml
  deploy/kubernetes/helm/che/templates/workspace-exec-role-binding.yaml
  deploy/kubernetes/helm/che/templates/workspace-service-account.yaml
  deploy/kubernetes/helm/che/templates/workspace-view-role-binding.yaml
  deploy/openshift/deploy_che.sh
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/che-workspace-service-account.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ServiceAccountProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
Labels: kind/task, status/code-review

#11205 Fix the plugins registry location
  dashboard/src/components/api/plugin-registry.factory.ts
Labels: status/code-review

#11191 Selenium: Add the 'try/catch' to tests in the 'refactor.parameters' package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/parameters/FailParametersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/parameters/RenameParametersTest.java
Labels: kind/task, status/code-review, team/che-qe

#11190 Add the 'try/catch' to the 'ImportAndValidateEclipseCheProjectTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/ImportAndValidateEclipseCheProjectTest.java
Labels: kind/task, status/code-review, team/che-qe

#11207 Close browser window after factory-related E2E tests finished
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/factory/TestFactory.java
Labels: kind/bug, team/che-qe

#11216 [Selenium] Create page object for "QuickOpenView" form
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/quickopen/QuickOpenViewImpl.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/quickopen/QuickOpenViewImpl.ui.xml
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AssistantFindPanel.java
Labels: kind/task, status/code-review, team/che-qe

#11225 [Selenium] Create "FindPreferencesConsoleTab" selenium page object
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FindReferencesConsoleTab.java
Labels: kind/task, status/code-review, team/che-qe

#11232 Do not skip selenium test which should run always
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
Labels: kind/task, team/che-qe

#11251 Selenium: correct the 'doRenamingByLanguageServerField()' method in t…
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
Labels: kind/task, status/code-review, team/che-qe

#11263 [ Selenium ] Cover the "PHP" language server functionality by selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestMenuCommandsConstants.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/php/PhpAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/php/PhpFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#11233 Stores logs of test workspaces which do not have RUNNING status
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/AbstractTestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/CheTestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/WaitUtils.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/WorkspaceDtoDeserializer.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/AbstractTestWorkspaceProvider.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestWorkspace.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestWorkspaceProvider.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/InjectTestWorkspace.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceLogsReader.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceProvider.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/WorkspaceTemplate.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/utils/WaitSuccessConditionTest.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/utils/WorkspaceDtoDeserializerTest.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceLogsReaderTest.java
  selenium/che-selenium-core/src/test/resources/templates/workspace/openshift/broken_workspace.json
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/hotupdate/HotUpdateUtil.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/gwt/CheckSimpleGwtAppTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/recreate/RecreateUpdateStrategyTest.java
Labels: kind/enhancement, status/code-review, team/che-qe

#11224 CHE-10909: Set Git committer name and email from profile on IDE start
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/CurrentUserInitializer.java
Labels: status/code-review

#11246 [Selenium] Create method for performing specified functionality with ignoring provided exception
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/WebDriverWaitFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
Labels: kind/task, status/code-review

#11239 Fix typo in Contributing.md
  CONTRIBUTING.md
Labels: kind/bug, status/code-review

#11268 Fix NPE for plugin volumes.
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
Labels: kind/task, status/code-review

#11277 [ Selenium ] Fix unexpected fail of "CheckWorkingWithTabsByUsingContextMenuTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckWorkingWithTabsByUsingContextMenuTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11280 Selenium: update "ClangFileEditingTest" selenium test according to language servers test plan
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ClangFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/console-cpp-simple/hello.cc
  selenium/che-selenium-test/src/test/resources/projects/console-cpp-simple/hello.cpp
Labels: kind/task, status/code-review, team/che-qe

#10902 Add extra workspace existence check before creating keypair
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilterTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilter.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineSigningKeyResolver.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenRegistry.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/SignatureKeyManager.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/SignatureKeyManagerException.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/SignaturePublicKeyEnvProvider.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/jpa/JpaSignatureKeyDao.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilterTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenRegistryTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/signature/SignatureKeyManagerTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/signature/spi/tck/SignatureKeyDaoTest.java
Labels: kind/bug, status/code-review

#11247 Imrove code readability by following sonar lint guidance
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticator.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryLinksHelper.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
Labels: status/code-review

#11289 [docker] Fix unison build
  dockerfiles/mount/Dockerfile
Labels: kind/bug, status/code-review

#11288 Change default sidecar memory limit to 512MB to let Theia work OOTB
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#11253 Fix k8s/OS workspace deployment cleanup when pod failed to start
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
Labels: kind/bug, status/code-review

#11283 [ Selenium ] Update usecases in "PhpAssistantFeaturesTest" for catching known bugs #10117 #10698
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/php/PhpAssistantFeaturesTest.java
Labels: kind/task, status/code-review, team/che-qe

#11199 Make OpenShift infrastructure create a special service account for workspaces
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/openshift/deploy_che.sh
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/WorkspaceServiceAccount.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
Labels: kind/task, status/code-review

#11298 Added exec plugin to ws-next stacks
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#11309 Selenium: update expected stacks lists in 'NewWorkspacesPageTest' test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
Labels: kind/task, status/code-review, team/che-qe

#11307 Selenium: update "JsonFileEditingTest" selenium test according to language servers test plan
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AssistantFindPanel.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/JsonFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpFileAdvancedOperationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/php/PhpAssistantFeaturesTest.java
Labels: kind/task, status/code-review, team/che-qe

#11296 Add Apache Camel icon for the Stack (#11236)
  ide/che-core-ide-stacks/pom.xml
  ide/che-core-ide-stacks/src/main/resources/stacks-images/type-apache-camel.svg
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#11310 Add org.eclipse.che.ls.java installer into E2E test workspace templates
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/default.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_jdk8.json
Labels: kind/task, team/che-qe

#11213 Add support of dockerimage and kubernetes recipes in some cases
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/ComposeEnvironment.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerfile/DockerfileEnvironment.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerimage/DockerImageEnvironment.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/DockerRuntimeInfrastructure.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/convert/ComposeEnvironmentConverter.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/convert/DockerImageEnvironmentConverter.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/convert/DockerfileEnvironmentConverter.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/model/DockerEnvironment.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/convert/ComposeEnvironmentConverterTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/convert/DockerImageEnvironmentConverterTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/convert/DockerfileEnvironmentConverterTest.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironment.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/convert/DockerImageEnvironmentConverter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarToolingProvisioner.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfrastructure.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironment.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironment.java
Labels: kind/task, status/code-review

#11248 CHE-11097: Add per-sidecar memory limit in WS.NEXT
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Containers.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolverBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarServicesProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/ContainersTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolverBuilderTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolverTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarServicesProvisionerTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheContainer.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/ChePlugin.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/ChePluginEndpoint.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/Command.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/EditorCompatibility.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginBase.java
Labels: kind/task, status/code-review

#11321 Add an ability to configure Pull policy for broker
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/KubernetesBrokerEnvironmentFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/wsplugins/brokerphases/OpenshiftBrokerEnvironmentFactory.java
Labels: kind/enhancement, status/code-review

#11314 Don't use eclipse.text classes to convert text edits
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/quickassist/ApplyWorkspaceEditAction.java
  wsagent/che-core-api-languageserver-shared/src/main/java/org/eclipse/che/api/languageserver/shared/util/CharStreamEditor.java
  wsagent/che-core-api-languageserver-shared/src/main/java/org/eclipse/che/api/languageserver/shared/util/CharStreamIterator.java
  wsagent/che-core-api-languageserver/pom.xml
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/TextDocumentService.java
  wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/ExtendedTextEditTest.java
Labels: selenium/failure, status/code-review, target/branch, team/languages

#11323 CHE-11097: Allow setting sidecar memory limit in ws attributes
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverBuilder.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheContainer.java
Labels: kind/task, status/code-review

#11293 [ Selenium ] Cover the "Python" language server functionality by selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FindReferencesConsoleTab.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/php/PhpAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/python/PythonAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/python/PythonFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#11332 [dockerfile] Add textmate and minibrowser extensions
  dockerfiles/theia/src/package.json
Labels: status/code-review, team/ide2

#11331 Add memory limit to the Openshift Theia stack.
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review

#11325 [Selenium] Fix unexpected fail of "InheritClassTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
Labels: kind/bug, team/che-qe

#11322 [Selenium] Fix unexpected fail of "CheckRestoringSplitEditorTest" selenium test
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.ui.xml
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
Labels: kind/bug, team/che-qe

#11291 Add plugins widget on workspace creation
  dashboard/src/app/workspaces/create-workspace/create-workspace.controller.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.html
  dashboard/src/app/workspaces/create-workspace/create-workspace.service.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.styl
Labels: kind/enhancement, status/code-review

#11334 Don't fail when jdt.ls messages are not found
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Consoles.java
Labels: selenium/failure, status/code-review, target/branch, team/languages

#11312 Selenium: Update the 'GolangFileEditingTest' according to the test plan
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AssistantFindPanel.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FindReferencesConsoleTab.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
Labels: kind/task, status/code-review, team/che-qe

#11329 Selenium: rework "FindUsages" selenium page object by "SeleniumWebDriverHelper" class
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FindUsages.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindUsagesBaseOperationTest.java
Labels: kind/task, status/code-review, team/che-qe

#11336 Selenium: update "YamlFileEditingTest" selenium test according to language servers test plan
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Preferences.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/YamlFileEditingTest.java
Labels: kind/task, status/code-review, team/che-qe

#11347 Selenium: Update the 'ApacheCamelFileEditingTest' according to the test plan
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/WorkspaceTemplate.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ApacheCamelFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/spring_boot_with_apache_camel_ls.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/spring_boot_with_apache_camel_ls.json
Labels: kind/task, status/code-review, team/che-qe

#11348 Restore some loader.waitOnClosed() calls
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
Labels: status/code-review, target/branch

#11084 New folders do not register in the jdt.ls workspace #10115
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/inject/PlainJavaProjectSourceFolderWatcher.java
Labels: status/code-review, target/branch

#11358 Change default sidecar memory limit to 128MB
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#11354 Setup default value for CHE_WORKSPACE_PLUGIN__REGISTRY__URL
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/kubectl/che-kubernetes.yaml
  deploy/openshift/deploy_che.sh
Labels: kind/task, status/code-review

#11355 Remove multiuser module from single-user integration tests
  wsmaster/integration-tests/postgresql-tck/pom.xml
  wsmaster/integration-tests/postgresql-tck/src/test/java/PostgreSqlTckModule.java
Labels: kind/bug, status/code-review

#11333 Add to TypeScriptEditing test all supported language capabilities
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AssistantFindPanel.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ApacheCamelFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/JsonFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/TypeScriptEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/YamlFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/python/PythonAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/languageServers/typeScriptAfterFormatting.txt
Labels: kind/task, status/code-review

#11365 Selenium: stabilize FindUsagesBaseOperationTest selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FindUsages.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindUsagesBaseOperationTest.java
Labels: kind/task, status/code-review, team/che-qe

#11369 Selenium: Rework the 'waitGitDeletionMarkerInPosition()' to avoid unexpected 'stale element exception'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
Labels: kind/task, status/code-review, team/che-qe

#11368 Add possibility to configure timeout for plugin broker
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/WaitBrokerResult.java
Labels: kind/task, status/code-review

#11371 #11192 - added multiuser tck tests for MySQL
  multiuser/integration-tests/che-multiuser-mysql-tck/pom.xml
  multiuser/integration-tests/che-multiuser-mysql-tck/src/test/java/MultiuserMySqlTckModule.java
  multiuser/integration-tests/che-multiuser-mysql-tck/src/test/resources/META-INF/persistence.xml
  multiuser/integration-tests/che-multiuser-mysql-tck/src/test/resources/META-INF/services/org.eclipse.che.commons.test.tck.TckModule
  multiuser/integration-tests/che-multiuser-mysql-tck/src/test/resources/logback-test.xml
  multiuser/integration-tests/pom.xml
  pom.xml
  wsmaster/integration-tests/mysql-tck/mysql-tests/pom.xml
Labels: kind/task, status/code-review, target/branch

#11375 Close 'Project Configuration' form when configure Che in Che
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/WebDriverWaitFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/ImportAndValidateEclipseCheProjectTest.java
Labels: kind/task, status/code-review, team/che-qe

#11378 Implementers is Broken for Class Files #10337
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
Labels: kind/bug, status/code-review, target/branch

#11367 Add different small improvements
  assembly/assembly-ide-war/src/main/java/org/eclipse/che/ApiAccessRejectionFilter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/convert/DockerImageEnvironmentConverter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/convert/DockerImageEnvironmentConverterTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/bootstrap/AbstractBootstrapper.java
Labels: kind/bug, status/code-review

#11344 Added propagation of plugin broker failing error
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/UnrecoverablePodEventListener.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/UnrecoverablePodEventListenerFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/ListenBrokerEvents.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/WaitBrokerResult.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerService.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerStatusListener.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/UnrecoverablePodEventListenerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBrokerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerStatusListenerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
  multiuser/permission/che-multiuser-permission-infra-kubernetes/src/main/java/org/eclipse/che/multiuser/permission/workspace/infra/kubernetes/BrokerServicePermissionFilter.java
  multiuser/permission/che-multiuser-permission-infra-kubernetes/src/test/java/org/eclipse/che/multiuser/permission/workspace/infra/kubernetes/BrokerServicePermissionFilterTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/BrokerStatusChangedEvent.java
Labels: kind/enhancement, status/code-review

#11343 Adding support of the ephemeral workspaces (using `emptyDir` volume instead of PVC) via 'persistVolumes' attribute
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/EphemeralWorkspaceAdapter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleaner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspaceVolumesStrategy.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/EphemeralWorkspaceAdapterTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleanerTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
Labels: kind/enhancement, status/in-progress

#11388 [Selenium] Create Selenium test covered Theia stack
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaDeleteFileDialog.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaNewFileDialog.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaTerminal.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaDockerStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaOpenshiftStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#11399 [Selenium] Fix of unexpected fail of "UploadIntoProjectTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/UploadIntoProjectTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11389 Correct the 'GitPullTest' related to unexpected stale element reference
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
Labels: kind/task, status/code-review, team/che-qe

#11386 Quick fix for TypeScriptEditingTest
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AssistantFindPanel.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FindReferencesConsoleTab.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/TypeScriptEditingTest.java
Labels: kind/bug, status/code-review

#11407 Selenium: Correct the 'openItemByPath()' to avoid the 'NoSuchElementException'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
Labels: kind/task, status/code-review, team/che-qe
