Repository eclipse-che/che, pull requests merged in 2018-03, with the labels that each got.

#8928 Do not add hidden items to project registry
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/OnWorkspaceStartProjectInitializer.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/RootDirCreationHandler.java
Labels: kind/bug, status/code-review

#8961 Selenium: Transform locators from "CodenvyEditor" page object to enumerations and rework related methods
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/assistant/OrganizeImportsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckWorkingWithTabByUsingTabListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckWorkingWithTabsByUsingContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/SplitEditorFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteFeaturesInEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteJSFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteWithInheritTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/EditorValidationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/InheritClassTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/QuickFixAndCodeAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/ShowHintsCommandTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromUiWithKeepDirTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CheckMainFeatureForCSharpLanguageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckMavenPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ResolveDependencyAfterRecreateProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0087Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0093Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0114Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0115Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0120Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/ConfigureSomeSourceFoldersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/PlainJavaProjectConfigureClasspathTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/RunPlainJavaProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/CheckErrorsWarningsTabTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/CodeAssistAfterMoveItemTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/FailMoveItemTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/parameters/RenameParametersTest.java
Labels: kind/task, status/code-review

#8899 Add fmt:format and sortpom:sort
  assembly/assembly-wsmaster-war/src/main/resources/che-in-che.json
Labels: kind/enhancement, status/code-review

#8980 Selenium: Rework methods from "CodenvyEditor" page object with using "SeleniumWebDriverHelper" and "WebDriverWaitFactory" classes
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/WebDriverWaitFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsEditor.java
Labels: kind/task, status/code-review, team/che-qe

#8994 Selenium: remove info about known issue from NavigateToFileTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/NavigateToFileTest.java
Labels: status/code-review, team/che-qe

#9003 Selenium: open the New Workspace page before each test method in CreateWorkspaceTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
Labels: status/code-review, team/che-qe

#8995 Selenium: Add new methods to the "SeleniumWebDriverHelper" class
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
Labels: kind/task, status/code-review

#9000 Restore Che5 factory behavior.
  plugins/plugin-urlfactory/src/main/java/org/eclipse/che/plugin/urlfactory/URLFactoryBuilder.java
  plugins/plugin-urlfactory/src/test/java/org/eclipse/che/plugin/urlfactory/URLFactoryBuilderTest.java
Labels: status/code-review

#8732 Theia docker file with launcher script
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/build.sh
  dockerfiles/theia/src/main.js
  dockerfiles/theia/theia-default-package.json
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/task, status/code-review

#9011 Add missed binding for MANAGE_USERS system action
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
Labels: kind/bug, status/code-review

#8926 Add ability storing of webdriver console and network logs after failing tests
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/pom.xml
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/SeleniumWebDriver.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/utils/BrowserLogsUtil.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/log/Log.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/log/Message.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/log/Params.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/log/Request.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/log/Response.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/log/WebDriverLogsReader.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/log/WebDriverLogsReaderFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteWithInheritTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/ShowHintsCommandTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerUserCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0093Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0115Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0121Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewPackagesWithHelpCreationJavaClassTest.java
  selenium/che-selenium-test/src/test/resources/conf/selenium.properties
Labels: kind/task, status/code-review

#8838 Workspace loader
  .gitignore
  assembly/assembly-main/pom.xml
  assembly/assembly-main/src/assembly/assembly.xml
  assembly/assembly-workspace-loader-war/pom.xml
  assembly/assembly-workspace-loader-war/src/main/java/org/eclipse/che/WSLoaderController.java
  assembly/assembly-workspace-loader-war/src/main/webapp/WEB-INF/web.xml
  assembly/pom.xml
  dashboard/gulp/proxy.js
  dashboard/src/app/ide/ide.service.ts
  dashboard/src/components/api/che-organizations.factory.ts
  dashboard/src/components/api/test/che-http-backend.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/IDE.html
  pom.xml
  workspace-loader/.dockerignore
  workspace-loader/.gitignore
  workspace-loader/Dockerfile
  workspace-loader/assembly.xml
  workspace-loader/package.json
  workspace-loader/pom.xml
  workspace-loader/src/custom.d.ts
  workspace-loader/src/index.html
  workspace-loader/src/index.ts
  workspace-loader/src/json-rpc/che-json-rpc-api-service.ts
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/json-rpc/json-rpc-client.ts
  workspace-loader/src/json-rpc/util.ts
  workspace-loader/src/json-rpc/websocket-client.ts
  workspace-loader/src/loader/loader.ts
  workspace-loader/src/style.css
  workspace-loader/test/mock.js
  workspace-loader/test/preprocessor.js
  workspace-loader/test/test.spec.ts
  workspace-loader/tsconfig.json
  workspace-loader/tslint.json
  workspace-loader/webpack.common.js
  workspace-loader/webpack.dev.js
  workspace-loader/webpack.prod.js
Labels: kind/enhancement, status/code-review

#9007 Upgrade php language server
  agents/ls-php/src/main/resources/installers/5.3.7/org.eclipse.che.ls.php.json
  agents/ls-php/src/main/resources/installers/5.3.7/org.eclipse.che.ls.php.script.sh
Labels: status/code-review

#9002 CHE-8571 add UD permissive to unknown recipe types which are supported by the server side.
  dashboard/src/app/stacks/stack-details/stack-validation.service.ts
  dashboard/src/app/workspaces/workspace-details/che-recipe.service.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/edit-machine-dialog/edit-machine-dialog.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/edit-machine-dialog/edit-machine-dialog.html
  dashboard/src/components/api/environment/che-environment-manager.factory.ts
  dashboard/src/components/api/environment/default-environment-manager.ts
  dashboard/src/components/api/environment/kubernetes-environment-manager.spec.ts
  dashboard/src/components/api/environment/kubernetes-environment-manager.ts
  dashboard/src/components/api/environment/kubernetes-environment-recipe-parser.ts
  dashboard/src/components/api/environment/kubernetes-machine-recipe-parser.ts
  dashboard/src/components/api/environment/openshift-environment-manager.spec.ts
  dashboard/src/components/api/environment/openshift-environment-manager.ts
  dashboard/src/components/api/recipe/che-recipe-types.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  dashboard/src/components/typings/che.d.ts
  dashboard/src/components/widget/editor/che-editor.controller.ts
  dashboard/src/components/widget/editor/che-editor.directive.ts
  dashboard/src/components/widget/input/che-number-spinner.directive.ts
Labels: kind/task, status/code-review

#9004 Selenium: Update javadocs to actual state in the "SeleniumWebDriverHelper" class
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
Labels: kind/task, status/code-review, team/che-qe

#9005 Selenium: Improve and rework the 'FetchUpdatesAndMergeRemoteBranchIntoLocalTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/FetchAndMergeRemoteBranchIntoLocalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/FetchUpdatesAndMergeRemoteBranchIntoLocalTest.java
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/FetchUpdatesAndMergeRemoteBranchIntoLocalTest.txt
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/GitPullTest.txt
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/PullRemovedFile.txt
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/PushChangeNonUpdatedRepoTest.txt
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/README.md
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/newFile.css
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/pom.xml
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/src/main/java/commenttest/FetchUpdatesAndMergeRemoteBranchIntoLocalTest.java
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/src/main/java/commenttest/GitPullTest.java
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/src/main/java/commenttest/JavaCommentsTest.java
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/src/main/java/commenttest/PushingChangesTest.java
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/src/main/webapp/WEB-INF/jsp/hello_view.jsp
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/src/main/webapp/WEB-INF/spring-servlet.xml
  selenium/che-selenium-test/src/test/resources/projects/testRepo-1/src/main/webapp/index.jsp
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#8889 Buffer input file change events and disable file tracking during git reset
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/ProjectTreeChangeHandler.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/ProjectTreeStateNotificationOperation.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/branch/BranchViewImpl.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/checkout/CheckoutReferencePresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/ComparePresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/merge/MergePresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/pull/PullPresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/remote/RemotePresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/remove/RemoveFromIndexPresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/reset/commit/ResetToCommitPresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/revert/RevertCommitPresenter.java
  plugins/plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/BaseTest.java
  plugins/plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/checkout/CheckoutReferenceTest.java
  plugins/plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/merge/MergePresenterTest.java
Labels: kind/bug, severity/P1, status/in-progress, team/ide

#9017 Fix removal of inactive containers
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/Labels.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/monit/DockerAbandonedResourcesCleaner.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/monit/DockerAbandonedResourcesCleanerTest.java
Labels: kind/bug, status/code-review

#9034 CHE-9024: fix ability to start a workspace from Dashboard
  workspace-loader/src/index.ts
  workspace-loader/webpack.dev.js
Labels: kind/bug, status/code-review

#8998 Allow to configure logback logger with env variables
  assembly/assembly-ide-war/pom.xml
  core/commons/che-core-commons-logback/pom.xml
  core/commons/che-core-commons-logback/src/main/java/org/eclipse/che/commons/logback/EnvironmentVariablesLogLevelPropagator.java
  wsagent/che-wsagent-core/pom.xml
Labels: kind/task, status/code-review

#9065 Add new common methods in the 'SeleniumWebDriverHelper' class
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
Labels: kind/task, status/code-review

#8898 Fix selenium tests
  plugins/plugin-java-debugger/che-plugin-java-debugger-ide/src/main/java/org/eclipse/che/plugin/jdb/ide/debug/ExternalResourceLocationHandler.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/service/JavaLanguageExtensionServiceClient.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ConditionalBreakpointsTest.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/service/LanguageServiceUtils.java
Labels: kind/task, status/code-review, target/branch

#9059 Selenium: Delete the 'try/catch' from selenium tests in the 'opendeclaration' package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0093Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0115Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0120Test.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/opendeclaration/Eclipse0121Test.java
Labels: kind/task, status/code-review, team/che-qe

#9075 Add catching known issue to the 'GitColorsTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitColorsTest.java
Labels: kind/bug, status/code-review

#9073 Unable to open Theia IDE
  workspace-loader/src/index.ts
  workspace-loader/src/loader/loader.ts
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/ServersChecker.java
Labels: kind/bug, status/code-review, team/plugin

#9043 Add authentication filters for websocket connections
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/AbstractKeycloakFilter.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilter.java
Labels: kind/task

#9031 Selenium: Inspect methods logic in the "CodenvyEditor" pageobject and rework it where it necessary
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/debug/DebugPanel.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringSplitEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckWorkingWithTabByUsingTabListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckWorkingWithTabsByUsingContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/SplitEditorFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteWithInheritTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/CheckAutocompleteFeaturesInTheTestFolderTest.java
Labels: kind/task, status/code-review, team/che-qe

#9069 Add ability to exclude github-specific selenium tests from test execution
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/TestGroup.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubKeyUploader.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceImpl.java
  selenium/che-selenium-test/README.md
  selenium/che-selenium-test/pom.xml
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithMultiModuleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithSparseCheckoutTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithKeepDirectoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AddFilesToIndexTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AmendCommitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromImportTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromPreferencesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/BranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutReferenceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchWhichAlreadyHasLinkedLocalBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesByMultiSelectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CreateAndDeleteLocalBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/FetchAndMergeRemoteBranchIntoLocalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitChangeMarkersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitColorsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitCompareTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportProjectIntoSpecifiedBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportRecursiveSubmoduleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/InitializeAndDeleteLocalRepositoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/KeepDirectoryGitImportTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginWithForkTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PushChangeNotUpdatedRepoTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PushingChangesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/RevertCommitTest.java
  selenium/che-selenium-test/src/test/resources/conf/selenium.properties
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#9089 remove outdated s2i from init image
  dockerfiles/init/Dockerfile
  dockerfiles/init/s2i/keycloak/assemble
  dockerfiles/init/s2i/keycloak/run
  dockerfiles/init/s2i/postgres/assemble
  dockerfiles/init/s2i/postgres/run
Labels: kind/task, status/code-review

#9072 CHE-8752: Fix error when creating project inside existing folder
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitStatusProvider.java
  wsagent/che-core-api-git/src/test/java/org/eclipse/che/api/git/GitStatusProviderTest.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceVcsStatusInjector.java
  wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/fs/server/impl/ProjectServiceVcsStatusInjectorTest.java
Labels: kind/bug, status/code-review

#9101 Selenium: change method for expanding test project in CreateWorkspaceOnDashboardTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
Labels: kind/bug, status/code-review, team/che-qe

#9102 Selenium: add info about known issue #9100 to ProjectExplorer selenium page object
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
Labels: status/code-review, team/che-qe

#9087 Selenium: add checking that a workspace name is valid in RenameWorkspaceTest
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceOverview.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
Labels: kind/task, status/code-review, team/che-qe

#9093 Do not duplicate Error/Warnings items in Preferences
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/settings/compiler/JavaCompilerPreferencePresenter.java
Labels: kind/bug

#9091 Adapt to the new version of lsp4j
  plugins/plugin-java/che-plugin-java-server/pom.xml
Labels: kind/task, status/code-review, target/branch

#9111 Allow using --build-arg in build.sh scripts
  dockerfiles/build.include
Labels: kind/enhancement, kind/task, status/code-review

#9092 Don't publish ProjectCreatedEvent on importing arbitrary zipped resources
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
Labels: status/code-review

#8784 CHE-8557: No Dto available for FormattingOptions
  core/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/LanguageServerFormatter.java
  wsagent/che-core-api-languageserver-maven-plugin/src/main/java/org/eclipse/che/api/languageserver/generator/FromJsonGenerator.java
  wsagent/che-core-api-languageserver-maven-plugin/src/main/java/org/eclipse/che/api/languageserver/generator/ToDtoGenerator.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/util/EitherUtil.java
  wsagent/che-core-api-languageserver/src/main/resources/META-INF/services/com.google.gson.TypeAdapterFactory
  wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/dto/DtoConversionTest.java
Labels: kind/bug, status/code-review

#9030 Improve and rework the 'RevertCommitTest' to use the 'kohsuke Github library'
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitRevertCommit.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/RevertCommitTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#9117 Selenium: check that the IDE is loaded before switching to IDE application frame
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/SeleniumWebDriver.java
Labels: kind/bug, status/code-review, team/che-qe

#9088 CHE-9067: Fix bug with git colors in editor tabs
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/plugins/EditorTabsColorizer.java
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/plugins/ProjectExplorerTreeColorizer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitColorsTest.java
Labels: kind/bug, status/code-review

#9116 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#9115 Selenium: Update javadocs to actual state in the "CodenvyEditor" class
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
Labels: kind/task, status/code-review

#9137 Fix version of jdtls runner
  agents/ls-java/src/main/resources/installers/1.0.1/org.eclipse.che.ls.java.script.sh
Labels: status/code-review, target/branch

#9141 Encapsulate kohsuke-related code and ensure test repo creation
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubServiceClient.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/FetchAndMergeRemoteBranchIntoLocalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
Labels: kind/bug, status/code-review, team/che-qe

#9153 Fix TestGitHubRepository formatting
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
Labels: kind/bug, status/code-review

#9118 che #9062: Adding property for setting workspace pod termination grace period for Kubernetes / OpenShift infrastructures
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/PodTerminationGracePeriodProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
Labels: kind/task, status/code-review

#9159 fix ocp.sh ability to be launched from any place
  deploy/openshift/ocp.sh
Labels: kind/bug, status/code-review

#9160 apply codeowners for deploy module
  .github/CODEOWNERS
Labels: status/code-review

#9165 fix deploy_che.sh ability to be launched from any place
  deploy/openshift/deploy_che.sh
Labels: kind/bug, status/code-review

#9138 docker-compose: stop exposing postgres to external
  dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
Labels: status/code-review

#9168 Do not redirect to UD requests intended to be for the API
  assembly/assembly-ide-war/src/main/java/org/eclipse/che/ApiAccessRejectionFilter.java
  assembly/assembly-ide-war/src/main/java/org/eclipse/che/DashboardModule.java
  assembly/assembly-ide-war/src/test/java/org/eclipse/che/ApiAccessRejectionFilterTest.java
Labels: kind/bug, status/code-review

#9161 Introduce logger REST API to manage log level at runtime
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  multiuser/permission/che-multiuser-permission-logger/pom.xml
  multiuser/permission/che-multiuser-permission-logger/src/main/java/org/eclipse/che/multiuser/permission/logger/LoggerServicePermissionsFilter.java
  multiuser/permission/che-multiuser-permission-logger/src/test/java/org/eclipse/che/multiuser/permission/user/LoggerServicePermissionsFilterTest.java
  multiuser/permission/pom.xml
  pom.xml
  wsmaster/che-core-api-logger-shared/pom.xml
  wsmaster/che-core-api-logger-shared/src/main/java/org/eclipse/che/api/logger/shared/dto/LoggerDto.java
  wsmaster/che-core-api-logger/pom.xml
  wsmaster/che-core-api-logger/src/main/java/org/eclipse/che/api/logger/LoggerService.java
  wsmaster/che-core-api-logger/src/test/java/org/eclipse/che/api/logger/LoggerServiceTest.java
  wsmaster/pom.xml
Labels: kind/enhancement, status/code-review

#9170 CHE-8675: fix reconnection to a WebSocket entrypoint
  dashboard/src/components/api/json-rpc/che-json-rpc-api.factory.ts
  dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts
  dashboard/src/components/api/json-rpc/json-rpc-client.ts
  dashboard/src/components/api/json-rpc/websocket-client.ts
Labels: kind/bug, status/code-review

#9177 ocp.sh clean-up
  deploy/openshift/ocp.sh
Labels: status/code-review

#9173 Cleanup view before showing new results
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/navigation/NavigateToFileViewImpl.java
Labels: kind/task, status/code-review

#9144 Selenium: Remove inheriting between "CodenvyEditor" and "CommandsEditor"
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/QuickFixAndCodeAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/AutocompleteCommandsEditorTest.java
Labels: kind/task, status/code-review, team/che-qe

#9185 fix wait CHE pod in deploy script
  deploy/openshift/deploy_che.sh
Labels: kind/bug, status/code-review

#9188 Selenium: remove info about known issues from dashboard and miscellaneous packages
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/RenameOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FileStructureBaseOperationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ResolveDependencyAfterRecreateProjectTest.java
Labels: kind/task, status/code-review, team/che-qe

#9167 Selenium: cover sharing workspaces in organization by selenium test
  dashboard/src/app/workspaces/share-workspace/add-members/add-members.html
  dashboard/src/app/workspaces/share-workspace/share-workspace.html
  dashboard/src/app/workspaces/share-workspace/user-item/user-item.html
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceShare.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#9189 Selenium: test SSH and Volumes tab on workspace details page
  dashboard/src/app/workspaces/workspace-details/workspace-ssh/workspace-details-ssh.html
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceSsh.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspacesVolumes.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/WorkspaceDetailsSingleMachineTest.java
Labels: kind/task, status/code-review, team/che-qe

#8992 Progress UI for Language Servers
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaCss.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaExtension.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/inject/JavaGinModule.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/inject/factories/ProgressWidgetFactory.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressMessagesHandler.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressMonitorPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressMonitorView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressMonitorViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressMonitorViewImpl.ui.xml
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressViewImpl.ui.xml
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/ProgressorJsonRpcHandler.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/background/BackgroundLoaderPresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/background/BackgroundLoaderView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/background/BackgroundLoaderViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/background/BackgroundLoaderViewImpl.ui.xml
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/progressor/background/ProgressMonitorAction.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.properties
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/java.css
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/progressor/background/Loader.css
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/progressor/background/error.svg
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/progressor/background/loaderIcon.svg
  plugins/plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/Constants.java
  plugins/plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/dto/progressor/ProgressReportDto.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/inject/JavaModule.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageClient.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProcessorJsonRpcCommunication.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProgressReport.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/MavenExtension.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/registry/LanguageServerRegistryImpl.java
Labels: kind/enhancement, status/code-review, target/branch

#9182 hide "Users" menu item in left navbar when keycloack is used
  dashboard/src/app/navbar/navbar.controller.ts
  dashboard/src/app/navbar/navbar.html
Labels: kind/bug, status/code-review

#9193 Do not throw Exception when not project item is found in root
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/SimpleFsDtoConverter.java
Labels: kind/bug

#9187 Fix handling messages from Maven server after workspace restart
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/MavenJsonRpcHandler.java
Labels: kind/bug

#8650 Support alternate OIDC providers, to prepare for the switch from Keycloak to `fabric8_auth`
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/keycloak/OIDCKeycloak.js
  dashboard/src/app/index.module.ts
  dashboard/src/app/profile/profile.controller.ts
  dashboard/src/app/profile/profile.html
  dockerfiles/init/manifests/che.env
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/IDE.html
  multiuser/keycloak/che-multiuser-keycloak-ide/src/main/java/org/eclipse/che/multiuser/keycloak/ide/Keycloak.java
  multiuser/keycloak/che-multiuser-keycloak-ide/src/main/java/org/eclipse/che/multiuser/keycloak/ide/KeycloakProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/AbstractKeycloakFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakAuthenticationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakConfigurationService.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettings.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/dao/KeycloakProfileDao.java
  multiuser/keycloak/che-multiuser-keycloak-shared/src/main/java/org/eclipse/che/multiuser/keycloak/shared/KeycloakConstants.java
  workspace-loader/src/index.ts
Labels: status/code-review

#9207 ocp.sh clean up
  deploy/openshift/ocp.sh
Labels: status/code-review

#9163 CHE-9095: Improve Theia build stability on plugin list changes
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/src/main.js
Labels: kind/bug, status/code-review

#9205 Selenium: fix unstable selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/SeleniumWebDriver.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteRunningWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckRestoringWorkspaceAfterStoppingWsAgentProcess.java
Labels: kind/bug, status/code-review, team/che-qe

#9174 Selenium: Inspect methods logic in the "CommandsEditor" pageobject
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/QuickFixAndCodeAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/MacrosCommandsEditorTest.java
Labels: kind/task, status/code-review

#9217 Selenium: Delete not actual "known issue" from "editor" and "projectexplorer" test packages
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteWithInheritTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/ShowHintsCommandTest.java
Labels: kind/task, status/code-review, team/che-qe

#9219 Improve interaction between selenium tests and GitHub
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/FetchAndMergeRemoteBranchIntoLocalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
Labels: kind/enhancement, status/code-review, team/che-qe

#9222 Fix deployment che-multi on docker
  dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
Labels: kind/bug, status/code-review

#9240 Allow overriding CHE props defined in che-config file
  deploy/openshift/che-config
Labels: kind/enhancement, status/code-review

#9227 Fix File Watcher exclude feature
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/filewatcher/FileWatcherExcludesOperation.java
Labels: kind/bug, status/code-review

#9216 Add and use script for adding git hosted plugins into Theia image
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/src/add-native-plugins.js
Labels: kind/enhancement, status/code-review

#9250 CHE-9095: Hot fix
  dockerfiles/theia/src/main.js
Labels: kind/bug, status/code-review

#9229 Add handler to clean up project config registry
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectApiModule.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/RootDirRemovalHandler.java
Labels: kind/bug, status/code-review

#9242 Selenium: Update javadocs to actual state in the "CommandsEditor" class
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/MacrosCommandsEditorTest.java
Labels: kind/task, status/code-review

#9249 Selenium: Add new methods to the "SeleniumWebDriverHelper" class
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
Labels: kind/task, status/code-review

#9256 Selenium: Rework static classes "CommandsEditorType" and "CommandsMacrosLinkType" to enumerations
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/AutocompleteCommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/MacrosCommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/PreviewUrlIntoCommandsEditorTest.java
Labels: kind/task, status/code-review, team/che-qe

#9230 Fix K8s Helm Chart
  deploy/kubernetes/helm/.gitignore
  deploy/kubernetes/helm/che/Chart.yaml
  deploy/kubernetes/helm/che/templates/cert-issuer.yaml
  deploy/kubernetes/helm/che/templates/staging-cert-issuer.yaml
Labels: kind/bug, status/code-review

#9263 Handle issue #9251 in selenium tests related to debugger
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/machineperspective/MachineTerminal.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ChangeVariableWithEvaluatingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/DebuggerUtils.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/StepIntoStepOverStepReturnWithChangeVariableTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromUiWithKeepDirTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
Labels: kind/task, status/code-review, team/che-qe

#9278 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#9264 Add ability to configure Theia port
  dockerfiles/theia/src/main.js
Labels: kind/enhancement, status/code-review

#9261 Selenium: Unexpected fail of TransitiveDependencyTest in the selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/TransitiveDependencyTest.java
Labels: kind/bug, status/code-review

#9259 Provide configuration property to be able to set docker image build timeout
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  dockerfiles/init/manifests/che.env
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerConnector.java
  infrastructures/docker/docker-client/src/test/java/org/eclipse/che/infrastructure/docker/client/DockerConnectorTest.java
Labels: kind/enhancement, status/code-review

#9270 Provide configuration property to be able to set docker image build timeout
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
  dockerfiles/init/manifests/che.env
  plugins/plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnector.java
  plugins/plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/DockerConnectorTest.java
  plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
  plugins/plugin-docker/che-plugin-openshift-client/src/test/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnectorTest.java
Labels: kind/enhancement, status/code-review

#9228 Selenium: Rework the 'CheckoutToRemoteBranchTest' to run in multi-threaded mode
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/pom.xml
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/FetchAndMergeRemoteBranchIntoLocalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
Labels: kind/task, status/code-review, team/che-qe

#9171 Add the test for checking inactive workspace
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestWorkspaceServiceClient.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStoppingWsByTimeoutTest.java
  selenium/che-selenium-test/src/test/resources/conf/selenium.properties
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review

#9237 Set correct response for non-working services in Multi User Che
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/UnavailableResourceInMultiUserFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakServletModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/UnavailableResourceInMultiUserFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/resources/logback.xml
Labels: kind/task, status/code-review

#9293 Selenium: Improve and rework the 'KeepDirectoryGitImportTest' for ability to launching in multi-threaded mode
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/KeepDirectoryGitImportTest.java
Labels: kind/task, status/code-review

#9274 Use the owner Id only in the workspace `RuntimeIdentity` (#8859)
  agents/go-agents/bootstrapper/booter/booter_test.go
  agents/go-agents/bootstrapper/booter/events.go
  agents/go-agents/bootstrapper/cfg/cfg.go
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/runtime/RuntimeIdentity.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/Labels.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/bootstrap/DockerBootstrapper.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/DockerEnvironmentNormalizer.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/DockerInternalRuntimeTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/LabelsTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/container/DockerContainersTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/local/installer/WsAgentServerConfigProvisionerTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/local/projects/BindMountProjectsVolumeProvisionerTest.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/server/mapping/SinglePortUrlRewriterTest.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategyTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/RuntimeIdentityDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/bootstrap/AbstractBootstrapper.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/RuntimeIdentityImpl.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/InternalRuntime.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/RuntimeStartInterruptedException.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/probe/WorkspaceProbesFactoryTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/InternalRuntimeTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/provision/env/EnvVarEnvironmentProvisionerTest.java
Labels: kind/enhancement, status/code-review

#9303 Change the name of test project for better readability
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
Labels: kind/enhancement, status/code-review
