Repository eclipse-che/che, pull requests merged in 2018-08, with the labels that each got.

#10607 Fix remaining notes about old EPL 1.0 license
  LICENSE
  README.md
  dashboard/README.md
Labels: kind/task, status/code-review

#10556 Selenium: Fix logical mistakes in the "SeleniumWebDriverHelper" class methods
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
Labels: kind/bug, status/code-review, team/che-qe

#10608 Fix build errors after rebase
  plugins/plugin-java/che-plugin-java-ext-lang-server/pom.xml
  plugins/plugin-maven/che-plugin-maven-server/pom.xml
Labels: kind/bug, status/code-review, target/branch

#10614 [stack] Update theia image to latest one
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: status/code-review

#10616 Fix java debugger integration tests
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/BreakpointConditionTest.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/BreakpointsTest.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/EvaluateExpressionTest1.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/GetValueTest1.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/JavaDebuggerTest.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/StackFrameDumpTest1.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/SuspendPolicyTest.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/ThreadDumpTest1.java
Labels: kind/bug, status/code-review, team/languages

#10623 Fix for checking Java Compiler settings in selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/CheckErrorsWarningsTabTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/preferences/embed-code
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/.gitignore
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/README.md
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/pom.xml
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/src/main/java/che/eclipse/sample/Aclass.java
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/src/main/java/org/eclipse/qa/examples/AppController.java
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/src/main/webapp/WEB-INF/jsp/guess_num.jsp
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/src/main/webapp/WEB-INF/spring-servlet.xml
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/src/main/webapp/WEB-INF/web.xml
  selenium/che-selenium-test/src/test/resources/projects/prefs-spring-project/src/main/webapp/index.jsp
Labels: kind/bug, status/code-review, target/branch, team/languages

#10622 Set Che QE team members as owners of selenium tests sub-project
  .github/CODEOWNERS
Labels: kind/task, status/code-review

#10517 Add a missing file required to correctly bootstrap Ceylon user projects
  plugins/plugin-ceylon/che-plugin-ceylon-lang-server/src/main/resources/project/.ceylon/bootstrap/ceylon-bootstrap.jar
Labels: kind/enhancement, status/code-review

#10619 Loader fix
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.html
Labels: kind/task, status/code-review

#10635 Update resource of the generated effective pom
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckGeneratingMavenArchetypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/GenerateEffectivePomTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/mavenplugin/jar-module
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/mavenplugin/main
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/mavenplugin/war-module
Labels: status/code-review, target/branch, team/languages

#10658 Selenium: adapt template project file after updating licenses headers
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/refactor/move/test7/out/A.java
Labels: kind/bug, status/code-review, team/che-qe

#10633 Rewrite JWTProxyConfigBuilder to use model objects to create config YAML
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyConfigBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/model/Config.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/model/JWTProxy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/model/RegistrableComponentConfig.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/model/SignerProxy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/model/VerifierConfig.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/model/VerifierProxyConfig.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyConfigBuilderTest.java
  infrastructures/kubernetes/src/test/resources/jwtproxy-confg.yaml
Labels: kind/task, status/code-review

#10661 Selenium: Cover "Dashboard / Workspace Details / Overview" part of test plan by selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/AddOrImportForm.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceOverview.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#10625 Selenium: cover Golang language server functionality by selenium test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/project/ProjectTemplates.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/WorkspaceTemplate.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/intelligent/CommandsEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/CheckAutocompleteFeaturesInTheTestFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/InheritClassTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ApacheCamelFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ClangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PhpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/PythonFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/TypeScriptEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/YamlFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/go-simple/format.go
  selenium/che-selenium-test/src/test/resources/projects/go-simple/main.go
  selenium/che-selenium-test/src/test/resources/projects/go-simple/print.go
  selenium/che-selenium-test/src/test/resources/projects/go-simple/towers.go
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
  selenium/che-selenium-test/src/test/resources/templates/project/go.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/ubuntu_go.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_go.json
Labels: kind/task, status/code-review, team/che-qe

#10676 Added an ability to remove user when third-party user management service is configured
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakServletModule.java
Labels: kind/task, status/code-review

#10681 Selenium: Increase stability of the "WorkspacesListTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10686 Selenium: Increase stability of the "AddOrImportProjectFormTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10642 CHE-10538: improves workspace loader
  workspace-loader/Dockerfile
  workspace-loader/assembly.xml
  workspace-loader/src/index.html
  workspace-loader/src/index.ts
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/loader/loader.ts
  workspace-loader/src/style.css
  workspace-loader/test/mock.js
  workspace-loader/test/preprocessor.js
  workspace-loader/test/test.spec.ts
  workspace-loader/webpack.common.js
  workspace-loader/webpack.dev.js
  workspace-loader/webpack.prod.js
Labels: kind/bug, status/code-review

#10606 CHE-9937 Fix Composer project type
  plugins/plugin-composer/che-plugin-composer-server/src/main/java/org/eclipse/che/plugin/composer/server/projecttype/ComposerProjectGenerator.java
  plugins/plugin-composer/che-plugin-composer-server/src/main/java/org/eclipse/che/plugin/composer/server/projecttype/ComposerValueProviderFactory.java
Labels: kind/bug, status/code-review

#10529 Simplify OpenShift/Kubernetes admin configuration
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/kubectl/che-kubernetes.yaml
  deploy/openshift/deploy_che.sh
  deploy/openshift/templates/che-server-template.yaml
  dockerfiles/init/manifests/che.env
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
Labels: kind/bug, status/code-review

#10684 Do not expose workspace runtime for user if he does not have `use` permission
  multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenProviderImpl.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenProviderImplTest.java
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/token/MachineAccessForbidden.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/token/MachineTokenProvider.java
Labels: kind/bug, status/code-review

#10688 CHE-10540: stop progress on websocket error
  workspace-loader/src/index.ts
  workspace-loader/test/test.spec.ts
Labels: kind/bug, status/code-review

#10691 Selenium: Cover "Dashboard / Workspace Details / Projects" part of test plan by selenium test
  dashboard/src/app/stacks/stack-details/stack.spec.ts
  dashboard/src/components/widget/popover/che-toggle-button-popover.directive.ts
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjects.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjectsSamples.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteRunningWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteStoppingWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsComposeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsSingleMachineTest.java
Labels: kind/task, status/code-review, team/che-qe

#10665 New folders do not register in the jdt.ls workspace #10115
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/NodeLoader.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/util/JavaLanguageServerExtensionStub.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/classpath/ClasspathResolver.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/pom.xml
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/rest/ClasspathUpdaterService.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/ExecuteClientCommandProcessor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveJavaFileInNewSourceFolderTest.java
Labels: status/code-review, target/branch

#10719 Render context menu correctly in different screen resolutions
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/menu/ContextMenu.java
Labels: kind/bug, severity/P2, status/code-review, team/ide

#10717 Selenium: fix unstable selenium tests from dashboard and miscellaneous packages
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceImpl.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjects.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/MachinesAsynchronousStartTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, selenium/failure, status/code-review, team/che-qe

#10722 Selenium: Add catching of known #10713 issue to 'CheckIntelligenceCommandFromToolbarTest' selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
Labels: kind/task, status/code-review, team/che-qe

#10727 Selenium: Fix of unexpected fail of "OpenExternalLibraryFileAfterRefreshTest" selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/dependencies/OpenExternalLibraryFileAfterRefreshTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10689 Update maven module if parent was changed
  plugins/plugin-java/che-plugin-java-server/pom.xml
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/ExecuteClientCommandProcessor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckMavenPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/RenamePrivateFieldSmokeTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#10734 CHE-10687: fix log message, add check for runtime in running workspace
  workspace-loader/package.json
  workspace-loader/src/index.ts
  workspace-loader/test/test.spec.ts
Labels: kind/bug, status/code-review

#10741 Remove test github repo created by PullRequestPluginWithForkTest
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjectsSamples.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginWithForkTest.java
Labels: kind/task, status/code-review

#10694 CHE-10656: persist 'yarn.lock' with fixed dependency versions
  workspace-loader/.dockerignore
  workspace-loader/Dockerfile
  workspace-loader/pom.xml
  workspace-loader/yarn.lock
Labels: kind/task, status/code-review

#10721 Added attributes field to workspace config object
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/WorkspaceConfig.java
  dashboard/src/app/stacks/stack-details/stack-validation.service.ts
  dashboard/src/components/typings/che.d.ts
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/workspace/model/WorkspaceConfigImpl.java
  ide/commons-gwt/pom.xml
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/TestObjects.java
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/TestObjectsFactory.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/jpa/MultiuserJpaWorkspaceDaoTest.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/spi/jpa/RemoveWorkersBeforeWorkspaceRemovedEventSubscriberTest.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/spi/tck/WorkerDaoTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WorkspaceConfigDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/WorkspaceConfigImpl.java
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.10.0/1__add_workspace_cfg_attributes.sql
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/TestObjectsFactory.java
  wsmaster/integration-tests/postgresql-tck/pom.xml
Labels: kind/task, status/code-review

#10737 Added an ability to configure JwtProxy container and memory limit for it
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/factory/JwtProxyConfigBuilderFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/factory/JwtProxyProvisionerFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/factory/JwtProxySecureServerExposerFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
Labels: kind/task, status/code-review

#10747 fix k8s deployment fail
  deploy/kubernetes/helm/che/templates/configmap.yaml
Labels: kind/bug, status/code-review

#10752 Add utility method to remove test github repos with certain prefix
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubRepository.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjectsSamples.java
Labels: kind/task, status/code-review, team/che-qe

#10750 CHE-9148: fix workspace item in organization's workspaces list
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.controller.ts
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.html
Labels: kind/bug, status/code-review

#10736 Change steps for increasing stability tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Events.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerUserCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginTestNgTest.java
Labels: kind/bug, status/code-review

#10765 Don't write files to test codebase
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestProjectServiceClient.java
Labels: kind/bug, selenium/failure, status/code-review, target/branch, team/languages

#10773 Update copyright in test to epl 2.0
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
Labels: selenium/failure, status/code-review, target/branch, team/languages

#10771 Change steps in the CSharpFileEditingTest according to new behavior for init the LS
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CSharpFileEditingTest.java
Labels: kind/task, status/code-review

#10777 [Selenium] Fix expected number of process counter in CheckIntelligenceCommandFromToolbarTest selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Wizard.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CommandsEditorTest.java
Labels: kind/task, status/code-review, team/che-qe

#10763 Added an ability to configure whether machine server authentication via cookies is enabled
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/ServerConfig.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyConfigBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/model/VerifierConfig.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyConfigBuilderTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  infrastructures/kubernetes/src/test/resources/jwtproxy-confg.yaml
Labels: kind/task, status/code-review

#10509 Make host calculation more short and concise for che master
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/ingress.yaml
  deploy/kubernetes/helm/che/templates/_hostHelper.tpl
  deploy/kubernetes/helm/che/templates/_keycloakAuthUrlHelper.tpl
  deploy/kubernetes/helm/che/templates/_keycloakHostHelper.tpl
  deploy/kubernetes/helm/che/templates/certificate.yaml
  deploy/kubernetes/helm/che/templates/ingress.yaml
  dockerfiles/keycloak/kc_realm_user.sh
Labels: status/code-review

#10786 Selenium: fix unstable selenium tests from dashboard and miscellaneous packages
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Refactor.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/bug, status/code-review, team/che-qe

#10790 Add info about known issue #10789 to CSharpFileEditingTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CSharpFileEditingTest.java
Labels: kind/bug, status/code-review

#10797 Fix formatting of CSharpFileEditingTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CSharpFileEditingTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10799 Add 500 error to the rest framework for go agents
  agents/go-agents/core/rest/errors.go
Labels: kind/enhancement, status/code-review

#10785 Fix parent path handling when importing test projects
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/ZipUtils.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestProjectServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/AbstractUploadUtil.java
Labels: kind/bug, selenium/failure, status/code-review, target/branch, team/languages

#10787 Fix name of 'Java Theia(openshift)' stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review, team/che-qe

#10804 Selenium: add info about known issue #9100 to CheckFactoryWithPerClickCreatePolicyTest and CheckFactoryWithMultiModuleTest tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithMultiModuleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerClickCreatePolicyTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10802 Fix redirect URIs and webOrigins
  dockerfiles/keycloak/kc_realm_user.sh
Labels: kind/bug, status/code-review

#10760 CHE-5650: set fixed sorting order for prioritized stacks
  dashboard/src/app/workspaces/create-workspace/stack-selector/stack-selector-item/stack-selector-item.directive.ts
  dashboard/src/app/workspaces/create-workspace/stack-selector/stack-selector-item/stack-selector-item.html
  dashboard/src/app/workspaces/create-workspace/stack-selector/stack-selector-item/stack-selector-item.styl
  dashboard/src/app/workspaces/create-workspace/stack-selector/stack-selector.controller.ts
  dashboard/src/app/workspaces/create-workspace/stack-selector/stack-selector.html
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
Labels: kind/bug, status/code-review

#10801 CHE_INFRASTRUCTURE and CHE_MULTIUSER vars can be now passed as system
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/configuration/InMemoryTestConfiguration.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/configuration/SeleniumTestConfiguration.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
Labels: status/code-review

#10811 Selenium: add info about known issue #10809 to CheckIntelligenceCommandFromToolbarTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10670 New test case for rolling update
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/hotupdate/HotUpdateUtil.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithStartedWorkspaceTest.java
Labels: status/code-review

#10815 Fix resource leak in ZipUtils
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/ZipUtils.java
  core/commons/che-core-commons-lang/src/test/java/org/eclipse/che/commons/lang/ZipUtilsWriteTest.java
Labels: kind/bug, selenium/failure, status/code-review, target/branch

#10632 Fixing of letters cut-off in left menu.
  dashboard/src/components/attribute/clip-the-middle/che-clip-the-middle.styl
Labels: kind/bug, status/code-review

#10778 CHE-10121: fix behavior of the factory's "Create" button
  dashboard/src/app/factories/create-factory/create-factory.html
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
Labels: kind/bug, status/code-review

#10640 Add ability to get File Type by provider and avoid File Type collision
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/editor/EditorRegistry.java
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/filetypes/FileType.java
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/filetypes/FileTypeRegistry.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorAgentImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorRegistryImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/filetypes/FileTypeProviderImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/filetypes/FileTypeRegistryImpl.java
  plugins/plugin-ceylon/che-plugin-ceylon-lang-ide/src/main/java/org/eclipse/che/plugin/ceylon/ide/inject/CeylonGinModule.java
  plugins/plugin-cpp/che-plugin-cpp-lang-ide/src/main/java/org/eclipse/che/plugin/cpp/ide/inject/CppGinModule.java
  plugins/plugin-csharp/che-plugin-csharp-lang-ide/src/main/java/org/eclipse/che/plugin/csharp/ide/inject/CSharpGinModule.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/inject/JavaGinModule.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/LanguageRegexesInitializer.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/inject/LanguageServerGinModule.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/registry/LanguageServerRegistry.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/MavenExtension.java
  plugins/plugin-php/che-plugin-php-lang-ide/src/main/java/org/eclipse/che/plugin/php/ide/inject/PhpGinModule.java
  plugins/plugin-python/che-plugin-python-lang-ide/src/main/java/org/eclipse/che/plugin/python/ide/inject/PythonGinModule.java
  plugins/plugin-web/che-plugin-web-ext-web/src/main/java/org/eclipse/che/plugin/web/client/inject/WebModule.java
Labels: kind/bug, status/code-review

#10814 Make clickable the whole workspace item row in workspaces list of an organization
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.html
Labels: kind/bug, status/code-review

#10791 Fix selenium test groups management
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/TestFilter.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/inject/TestFilterTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/AccountTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AdminOfParentOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AdminOfSubOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/CreateRootOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationByBulkTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationInListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/FilterOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/MemberOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/OrganizationMembersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/RenameOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/SystemAdminOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/UserEmptyOrganizationTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review

#10709 Fix unrecoverable events functionality after move to deployments
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
Labels: kind/bug, status/code-review

#10545 Fix sequential start of workspace machines
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Constants.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
Labels: kind/bug, status/code-review

#10761 Make machine token signing key per-workspace
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  multiuser/integration-tests/che-multiuser-cascade-removal/pom.xml
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/TestObjectsFactory.java
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/resources/META-INF/persistence.xml
  multiuser/integration-tests/che-multiuser-postgresql-tck/pom.xml
  multiuser/integration-tests/che-multiuser-postgresql-tck/src/test/java/MultiuserPostgresqlTckModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/AbstractKeycloakFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakAuthenticationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakJwkProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakJwtParserProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSigningKeyResolver.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/MachineTokenJwtException.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/AbstractKeycloakFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakAuthenticationFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSigningKeyResolverTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilter.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineSessionInvalidator.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineSigningKeyResolver.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenRegistry.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/NotMachineTokenJwtException.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/SignatureKeyManager.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/SignatureKeyPair.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/SignaturePublicKeyEnvProvider.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/jpa/JpaSignatureKeyDao.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/model/impl/SignatureKeyPairImpl.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/signature/spi/SignatureKeyDao.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilterTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineTokenRegistryTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/signature/SignatureKeyManagerTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/signature/jpa/SignatureKeyTckModule.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/signature/spi/tck/SignatureKeyDaoTest.java
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.10.0/2__change_signature_key_pair_id.sql
Labels: kind/task, status/code-review

#10835 Get rid of redundant dependency
  plugins/plugin-java/che-plugin-java-ext-lang-server/pom.xml
  plugins/plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/plugin/java/server/inject/JdtGuiceModule.java
  pom.xml
Labels: status/code-review, target/branch

#10845 Filter test configuration methods which belong to improper groups
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/TestFilter.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/inject/TestFilterTest.java
Labels: kind/bug, status/code-review, team/che-qe

#10820 CHE-10769: improve loader.html page
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.css
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.html
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.js
Labels: kind/task, status/code-review

#10847 Fix PreviewRefactoringTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/preview/PreviewRefactoringTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#10851 Selenium: remove info about known issues, fix unstable tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Swagger.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/TestWebElementRenderChecker.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/NodeJsDebugTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromUiWithKeepDirTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
Labels: kind/task, status/code-review, team/che-qe

#10859 Adapt NewWorkspacePageTest to run against Eclipse Che on K8S
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
Labels: kind/task, status/code-review, team/che-qe

#10828 CHE-10827 Add patch to the target centos image
  dockerfiles/theia/src/setup.sh
Labels: kind/bug

#10788 Remove test language server
  pom.xml
  wsagent/che-core-api-languageserver/pom.xml
Labels: status/code-review

#10824 Adapt tests to correct observed behaviour
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/TypeScriptEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/YamlFileEditingTest.java
Labels: selenium/failure, status/code-review, target/branch, team/languages

#10871 Stabilize selenium test UploadIntoProjectTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/UploadIntoProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromSpringBootStackTest.java
Labels: status/code-review

#10718 CHE-10360: Hide the 'From Archetype' field if parent folder with pom.xml is selected
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/ErrorCodes.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/MavenLocalizationConstant.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/wizard/MavenPagePresenter.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/resources/org/eclipse/che/plugin/maven/client/MavenLocalizationConstant.properties
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/projecttype/handler/ArchetypeGenerationStrategy.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Wizard.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckGeneratingMavenArchetypeTest.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/SimpleFsDtoConverter.java
Labels: kind/bug, status/code-review

#10873 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#10783 CHE-10775 Upgrade lodash to version 4.17.10
  dashboard/package.json
  workspace-loader/package.json
Labels: kind/bug, status/code-review

#10858 Remove unnecessary Services class from all dependent tests for increasing stability
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Refactor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/Services.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/RenameNotPrivateFieldTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/fields/RenamePrivateFieldTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameStaticMethodsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestFailTest.java
Labels: kind/task, status/code-review

#10831 Fix Che server protocol deserialization in k8s/OS infras
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Annotations.java
Labels: kind/bug, status/code-review

#10877 Selenium: add info about known issues, fix unstable selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Consoles.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/CSharpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
Labels: kind/task, status/code-review, team/che-qe

#10826 Selenium: fix locator for hover popup
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
Labels: kind/task, status/in-progress, team/che-qe

#10837 Fixed skipFirstLevel project parameter for factories
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryConstants.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/impl/SourceStorageParametersValidator.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/impl/FactoryBaseValidatorTest.java
Labels: kind/bug, status/code-review

#10766 Multiple changes to deploy scripts
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
  deploy/openshift/templates/multi/keycloak-template.yaml
Labels: status/code-review

#10891 Selenium: remove info about #10809 known issue in CheckIntelligenceCommandToolbarTest test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
Labels: kind/task, status/code-review, team/che-qe

#10899 Fix tests in org.eclipse.che.selenium.editor
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteFeaturesInEditorTest.java
  selenium/che-selenium-test/src/test/resources/org/eclipse/che/selenium/editor/split-editor-restore-exp-text.txt
Labels: status/code-review, target/branch, team/languages

#10900 Change the method to expand the project tree in the 'SplitEditorFeatureTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/SplitEditorFeatureTest.java
Labels: kind/task, status/code-review, team/che-qe

#10901 Selenium: Change the timeout to resolve dependencies in the 'ImportAndValidateEclipseCheProjectTest'
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/ImportAndValidateEclipseCheProjectTest.java
Labels: kind/task, status/code-review, team/che-qe

#10896 Don't skip maven site plugin in selenium tests
  selenium/che-selenium-test/pom.xml
Labels: kind/task, status/code-review, team/che-qe

#10830 Fix the link to docs.
  docs/README.md
Labels: kind/bug, status/code-review

#10843 CHE-9709: fix ability to create a factory from a Git URL
  dashboard/src/app/factories/create-factory/create-factory.controller.ts
  dashboard/src/components/api/che-factory-template.factory.ts
  dashboard/src/components/api/factory-templates.ts
Labels: kind/bug, status/code-review

#10930 Fix config initialization
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerService.java
Labels: kind/bug, target/branch, team/languages

#10907 Removed Eclipse Dependencies
  assembly/assembly-wsagent-server/pom.xml
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/pom.xml
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/test/java/org/eclipse/che/plugin/jdb/server/util/ProjectApiUtils.java
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-core-filebuffers/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-core-filesystem/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-core-resources/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/che/jdt/internal/compiler/parser/SourceTypeConverter.java
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jface-text/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jface/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-ltk-core-refactoring/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-search/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-ui-ide/pom.xml
  plugins/plugin-java/che-plugin-java-ext-jdt/pom.xml
  plugins/plugin-java/che-plugin-java-ext-lang-server/pom.xml
  plugins/plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/plugin/java/server/inject/JdtGuiceModule.java
  plugins/plugin-testing-php/plugin-testing-phpunit/che-plugin-testing-phpunit-server/pom.xml
  plugins/plugin-testing-php/plugin-testing-phpunit/che-plugin-testing-phpunit-server/src/main/java/org/eclipse/che/plugin/testing/phpunit/server/PHPUnitTestEngine.java
  pom.xml
Labels: kind/task, status/code-review, target/branch, team/languages

#10892 CHE-10850: Add notification about stop workspace by idle timeout
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/workspace/event/WorkspaceStoppingEvent.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/WorkspaceStatusNotification.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/events/WorkspaceStatusEventHandler.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStoppingWsByTimeoutTest.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManager.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
Labels: kind/enhancement, status/code-review

#10951 Fix selenium tests in debug package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ThreadDumpTest.java
Labels: team/languages

#10959 Fix css styles for Firefox
  ide/che-core-ide-api/src/main/resources/org/eclipse/che/ide/api/parts/partstack.css
Labels: kind/bug, severity/P2, status/code-review, team/ide

#10960 Fix clone and yo in Theia image
  dockerfiles/theia/src/setup.sh
  dockerfiles/theia/src/start.sh
Labels: kind/bug, status/code-review

#10921 Fix selenium tests in factory package
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/WorkspaceSynchronizer.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/projecttype/handler/MavenProjectInitHandler.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithMultiModuleTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromUiWithKeepDirTest.java
  selenium/che-selenium-test/src/test/resources/templates/factory/docker/minimal.json
  selenium/che-selenium-test/src/test/resources/templates/factory/k8s/minimal.json
  selenium/che-selenium-test/src/test/resources/templates/factory/openshift/minimal.json
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerInitializer.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
Labels: kind/task, status/code-review, target/branch

#10933 Cleanup maven client side
  plugins/plugin-maven/che-plugin-maven-ide/pom.xml
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/MavenExtension.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/MavenJsonRpcHandler.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/comunnication/MavenMessagesHandler.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/comunnication/PomEditorReconciler.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/editor/ClassFileSourcesDownloader.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/inject/MavenGinModule.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/project/MavenModelImporter.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/project/ResolvingMavenProjectStateHolder.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/service/MavenServerServiceClient.java
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/service/MavenServerServiceClientImpl.java
  plugins/plugin-maven/che-plugin-maven-ide/src/test/java/org/eclipse/che/plugin/maven/client/comunnication/MavenMessagesHandlerTest.java
Labels: kind/task, status/code-review, target/branch, team/languages

#10969 Jdt.ls: fix selenium fix stack ordering
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
Labels: kind/bug, status/code-review, target/branch

#10965 Jdt.ls: fix few Selenium tests for Refactoring feature
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Refactor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveItemsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/MoveJavaFileInNewSourceFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/GenericsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/IllegalTypeNameTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestAnnotationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestEnumerationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestFailTest.java
Labels: kind/bug, status/code-review, target/branch

#10972 Fix dependencies
  plugins/plugin-maven/che-plugin-maven-server/pom.xml
Labels: kind/bug, status/code-review, target/branch

#10690 Rework GitStatusProvider to use cached status storage
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/CachedGitStatusProvider.java
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitChangesDetector.java
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitModule.java
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitStatusChangedDetector.java
  wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitStatusProvider.java
  wsagent/che-core-api-git/src/test/java/org/eclipse/che/api/git/CachedGitStatusProviderTest.java
Labels: kind/bug, status/code-review

#10963 Use equinox launcher independently of its version
  agents/ls-java/src/main/resources/installers/1.0.1/org.eclipse.che.ls.java.script.sh
Labels: status/code-review, target/branch, team/languages

#10947 Revert update to 3.10
  deploy/openshift/ocp.sh
Labels: status/code-review

#10967 [Selenium] Fix of unexpected fail of " RollingUpdateStrategyWithWorkspacesStartStopTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
Labels: kind/bug, status/code-review

#10968 Do not set incorrect presentable text marker for pom file
  plugins/plugin-maven/che-plugin-maven-ide/src/main/java/org/eclipse/che/plugin/maven/client/resource/PomInterceptor.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/core/project/MavenModelReader.java
  plugins/plugin-maven/che-plugin-maven-shared/src/main/java/org/eclipse/che/plugin/maven/shared/MavenAttributes.java
Labels: kind/bug, status/code-review

#10975 Fix tests in org.eclipse.che.selenium.editor.autocomplete
  ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/signature/SignatureWidget.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteFeaturesInEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteProposalJavaDocTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteWithInheritTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/CheckAutocompleteFeaturesInTheTestFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/InheritClassTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/JavaDocPopupLinkTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/QuickFixAndCodeAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/ShowHintsCommandTest.java
Labels: kind/bug, status/code-review, target/branch, team/languages

#10939 Make E2E tests screenshots available in report on CI
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/SeleniumTestHandler.java
  selenium/che-selenium-test/src/test/resources/conf/selenium.properties
Labels: kind/task, status/code-review, team/che-qe

#10970 Prevent XSS attack during render popup menu items
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/PopupMenu.java
Labels: kind/task, status/code-review, team/ide

#10993 Fixed putting Che Subject into ServerEndpointConfig if http session is null
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/websocket/impl/GuiceInjectorEndpointConfigurator.java
Labels: kind/bug, status/code-review

#11010 Fix path to OCP oauth certificate
  deploy/openshift/deploy_che.sh
Labels: kind/bug, status/code-review

#11002 Fix override and skip root behaviors
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/folder/UploadFolderFromZipPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/folder/UploadFolderFromZipView.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/folder/UploadFolderFromZipViewImpl.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/UploadIntoProjectTest.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/ZipArchiver.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
  wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java
Labels: kind/bug, status/code-review

#11024 Save all webdriver network logs with request URL starting from 'ws://'
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/log/WebDriverLogsReader.java
Labels: kind/bug, status/code-review
