Repository eclipse-che/che, pull requests merged in 2018-11, with the labels that each got.

#11795 drop codenvy nexus repository
  pom.xml
Labels: status/code-review

#11785 Change access modifiers of debug config classes for reusing code
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/debug/AbstractDebugConfig.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/debug/CppDebugConfig.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/debug/JavaDebugConfig.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/debug/NodeJsDebugConfig.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/debug/PhpDebugConfig.java
Labels: kind/enhancement, status/code-review

#11783 [Selenium] Create Selenium test covered "start Theia in hosted mode and test the plugin"
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaHostedPluginSelectPathForm.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProposalForm.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/task, status/code-review, team/che-qe

#11799 Selenium: fix exception type in selenium tests from refactor.types package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/CheckAutocompleteFeaturesInTheTestFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/GenericsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestAnnotationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestEnumerationsTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11800 [Selenium] Create selenium test for checking of the "Che 7 Preview" stack creation
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/Che7PreviewStackStartTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review

#11778 Add ability to handle case when active tab is closed
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/panel/ProcessesPanelPresenter.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/panel/ProcessesPanelView.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/panel/ProcessesPanelViewImpl.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/multisplitpanel/SubPanel.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/multisplitpanel/actions/ClosePaneAction.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/multisplitpanel/actions/RemoveAllWidgetsInPaneAction.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/multisplitpanel/panel/ActiveTabClosedHandler.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/multisplitpanel/panel/SubPanelPresenter.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/multisplitpanel/panel/SubPanelView.java
  ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/multisplitpanel/panel/SubPanelViewImpl.java
Labels: kind/bug

#11805 Selenium: update expected stacks lists in 'NewWorkspacesPageTest' test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
Labels: kind/task, status/code-review, team/che-qe

#11787 Add debug output for workspace startup
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesRuntimeContext.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarToolingProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/ListenBrokerEvents.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/WaitBrokerResult.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftRuntimeContext.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/InstallerConfigProvisioner.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/MachineNameProvisioner.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/ProjectsVolumeForWsAgentProvisioner.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/EnvVarEnvironmentProvisioner.java
Labels: kind/task, status/code-review

#11770 Selenium: Add the 'try-catch' to the 'GitCompareTest' according to the known issue #11769
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitCompare.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitCompareTest.java
Labels: kind/task, status/code-review, team/che-qe

#11689 Do not execute selenium tests under repair by default
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/TestGroup.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/inject/TestFilter.java
  selenium/che-selenium-core/src/test/java/org/eclipse/che/selenium/core/inject/TestFilterTest.java
  selenium/che-selenium-test/README.md
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/ChangeVariableWithEvaluatingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/InnerClassAndLambdaDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteWithInheritTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/QuickFixAndCodeAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/ShowHintsCommandTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/filewatcher/RemoveFilesWithActiveTabs.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportWizardFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/TypeScriptEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpClassRenamingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpFileAdvancedOperationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/php/PhpAssistantFeaturesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/RunPlainJavaProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameVirtualMethodsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/move/CodeAssistAfterMoveItemTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/ImportAndValidateEclipseCheProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginTestNgTest.java
Labels: kind/enhancement, status/code-review, team/che-qe

#11813 [Selenium] Fix unexpected fail of "TheiaBuildPluginTest" and "Che7PreviewStackStartTest" selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/bug, status/code-review, team/che-qe

#11815 Exclude E2E tests which failed permanently from default test execution
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitCompareTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
Labels: kind/task, team/che-qe

#11745 Prevent duplication of command in context menu after update meta information
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/editor/page/name/NamePage.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/execute/ExecuteCommandActionManager.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/execute/GoalPopUpGroup.java
  ide/commons-gwt/src/main/java/org/eclipse/che/ide/util/NameUtils.java
  ide/commons-gwt/src/test/java/org/eclipse/che/ide/util/NameUtilsTest.java
Labels: kind/bug, severity/P2, status/code-review, team/ide

#11794 Reuse the Dashboard Keycloak instance in IDE frames when possible
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/IDE.html
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/loader.js
  workspace-loader/src/index.ts
Labels: kind/task, status/code-review

#11809 Add Che 7 stack: Java + MySQL
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/task, status/code-review

#11839 Selenium: update info about known issue, update tests for Apache Camel stack
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/JavaDocPopupTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
  selenium/che-selenium-test/src/test/resources/projects/project-for-camel-ls/main/java/org/eclipse/qa/examples/AppController.java
  selenium/che-selenium-test/src/test/resources/projects/project-for-camel-ls/main/webapp/WEB-INF/jsp/guess_num.jsp
  selenium/che-selenium-test/src/test/resources/projects/project-for-camel-ls/main/webapp/WEB-INF/spring-servlet.xml
  selenium/che-selenium-test/src/test/resources/projects/project-for-camel-ls/main/webapp/WEB-INF/web.xml
  selenium/che-selenium-test/src/test/resources/projects/project-for-camel-ls/main/webapp/index.jsp
  selenium/che-selenium-test/src/test/resources/projects/project-for-camel-ls/pom.xml
  selenium/che-selenium-test/src/test/resources/templates/workspace/docker/spring_boot_with_apache_camel_ls.json
  selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/spring_boot_with_apache_camel_ls.json
Labels: status/code-review, team/che-qe

#11825 Do not inform language server about file rename for not registered file type
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/registry/LanguageServerRegistry.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/rename/RenamePresenter.java
Labels: kind/bug, status/code-review

#11840 The PVC cleaning on workspace deletion is done in the wrong condition
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleaner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleanerTest.java
Labels: kind/bug, status/code-review

#11845 Selenium: update info about known issue, fix expected stacks list on Dashboard
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ApacheCamelFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindUsagesBaseOperationTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#11847 Get suite xml file from 'target/test-classes/suite' directory
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/enhancement, status/code-review, team/che-qe

#11756 Add item menu for Che Public Chat and Issue Tracker
  plugins/plugin-product-info/pom.xml
  plugins/plugin-product-info/src/main/java/org/eclipse/che/plugin/product/info/client/CheProductExtension.java
  plugins/plugin-product-info/src/main/java/org/eclipse/che/plugin/product/info/client/LocalizationConstant.java
  plugins/plugin-product-info/src/main/java/org/eclipse/che/plugin/product/info/client/RedirectToIssueTrackerAction.java
  plugins/plugin-product-info/src/main/java/org/eclipse/che/plugin/product/info/client/RedirectToPublicChatAction.java
  plugins/plugin-product-info/src/main/resources/org/eclipse/che/plugin/product/info/client/LocalizationConstant.properties
Labels: kind/enhancement, status/code-review

#11835 Allow POSTGRESQL_LOG_DEBUG variable to be unset in PostgreSQL image
  dockerfiles/postgres/init-debug.sh
Labels: kind/bug, status/code-review

#11861 Selenium: update info about known issues
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/CheckAutocompleteFeaturesInTheTestFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckFactoryWithPerUserCreatePolicyTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
Labels: status/code-review, team/che-qe

#10264 Apache Camel Language LSP client compatible with Java files
  plugins/plugin-camel/che-plugin-camel-server/src/main/java/org/eclipse/che/plugin/camel/server/languageserver/CamelLanguageServerConfig.java
  plugins/plugin-web/che-plugin-web-ext-web/src/main/java/org/eclipse/che/plugin/web/client/CamelLanguageDescriptionProvider.java
  plugins/plugin-web/che-plugin-web-ext-web/src/main/java/org/eclipse/che/plugin/web/client/inject/WebModule.java
Labels: kind/question, status/code-review

#11868 [dockerfile] Update theia image
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
  dockerfiles/theia/e2e/src/docker-run.sh
  dockerfiles/theia/e2e/test.sh
  dockerfiles/theia/src/builder/setup-nodejs.sh
Labels: kind/bug, status/code-review

#11836 Check file vcs status before reopen folder node
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/impl/ResourceManager.java
Labels: kind/bug, status/code-review

#11873 Selenium: check Apache Camel language server initialization before project import
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ApacheCamelFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCamelStackTest.java
Labels: status/code-review, team/che-qe

#11870 Wait on test workspace removal before running next test
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/AbstractTestWorkspaceServiceClient.java
Labels: kind/enhancement, status/code-review, team/che-qe

#11874 [ Selenium ] Get rid of boilerplate code in the "Menu" selenium page object
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Menu.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeletePackageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeletePackageWithOpenedFilesTabTest.java
Labels: kind/task, status/code-review, team/che-qe

#11844 Basic tracing support for OpenShift
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterServletModule.java
  core/che-core-tracing-core/pom.xml
  core/che-core-tracing-core/src/main/java/org/eclipse/che/core/tracing/TracerProvider.java
  core/che-core-tracing-core/src/main/java/org/eclipse/che/core/tracing/TracingModule.java
  core/che-core-tracing-web/pom.xml
  core/che-core-tracing-web/src/main/java/org/eclipse/che/core/tracing/web/TracingFilterProvider.java
  core/che-core-tracing-web/src/main/java/org/eclipse/che/core/tracing/web/TracingWebModule.java
  core/pom.xml
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/jaeger-all-in-one-template.yml
  pom.xml
Labels: kind/task, status/code-review

#11878 Add log warning for using less than minimal workspace idle timeout
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManager.java
Labels: kind/bug, status/code-review

#11892 Update python content to valid Python 3.x syntax (#11891)
  plugins/plugin-python/che-plugin-python-lang-server/src/main/resources/files/default_python_content
Labels: kind/enhancement, status/code-review

#11857 CHE-10480: Fix NullPointerException
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/TextDocumentService.java
Labels: kind/bug, status/code-review

#11886 Add ability to cancel rename operation
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/EmptyOperation.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/Operation.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenameView.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenameViewImpl.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.properties
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
Labels: kind/bug, status/code-review

#11909 Selenium: stabilize selenium tests, remove info about resolved known issues
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/FindReferencesConsoleTab.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/NodeJsDebugTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateNamedFactoryFromDashboardTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/methods/RenameVirtualMethodsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/packages/RenamePackageTest.java
Labels: status/code-review, team/che-qe

#11908 Revert "CHE-10480: Fix NullPointerException (#11857)"
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/TextDocumentService.java
Labels: kind/bug, status/code-review

#11899 [ Selenium ] Fix unexpected fail of "TheiaBuildPluginTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaEditor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11919 Revert "Revert "CHE-10480: Fix NullPointerException (#11857)" (#11908)"
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/TextDocumentService.java
Labels: kind/bug, status/code-review

#11915 Do not show warning about low timeout value, if it is set to less than 0
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManager.java
Labels: kind/bug, status/code-review

#11875 Changelog 6.13.1
  CHANGELOG.md
Labels: kind/enhancement, status/code-review

#11918 che-theia: Upgrade theia factory plugin to include fixes #11838 and #11837
  dockerfiles/theia/Dockerfile
Labels: kind/bug, status/code-review, team/ide2

#11889 [ Selenium ] Get rid of legacy code in the "Consoles" selenium page object
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Consoles.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeleteProjectsTest.java
Labels: kind/task, status/code-review, team/che-qe

#11925 Selenium: stabilize unstable selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Ide.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Menu.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Refactor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/ClangFileEditingTest.java
Labels: status/code-review, team/che-qe

#11894 Remove pure kubectl deployment
  deploy/kubernetes/README.md
  deploy/kubernetes/helm/che/readme.md
  deploy/kubernetes/kubectl/Deploy Che.md
  deploy/kubernetes/kubectl/che-kubernetes.yaml
Labels: kind/task, status/code-review

#11905 Jdbc tracing support
  core/che-core-db/pom.xml
  core/che-core-db/src/main/java/org/eclipse/che/core/db/JNDIDataSourceFactory.java
  core/che-core-db/src/main/java/org/eclipse/che/core/db/TracingDataSource.java
  core/che-core-db/src/test/java/org/eclipse/che/core/db/TracingDataSourceTest.java
  wsmaster/che-core-api-user/src/test/java/org/eclipse/che/api/user/server/UserServiceTest.java
Labels: kind/task, status/code-review

#11931 [ Selenium ] Quick fix of the 'TheiaBuildPluginTest' selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/bug, status/code-review, team/che-qe

#11939 [ Selenium ] Rework methods for getting nodes count in the 'AssistantFindPanel' page object
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/AssistantFindPanel.java
Labels: kind/task, status/code-review, team/che-qe

#11920 Made PVC Strategies wait until PVCs are bound during preparing
  core/commons/che-core-commons-logback/src/main/java/org/eclipse/che/commons/logback/EnvironmentVariablesLogLevelPropagator.java
  deploy/kubernetes/helm/che/values.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPersistentVolumeClaims.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspaceVolumesStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarToolingProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/PrepareStorage.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/SidecarToolingProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategyTest.java
  plugins/plugin-java-debugger/che-plugin-java-debugger-server/pom.xml
Labels: kind/bug, status/code-review

#11974 Selenium: Delete try-catch from the 'GitCompareTest' related to resolve issue #11791
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitCompareTest.java
Labels: kind/task, status/code-review, team/che-qe

#11957 Fix failed test due to the wrong mock reset
  wsmaster/che-core-api-user/src/test/java/org/eclipse/che/api/user/server/ProfileServiceTest.java
Labels: kind/bug, status/code-review

#11940 Remove unneeded listening of PluginBrokers Pod events
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBrokerTest.java
Labels: kind/task, status/code-review

#11823 Ignore Java files in `node_modules/` on the build phase.
  dashboard/pom.xml
Labels: status/code-review

#11979 [ Selenium ] Fix of unexpected fail of "CheckOnValidAndInvalidClassNameTest" and "RenamedAlreadyCreatedNotJavaFileTest" selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckOnValidAndInvalidClassNameTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/RenamedAlreadyCreatedNotJavaFileTest.java
Labels: kind/bug, status/code-review

#11971 RELEASE: Update CHANGELOG 6.14.1
  CHANGELOG.md
Labels: status/code-review

#11913 [ Selenium ] Get rid of redundant methods in the "SeleniumWebDriverHelper" class
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/CheckErrorsWarningsTabTest.java
Labels: kind/task, status/code-review, team/che-qe

#11137 Use proxy forwarding
  deploy/openshift/templates/multi/keycloak-template.yaml
Labels: kind/question, status/code-review

#11977 Upgrade java8 version for workspace master
  dockerfiles/che/Dockerfile
  dockerfiles/che/open-jdk-source-file-location
Labels: status/code-review

#11995 [ Selenium ] Fix of unexpected fail of "CheckErrorsWarningsTabTest" selenium test
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/CheckErrorsWarningsTabTest.java
Labels: kind/bug, status/code-review, team/che-qe

#12001 [ Selenium ] Fix of unexpected fail of "TheiaBuildPluginTest" and "RenameProjectTest" selenium tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/RenameProjectTest.java
Labels: kind/bug, status/code-review

#12004 build.sh become working on Ubuntu / Linux Mint
  dockerfiles/action/build.sh
  dockerfiles/base/build.sh
  dockerfiles/bats/build.sh
  dockerfiles/build.include
  dockerfiles/build.sh
  dockerfiles/che/build.sh
  dockerfiles/cli/build.sh
  dockerfiles/dev/build.sh
  dockerfiles/dir/build.sh
  dockerfiles/init/build.sh
  dockerfiles/ip/build.sh
  dockerfiles/keycloak/build.sh
  dockerfiles/lib/build.sh
  dockerfiles/mount/build.sh
  dockerfiles/postgres/build.sh
  dockerfiles/test/build.sh
  dockerfiles/theia/build.sh
  dockerfiles/theia/e2e/build.sh
Labels: status/code-review

#12010 Use 'versions.sh' from proper place
  dockerfiles/theia/src/add-extensions.js
Labels: status/code-review

#11890 Make a workspace run without any user env
  assembly/assembly-wsmaster-war/src/main/resources/META-INF/persistence.xml
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/Runtime.java
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/WorkspaceConfig.java
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/runtime/RuntimeIdentity.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/context/AppContextImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/loading/WorkspaceLoadingTrackerImpl.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/runtime/ContextBasedRuntimeInfoProvider.java
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/WorkspaceServiceClient.java
  infrastructures/docker/environment/pom.xml
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/ComposeEnvironmentFactory.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerfile/DockerfileEnvironmentFactory.java
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerimage/DockerImageEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesRuntimeStateCache.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/model/KubernetesRuntimeState.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaTckModule.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/KubernetesMachinesCacheTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/KubernetesRuntimeStateCacheTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/TestObjects.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfrastructure.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironment.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactory.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/usage/tracker/EnvironmentRamCalculator.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/usage/tracker/RamResourceUsageTracker.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/workspace/LimitsCheckingWorkspaceManager.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/CheTestWorkspaceServiceClient.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/gwt/CheckSimpleGwtAppTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WorkspaceConfigDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/NoEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/SidecarToolingWorkspaceUtil.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceValidator.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/bootstrap/AbstractBootstrapper.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/RuntimeIdentityImpl.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/WorkspaceConfigImpl.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/InternalRuntime.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactoryTest.java
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.15.0/1__remove_not_null_constraint_from_env_name_fields.sql
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.15.0/mysql/1__remove_not_null_constraint_from_env_name_fields.sql
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.15.0/postgresql/1__remove_not_null_constraint_from_env_name_fields.sql
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
  wsmaster/integration-tests/mysql-tck/src/test/java/MySqlTckModule.java
  wsmaster/integration-tests/postgresql-tck/src/test/java/PostgreSqlTckModule.java
Labels: status/code-review

#12007 [ Selenium ] Do minor fixing changes for stabilizing of "TheiaBuildPluginTest", "CreateNewJavaFilesTest", "DeletePackageTest" selenium tests
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CreateNewJavaFilesTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeletePackageTest.java
Labels: kind/bug, status/code-review, team/che-qe

#12008 Selenium: cover workspace sharing feature by selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceMemberTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceOwnerTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#12029 rh-che #1075: Adding 'ImpersonatorInterceptor' during creation of KubernetesClient
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
Labels: status/code-review

#12034 Changes required for 6.14.2 version
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/ServersChecker.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/ServersCheckerTest.java
Labels: kind/enhancement, status/code-review, target/branch

#12037 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#12023 Remove redundant <version> elements.
  agents/pom.xml
  assembly/pom.xml
  core/pom.xml
  dashboard/pom.xml
  dockerfiles/pom.xml
  dockerfiles/theia/pom.xml
  plugins/pom.xml
  pom.xml
  workspace-loader/pom.xml
  wsagent/pom.xml
  wsmaster/pom.xml
Labels: status/code-review

#12028 Properly handle no-environment in workspace config from UD
  dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.ts
  dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
  dashboard/src/app/factories/list-factories/factory-item/factory-item.controller.ts
  dashboard/src/app/stacks/stack-details/stack-validation.service.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.controller.ts
  dashboard/src/app/workspaces/create-workspace/stack-selector/stack-selector.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/workspace-machines.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/workspace-machines.html
  dashboard/src/app/workspaces/workspace-details/workspace-ssh/workspace-details-ssh.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-ssh/workspace-details-ssh.html
  dashboard/src/app/workspaces/workspaces.service.ts
  dashboard/src/components/api/environment/che-environment-manager.factory.ts
  dashboard/src/components/api/environment/no-environment-manager.ts
  dashboard/src/components/api/recipe/che-recipe-types.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  dashboard/src/components/typings/che.d.ts
Labels: status/code-review

#11989 Change Centos Nodejs stack Run Command
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#12022 Fix typo.
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/bug, status/blocked, status/code-review

#12056 [docker] [theia] Update factory plug-in
  dockerfiles/theia/Dockerfile
Labels: status/code-review

#11990 Metrics POC
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterServletModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  core/che-core-metrics-core/pom.xml
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/FileStoresMeterBinder.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsBinder.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsModule.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsServer.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsServletModule.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/PrometheusMeterRegistryProvider.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/TomcatMetricsProvider.java
  core/che-core-metrics-core/src/test/java/org/eclipse/che/core/metrics/FileStoresMeterTest.java
  core/che-core-metrics-core/src/test/resources/logback-test.xml
  core/pom.xml
  deploy/openshift/templates/che-server-template.yaml
  pom.xml
Labels: kind/task, status/code-review

#12051 fix default stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review

#10128 Added optional ability to configure custom projects root for language servers
  plugins/plugin-camel/che-plugin-camel-server/pom.xml
  plugins/plugin-camel/che-plugin-camel-server/src/main/java/org/eclipse/che/plugin/camel/server/languageserver/CamelLanguageServerConfig.java
  plugins/plugin-clangd/che-plugin-clangd-lang-server/src/main/java/org/eclipse/plugin/clangd/languageserver/ClangDLanguageServerConfig.java
  plugins/plugin-csharp/che-plugin-csharp-lang-server/src/main/java/org/eclipse/che/plugin/csharp/languageserver/CSharpLanguageServerConfig.java
  plugins/plugin-golang/che-plugin-golang-lang-server/src/main/java/org/eclipse/che/plugin/golang/languageserver/GolangLanguageServerConfig.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-json/che-plugin-json-server/pom.xml
  plugins/plugin-json/che-plugin-json-server/src/main/java/org/eclipse/che/plugin/json/languageserver/JsonLanguageServerConfig.java
  plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/lsp/MavenLanguageServerConfig.java
  plugins/plugin-php/che-plugin-php-lang-server/src/main/java/org/eclipse/che/plugin/php/languageserver/PhpLanguageServerConfig.java
  plugins/plugin-python/che-plugin-python-lang-server/src/main/java/org/eclipse/che/plugin/python/languageserver/PythonLanguageSeverConfig.java
  plugins/plugin-web/che-plugin-web-ext-server/src/main/java/org/eclipse/che/plugin/web/typescript/TypeScriptLanguageServerConfig.java
  plugins/plugin-yaml/che-plugin-yaml-server/pom.xml
  plugins/plugin-yaml/che-plugin-yaml-server/src/main/java/org/eclipse/che/plugin/yaml/server/languageserver/YamlLanguageServerConfig.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/CheLanguageClient.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/InitializeParamsProvider.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerConfig.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerConfigInitializer.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerModule.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LanguageServerPathTransformer.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/LsParamsCloner.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/PublishDiagnosticsParamsJsonRpcTransmitter.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/RegistryContainer.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/ShowMessageJsonRpcTransmitter.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/TextDocumentService.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/WorkspaceConfigProvider.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/WorkspaceService.java
  wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/LanguageServerPathTransformerTest.java
  wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/SnippetTest.java
Labels: kind/enhancement, status/in-progress

#12064 Made Workspace Loader listen to installer output and print it
  workspace-loader/src/index.ts
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/test/test.spec.ts
Labels: kind/task, status/code-review

#12068 Selenium: fix unstable selenium tests, add info about known issues
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/GenericsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestAnnotationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestEnumerationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromCamelStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaDockerStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaOpenshiftStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromNodeStackTest.java
Labels: kind/task, selenium/failure, status/code-review, team/che-qe

#12070 [dockerfile] [theia] Simplify the build
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
  dockerfiles/theia/src/.yarnclean
  dockerfiles/theia/src/add-extensions.js
  dockerfiles/theia/src/builder/add-extensions.sh
  dockerfiles/theia/src/builder/assemble-theia.sh
  dockerfiles/theia/src/builder/build-and-publish-theia.sh
  dockerfiles/theia/src/builder/clone.sh
  dockerfiles/theia/src/builder/production-mode.sh
  dockerfiles/theia/src/cleanup-exact
  dockerfiles/theia/src/cleanup-find
  dockerfiles/theia/src/cleanup.sh
  dockerfiles/theia/src/config.yaml
  dockerfiles/theia/src/extensions.json
  dockerfiles/theia/src/package.json
  dockerfiles/theia/src/resolutions-provider.js
  dockerfiles/theia/src/versions.sh
Labels: status/code-review

#12072 Fix MetricsServer deployment
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsServer.java
Labels: kind/bug, status/code-review

#12060 Fields are declared at the top of the class
  plugins/plugin-zend-debugger/che-plugin-zend-debugger-server/src/main/java/org/eclipse/che/plugin/zdb/server/connection/ZendDbgConnection.java
Labels: status/code-review

#12073 CHE-11697: Remove redundant synchronize call
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorFileStatusNotificationOperation.java
Labels: kind/bug, status/code-review

#11914 Use absolute folder path to open it as working dir in terminal
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/OpenInTerminalAction.java
Labels: kind/bug, severity/P1, status/code-review, team/ide

#12078 Regenerate dashboard/yarn.lock
  dashboard/yarn.lock
Labels: kind/bug, status/code-review

#9675 [kubernetes] set PROXY_ADDRESS_FORWARDING in keycloak deployment when tls is enabled
  deploy/kubernetes/helm/che/charts/che-keycloak/templates/deployment.yaml
Labels: kind/question, status/code-review

#12086 Selenium: remove info about known #11779 and #11697 issues
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/ContextMenuEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/GenericsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/RenameTypeTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestAnnotationsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/TestEnumerationsTest.java
Labels: status/code-review, team/che-qe
