Repository eclipse-che/che, pull requests merged in 2019-08, with the labels that each got.

#14077 Remove outdated devfile documentation
  wsmaster/che-core-api-workspace/README-devfile.md
  wsmaster/che-core-api-workspace/src/main/resources/Dockerfile
  wsmaster/che-core-api-workspace/src/main/resources/build_docs.sh
Labels: status/code-review

#14089 Use v0.19 minor version of plugin broker image instead of bugfix
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#14061 Set 'next' version for che-machine-exec as default
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/openshift/deploy_che.sh
Labels: status/code-review

#14062 E2E: Create e2e test to install Eclipse Che by OperatorHub UI on OCP 4.x
  e2e/TestConstants.ts
  e2e/index.ts
  e2e/inversify.config.ts
  e2e/inversify.types.ts
  e2e/mocha-che-operatorhub.opts
  e2e/package-lock.json
  e2e/package.json
  e2e/pageobjects/login/ICheLoginPage.ts
  e2e/pageobjects/login/IOcpLoginPage.ts
  e2e/pageobjects/login/MultiUserLoginPage.ts
  e2e/pageobjects/login/OcpLoginByTempAdmin.ts
  e2e/pageobjects/login/SingleUserLoginPage.ts
  e2e/pageobjects/openshift/OcpLoginPage.ts
  e2e/pageobjects/openshift/OcpWebConsolePage.ts
  e2e/tests/e2e/WorkspaceCreationAndLsInitialization.spec.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/tests/e2e_install_che_operatorhub/InstallCheByOperatorHub.spec.ts
  e2e/utils/DriverHelper.ts
Labels: kind/task, status/code-review, team/che-qe

#14086 [TS_SELENIUM] Implement method for storing screenshots while tests execution
  e2e/TestConstants.ts
  e2e/driver/CheReporter.ts
  e2e/inversify.config.ts
  e2e/inversify.types.ts
  e2e/package-lock.json
  e2e/package.json
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/utils/ScreenCatcher.ts
Labels: kind/task, status/code-review, team/che-qe

#13839 Update README for che7
  CONTRIBUTING.md
  CUSTOMIZING.md
  README.md
Labels: kind/enhancement, status/code-review

#14106 E2E: Change waiting timeout to increase reliability test
  e2e/TestConstants.ts
  e2e/pageobjects/openshift/OcpWebConsolePage.ts
Labels: kind/task, status/code-review, team/che-qe

#14105 [TS_SELENIUM] Implement workaround for avoiding the "#13427" ("Java LS "Classpath is incomplete" warning when loading petclinic")
  e2e/files/happy-path/petclinic-classpath.txt
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/task, status/code-review, team/che-qe

#14107 chore: fix readme with direct link to submit new bugs
  README.md
Labels: kind/bug, status/code-review

#14127 [TS_SELENIUM] Implement workaround for bug described in the issue #14121 (Can not access to application by route because of service unavailable)
  e2e/pageobjects/ide/Ide.ts
Labels: kind/task, status/code-review, team/che-qe

#14118 [E2E] Add export for all classes so we can reuse them on RH-Che side.
  e2e/index.ts
Labels: kind/task, status/code-review

#14135 increase registries memory limit to 256Mi in helm charts
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/values.yaml
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/values.yaml
Labels: kind/task, status/code-review

#14156 Fix mount path for case with '.' in host name
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeysProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeySecretProvisionerTest.java
Labels: kind/bug, status/code-review

#14149 Add Jenkinsfile to run E2E Happy path tests against K8S
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/task, status/code-review, team/che-qe

#14182 Fix commands to download latest release version of chectl in E2E happy path tests PR job
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#14180 [Happy Path] Fix of issue #14141 (Sometimes the "Happy path" test fails when click on "Start debug" button)
  e2e/files/happy-path/containers-happy-path.yaml
  e2e/pageobjects/ide/Editor.ts
  e2e/pageobjects/ide/Ide.ts
  e2e/pageobjects/ide/ProjectTree.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/utils/DriverHelper.ts
  e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/bug, status/code-review, team/che-qe

#14176 Use different secrets for TLS and self-signed-cert
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/task, status/code-review

#14199 [Happy Path] Sometimes the "Happy Path" test fails on "ProjectTree.expandPathAndOpenFile" step
  e2e/pageobjects/ide/ProjectTree.ts
Labels: kind/bug, status/code-review, team/che-qe

#14185 [TS_SELENIUM] Implement logic to be able to run tests with provided chromedriver
  e2e/TestConstants.ts
  e2e/driver/CheReporter.ts
  e2e/driver/ChromeDriver.ts
Labels: kind/task, status/code-review, team/che-qe

#14214 Simplify build of che artifacts by PR check pipeline job
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review, team/che-qe

#14247 Use next version for default plugins
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: status/code-review

#14063 compose plugin id
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/ExtendedPluginFQN.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginFQN.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/wsplugins/PluginFQNParserTest.java
Labels: kind/bug, status/code-review

#14222 Add workspace-loader flow
  CONTRIBUTING.md
Labels: kind/enhancement, status/code-review

#13942 Make plugins/editors show one entry for each plugin with a drop down for version
  dashboard/src/app/workspaces/workspace-details/workspace-editors/workspace-editors.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-editors/workspace-editors.html
  dashboard/src/app/workspaces/workspace-details/workspace-editors/workspace-editors.styl
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.html
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.styl
  dashboard/src/components/api/plugin-registry.factory.ts
Labels: kind/enhancement, status/code-review

#14239 watch PVC `WaitForFirstConsumer` event to avoid deadlock
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPersistentVolumeClaims.java
Labels: kind/bug, status/code-review

#14259 set plugin registry image to nightly
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/values.yaml
Labels: status/code-review

#14174 Allow chePlugin preferences to be string, int or boolean type
  assembly/assembly-wsmaster-war/src/main/resources/META-INF/persistence.xml
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/devfile/Component.java
  core/commons/che-core-commons-test/src/main/java/org/eclipse/che/commons/test/db/PersistTestModuleBuilder.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaTckModule.java
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/resources/META-INF/persistence.xml
  multiuser/integration-tests/che-multiuser-mysql-tck/src/test/resources/META-INF/persistence.xml
  multiuser/integration-tests/che-multiuser-postgresql-tck/src/test/resources/META-INF/persistence.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/signature/jpa/SignatureKeyTckModule.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/jpa/WorkspaceTckModule.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/spi/jpa/JpaTckModule.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/jpa/WorkspaceActivityTckModule.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/ComponentDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/PreferencesDeserializer.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/SerializableConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/component/plugin/PluginComponentToWorkspaceApplier.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/devfile/ComponentImpl.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/PreferencesDeserializerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/convert/component/plugin/PluginComponentToWorkspaceApplierTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/jpa/WorkspaceTckModule.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/tck/WorkspaceDaoTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/devfile.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/editor_plugin_component/devfile_plugin_components_with_preferences.yaml
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/7.1.0/1__change_devfile_component_preferences_type.sql
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/7.1.0/postgresql/1__change_devfile_component_preferences_type.sql
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
  wsmaster/integration-tests/mysql-tck/src/test/java/MySqlTckModule.java
  wsmaster/integration-tests/postgresql-tck/src/test/java/PostgreSqlTckModule.java
Labels: status/code-review

#14181 Add docs how to build Che server in Che workspace
  .che-dev.yaml
  CONTRIBUTING.md
  devfile.yaml
  dockerfiles/che/entrypoint.sh
Labels: area/doc, kind/enhancement, status/code-review

#14264 Set all image version to the 7.0.0 to align it with CheTheia version
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/values.yaml
  deploy/kubernetes/helm/che/values.yaml
  deploy/openshift/deploy_che.sh
Labels: status/code-review

#14278 Set che-plugin-registry image version to 7.0.0
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/values.yaml
Labels: status/code-review

#14269 6 backport - Watch PVC `WaitForFirstConsumer` event to avoid deadlock (#14239)
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPersistentVolumeClaims.java
  typescript-dto/dto-pom.xml
  wsmaster/integration-tests/mysql-tck/pom.xml
  wsmaster/integration-tests/postgresql-tck/pom.xml
Labels: kind/bug, status/code-review, target/branch

#14267 Update default plugin/devfile registries to use prod-preview
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#14270 Add the jwt-proxy memory as a part of stack's globalMemoryLimit
  dashboard/src/app/stacks/list-stacks/list-stacks.controller.ts
  dashboard/src/app/workspaces/create-workspace/devfile-selector/devfile-selector.html
  dashboard/src/components/api/devfile-registry.factory.ts
Labels: kind/bug, status/code-review

#14157 add `generateName` to devfile metadata
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/devfile/Metadata.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/MetadataDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/devfile/MetadataImpl.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/devfile.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_just_generatename.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_missing_name_and_generatename.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_name_and_generatename.yaml
Labels: kind/bug, status/code-review

#14292 Add trailing 0 to Happy path tests screencast png's
  e2e/TestConstants.ts
  e2e/driver/CheReporter.ts
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
  e2e/utils/ScreenCatcher.ts
Labels: kind/enhancement, status/code-review

#14285 use the latest nightly image
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/values.yaml
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/values.yaml
  deploy/kubernetes/helm/che/values.yaml
  deploy/openshift/deploy_che.sh
  e2e/driver/CheReporter.ts
  e2e/driver/ContainerInitializer.ts
  e2e/inversify.types.ts
  e2e/mocha-happy-path.opts
  e2e/package.json
  e2e/pageobjects/ide/Editor.ts
  e2e/pageobjects/ide/Ide.ts
  e2e/pageobjects/ide/OpenWorkspaceWidget.ts
  e2e/pageobjects/ide/PreviewWidget.ts
  e2e/pageobjects/ide/ProjectTree.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/utils/DriverHelper.ts
  e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: status/code-review

#14281 [E2E] Adding script for generating index.ts file.
  e2e/generateIndex.sh
  e2e/index.ts
  e2e/package.json
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: status/code-review

#14311 factory will always use devfile generateName
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java
Labels: kind/bug, status/code-review

#14058 Fix the list of workspaces in organization
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.controller.ts
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.html
Labels: kind/bug

#14320 Avoid using DtoImpls directly
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/IdentityProviderConfigBuilderTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/task, status/code-review

#14323 [Selenium] Delete Che7PreviewStackStartTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/Che7PreviewStackStartTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: status/code-review, team/che-qe

#14299 [e2e] - Add source maps. Fixes #14298
  e2e/mocha-happy-path.opts
  e2e/tsconfig.json
Labels: kind/enhancement, status/code-review

#14327 Exclude failing java selenium tests from default execution
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
Labels: kind/task, status/code-review

#14207 Make code & test independent from environment and time of execution
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/FileStoresMeterBinder.java
  core/che-core-metrics-core/src/test/java/org/eclipse/che/core/metrics/FileStoresMeterTest.java
Labels: kind/bug, status/code-review

#14037 Add target="_blank" to the link for "Make a wish" button.
  dashboard/src/components/widget/footer/che-footer.html
Labels: kind/enhancement, status/code-review

#14213 Add possibility to build images from "dockerfiles" folder with '--no-cache' option
  dockerfiles/e2e/Dockerfile
  dockerfiles/e2e/README.md
  dockerfiles/e2e/docker-entrypoint.sh
  dockerfiles/e2e/entrypoint.sh
  e2e/README.md
  e2e/package.json
Labels: kind/task, status/code-review

#14337 [Selenium] Fix Java selenium tests to run against Che with next version for default plugins
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
Labels: kind/task, status/code-review, team/che-qe

#14339 Don't blow up on missing path transform configuration
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/IngressPathTransformInverter.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/IngressPathTransformInverterTest.java
Labels: status/code-review

#14351 Update existed "che-e2e" image for using on CI
  dockerfiles/e2e/README.md
  dockerfiles/e2e/entrypoint.sh
  e2e/README.md
  e2e/index.ts
  e2e/package-lock.json
  e2e/package.json
Labels: kind/task, status/code-review

#14377 Fix converting URL for UD
  dashboard/e2e/stacks/stack-details/rename-machine/rename-machine.spec.js
  dashboard/src/app/factories/last-factories/last-factories.controller.ts
  dashboard/src/app/factories/load-factory/load-factory.controller.ts
  dashboard/src/app/organizations/organizations.controller.ts
  dashboard/src/app/stacks/list-stacks/list-stacks.controller.ts
  dashboard/src/app/teams/team-details/team-workspaces/list-team-workspaces.controller.ts
  dashboard/src/app/workspaces/list-workspaces/workspace-item/workspace-item.controller.ts
  dashboard/src/components/api/che-factory-template.factory.ts
  dashboard/src/components/api/che-factory.factory.ts
  dashboard/src/components/api/che-organizations.factory.ts
  dashboard/src/components/api/che-project.ts
  dashboard/src/components/api/che-team-events-manager.factory.ts
  dashboard/src/components/api/devfile-registry.factory.ts
  dashboard/src/components/widget/loader/che-loader-crane.directive.ts
Labels: kind/bug, status/code-review

#14394 Update screencatcher in the e2e folder for avoiding errors
  e2e/utils/ScreenCatcher.ts
Labels: kind/task, status/code-review, team/che-qe
