Repository eclipse-che/che, pull requests merged in 2019-02, with the labels that each got.

#12560 Make Che 7 model fields use camel-case
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheContainer.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/Command.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginBase.java
Labels: kind/enhancement, status/code-review

#12597 fix cacerts path
  dockerfiles/che/entrypoint.sh
Labels: kind/bug, status/code-review

#12598 Make CheTestWorkspaceProvider class visible outside the package
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/CheTestWorkspaceProvider.java
Labels: status/code-review

#12580 Update version of 'webpack-dev-server'
  workspace-loader/Dockerfile
  workspace-loader/package.json
  workspace-loader/webpack.dev.js
  workspace-loader/webpack.prod.js
  workspace-loader/yarn.lock
Labels: kind/enhancement, status/code-review

#12590 Do autosave after user stops typing for a while and avoid formatting during typing
  dashboard/src/app/workspaces/workspace-details/config-import/workspace-config-import.controller.ts
  dashboard/src/app/workspaces/workspace-details/config-import/workspace-config-import.directive.ts
  dashboard/src/app/workspaces/workspace-details/config-import/workspace-config-import.html
  dashboard/src/app/workspaces/workspace-details/config-import/workspace-config-import.styl
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.html
  dashboard/src/app/workspaces/workspace-details/workspace-details.styl
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.styl
Labels: kind/bug, status/code-review

#12599 Update version of plugin brokers
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#12589 Added machine name estimation for commands in K8s/OS tool
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  wsmaster/che-core-api-devfile/pom.xml
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileConverter.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileEnvironmentFactory.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/KubernetesToolApplier.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileConverterTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileManagerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/KubernetesToolApplierTest.java
Labels: kind/task, status/code-review

#12561 CHE-12376: Fix IDE link navigation
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/IDE.html
  ide/che-ide-gwt-app/src/main/resources/org/eclipse/che/ide/public/bundle.js
Labels: kind/bug, status/code-review

#12612 move ts dto to theia project
  pom.xml
  typescript-dto/build.sh
  typescript-dto/pom.xml
Labels: status/code-review

#12619 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#12539 Fixed handling creating of free resources limit that references non-existing account
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/free/FreeResourcesLimitManager.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/free/FreeResourcesLimitService.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/spi/FreeResourcesLimitDao.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/spi/jpa/JpaFreeResourcesLimitDao.java
  multiuser/api/che-multiuser-api-resource/src/test/java/org/eclipse/che/multiuser/resource/spi/tck/FreeResourcesLimitDaoTest.java
Labels: kind/bug, status/code-review

#12537 Selenium: Delete the 'try-catch' from selenium tests related to fix issues
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitCompareTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
Labels: kind/task, status/code-review, team/che-qe

#12623 Fix link for deploying multi-user che to kubernetes
  deploy/kubernetes/README.md
Labels: kind/bug, status/code-review

#12630 [Selenium] Update selenium tests from dashboard package according to workspace details changes, fix unstable tests
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ConfigureClasspath.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ProjectExplorer.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjects.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsMachinesRamTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/autocomplete/AutocompleteFeaturesInEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckOpenFileFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckMavenPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/plainjava/ConfigureClasspathBaseTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/DeleteFilesFromContextMenuTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStoppingWsByTimeoutTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#12639 Upgrade Che brokers versions
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/task, status/code-review

#10646 Add keycloak realm & client id parameters
  deploy/openshift/templates/che-server-template.yaml
Labels: kind/enhancement, status/code-review

#12640 Bind the workspace activity checker also in the multiuser environment
  multiuser/api/che-multiuser-api-workspace-activity/src/main/java/org/eclipse/che/multiuser/api/workspace/activity/MultiUserWorkspaceActivityModule.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/inject/WorkspaceActivityModule.java
Labels: kind/bug, status/code-review

#12305 Initial devfile to work che in che
  .che-dev.yaml
  .devfile
Labels: status/code-review

#12646 Introduce devfile docs build & deploy script
  wsmaster/che-core-api-devfile/pom.xml
  wsmaster/che-core-api-devfile/src/main/resources/Dockerfile
  wsmaster/che-core-api-devfile/src/main/resources/build_docs.sh
Labels: kind/task, status/code-review

#12489 Handle more fields in plugin meta YAML
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginMeta.java
Labels: status/code-review

#12653 Change package validation using 'command' instead of 'rpm'
  wsmaster/che-core-api-devfile/src/main/resources/build_docs.sh
Labels: kind/task, status/code-review

#12637 Allow to change preferences with machine token
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java
Labels: kind/task, status/code-review

#12648 Update versions of plugin brokers to v0.12.0
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#12654 Set kubernetes namespace to null on workspace recipe parsing
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactory.java
Labels: kind/bug, status/code-review

#12615 Use plugin ID instead of sidecar container name to override sidecar memory using workspace attributes
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/KubernetesSize.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
Labels: kind/bug, status/code-review

#12629 Detect tools containers on dashboard and disable action items for them
  dashboard/src/app/workspaces/workspace-details/workspace-machine-env-variables/env-variables.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-env-variables/env-variables.html
  dashboard/src/app/workspaces/workspace-details/workspace-machine-servers/machine-servers.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-servers/machine-servers.html
  dashboard/src/app/workspaces/workspace-details/workspace-machine-volumes/machine-volumes.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-volumes/machine-volumes.html
  dashboard/src/components/api/environment/che-environment-manager.factory.ts
  dashboard/src/components/api/environment/environment-manager.ts
  dashboard/src/components/api/environment/kubernetes-environment-manager.ts
  dashboard/src/components/api/workspace/che-machine-source-types.ts
  dashboard/src/components/typings/che.d.ts
Labels: kind/bug, status/code-review

#12642 Add targetPort attribute to runtime server
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/RuntimeServerBuilder.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerResolverTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftServerResolver.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftServerResolverTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
Labels: kind/enhancement, status/code-review

#12649 Add support of dockerimage tool in Devfile
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/Constants.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileConverter.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DockerimageToolApplier.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/KubernetesToolApplier.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/validator/DevfileIntegrityValidator.java
  wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileConverterTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileManagerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DockerimageToolApplierTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileIntegrityValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/command/devfile_missing_command_actions.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/command/devfile_missing_command_name.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/command/devfile_multiple_commands_actions.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/devfile/devfile_missing_name.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/devfile/devfile_missing_spec_version.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/devfile/devfile_with_undeclared_field.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/dockerimage_tool/devfile_dockerimage_tool.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/dockerimage_tool/devfile_dockerimage_tool_with_missing_image.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/dockerimage_tool/devfile_dockerimage_tool_with_missing_memory_limit.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/editor_plugin_tool/devfile_editor_plugins.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/editor_plugin_tool/devfile_editor_tool_with_missing_id.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_openshift_tool.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_openshift_tool_with_missing_local.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/tool/devfile_missing_tool_name.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/tool/devfile_missing_tool_type.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/tool/devfile_tool_with_undeclared_field.yaml
Labels: kind/enhancement, status/code-review

#12657 Enable getting workspace events from ReplicaSets and Deployments
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
Labels: kind/bug, status/code-review

#12666 Fix NPE during selector matching when kubernetes tool objects does not have labels
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/KubernetesToolApplier.java
  wsmaster/che-core-api-devfile/src/test/resources/petclinic.yaml
Labels: kind/bug, status/code-review

#12662 #12626 [CRW 1.0.1 blocker] Set kubernetes namespace to null on...
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactory.java
Labels: status/code-review, target/branch

#12669 Provision plugin attribute for machines that contains related plugin id
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
Labels: kind/task, status/code-review

#12688 Added -f -S flags for curl commands in installers
  agents/exec/installer/src/main/resources/installers/1.0.1/org.eclipse.che.exec.script.sh
  agents/terminal/src/main/resources/installers/1.0.1/org.eclipse.che.terminal.script.sh
  wsagent/agent/src/main/resources/installers/1.0.3/org.eclipse.che.ws-agent.script.sh
Labels: kind/task, status/code-review

#12683 Deployment of tracing/monitoring/debug on OpenShift
  deploy/openshift/deploy_che.sh
  deploy/openshift/templates/che-monitoring.yaml
  deploy/openshift/templates/che-server-template.yaml
Labels: kind/task, status/code-review

#12687 Use Java Base64 method instead of javax.xml.bind.DatatypeConverter
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubServiceClient.java
Labels: status/code-review

#12691 API info service to use meta-info from war-s manifest instead of jar
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/ApiInfoProvider.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/ApiInfoService.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/CoreRestModule.java
Labels: status/code-review

#12043 Fix a potentially bug.
  workspace-loader/src/json-rpc/util.ts
Labels: kind/bug, status/code-review

#12704 Added propagating curl errors in exec/terminal installers
  agents/exec/installer/src/main/resources/installers/1.0.1/org.eclipse.che.exec.script.sh
  agents/terminal/src/main/resources/installers/1.0.1/org.eclipse.che.terminal.script.sh
Labels: kind/task, status/code-review

#12718 Fix the way the activity checker decides whether workspace idling is configured or not
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityChecker.java
Labels: kind/task, status/code-review

#12682 Refactored Devfile converting process
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/local/projects/BindMountProjectsVolumeProvisioner.java
  wsmaster/che-core-api-devfile/pom.xml
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/Constants.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileConverter.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileFactory.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileManager.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileModule.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileService.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DockerimageToolApplier.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/FileContentProvider.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/CommandConverter.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/DevfileConverter.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/ProjectConverter.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/ToolProvisioner.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/ToolToWorkspaceApplier.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/dockerimage/DockerimageToolProvisioner.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/dockerimage/DockerimageToolToWorkspaceApplier.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/editor/EditorToolProvisioner.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/editor/EditorToolToWorkspaceApplier.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/kubernetes/KubernetesToolProvisioner.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/kubernetes/KubernetesToolToWorkspaceApplier.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/plugin/PluginProvisioner.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/plugin/PluginToolToWorkspaceApplier.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileConverterTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileManagerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DockerimageToolApplierTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/CommandConverterTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/DevfileConverterTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/ProjectConverterTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/dockerimage/DockerimageToolProvisionerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/dockerimage/DockerimageToolToWorkspaceApplierTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/editor/EditorToolProvisionerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/editor/EditorToolToWorkspaceApplierTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/kubernetes/KubernetesToolProvisionerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/kubernetes/KubernetesToolToWorkspaceApplierTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/plugin/PluginProvisionerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/plugin/PluginToolToWorkspaceApplierTest.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/ProjectsVolumeForWsAgentProvisioner.java
Labels: kind/task, status/code-review

#12735 Fix webdriver.sh to attach test resources to selenium e2e test report
  selenium/che-selenium-core/bin/webdriver.sh
Labels: kind/bug, status/code-review, team/che-qe

#12737 Add `<b>kubernetes</b>` to messages.
  dashboard/src/app/workspaces/workspace-details/environments/environments.html
  dashboard/src/app/workspaces/workspace-details/workspace-machine-env-variables/env-variables.html
  dashboard/src/app/workspaces/workspace-details/workspace-machines/workspace-machines.html
Labels: kind/enhancement, status/code-review

#12713 Add an ability to provide local file content in devfile
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/tool/kubernetes/KubernetesToolToWorkspaceApplier.java
  wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/tool/kubernetes/KubernetesToolToWorkspaceApplierTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_kubernetes_tool_content_without_local.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_kubernetes_tool_local.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_kubernetes_tool_local_and_content_as_block.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_openshift_tool_content_without_local.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_openshift_tool_local_and_content.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_openshift_tool_local_and_content_as_block.yaml
Labels: kind/enhancement, status/code-review

#12655 Add more traces and cleanup code
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/MachineLogsPublisher.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/UnrecoverablePodEventListenerFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarToolingProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBrokerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
Labels: kind/enhancement, status/code-review

#12738 Add log message when starting InconsistentRuntimesDetector
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/InconsistentRuntimesDetector.java
Labels: kind/enhancement, status/code-review

#12725 Fix editing running workspace config with tools containers and multiuser
  dashboard/src/components/api/environment/kubernetes-environment-manager.ts
  dashboard/src/components/api/environment/kubernetes-machine-recipe-parser.ts
Labels: kind/bug, status/code-review

#12744 Different improvements of script that helps to build Devfile Docs
  wsmaster/che-core-api-devfile/src/main/resources/Dockerfile
  wsmaster/che-core-api-devfile/src/main/resources/build_docs.sh
Labels: kind/bug, status/code-review

#12734 Improve json schema validation messages
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileManager.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileService.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidator.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/validator/ErrorMessageComposer.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileManagerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileServiceTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
Labels: kind/task, status/code-review

#12652 Adding tracing tags to workspace related operations
  core/commons/che-core-commons-tracing/src/main/java/org/eclipse/che/commons/tracing/TracingTags.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/workspace/LimitsCheckingWorkspaceManager.java
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilterTest.java
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/spi/jpa/MultiuserJpaWorkspaceDao.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/jpa/JpaWorkspaceDao.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/WorkspaceDao.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/tck/WorkspaceDaoTest.java
  wsmaster/wsmaster-local/pom.xml
  wsmaster/wsmaster-local/src/main/java/org/eclipse/che/api/local/filters/EnvironmentInitializationFilter.java
Labels: kind/task, status/code-review

#12753 Trust self-signed TLS certificate in selenium tests
  selenium/che-selenium-core/bin/webdriver.sh
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/SeleniumWebDriver.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/TestKeycloakSettingsServiceClient.java
Labels: status/code-review

#12689 Make variable expansion work for environment variables in k8s
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/TopologicalSort.java
  core/commons/che-core-commons-lang/src/test/java/org/eclipse/che/commons/lang/TopologicalSortTest.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/env/EnvVarsConverter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/EnvVars.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/env/EnvVarsConverterTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/EnvVarsTest.java
Labels: kind/enhancement, status/code-review, team/platform

#12756 Selenium: Correct the selenium tests to increase reliability
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/Git.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CommitFilesByMultiSelectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitChangeMarkersTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/AutocompleteCommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/mavenplugin/CheckMavenPluginTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/preferences/CheckErrorsWarningsTabTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor/types/GenericsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStoppingWsByTimeoutTest.java
Labels: kind/task, status/code-review, team/che-qe

#12700 Improved JSON Schema not to allow fields that are not typical for concrete tool type
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/validator/DevfileIntegrityValidator.java
  wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileIntegrityValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/dockerimage_tool/devfile_dockerimage_tool_with_indistinctive_field_selector.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/editor_plugin_tool/devfile_editor_tool_with_indistinctive_field_local.yaml
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_tool/devfile_openshift_tool_with_indistinctive_field_id.yaml
Labels: kind/task, status/code-review

#12748 Continue recovering workspaces when unchecked exception is thrown
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
Labels: kind/bug, status/code-review

#12760 Add Angel Misevski and Lukas Krejci to the codeowners of infras code
  .github/CODEOWNERS
Labels: kind/enhancement, status/code-review

#12749 Add ProcessMemoryMetrics ProcessThreadMetrics
  core/che-core-metrics-core/pom.xml
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsModule.java
  deploy/openshift/templates/che-monitoring.yaml
Labels: kind/enhancement, status/code-review

#12673 Introduced two web-socket endpoints for workspace master to split JSON-RPC messages
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/MetricsOverrideBinding.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheJsonRpcWebSocketConfigurationModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMajorWebSocketEndpoint.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMajorWebSocketEndpointConfiguration.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMajorWebSocketEndpointExecutorServiceProvider.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMinorWebSocketEndpoint.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMinorWebSocketEndpointConfiguration.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMinorWebSocketEndpointExecutorServiceProvider.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/test/java/org/eclipse/che/MetricsOverrideBindingTest.java
  assembly/assembly-wsmaster-war/src/test/resources/logback-test.xml
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcMessageReceiver.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/RequestProcessor.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/RequestProcessorConfigurationProvider.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/JsonRpcModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/ServerSideRequestProcessor.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/ServerSideRequestProcessorConfigurator.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/websocket/impl/WebsocketIdService.java
  core/che-core-api-core/src/test/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcMessageReceiverTest.java
  core/che-core-metrics-core/pom.xml
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/ExecutorServiceMetrics.java
  core/commons/che-core-commons-lang/pom.xml
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/execution/ExecutorServiceProvider.java
  core/commons/che-core-commons-lang/src/test/java/org/eclipse/che/commons/lang/execution/ExecutorServiceProviderTest.java
  deploy/openshift/templates/che-server-template.yaml
  ide/commons-gwt/src/main/java/org/eclipse/che/ide/jsonrpc/ClientSideRequestProcessor.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/bootstrap/DockerBootstrapper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java
  wsagent/che-wsagent-core/pom.xml
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/WsAgentModule.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/jsonrpc/WsAgentWebSocketEndpoint.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/jsonrpc/WsAgentWebSocketEndpointConfiguration.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/jsonrpc/WsAgentWebSocketEndpointExecutorServiceProvider.java
  wsagent/che-wsagent-core/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties
Labels: kind/bug, status/code-review
