Repository eclipse-che/che, pull requests merged in 2019-04, with the labels that each got.

#13029 Update Devfile doc with default editor info
  wsmaster/che-core-api-devfile/README.md
Labels: kind/docs, status/code-review

#13031 [Cypress] Change sample project used in "WorkspaceCreationAndLanguageServerInitialization.spec.ts" cypress test
  cypress-tests/cypress.json
  cypress-tests/cypress/integration/WorkspaceCreationAndLanguageServerInitialization.spec.ts
  cypress-tests/cypress/pageobjects/dashboard/NewWorkspace.ts
Labels: kind/bug, status/code-review, team/che-qe

#13036 [Cypress] Rework "cypress-tests" module with using "InversifyJS" library
  .gitignore
  cypress-tests/cypress/integration/WorkspaceCreationAndLanguageServerInitialization.spec.ts
  cypress-tests/cypress/inversifyJS/inversify.config.ts
  cypress-tests/cypress/inversifyJS/types.ts
  cypress-tests/cypress/pageobjects/dashboard/LoginPage.ts
  cypress-tests/cypress/pageobjects/dashboard/LoginPageMultiUser.ts
  cypress-tests/cypress/pageobjects/dashboard/LoginPageSingleUser.ts
  cypress-tests/cypress/pageobjects/dashboard/interfaces/ILoginPage.ts
  cypress-tests/cypress/pageobjects/ide/Editor.ts
  cypress-tests/cypress/pageobjects/ide/Ide.ts
  cypress-tests/cypress/pageobjects/ide/ProjectTree.ts
  cypress-tests/cypress/utils/workspace/TestWorkspaceUtil.ts
  cypress-tests/package-lock.json
  cypress-tests/package.json
  cypress-tests/tsconfig.json
Labels: kind/task, status/code-review, team/che-qe

#13033 Remove plugins and editors from workspace creation page
  dashboard/src/app/workspaces/create-workspace/create-workspace.controller.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.html
  dashboard/src/app/workspaces/create-workspace/create-workspace.service.ts
Labels: kind/enhancement, status/code-review

#13039 [Cypress] Use an "Electron" browser for "headless" mode
  cypress-tests/package.json
Labels: kind/task, team/che-qe

#13041 Fixed NPE during provisioning of selector for Deployments
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesObjectUtil.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/component/dockerimage/DockerimageComponentToWorkspaceApplier.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/component/dockerimage/DockerimageComponentToWorkspaceApplierTest.java
Labels: kind/bug, status/code-review

#13049 Selenium: update dashboard selenium tests according to adding Java Maven and Java Gradle stacks
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/constant/TestIntelligentCommandsConstants.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStopStartWsTest.java
Labels: kind/task, status/code-review, team/che-qe

#13043 Use a default message of original exception does not have any
  deploy/openshift/deploy_che.sh
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
Labels: status/code-review

#13068 [Cypress] Update the "WorkspaceCreationAndLanguageServerInitialization.spec.ts" cypress test according to the dashboard changes
  cypress-tests/README.md
  cypress-tests/cypress.json
  cypress-tests/cypress/integration/WorkspaceCreationAndLanguageServerInitialization.spec.ts
  cypress-tests/cypress/pageobjects/dashboard/NewWorkspace.ts
  cypress-tests/cypress/pageobjects/dashboard/workspace-details/WorkspaceDetails.ts
  cypress-tests/cypress/pageobjects/dashboard/workspace-details/WorkspaceDetailsPlugins.ts
  cypress-tests/cypress/pageobjects/ide/Ide.ts
  cypress-tests/cypress/pageobjects/ide/ProjectTree.ts
  cypress-tests/cypress/utils/ElementStateChecker.ts
Labels: kind/bug, status/code-review, team/che-qe

#13077 Selenium: update expected stacks list on NewWorkspacePageTest selenium test
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromEclipseCheStackTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaCentosStackTest.java
Labels: kind/task, status/code-review, team/che-qe

#13097 [Cypress] Update "ProjectTree.waitProjectImported" method according to the "Cypress" principles
  cypress-tests/cypress.json
  cypress-tests/cypress/pageobjects/ide/ProjectTree.ts
  cypress-tests/cypress/utils/ElementStateChecker.ts
  cypress-tests/cypress/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/bug, status/code-review, team/che-qe

#13105 Fix invalid return types.
  dashboard/src/components/api/che-profile.factory.ts
Labels: kind/bug

#12695 Define Theia dev stack for development che-theia, Theia plugins and plugin api.
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/question, status/code-review

#13140 Revert a part of 2a18d4d2. (applyed by #13105)
  dashboard/src/components/api/che-profile.factory.ts
Labels: kind/bug, severity/P1

#13122 Made Devfile part of a workspace
  core/che-core-api-model/pom.xml
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/Workspace.java
  dashboard/pom.xml
  ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/workspace/model/WorkspaceImpl.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/spi/jpa/JpaWorkerDaoTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WorkspaceDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/ComponentDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/DevfileActionDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/DevfileCommandDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/DevfileDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/DevfileVolumeDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/EndpointDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/EntrypointDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/EnvDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/ProjectDto.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/SourceDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/WorkspaceImpl.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/TemporaryWorkspaceRemoverTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
Labels: kind/task

#13129 Add an ability to enable ephemeral mode with devfile
  wsmaster/che-core-api-devfile/README.md
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/DevfileConverter.java
  wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/DefaultEditorProvisionerTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/DevfileConverterTest.java
Labels: kind/task, status/code-review

#13135 Add Django sample
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  ide/che-core-ide-templates/src/main/resources/samples.json
Labels: kind/task

#13174 Fix filter of the plugins list
  dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.controller.ts
Labels: kind/bug, status/code-review

#13176 Add Che7 Go stack and samples
  ide/che-core-ide-stacks/src/main/resources/stacks.json
  ide/che-core-ide-templates/src/main/resources/samples.json
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromGoStackTest.java
Labels: kind/task, target/che7, team/languages

#13161 Ignore `.theia/` directories.
  .gitignore
Labels: kind/task

#13191 Make reference of kubernetes component optional if referenceContent is provided
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/Components.java
  wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileIntegrityValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-devfile/src/test/resources/schema_test/kubernetes_openshift_component/devfile_openshift_component_with_missing_reference_and_referenceContent.yaml
Labels: kind/task

#13196 [Cypress] Change workspace details tabs list according to UI changes
  cypress-tests/cypress/integration/WorkspaceCreationAndLanguageServerInitialization.spec.ts
  cypress-tests/cypress/pageobjects/dashboard/workspace-details/WorkspaceDetails.ts
Labels: kind/task, status/code-review, team/che-qe

#13185 Added an ability to use Devfile as workspace configuration as an alternative to WorkspaceConfig
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/BadRequestException.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/local/projects/LocalProjectsMigrator.java
  infrastructures/docker/infrastructure/src/test/java/org/eclipse/che/workspace/infrastructure/docker/local/projects/LocalProjectMigratorTest.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/EphemeralWorkspaceUtility.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/usage/tracker/RamResourceUsageTracker.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/workspace/LimitsCheckingWorkspaceManager.java
  multiuser/api/che-multiuser-api-resource/src/test/java/org/eclipse/che/multiuser/resource/api/workspace/LimitsCheckingWorkspaceManagerTest.java
  multiuser/integration-tests/che-multiuser-cascade-removal/pom.xml
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/spi/jpa/MultiuserJpaWorkspaceDao.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilterTest.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileModule.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/convert/DevfileConverter.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/convert/DevfileConverterTest.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolverTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DevfileToWorkspaceConfigConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceLinksGenerator.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/jpa/JpaWorkspaceDao.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/WorkspaceImpl.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceNameEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceLinksGeneratorTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/jpa/JpaWorkspaceDaoTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceNameEnvVarProviderTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/tck/WorkspaceDaoTest.java
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
Labels: kind/enhancement
