Repository eclipse-che/che, pull requests merged in 2019-10, with the labels that each got.

#14682 Set Y axis unit to none
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
Labels: kind/enhancement, status/code-review

#14730 [TS_SELENIUM] Add VNC server to the "eclipse/che-e2e" docker image
  dockerfiles/e2e/Dockerfile
  dockerfiles/e2e/entrypoint.sh
  e2e/README.md
  e2e/package.json
Labels: kind/task, status/code-review, team/che-qe

#14744 Selenium: Enable selenium java tests related to Github OAuth authorization
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
Labels: kind/task, status/code-review, team/che-qe

#14716 [Selenium] Adapt selenium tests from workspaces package
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStoppingWsByTimeoutTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java
Labels: kind/task, status/code-review, team/che-qe

#14700 Update Deployments yamls in helm charts to be compatible with k8s v1.16
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/deployment.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
Labels: kind/enhancement, status/code-review

#14747 Changed default idle timeout and limit of running workspaces per user
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/enhancement, status/code-review

#14765 [Selenium] Adapt selenium tests from hotupdate.rolling package
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/hotupdate/HotUpdateUtil.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithStartedWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithWorkspacesStartStopTest.java
Labels: kind/task, status/code-review, team/che-qe

#14684 Change grafana configuration to match hosted che configuration
  deploy/openshift/deploy_che.sh
  deploy/openshift/templates/monitoring/che-monitoring.yaml
  deploy/openshift/templates/monitoring/grafana-dashboard-provider.yaml
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
Labels: kind/enhancement, status/code-review

#14777 [Selenium] Adapt selenium test from hotupdate.recreate package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/recreate/RecreateUpdateStrategyTest.java
Labels: kind/task, status/code-review, team/che-qe

#14774 Increase test workspace editor memory; grab Happy path tests logs and configs
  e2e/files/happy-path/happy-path-workspace.yaml
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: status/code-review

#14767 Generate a new SSH key if no keys are registered while ssh mount
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeysProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeySecretProvisionerTest.java
Labels: area/che-theia, kind/enhancement, status/code-review

#14701 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#14792 Serialize/deseialize list of DTO using same mechanism as single DTO object
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/CheJsonProvider.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/bug, status/code-review

#14757 chore(github): Fix template label for bugs
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: kind/bug, status/code-review

#14740 Devfile validation via message entity provider
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/CoreRestModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/WebApplicationExceptionMapper.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilterTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceEntityProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileEntityProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileModule.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceEntityProviderTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/DevfileEntityProviderTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/devfile.json
Labels: kind/bug, status/code-review

#14812 Revert "Devfile validation via message entity provider"
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/CoreRestModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/WebApplicationExceptionMapper.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilterTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceEntityProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileEntityProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileModule.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceEntityProviderTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/DevfileEntityProviderTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/devfile.json
Labels: status/code-review

#14814 Add workaround for handling unexpected pop ups during redirection maven build to editor
  e2e/files/happy-path/happy-path-workspace.yaml
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/enhancement, status/code-review

#14791 Set 600 file permissions to mounted SSH keys
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeysProvisioner.java
Labels: area/che-theia, kind/bug, status/code-review

#14728 prevent workspace restarting if user intentionally stopped it
  workspace-loader/src/workspace-loader.ts
  workspace-loader/test/test.spec.ts
Labels: kind/bug, status/code-review

#14818 Added missing setnev.sh after moving from che-lib
  assembly/assembly-che-tomcat8/src/assembly/bin/setenv.sh
Labels: kind/task, status/code-review

#14541 Add an ability to list available k8s namespaces
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/api/server/KubernetesNamespaceService.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/api/server/impls/KubernetesNamespaceMetaImpl.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/api/shared/KubernetesNamespaceMeta.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/api/shared/dto/KubernetesNamespaceMetaDto.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/api/server/KubernetesNamespaceServiceTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/openshift/pom.xml
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/Constants.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientConfigFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/IdentityProviderConfigFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/IdentityProviderConfigFactoryTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
Labels: kind/task, status/code-review

#14826 Validation of devfiles on workspace update
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/CoreRestModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/WebApplicationExceptionMapper.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilterTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceEntityProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileEntityProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileModule.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceEntityProviderTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/DevfileEntityProviderTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/devfile.json
Labels: kind/bug, status/code-review

#14798 E2E: Modify e2e test 'InstallCheByOperatorHub' to use with both Che and Crw
  e2e/TestConstants.ts
  e2e/package-lock.json
  e2e/pageobjects/openshift/OcpWebConsolePage.ts
  e2e/tests/e2e_install_che_operatorhub/InstallCheByOperatorHub.spec.ts
  e2e/utils/DriverHelper.ts
Labels: kind/task, status/code-review, team/che-qe

#14832 Use newer che-plugin-broker with che-theia remote runtime injection
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#14841 Selenium: Disable java selenium e2e test from test suite
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
Labels: kind/task, status/code-review, team/che-qe

#14836 Fix load-factory redirection in case of policies.create='peruser'
  dashboard/src/app/factories/load-factory/load-factory.controller.ts
  dashboard/src/app/factories/load-factory/load-factory.html
  dashboard/src/app/workspaces/create-workspace/create-workspace.controller.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.html
  dashboard/src/app/workspaces/create-workspace/devfile-selector/devfile-selector.controller.ts
  dashboard/src/app/workspaces/create-workspace/devfile-selector/devfile-selector.directive.ts
  dashboard/src/app/workspaces/list-workspaces/list-workspaces.html
  dashboard/src/app/workspaces/list-workspaces/workspace-item/workspace-item.controller.ts
  dashboard/src/app/workspaces/list-workspaces/workspace-item/workspace-item.html
  dashboard/src/components/typings/che.d.ts
Labels: kind/bug, status/code-review

#14834 load devfile schema for validation by it's apiVersion
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/schema/DevfileSchemaProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidator.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/DevfileServiceTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/schema/DevfileSchemaProviderTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
Labels: kind/enhancement, status/code-review

#14869 check devfile apiVersion against all supported versions
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/DevfileConverter.java
Labels: kind/enhancement, status/code-review

#14870 Selenium: Enable java selenium E2E test to test suite
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
Labels: kind/task, status/code-review, team/che-qe

#14875 Remove namespace in command prefix in Happy path tests
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review

#14884 Extend the size of the pool that is handling workspace related operations
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/task, status/code-review

#14779 [TS_SELENIUM] Create image for the "Happy Path" tests based on the "quay.io/eclipse/che-java11-maven" image
  e2e/files/happy-path/happy-path-workspace.yaml
  e2e/pageobjects/ide/Editor.ts
  e2e/pageobjects/ide/ProjectTree.ts
  e2e/tests/e2e/JavaVertx.spec.ts
  e2e/tests/e2e/WorkspaceCreationAndLsInitialization.spec.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/task, status/code-review, team/che-qe

#14675 Change 'Docker Registries' to 'Container Registries'
  dashboard/src/app/administration/administration.html
Labels: kind/enhancement, status/code-review

#14823 Add sparseCheckoutDir parameter into devfile spec
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/SourceStorage.java
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/devfile/Source.java
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubSourceStorageBuilder.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/SourceDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/ProjectConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/devfile/SourceImpl.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/convert/ProjectConverterTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/tck/WorkspaceDaoTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_with_sparse_checkout_dir.yaml
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/7.4.0/1__add_devfile_source_sparse_checkout_dir.sql
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/TestObjectsFactory.java
Labels: kind/task, status/code-review

#14919 Remove old dependencies
  typescript-dto/dto-pom.xml
  typescript-dto/package.json
Labels: status/code-review

#14924 7.3.0 vert.x E2E test fixup
  e2e/tests/e2e/JavaVertx.spec.ts
Labels: kind/bug, status/code-review, target/branch

#14925 Fix of Vert.x E2E test (#14924)
  e2e/tests/e2e/JavaVertx.spec.ts
Labels: kind/bug, status/code-review

#14921 Disable cors on master. Cleanup cors configuration on ws-agent
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterServletModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsAllowCredentialsEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsAllowedOriginsEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsEnabledEnvVarProvider.java
Labels: kind/enhancement, status/code-review

#14929 Stabilize DirectUrlFactoryWithSpecificBranchTest
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
Labels: kind/task, status/code-review

#14920 Use newer version of Jgroups and EclipseLink to prevent PKIX errors on OCP 4.x
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/jgroups/che-tcp.xml
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/JGroupsWorkspaceStatusCache.java
Labels: kind/bug, status/code-review

#14936 Change version of maven artifacts after updating the happy-path project
  e2e/files/happy-path/happy-path-workspace.yaml
Labels: kind/bug, status/code-review

#14928 Fix typo in plugin broker error messages
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/events/BrokerStatusListener.java
Labels: kind/bug, status/code-review

#14940 Remove outaded agent auth filter and unused models;
  multiuser/machine-auth/che-multiuser-machine-authentication-agent/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication-agent/src/main/java/org/eclipse/che/multiuser/machine/authentication/agent/MachineLoginFilter.java
  multiuser/machine-auth/che-multiuser-machine-authentication-agent/src/test/java/org/eclipse/che/multiuser/machine/authentication/agent/MachineLoginFilterTest.java
  multiuser/machine-auth/pom.xml
  wsmaster/che-core-api-auth-shared/src/main/java/org/eclipse/che/api/auth/shared/dto/Credentials.java
  wsmaster/che-core-api-auth-shared/src/main/java/org/eclipse/che/api/auth/shared/dto/Token.java
Labels: status/code-review

#14945 Get rid of non-working workaround to flakiness when Java LS server initialization failed
  e2e/pageobjects/ide/Ide.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/utils/DriverHelper.ts
Labels: kind/bug, status/code-review

#14952 Cherry-pick CORS changes from master to 7.3.x
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterServletModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsAllowCredentialsEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsAllowedOriginsEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsEnabledEnvVarProvider.java
Labels: status/code-review, target/branch

#14953 Backport: Use newer version of Jgroups and EclipseLink to prevent PKIX errors on OCP 4.x
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/jgroups/che-tcp.xml
  multiuser/api/che-multiuser-api-jgroups/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/JGroupsWorkspaceStatusCache.java
Labels: kind/bug, status/code-review, target/branch

#14937 Add support endpoints for VSCode extensions and Theia plugins.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#14828 Use che.infrastructure.kubernetes.namespace.default during workspace namespace resolution
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/templates/exec-role.yaml
  deploy/kubernetes/helm/che/templates/workspace-exec-role-binding.yaml
  deploy/kubernetes/helm/che/templates/workspace-service-account.yaml
  deploy/kubernetes/helm/che/templates/workspace-view-role-binding.yaml
  deploy/kubernetes/helm/che/templates/workspace-view-role.yaml
  deploy/kubernetes/helm/che/values.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/RemoveNamespaceOnWorkspaceRemove.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleaner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/RemoveNamespaceOnWorkspaceRemoveTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleanerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/RemoveProjectOnWorkspaceRemove.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/RemoveProjectOnWorkspaceRemoveTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
Labels: kind/task, status/code-review

#14969 Don't override entrypoint for remote binary.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#14975 Do not use spy in ServerCheckerTest
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/ServerCheckerTest.java
Labels: status/code-review

#14984 Fix branding for UD
  dashboard/src/components/branding/che-branding.factory.ts
Labels: kind/bug, status/code-review

#14980 [Selenium] Adapt selenium tests from dashboard package
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/AbstractTestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestWorkspaceServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceConfig.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjects.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjectsSamples.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsProjectsTest.java
Labels: kind/task, status/code-review, team/che-qe

#15004 Fix bug where broker container name can exceed 63 characters
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Names.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java
Labels: kind/bug, status/code-review, target/branch

#15010 7.3.x E2E happy path tests fixup
  e2e/files/happy-path/happy-path-workspace.yaml
  e2e/pageobjects/ide/Ide.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/utils/DriverHelper.ts
Labels: kind/task, status/code-review, target/branch

#14913 Disable autosave on Devfile editor page
  dashboard/src/app/admin/user-management/user-management.controller.ts
  dashboard/src/app/administration/docker-registry/docker-registry-list/docker-registry-list.controller.ts
  dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.ts
  dashboard/src/app/factories/list-factories/list-factories.controller.ts
  dashboard/src/app/navbar/recent-workspaces/recent-workspaces.controller.ts
  dashboard/src/app/organizations/list-organizations/list-organizations.controller.ts
  dashboard/src/app/organizations/list-organizations/organizations-item/organizations-item.controller.ts
  dashboard/src/app/organizations/organization-details/organization-details.controller.ts
  dashboard/src/app/organizations/organization-details/organization-members/list-organization-members.controller.ts
  dashboard/src/app/teams/list/list-teams.controller.ts
  dashboard/src/app/teams/list/team-item/team-item.controller.ts
  dashboard/src/app/teams/team-details/team-details.controller.ts
  dashboard/src/app/teams/team-details/team-members/list-team-members.controller.ts
  dashboard/src/app/teams/team-details/team-members/member-item/member-item.controller.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.service.ts
  dashboard/src/app/workspaces/list-workspaces/list-workspaces.controller.ts
  dashboard/src/app/workspaces/share-workspace/share-workspace.controller.ts
  dashboard/src/app/workspaces/share-workspace/user-item/user-item.controller.ts
  dashboard/src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.controller.ts
  dashboard/src/app/workspaces/workspace-details/environments/list-env-variables/list-env-variables.controller.ts
  dashboard/src/app/workspaces/workspace-details/environments/list-servers/list-servers.controller.ts
  dashboard/src/app/workspaces/workspace-details/environments/machine-config/machine-config.controller.ts
  dashboard/src/app/workspaces/workspace-details/list-commands/list-commands.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.html
  dashboard/src/app/workspaces/workspace-details/workspace-details.service.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-env-variables/env-variables.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-servers/machine-servers.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machine-volumes/machine-volumes.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/workspace-machines.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.html
  dashboard/src/app/workspaces/workspace-details/workspace-projects/workspace-details-projects.controller.ts
  dashboard/src/components/service/confirm-dialog/che-confirm-dialog.html
  dashboard/src/components/service/confirm-dialog/confirm-dialog.service.ts
  dashboard/src/components/widget/edit-mode-overlay/che-edit-mode-overlay.controller.ts
  dashboard/src/components/widget/edit-mode-overlay/che-edit-mode-overlay.directive.ts
  dashboard/src/components/widget/widget-config.ts
Labels: kind/bug, status/code-review

#14664 Set postgres deployment to use recreate deployment strategy
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/deployment.yaml
Labels: kind/enhancement, status/code-review

#14950 Mount each private key into single kubernetes secret
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeysProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeySecretProvisionerTest.java
Labels: kind/task, severity/P2, status/code-review, team/ide

#14727 Monitoring & Tracing capability for multiple Thread pools of Che Server
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/MetricsOverrideBinding.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheJsonRpcWebSocketConfigurationModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMajorWebSocketEndpointConfiguration.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMajorWebSocketEndpointExecutorServiceProvider.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMinorWebSocketEndpointConfiguration.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/jsonrpc/CheMinorWebSocketEndpointExecutorServiceProvider.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/test/java/org/eclipse/che/MetricsOverrideBindingTest.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/ExecutorServiceMetrics.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsModule.java
  core/commons/che-core-commons-lang/pom.xml
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/execution/ExecutorServiceBuilder.java
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/execution/ExecutorServiceProvider.java
  core/commons/che-core-commons-lang/src/test/java/org/eclipse/che/commons/lang/execution/ExecutorServiceBuilderTest.java
  core/commons/che-core-commons-lang/src/test/java/org/eclipse/che/commons/lang/execution/ExecutorServiceProviderTest.java
  core/commons/che-core-commons-mail/pom.xml
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/MailSender.java
  core/commons/che-core-commons-mail/src/test/java/org/eclipse/che/mail/MailSenderTest.java
  core/commons/che-core-commons-observability/pom.xml
  core/commons/che-core-commons-observability/src/main/java/io/micrometer/core/instrument/internal/TimedCronExecutorService.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/CountedRejectedExecutionHandler.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/CountedThreadFactory.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/ExecutorServiceWrapper.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/MeteredAndTracedExecutorServiceWrapper.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/MeteredExecutorServiceWrapper.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/NoopExecutorServiceWrapper.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/ObservableThreadPullLauncher.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/TracedCronExecutorService.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/TracedExecutorServiceWrapper.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/deploy/ExecutorWrapperModule.java
  core/commons/che-core-commons-observability/src/test/java/io/micrometer/core/instrument/internal/TimedCronExecutorServiceTest.java
  core/commons/che-core-commons-observability/src/test/java/org/eclipse/che/commons/observability/CountedRejectedExecutionHandlerTest.java
  core/commons/che-core-commons-observability/src/test/java/org/eclipse/che/commons/observability/CountedThreadFactoryTest.java
  core/commons/che-core-commons-observability/src/test/java/org/eclipse/che/commons/observability/MeteredExecutorServiceWrapperTest.java
  core/commons/che-core-commons-observability/src/test/java/org/eclipse/che/commons/observability/NoopExecutorServiceWrapperTest.java
  core/commons/che-core-commons-observability/src/test/resources/logback-test.xml
  core/commons/che-core-commons-schedule/src/main/java/org/eclipse/che/commons/schedule/executor/ThreadPullLauncher.java
  core/commons/pom.xml
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/KubernetesSharedPool.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelperTest.java
  multiuser/integration-tests/che-multiuser-cascade-removal/pom.xml
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
  pom.xml
  wsmaster/che-core-api-workspace/pom.xml
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceSharedPool.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/ProbeScheduler.java
  wsmaster/integration-tests/cascade-removal/pom.xml
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
Labels: kind/task, status/code-review

#15034 Fixed MeteredExecutorServiceWrapperTest that is failing some Linux system
  core/commons/che-core-commons-observability/src/test/java/org/eclipse/che/commons/observability/MeteredExecutorServiceWrapperTest.java
Labels: kind/bug, status/code-review
