Repository eclipse-che/che, pull requests merged in 2019-09, with the labels that each got.

#14397 Add init containers in the che plugin model
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/ChePlugin.java
Labels: kind/enhancement, status/code-review

#14347 Add small fixes for UD
  dashboard/src/app/factories/load-factory/load-factory.controller.ts
  dashboard/src/app/factories/load-factory/load-factory.service.ts
  dashboard/src/app/ide/ide-iframe/ide-iframe.service.ts
  dashboard/src/app/index.module.ts
  dashboard/src/app/navbar/navbar-config.ts
  dashboard/src/app/navbar/navbar-selected.controller.ts
  dashboard/src/app/navbar/navbar-selected.directive.ts
  dashboard/src/app/navbar/navbar.controller.ts
  dashboard/src/components/typings/che.d.ts
Labels: kind/bug, status/code-review

#14381 [Happy Path] Fix checking application readiness in HappyPath test
  e2e/pageobjects/ide/Ide.ts
Labels: kind/bug, status/code-review, team/che-qe

#14109 Remove Project Template API
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  pom.xml
  typescript-dto/dto-pom.xml
  wsmaster/che-core-api-project-templates-shared/pom.xml
  wsmaster/che-core-api-project-templates-shared/src/main/java/org/eclipse/che/api/project/templates/shared/dto/ProjectTemplateDescriptor.java
  wsmaster/che-core-api-project-templates/pom.xml
  wsmaster/che-core-api-project-templates/src/main/java/org/eclipse/che/api/project/server/template/ProjectTemplateDescriptionLoader.java
  wsmaster/che-core-api-project-templates/src/main/java/org/eclipse/che/api/project/server/template/ProjectTemplateRegistry.java
  wsmaster/che-core-api-project-templates/src/main/java/org/eclipse/che/api/project/server/template/ProjectTemplateService.java
  wsmaster/pom.xml
Labels: kind/task, status/code-review

#14410 Fix PR check Jenkinsfile
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#14402 Provision git configuration into each container
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitUserProfileProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitUserProfileProvisionerTest.java
Labels: kind/enhancement, status/code-review

#14417 [e2e] Added multiuser support.
  e2e/pageobjects/ide/Ide.ts
  e2e/pageobjects/login/SingleUserLoginPage.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/enhancement, status/code-review

#14433 che #14352 Setting new versions for editors, registries, and plugins for deploy script, helm charts and che.propoerties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/values.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/values.yaml
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/values.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/values.yaml
  deploy/kubernetes/helm/che/values.yaml
  deploy/openshift/deploy_che.sh
Labels: kind/task, status/code-review, target/branch

#13804 Fix handling of error status of a workspace
  workspace-loader/package.json
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/workspace-loader.ts
  workspace-loader/test/test.spec.ts
  workspace-loader/webpack.dev.js
Labels: kind/bug, status/code-review

#14435 [E2E] Fixing bug in opening file.
  e2e/pageobjects/ide/ProjectTree.ts
Labels: kind/bug, status/code-review

#14418 Add Host Key checking policy attribute to the ssh config
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeysProvisioner.java
Labels: area/che-theia, kind/bug, status/code-review

#14420 [Happy Path] Resolve problem with debug step of the "Happy-Path" scenario
  e2e/package-lock.json
  e2e/pageobjects/ide/Editor.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review, team/che-qe

#14441 RELEASE: Update CHANGELOG for 7.1.0
  CHANGELOG.md
Labels: kind/task, status/code-review

#14387 Fix PR check Jenkinsfile to use 'che-e2e' image
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/task, status/code-review

#14144 [Happy-Path] Update chromedriver to version 76.0.0
  e2e/package-lock.json
  e2e/package.json
Labels: kind/task, status/code-review

#14448 Do not apply proxy settings for JWTProxy container;
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ProxySettingsProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ProxySettingsProvisionerTest.java
Labels: kind/bug, status/code-review

#14493 Add step for selecting output parser into test
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/enhancement, status/code-review

#14453 Add ability override container root command.
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolver.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheContainer.java
Labels: kind/enhancement, status/code-review

#14383 Remove outdated Che6 concept. Devfile should be used instead
  Chefile
Labels: status/code-review

#14335 Support single-host mode on the multi-user server
  assembly/assembly-root-war/src/main/webapp/_app/loader.js
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/DefaultHostExternalServiceExposureStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServiceExposureStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/IngressServiceExposureStrategyProvider.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/MultiHostExternalServiceExposureStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/SingleHostExternalServiceExposureStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/CookiePathStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyConfigBuilder.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/model/VerifierConfig.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/DefaultHostExternalServiceExposureStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/MultiHostExternalServiceExposureStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyConfigBuilderTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposerTest.java
  infrastructures/kubernetes/src/test/resources/jwtproxy-confg.yaml
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftCookiePathStrategy.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftServerExposureStrategy.java
Labels: kind/task, status/code-review

#14306 Fix devfile component preferences deserialization through GSON
  core/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java
  core/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/SerializableInterfaceAdapterFactory.java
  core/che-core-api-dto/src/test/java/org/eclipse/che/dto/ServerDtoTest.java
  core/che-core-api-dto/src/test/java/org/eclipse/che/dto/definitions/DtoWithSerializable.java
Labels: kind/bug, status/code-review

#14442 Reconfigure Gson to parse more complex theia preference object
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Warnings.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitUserProfileProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitUserProfileProvisionerTest.java
Labels: kind/bug, status/code-review, team/ide

#14488 Add missing registration for git preferences provisioner
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
Labels: kind/task, status/code-review

#14396 Correct Che image tag in Helm Chart values file
  deploy/kubernetes/helm/che/values.yaml
Labels: status/code-review

#13034 Optimize PermissionChecker performance && adjust jsonrpc configuration
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/model/impl/WorkerImpl.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/spi/tck/WorkerDaoTest.java
Labels: kind/task, status/code-review

#14521 Refresh keycloak token
  dashboard/src/components/api/che-keycloak.factory.ts
  dashboard/src/components/api/json-rpc/che-json-rpc-api.factory.ts
  dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
Labels: kind/bug, status/code-review

#14528 Remove WsAgent specific classes from che-core-workspace-api
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  infrastructures/docker/environment/pom.xml
  infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/WsAgentMachineFinderUtil.java
  infrastructures/docker/environment/src/test/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/ComposeEnvironmentValidatorTest.java
  infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/local/installer/WsAgentServerConfigProvisioner.java
  selenium/che-selenium-core/pom.xml
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/AbstractTestWorkspaceServiceClient.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/CheTestWorkspaceServiceClient.java
  selenium/che-selenium-test/pom.xml
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/CheTestWorkspaceAgentApiEndpointUrlProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/MachineConfigsValidator.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/ProjectsVolumeForWsAgentProvisioner.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/MachineConfigsValidatorTest.java
Labels: kind/bug, status/code-review

#14557 Add Ssh Api methods to list of allowed requests signed with machine token
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java
Labels: kind/bug, status/code-review

#14561 Cleanup of temporary workspaces by schreduler instead of startup
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-workspace/pom.xml
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/TemporaryWorkspaceRemover.java
Labels: kind/bug, status/code-review

#14533 Add workspaces started under 60 seconds ratio panel
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
Labels: kind/task, status/code-review

#14572 replace sed delimiters to be able to use / in docker image buildscript
  dockerfiles/build.include
Labels: status/code-review

#14571 [Selenium] Fix unstable selenium tests from dashboard package
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceOwnerTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithKeepDirectoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
Labels: kind/bug, selenium/failure, status/code-review, team/che-qe

#14537 chore (CONTRIBUTING.md): update list of repos/components with links t…
  CONTRIBUTING.md
Labels: status/code-review

#14558 [E2E] Add test for Java Vertx workspace.
  e2e/mocha-java-vertx.opts
  e2e/package.json
  e2e/pageobjects/ide/ProjectTree.ts
  e2e/tests/e2e/JavaVertx.spec.ts
Labels: status/code-review

#14578 Add new Tomcat metrics dashboard in Grafana
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
Labels: kind/enhancement, status/code-review

#14524 workspace namespace/project placeholders
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
Labels: kind/enhancement, status/code-review

#14574 Makes sure the workspace activity checker reconciles the workspaces with their true statuses.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/InmemoryWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/JpaWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivity.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityChecker.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityCheckerTest.java
Labels: kind/bug, status/code-review

#14570 Implement workaround for Go to Definition feature HappyPath scenario
  e2e/driver/ChromeDriver.ts
  e2e/driver/ContainerInitializer.ts
  e2e/index.ts
  e2e/inversify.types.ts
  e2e/pageobjects/ide/ContextMenu.ts
  e2e/pageobjects/ide/Editor.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/utils/DriverHelper.ts
Labels: kind/task, status/code-review

#14619 [Selenium] Adapt selenium tests from ocpoauth package
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/OpenShiftKeycloakCliCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ocp/OpenShiftLoginPage.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ocp/OpenShiftProjectCatalogPage.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java
Labels: kind/task, status/code-review, team/che-qe

#14610 Add component alias into runtime machine if present in origin devfile
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/MachineConfig.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverBuilder.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
Labels: kind/task, status/code-review

#14643 Fix a UD-branding link
  dashboard/src/app/workspaces/list-workspaces/workspace-item/workspace-item.controller.ts
  dashboard/src/assets/branding/product.json
  dashboard/src/components/branding/che-branding.factory.ts
Labels: kind/bug, status/code-review

#14588 Change grafana dashboards for number of workspaces/users to be graphs with axes
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
Labels: kind/enhancement, status/code-review

#14626 Minor fixes to new Che workspace Grafana panels
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
Labels: kind/bug, status/code-review

#14644 Fix security vulnerability and Dashboard's workspace detail page
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  e2e/package-lock.json
  e2e/package.json
Labels: kind/bug, status/code-review

#14539 Plugin ephemeral volume feature for CheContainers
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/ChePluginsVolumeApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/Volume.java
Labels: area/installation, kind/enhancement, status/code-review

#14594 [Selenium] Adapt selenium tests to work with workspaces from Che7 stacks
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/CreateWorkspaceHelper.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceOverview.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateFactoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteRunningWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteStoppingWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/FactoriesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceMemberTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithKeepDirectoryTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: kind/task, status/code-review, team/che-qe

#14672 [TS_SELENIUM] Implement workaround for issue #14660 (Unexpected list of suggestions when use Java languageserver) in the "HappyPath" test.
  e2e/driver/ChromeDriver.ts
  e2e/index.ts
  e2e/pageobjects/ide/Editor.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/task, status/code-review, team/che-qe

#14642 [TS_SELENIUM] Increase logging of tests steps
  e2e/TestConstants.ts
  e2e/driver/CheReporter.ts
  e2e/index.ts
  e2e/pageobjects/ide/Ide.ts
  e2e/pageobjects/ide/ProjectTree.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/utils/DriverHelper.ts
  e2e/utils/Logger.ts
Labels: kind/task, status/code-review

#14686 [TS_SELENIUM] Increase logging of tests steps
  e2e/pageobjects/dashboard/Dashboard.ts
  e2e/pageobjects/dashboard/NewWorkspace.ts
  e2e/pageobjects/dashboard/Workspaces.ts
  e2e/pageobjects/dashboard/workspace-details/WorkspaceDetails.ts
  e2e/pageobjects/dashboard/workspace-details/WorkspaceDetailsPlugins.ts
  e2e/pageobjects/ide/ContextMenu.ts
  e2e/pageobjects/ide/DebugView.ts
  e2e/pageobjects/ide/Editor.ts
  e2e/pageobjects/ide/GitHubPlugin.ts
  e2e/pageobjects/ide/OpenWorkspaceWidget.ts
  e2e/pageobjects/ide/PreviewWidget.ts
  e2e/pageobjects/ide/QuickOpenContainer.ts
  e2e/pageobjects/ide/RightToolbar.ts
  e2e/pageobjects/ide/Terminal.ts
  e2e/pageobjects/ide/TopMenu.ts
  e2e/pageobjects/ide/WarningDialog.ts
  e2e/pageobjects/login/MultiUserLoginPage.ts
  e2e/pageobjects/login/OcpLoginByTempAdmin.ts
  e2e/pageobjects/login/SingleUserLoginPage.ts
  e2e/pageobjects/openshift/OcpLoginPage.ts
  e2e/pageobjects/openshift/OcpWebConsolePage.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/task, status/code-review, team/che-qe

#14688 Reduce the chances that successfulCheckTest will fail
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/ServerCheckerTest.java
Labels: kind/task, status/code-review

#14480 refactor: remove unused code
  dashboard/src/app/index.module.ts
  dashboard/src/assets/branding/product.json
  dashboard/src/components/branding/che-branding.factory.ts
  dashboard/src/components/components-config.ts
  dashboard/src/components/ide-fetcher/che-ide-fetcher-config.ts
  dashboard/src/components/ide-fetcher/che-ide-fetcher.service.ts
Labels: kind/enhancement, status/code-review

#14715 Fix editor components alias attribute format to match plugins attribute format
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/component/editor/EditorComponentToWorkspaceApplier.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/convert/component/editor/EditorComponentToWorkspaceApplierTest.java
Labels: kind/bug, status/code-review

#14719 Selenium: Disable selenium tests related to GitHub OAuth
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
Labels: kind/task, status/code-review, team/che-qe
