Repository eclipse-che/che, pull requests merged in 2019-07, with the labels that each got.

#13612 Deploy legacy variable only for che6 workspaces
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/AgentAuthEnableEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/JavaOptsEnvVariableProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/LegacyEnvVarEnvironmentProvisioner.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/LegacyEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/MavenOptsEnvVariableProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsAllowCredentialsEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsAllowedOriginsEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentCorsEnabledEnvVarProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/WorkspaceAgentJavaOptsEnvVariableProvider.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/provision/env/LegacyEnvVarEnvironmentProvisionerTest.java
Labels: status/code-review

#13542 Add dockerfile to execute E2E Che 7 typescript tests.
  dockerfiles/e2e/Dockerfile
  dockerfiles/e2e/README.md
  dockerfiles/e2e/build.sh
  dockerfiles/e2e/docker-entrypoint.sh
  dockerfiles/e2e/google-chrome.repo
Labels: kind/enhancement, status/code-review

#13663 [Selenium] Adapt selenium tests from ocpoauth package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java
Labels: kind/bug, selenium/failure, team/che-qe

#13535 Fix handling of error status of a workspace
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/workspace-loader.ts
  workspace-loader/test/test.spec.ts
Labels: kind/bug, status/code-review

#13588 Deprecate workspaces with Devfile stored as workspace config
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/factory/Factory.java
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/devfile/Component.java
  dashboard/src/app/factories/load-factory/load-factory.controller.ts
  dashboard/src/components/widget/accordion/che-accordion.directive.ts
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplier.java
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/factory/TestFactoryInitializer.java
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubSourceStorageBuilder.java
  wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java
  wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/dto/FactoryDto.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/ProjectConfigDtoMerger.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolverTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/ComponentDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/devfile/ComponentImpl.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/DevfileManagerTest.java
Labels: kind/task, status/code-review

#13615 [TS-SELENIUM] Cover the "Use Java IDE features and the inner loop" step from "Happy path" scenario
  deploy/kubernetes/helm/che/templates/configmap.yaml
  e2e/driver/CheReporter.ts
  e2e/files/happy-path/containers-happy-path.yaml
  e2e/files/happy-path/happy-path-workspace.yaml
  e2e/inversify.config.ts
  e2e/inversify.types.ts
  e2e/pageobjects/dashboard/NewWorkspace.ts
  e2e/pageobjects/ide/DebugView.ts
  e2e/pageobjects/ide/Editor.ts
  e2e/pageobjects/ide/GitHubPlugin.ts
  e2e/pageobjects/ide/Ide.ts
  e2e/pageobjects/ide/PreviewWidget.ts
  e2e/pageobjects/ide/ProjectTree.ts
  e2e/pageobjects/ide/QuickOpenContainer.ts
  e2e/pageobjects/ide/Terminal.ts
  e2e/pageobjects/ide/TopMenu.ts
  e2e/pageobjects/ide/WarningDialog.ts
  e2e/tests/e2e/WorkspaceCreationAndLsInitialization.spec.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
  e2e/utils/DriverHelper.ts
Labels: kind/task, status/code-review, team/che-qe

#13802 [TS-SELENIUM] Update HappyPath test according to fixed bug
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: status/in-progress, team/che-qe

#13569 Allow registry passwords longer than 128 chars
  dashboard/src/app/administration/docker-registry/docker-registry-list/edit-registry/edit-registry.html
Labels: kind/enhancement, status/code-review

#13831 [TS-SELENIUM] Fix containers-happy-path.yaml reference url
  e2e/files/happy-path/happy-path-workspace.yaml
Labels: status/in-progress, team/che-qe

#13777 chore(github): Update issue template to have several choices
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/a_question.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/task.md
Labels: kind/task

#13815 Remove Diagnostics widget on UD
  dashboard/src/app/diagnostics/diagnostic-callback-state.ts
  dashboard/src/app/diagnostics/diagnostic-callback.ts
  dashboard/src/app/diagnostics/diagnostic-item.ts
  dashboard/src/app/diagnostics/diagnostic-part-state.ts
  dashboard/src/app/diagnostics/diagnostic-part.ts
  dashboard/src/app/diagnostics/diagnostics-config.ts
  dashboard/src/app/diagnostics/diagnostics-widget.html
  dashboard/src/app/diagnostics/diagnostics.controller.ts
  dashboard/src/app/diagnostics/diagnostics.directive.ts
  dashboard/src/app/diagnostics/diagnostics.html
  dashboard/src/app/diagnostics/diagnostics.styl
  dashboard/src/app/diagnostics/test/diagnostics-websocket-wsmaster.factory.ts
  dashboard/src/app/diagnostics/test/diagnostics-workspace-check-workspace.factory.ts
  dashboard/src/app/diagnostics/test/diagnostics-workspace-start-check.factory.ts
  dashboard/src/app/index.module.ts
  dashboard/src/components/widget/footer/che-footer.html
Labels: kind/bug, severity/blocker, target/che7GA

#13645 modify url to get index.json
  dashboard/src/components/api/devfile-registry.factory.ts
Labels: kind/enhancement, status/code-review, target/che7GA

#13798 Add `securityContext.fsGroup`.
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/deployment.yaml
  dockerfiles/keycloak/Dockerfile
Labels: kind/bug

#13825 Adapt project selector widget to manage projects from devfile
  dashboard/src/app/stacks/stack-details/select-template/select-template.controller.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.controller.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.html
  dashboard/src/app/workspaces/create-workspace/create-workspace.service.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/add-import-project.controller.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/add-import-project.directive.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/add-import-project.html
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/add-import-project.service.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/template-selector/template-selector.controller.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/template-selector/template-selector.directive.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/template-selector/template-selector.service.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/edit-project/project-metadata/project-metadata.controller.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/edit-project/project-metadata/project-metadata.html
  dashboard/src/app/workspaces/create-workspace/project-source-selector/edit-project/project-metadata/project-metadata.service.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/project-source-selector.controller.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/project-source-selector.directive.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/project-source-selector.html
  dashboard/src/app/workspaces/create-workspace/project-source-selector/project-source-selector.service.ts
  dashboard/src/app/workspaces/workspace-config.service.ts
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-item/project-item.html
  dashboard/src/app/workspaces/workspace-details/workspace-projects/workspace-details-projects.controller.ts
  dashboard/src/components/api/builder/che-api-builder.factory.ts
  dashboard/src/components/api/che-api-config.ts
  dashboard/src/components/api/che-api.factory.ts
  dashboard/src/components/api/che-project-template.factory.ts
  dashboard/src/components/api/che-project-template.spec.ts
  dashboard/src/components/api/devfile-registry.factory.ts
Labels: kind/enhancement, status/code-review, target/che7GA

#13851 [TS-SELENIUM] Fix HappyPath Java language server validation
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: status/in-progress, team/che-qe

#13884 Selenium: Correct the e2e selenium tests related to changes on dashboard
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
Labels: kind/task, status/code-review, team/che-qe

#13887 Adapt Java selenium e2e tests to Openshift OAuth v4
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/site/CheLoginPage.java
Labels: team/che-qe

#13885 [TS-SELENIUM] Adapt WorkspaceCreationAndLsInitialization test according workspace creation from Dashboard changes
  e2e/pageobjects/dashboard/NewWorkspace.ts
  e2e/tests/e2e/WorkspaceCreationAndLsInitialization.spec.ts
Labels: status/in-progress, team/che-qe

#13923 Fix project clonePath is not considered on workspace creation
  dashboard/src/app/workspaces/create-workspace/create-workspace.service.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/import-git-project/import-git-project.service.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/import-github-project/import-github-project.service.ts
Labels: kind/bug, status/code-review

#13947 Store github token in session storage, remove on logout
  dashboard/src/components/api/che-keycloak.factory.ts
  dashboard/src/components/github/github-service.ts
Labels: kind/bug, status/code-review, target/che7GA

#13987 [TS SELENIUM] Fix the #13865 issue (Happy Path test is sometimes failing on "Error highlighting" step)
  e2e/pageobjects/ide/Ide.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review, team/che-qe

#13948 Remove the "npm" dependency vulnerability
  e2e/package-lock.json
Labels: kind/task, team/che-qe

#14019 [TS_SELENIUM] Resolve problem with notifications interaction (bug #13864)
  e2e/pageobjects/ide/Ide.ts
Labels: kind/bug, team/che-qe

#13895 [Selenium] Fix unstable selenium tests, add info about know issue
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: status/code-review, team/che-qe

#14046 [ Happy Path ] Fix #14018 bug (Somethimes "Happy Path" test fails on validation of autocomplete)
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: status/code-review, team/che-qe

#14057 Fix empty warning on workspace details page
  dashboard/src/app/workspaces/workspace-details/warnings/workspace-warnings.controller.ts
Labels: status/code-review
