Repository eclipse-che/che, pull requests merged in 2019-11, with the labels that each got.

#15083 Fixing Vert.x test
  e2e/tests/e2e/JavaVertx.spec.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review

#15078 Fix TypeScript DTO generator
  core/che-core-typescript-dto-maven-plugin/pom.xml
  core/che-core-typescript-dto-maven-plugin/src/it/resources/dto.spec.ts
  core/che-core-typescript-dto-maven-plugin/src/main/java/org/eclipse/che/plugin/typescript/dto/DTOHelper.java
  core/che-core-typescript-dto-maven-plugin/src/test/java/org/eclipse/che/plugin/typescript/dto/MyDtoWithSerializableDTO.java
  typescript-dto/build.sh
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/CommandDto.java
Labels: kind/bug, status/code-review

#15058 [Selenium] Adapt selenium tests from ocpoauth package
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ocp/OpenShiftProjectCatalogPage.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java
Labels: kind/task, team/che-qe

#15125 Improve docs and devfile on workspace loader development flow
  CONTRIBUTING.md
  workspace-loader/devfile.yaml
Labels: area/doc, status/code-review

#15112 Fix UD build
  dashboard/Dockerfile
  dashboard/index.d.ts
  dashboard/package.json
  dashboard/src/app/dashboard/last-workspaces/last-workspaces.controller.spec.ts
  dashboard/src/app/dashboard/last-workspaces/last-workspaces.controller.ts
  dashboard/src/app/factories/create-factory/config-file-tab/factory-from-file.controller.ts
  dashboard/src/app/factories/load-factory/load-factory.controller.ts
  dashboard/src/app/navbar/navbar-dropdown-menu/navbar-dropdown-menu.directive.ts
  dashboard/src/app/organizations/organizations-config.service.spec.ts
  dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/import-github-project/import-github-project.controller.ts
  dashboard/src/app/workspaces/create-workspace/ram-settings/ram-settings.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/workspace-machines.controller.ts
  dashboard/src/components/api/che-agent.factory.ts
  dashboard/src/components/api/devfile-registry.factory.ts
  dashboard/src/components/api/environment/compose-environment-manager.spec.ts
  dashboard/src/components/api/environment/docker-file-environment-manager.spec.ts
  dashboard/src/components/api/paging-resource/page-object-resource.ts
  dashboard/src/components/api/plugin-registry.factory.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  dashboard/src/components/filter/change-memory-unit/change-memory-unit.filter.ts
  dashboard/src/components/github/github-service.ts
  dashboard/src/components/utils/register.ts
  dashboard/src/components/widget/compile/che-compile.directive.ts
  dashboard/src/components/widget/input/che-input.directive.ts
  dashboard/src/components/widget/input/che-textarea.directive.ts
  dashboard/src/components/widget/learn-more/che-learn-more-template.directive.ts
  dashboard/src/components/widget/learn-more/che-learn-more.controller.ts
  dashboard/src/components/widget/list/che-list-helper.spec.ts
  dashboard/src/components/widget/list/che-list-helper.ts
  dashboard/src/components/widget/loader/che-loader-crane.directive.ts
  dashboard/tsconfig.json
  dashboard/typings.json
  dashboard/yarn.lock
Labels: kind/bug, status/code-review

#15149 Get rid of the redundant switching to the associated workspace in the "Happy Path" test
  e2e/pageobjects/ide/Ide.ts
  e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/enhancement, status/code-review, team/che-qe

#15147 [Workspace Loader] Add strict checks for typescript
  workspace-loader/Dockerfile
  workspace-loader/package.json
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/json-rpc/json-rpc-client.ts
  workspace-loader/src/json-rpc/util.ts
  workspace-loader/src/keycloak-loader.ts
  workspace-loader/src/loader/loader.ts
  workspace-loader/src/workspace-loader.ts
  workspace-loader/test/test.spec.ts
  workspace-loader/tsconfig.json
  workspace-loader/yarn.lock
Labels: kind/task, status/code-review

#15000 Use cached sessions behind any of the login filters
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/web.xml
  core/commons/che-core-commons-logback/src/main/java/org/eclipse/che/commons/logback/filter/IdentityIdLoggerFilter.java
  multiuser/api/che-multiuser-api-authentication-commons/pom.xml
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/Constants.java
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/DestroySessionListener.java
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/SessionStore.java
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/SubjectHttpRequestWrapper.java
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/filter/MultiUserEnvironmentInitializationFilter.java
  multiuser/api/che-multiuser-api-authentication-commons/src/test/java/org/eclipse/che/multiuser/api/authentication/commons/SessionStoreTest.java
  multiuser/api/che-multiuser-api-authentication-commons/src/test/java/org/eclipse/che/multiuser/api/authentication/commons/SubjectHttpRequestWrapperTest.java
  multiuser/api/che-multiuser-api-authentication-commons/src/test/java/org/eclipse/che/multiuser/api/authentication/commons/filter/MultiUserEnvironmentInitializationFilterTest.java
  multiuser/api/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/AbstractKeycloakFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakAuthenticationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitializationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakProfileRetriever.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClient.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakServletModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/oauth2/DelegatedOAuthAPI.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/AbstractKeycloakFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakAuthenticationFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitializationFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClientTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilter.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilterTest.java
  pom.xml
  wsmaster/wsmaster-local/src/main/java/org/eclipse/che/api/local/filters/EnvironmentInitializationFilter.java
Labels: kind/bug, status/code-review

#15154 [Workspace Loader] Add missing async keyword
  workspace-loader/src/workspace-loader.ts
Labels: status/code-review

#15156 Delete unused classes and functionality
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CustomPortService.java
  core/che-core-api-core/src/main/java/org/eclipse/che/everrest/CheAsynchronousJobPool.java
Labels: status/code-review

#15144 Use nightly che-machine-exec tag instead of deprecated next.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#15178 Use che-plugin-broker images 0.24
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review, target/branch

#15023 Remove/update deprecated machine start timeout env var in templates
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/openshift/templates/che-server-template.yaml
  selenium/che-selenium-test/src/test/resources/projects/nodejs-with-yaml/deployment.yaml
Labels: kind/task, status/code-review

#15181 [UD] Use default icon if actual icon is not accessible
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/devfile-selector/devfile-selector.controller.ts
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/devfile-selector/devfile-selector.html
  dashboard/src/components/attribute/img-src/img-src.directive.ts
Labels: kind/enhancement, status/code-review

#15194 Dashboard restart 7.3.x
  dashboard/src/app/ide/ide-iframe/ide-iframe.service.ts
  dashboard/src/app/ide/ide.service.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
Labels: kind/bug, status/code-review, target/branch

#15195 [UD] Use default icon if actual icon is not accessible
  dashboard/src/app/workspaces/create-workspace/devfile-selector/devfile-selector.controller.ts
  dashboard/src/app/workspaces/create-workspace/devfile-selector/devfile-selector.html
  dashboard/src/components/attribute/img-src/img-src.directive.ts
Labels: status/code-review, target/branch

#15180 Use dashboard to restart the workspace
  dashboard/src/app/ide/ide-iframe/ide-iframe.service.ts
  dashboard/src/app/ide/ide.service.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
Labels: kind/bug, status/code-review

#15158 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#15207 Provide metrics of k8s API execution
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/che-core-metrics-core/pom.xml
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsModule.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/NoopMetricsModule.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/OkHttpMetricsEventListenerProvider.java
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
Labels: status/code-review

#15205 Add whitespace to README.md
  typescript-dto/README.md
Labels: kind/bug, status/code-review

#15245 README: update links to documentation
  README.md
Labels: kind/task, status/code-review

#15255 README: update more links to documentation
  README.md
Labels: kind/task, status/code-review

#15198 Publish PluginBroker pod events as runtime log
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/RuntimeLogsPublisher.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/RuntimeEventsPublisher.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBrokerTest.java
Labels: kind/task, status/code-review

#15142 Add an ability to configure PVC strategy with helm chart
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/enhancement, status/code-review

#15236 Update a few links in order to point to che-7 docs
  dashboard/src/assets/branding/product.json
  dashboard/src/components/branding/che-branding.factory.ts
Labels: kind/bug, status/code-review

#15274 [Selenium] Stabilize workspace creation verification
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/CreateWorkspaceHelper.java
Labels: selenium/failure, status/code-review, team/che-qe

#15218 Support git operation for repos with self-signed SSL certs
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
  deploy/openshift/templates/che-server-template.yaml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitConfigProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSslCertificateProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitConfigProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSslCertificateProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
Labels: kind/task, status/code-review

#15282 Align JGroups labels property name and add one preventing to connect to unready pods
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/jgroups/che-tcp.xml
Labels: kind/bug, status/code-review

#15247 Improved handling of exceptions in workspace activities related operations
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/InmemoryWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/JpaWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityChecker.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityCheckerTest.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/spi/tck/WorkspaceActivityDaoTest.java
Labels: kind/bug, status/code-review

#15203 Used latest official jre8-slim image for che master
  dockerfiles/che/Dockerfile
  dockerfiles/che/open-jdk-source-file-location
Labels: status/code-review

#15296 Fixed path to default trust store of OpenJDK
  dockerfiles/che/entrypoint.sh
Labels: kind/bug, status/code-review

#15064 Various improvements of Jenkins pipeline to run Che E2E Happy path tests on PR check
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#15311 Fix test workspace devfile address for PR based on fork
  e2e/jenkins/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#15252 Added support of env for k8s/os component
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/EnvVars.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/EnvVarsTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/devfile/OpenshiftComponentToWorkspaceApplier.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/devfile/OpenshiftComponentToWorkspaceApplierTest.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.1-beta/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/kubernetes_openshift_component/devfile_k8s_openshift_component_with_env.yaml
Labels: kind/task, status/code-review

#15292 Set basic access authentication for registries requests
  dashboard/src/components/api/devfile-registry.factory.ts
  dashboard/src/components/api/plugin-registry.factory.ts
  dashboard/src/components/interceptor/keycloak-token-interceptor.ts
Labels: kind/bug, status/code-review

#12911 Dashboard: fail build when webpack has errors
  dashboard/gulp/inject.js
  dashboard/gulp/scripts.js
  dashboard/gulp/watch.js
Labels: kind/bug, status/code-review

#15254 Listen changing workspace status
  dashboard/src/app/ide/ide-iframe/ide-iframe.service.ts
Labels: kind/bug, status/code-review

#15335 Turn off the tests which check refresh
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
Labels: kind/bug, status/code-review

#15251 [UD] Fixed ability to start a workspace after changing its name.
  dashboard/src/app/navbar/recent-workspaces/recent-workspaces.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
Labels: kind/bug, status/code-review

#15344 Fix possible NPE when no URL parameter specified for factory
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/FactoryServiceTest.java
Labels: kind/bug, status/code-review

#15358 [Selenium] Adapt Java Vertx test
  e2e/pageobjects/dashboard/NewWorkspace.ts
Labels: selenium/failure, status/code-review, team/che-qe

#15359 Fix checking New Worspace page in Vert.x E2E test
  e2e/pageobjects/dashboard/NewWorkspace.ts
Labels: kind/bug, status/code-review

#15220 Make it possible to override values of the devfile by factory parameters
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
  wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolver.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolverTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
  wsmaster/che-core-api-workspace/pom.xml
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/OverridePropertiesApplier.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/exception/OverrideParameterException.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidator.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/DevfileManagerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/OverridePropertiesApplierTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
Labels: kind/enhancement, status/code-review

#15357 Drop che_workspace_expiration table
  assembly/assembly-wsmaster-war/src/main/resources/META-INF/persistence.xml
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/InmemoryWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/JpaWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceExpiration.java
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/7.6.0/1__drop_che_workspace_expiration.sql
  wsmaster/integration-tests/mysql-tck/src/test/java/MySqlTckModule.java
  wsmaster/integration-tests/postgresql-tck/src/test/java/PostgreSqlTckModule.java
Labels: kind/bug, status/code-review

#15366 Added the reason of problem to clean up preferences for owner of the workspace
  wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/AppStatesPreferenceCleaner.java
Labels: kind/enhancement, status/code-review

#15364 Print build information to the startup logs
  core/che-core-api-core/pom.xml
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/ApiInfoProvider.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/CoreRestModule.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/ApiInfoLogInformer.java
  core/che-core-api-core/src/test/java/org/eclipse/che/api/core/rest/it/ApiInfoProviderTest.java
Labels: status/code-review

#15369 add websocket stream check before sending a message
  dashboard/src/components/api/json-rpc/websocket-client.ts
Labels: kind/enhancement, status/code-review
