Repository eclipse-che/che, pull requests merged in 2019-06, with the labels that each got.

#13453 Add -Duser.home parameter to maven opts in java-maven stack
  ide/che-core-ide-stacks/src/main/resources/stacks.json
Labels: kind/bug

#13468 Selenium: remove selenium tests that check Che 6 compatible factories from CheSuite test suite
  selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: status/code-review, team/che-qe

#13455 Enable to set URLs for custom registries.
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/enhancement

#13544 [E2E] Update typescript tests according to workspace creation changes
  e2e/pageobjects/dashboard/NewWorkspace.ts
  e2e/tests/e2e/WorkspaceCreationAndLsInitialization.spec.ts
Labels: kind/bug, team/che-qe

#13546 Add creation of k8s secrets during deploying of broker
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBrokerTest.java
Labels: kind/bug
