Repository eclipse-che/che, pull requests merged in 2019-01, with the labels that each got.

#12325 Make Keycloak CLI client for E2E test as extendable
  selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/requestfactory/TestUserHttpJsonRequestFactory.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/CheSeleniumSuiteModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/TestExecutionModule.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/KeycloakTestAuthServiceClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/KeycloakCliClient.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/cli/OpenShiftKeycloakCliCommandExecutor.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/hotupdate/HotUpdateUtil.java
Labels: team/che-qe

#12331 Selenium: Do refactoring selenium tests in the 'intelligencecommand' package
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/AutocompleteCommandsEditorTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CheckIntelligenceCommandFromToolbarTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/CommandsPaletteTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/intelligencecommand/MacrosCommandsEditorTest.java
Labels: kind/task, status/code-review, team/che-qe

#12338 Selenium: Do refactoring selenium tests
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/GolangFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/JsonFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/languageserver/csharp/CSharpFileEditingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/projectexplorer/CheckShowHideHiddenFilesTest.java
Labels: kind/task, status/code-review, team/che-qe

#12222 Use the names of the enums instead of their ordinals when storing them to DB
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/model/KubernetesMachineImpl.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/model/KubernetesRuntimeState.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/model/KubernetesServerImpl.java
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.17.0/1__convert_enums_to_strings.sql
Labels: kind/bug, status/code-review

#12270 Publicize the number of workspaces per state as a prometheus metric.
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  pom.xml
  wsmaster/che-core-api-metrics/pom.xml
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceActivityMeterBinder.java
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WsMasterMetricsModule.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/InmemoryWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/JpaWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManager.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManagerTest.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/spi/tck/WorkspaceActivityDaoTest.java
  wsmaster/pom.xml
Labels: kind/task, status/code-review

#12368 Add workspace failure count metric.
  wsmaster/che-core-api-metrics/pom.xml
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceActivityMeterBinder.java
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceBinders.java
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceFailureMeterBinder.java
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WsMasterMetricsModule.java
  wsmaster/che-core-api-metrics/src/test/java/org/eclipse/che/api/metrics/WorkspaceFailureMeterBinderTest.java
Labels: kind/task, status/code-review, team/platform

#12149 Add binding of VS Code extension broker for Che 7
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
Labels: status/code-review

#12293 Generate and publish TS DTO interfaces
  pom.xml
  typescript-dto/.gitignore
  typescript-dto/Dockerfile
  typescript-dto/dto-pom.xml
  typescript-dto/package.json
  typescript-dto/pom.xml
Labels: kind/enhancement

#12417 [WIP]Upgrade the version of theia-generator version to 0.0.1-1547456396
  dockerfiles/theia-dev/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
Labels: status/code-review

#12399 Update to lsp4j 0.6.0
  plugins/plugin-java/che-plugin-java-server/pom.xml
  plugins/plugin-languageserver/che-plugin-languageserver-ide/pom.xml
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/quickassist/ApplyWorkspaceEditAction.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/rename/LSRenameAction.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/rename/RenamePresenter.java
  wsagent/che-core-api-languageserver/pom.xml
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/ServerCapabilitiesAccumulator.java
  wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/TextDocumentService.java
Labels: kind/task, status/code-review

#12410 Add workspace confing autosave
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-machines/workspace-machines.controller.ts
  dashboard/src/components/api/environment/environment-manager.ts
  dashboard/src/components/widget/editor/che-editor.controller.ts
  dashboard/src/components/widget/editor/che-editor.directive.ts
Labels: kind/enhancement, status/code-review

#12420 Copy resources in KubernetesEnvironment constructor instead of reusing
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironment.java
Labels: kind/bug, status/code-review

#12375 CHE-12329 Rework the way of retrieving editor provider by file-type
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorAgentImpl.java
Labels: kind/bug, status/code-review

#12343 Enable to build the `che-dev` container.
  dockerfiles/dev/Dockerfile
Labels: status/code-review

#12433 add parent version back
  pom.xml
Labels: kind/enhancement, status/code-review

#12041 Detect Simple Java Projects on Import
  ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/tree/ResourceNode.java
  multiuser/permission/che-multiuser-permission-workspace/pom.xml
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaExtension.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/command/ClasspathContainer.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/inject/JavaGinModule.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/classpath/ClasspathChangedEvent.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/classpath/ClasspathResolver.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/classpath/ProjectClasspathChangedEvent.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/service/CustomNotificationReceiver.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/tree/library/LibrariesNode.java
  plugins/plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/command/ClasspathContainerTest.java
  plugins/plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/Constants.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/ProjectsListener.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/inject/PlainJavaProjectModule.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/inject/PlainJavaProjectSourceFolderWatcher.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/projecttype/PlainJavaProjectUpdateUtil.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/projecttype/PlainJavaValueProviderFactory.java
  plugins/plugin-java/che-plugin-java-plain/che-plugin-java-plain-server/src/main/java/org/eclipse/che/plugin/java/plain/server/rest/ClasspathUpdaterService.java
  plugins/plugin-java/che-plugin-java-server/pom.xml
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLSWrapper.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerLauncher.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProjectClassPathChangedEvent.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/ProjectsSynchronizer.java
  plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/WorkspaceSynchronizer.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/pom.xml
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/LanguageServerExtension.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/inject/LanguageServerGinModule.java
  plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/CustomNotificationReceiver.java
  pom.xml
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/MutableProjectConfig.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectJsonRpcServiceBackEnd.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/notification/ProjectUpdatedEvent.java
Labels: kind/bug, status/code-review

#12404 [CORS] Correctly determine server from which IDE was loaded
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/cors/CheWsAgentCorsAllowedOriginsProvider.java
  dockerfiles/gwt-ide/Dockerfile
  wsagent/che-wsagent-core/pom.xml
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/CheWsAgentCorsAllowCredentialsProvider.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/CheWsAgentCorsAllowedOriginsProvider.java
  wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/CheWsAgentModule.java
  wsagent/che-wsagent-core/src/test/resources/logback-test.xml
Labels: kind/bug, status/code-review

#12365 Send project events on rename
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java
Labels: kind/bug, status/code-review

#12455 Check the latest version of @eclipse-che/api
  typescript-dto/Dockerfile
  typescript-dto/README.md
  typescript-dto/publish.sh
Labels: status/code-review

#12335 Added support of PVC in Kuberentes/OpenShift recipe
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Warnings.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentPodsValidator.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentValidator.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/EphemeralWorkspaceAdapter.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspacePVCCleaner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentPodsValidatorTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentValidatorTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/EphemeralWorkspaceAdapterTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/TestObjects.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategyTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/Warnings.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactoryTest.java
Labels: kind/enhancement, status/code-review

#12402 Selenium: Refactor selenium tests from the 'miscellaneous' package
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CheTerminal.java
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/CodenvyEditor.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/PhpProjectDebuggingTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/FindTextFeatureTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/MachinesAsynchronousStartTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/OpenInTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/ResolveDependencyAfterRecreateProjectTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithSplitPanelTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CreateWorkspaceOnDashboardTest.java
Labels: kind/task, status/code-review, team/che-qe

#12468 Fix outdated theia image readme file
  dockerfiles/theia/README.md
Labels: kind/bug, status/code-review

#12477 [theia-dev] generator: use latest tagged version
  dockerfiles/theia-dev/Dockerfile
  dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
Labels: status/code-review

#12481 RELEASE: Update CHANGELOG
  CHANGELOG.md
Labels: status/code-review

#12484 bump che-ls-jdt version
  pom.xml
Labels: status/code-review

#12416 Enable support for CHE_DEBUG_SUSPEND in docker image's entrypoint.sh
  dockerfiles/che/entrypoint.sh
Labels: kind/bug, status/code-review

#12358 Theia cdn support
  dockerfiles/theia-dev/Dockerfile
  dockerfiles/theia/.gitignore
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/README.md
  dockerfiles/theia/build.sh
  dockerfiles/theia/e2e/Dockerfile
  dockerfiles/theia/extract-for-cdn.sh
  dockerfiles/theia/push-cdn-files-to-akamai.sh
  dockerfiles/theia/src/entrypoint.sh
Labels: status/code-review

#12478 Add plugin generator to the theia-dev image.
  dockerfiles/theia-dev/Dockerfile
Labels: kind/docs, status/code-review

#12492 Update version of image of init plugin broker
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#12483 Add ability to configure workspace ephemeral mode
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.html
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.styl
Labels: kind/enhancement, status/code-review

#12502 [dockerfile] Use a tagged version of che-theia instead of master
  dockerfiles/theia-dev/Dockerfile
Labels: status/code-review

#12504 Upgrade to the latest version of the `che-theia-generator`
  dockerfiles/theia-dev/Dockerfile
Labels: status/code-review

#12495 Move theia and theia-dev docker files in to che-theia repository
  dockerfiles/pom.xml
  dockerfiles/theia-dev/Dockerfile
  dockerfiles/theia-dev/build.sh
  dockerfiles/theia-dev/e2e/Dockerfile
  dockerfiles/theia-dev/e2e/build.sh
  dockerfiles/theia-dev/pom.xml
  dockerfiles/theia-dev/src/entrypoint.sh
  dockerfiles/theia/.dockerignore
  dockerfiles/theia/.gitignore
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/README.md
  dockerfiles/theia/build.sh
  dockerfiles/theia/e2e/.dockerignore
  dockerfiles/theia/e2e/.gitignore
  dockerfiles/theia/e2e/Dockerfile
  dockerfiles/theia/e2e/build.sh
  dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
  dockerfiles/theia/e2e/cypress/plugins/index.js
  dockerfiles/theia/e2e/cypress/support/commands.ts
  dockerfiles/theia/e2e/cypress/support/index.ts
  dockerfiles/theia/e2e/src/cypress.json
  dockerfiles/theia/e2e/src/docker-run.sh
  dockerfiles/theia/e2e/src/package.json
  dockerfiles/theia/e2e/src/snapshots.js
  dockerfiles/theia/e2e/src/tsconfig.json
  dockerfiles/theia/e2e/src/tslint.json
  dockerfiles/theia/e2e/src/webpack.config.js
  dockerfiles/theia/e2e/src/yarn.lock
  dockerfiles/theia/e2e/test.sh
  dockerfiles/theia/extract-for-cdn.sh
  dockerfiles/theia/pom.xml
  dockerfiles/theia/push-cdn-files-to-akamai.sh
  dockerfiles/theia/src/entrypoint.sh
  dockerfiles/theia/src/patches/0.3.12/001-regexp.patch
  dockerfiles/theia/src/patches/0.3.16/001-hosted.patch
  dockerfiles/theia/src/patches/0.3.17/001-args.patch
  pom.xml
Labels: status/code-review

#12372 Use meaningful value for plugin broker container name instead of generated one
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java
Labels: kind/task, status/code-review

#12513 Enable precreate subpaths property by default in templates
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/openshift/templates/che-server-template.yaml
Labels: kind/bug, status/code-review

#12503 Use close form handler in git compare window to check file dirty state
  plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/CompareViewImpl.java
Labels: kind/bug, selenium/failure, severity/P2, status/code-review, team/ide

#12421 Fix browser crashing issues on workspace loader.
  workspace-loader/src/index.ts
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/json-rpc/json-rpc-client.ts
  workspace-loader/src/json-rpc/websocket-client.ts
Labels: kind/bug, status/code-review

#12461 Fix the old-fashioned sample code (C++).
  plugins/plugin-cpp/che-plugin-cpp-lang-server/src/main/resources/files/default_cpp_content
Labels: kind/bug, status/code-review

#12407 Fix resource leaks.
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/TarUtils.java
  infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerCertificates.java
  wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/search/server/impl/LuceneSearcher.java
Labels: kind/bug, status/code-review

#12529 Fix PerWorkspacePVC strategy
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelperTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategyTest.java
Labels: kind/bug, status/code-review

#12538 Add @JsonIgnoreProperties into PluginMeta to allow more fields in meta.yaml
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginMeta.java
Labels: kind/enhancement, status/code-review

#12465 Refactor PVCs strategies by extracting common functionality
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PodsVolumes.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/SubPathPrefixes.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PodsVolumesTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/SubPathPrefixesTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategyTest.java
Labels: kind/task, status/code-review

#12548 Add workspace ID to secret name (for self signed certs)
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/CertificateProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/CertificateProvisionerTest.java
Labels: kind/enhancement, status/code-review

#12552 Several json schema enhancements to being better documented
  wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileManagerTest.java
Labels: kind/task, status/code-review

#12386 Filter workspace containers like tools and user's
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactoryTest.java
Labels: status/code-review

#12528 Remove project details view, due to Che7 changes
  dashboard/src/app/workspaces/workspace-details/workspace-details-config.ts
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/project-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/project-details.html
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/project-details.styl
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/repository/project-repository-data.ts
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/repository/project-repository.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/repository/project-repository.directive.ts
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/repository/project-repository.html
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-details/repository/project-repository.styl
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-item/project-item.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-item/project-item.html
  selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceProjects.java
Labels: kind/bug, status/code-review

#12556 Add ability to dump values that is bind by CheBootstrap
  core/commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/CheBootstrap.java
Labels: kind/enhancement, status/code-review

#12563 Used non-blocking randomizer for Che master on OpenShift
  deploy/openshift/templates/che-server-template.yaml
Labels: kind/task, status/code-review
