Repository eclipse-che/che, pull requests merged in 2019-12, with the labels that each got.

#15365 Remove the beta status from the che.infra.kubernetes.namespace.allow_user_defined
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: status/code-review

#15379 Backport #15344 - fix NPE when no URL parameter specified for factory
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/FactoryServiceTest.java
Labels: kind/bug, status/code-review, target/branch

#15393 [Selenium] Turn off unstable selenium tests from test suite
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
Labels: kind/task, selenium/failure, status/code-review, team/che-qe

#15388 Remove outdated configuration properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: status/code-review

#15263 Provision proxy settings on init containers
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ProxySettingsProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ProxySettingsProvisionerTest.java
Labels: kind/bug, status/code-review

#15264 Ensure proxy settings are provisioned for init containers
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ProxySettingsProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ProxySettingsProvisionerTest.java
Labels: status/code-review, target/branch

#15413 Fix NPE in devfile schema validator
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceEntityProvider.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileManager.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/DevfileManagerTest.java
Labels: kind/bug, status/code-review

#15427 Update happy-path-workspace.yaml
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/e2e/files/happy-path/happy-path-workspace.yaml
Labels: kind/enhancement, status/code-review

#15441 Fix colliding of parameters between PR check builds
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/task, status/code-review

#15415 Restructurize auth modules and remove reduntant one
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/pom.xml
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/AuthenticationException.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/AuthenticationExceptionMapper.java
  core/commons/che-core-commons-auth/pom.xml
  core/commons/pom.xml
  multiuser/api/che-multiuser-api-authentication-commons/pom.xml
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/filter/MultiUserEnvironmentInitializationFilter.java
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/token/ChainedTokenExtractor.java
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/token/HeaderRequestTokenExtractor.java
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/token/QueryRequestTokenExtractor.java
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/token/RequestTokenExtractor.java
  multiuser/api/che-multiuser-api-authentication-commons/src/test/java/org/eclipse/che/multiuser/api/authentication/commons/filter/MultiUserEnvironmentInitializationFilterTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitializationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitializationFilterTest.java
  multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilter.java
  multiuser/machine-auth/che-multiuser-machine-authentication/src/test/java/org/eclipse/che/multiuser/machine/authentication/server/MachineLoginFilterTest.java
  pom.xml
Labels: status/code-review

#15409 upgrade angular version to 1.7.9
  dashboard/package.json
  dashboard/src/components/widget/editor/che-editor.directive.spec.ts
  dashboard/yarn.lock
Labels: kind/enhancement, status/code-review

#15452 "Happy Path" Update methods from the "e2e" project for simplifying and improve it's work
  .gitignore
  tests/e2e/driver/ContainerInitializer.ts
  tests/e2e/index.ts
  tests/e2e/inversify.types.ts
  tests/e2e/package-lock.json
  tests/e2e/pageobjects/dashboard/NewWorkspace.ts
  tests/e2e/pageobjects/ide/DialogWindow.ts
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/pageobjects/ide/TopMenu.ts
  tests/e2e/pageobjects/ide/WarningDialog.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/task, status/code-review, team/che-qe

#15457 Change redirect of output of maven build-to-file command
  tests/e2e/files/happy-path/happy-path-workspace.yaml
Labels: kind/enhancement, status/code-review

#15465 Listen to message from iframe in order to refresh keycloak token.
  dashboard/src/app/ide/ide-iframe/ide-iframe.service.ts
  dashboard/src/components/api/che-keycloak.factory.ts
Labels: kind/bug, status/code-review

#15446 Fix potential NPE
  core/commons/che-core-commons-tracing/src/main/java/org/eclipse/che/commons/tracing/TracingTags.java
Labels: kind/bug, status/code-review

#15435 Propagate plugin/editor component environment variables
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/WorkspaceConfig.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverBuilder.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/TestObjects.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/DevfileConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/component/ComponentToWorkspaceApplier.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/component/editor/EditorComponentToWorkspaceApplier.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/component/plugin/PluginComponentToWorkspaceApplier.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/WorkspaceConfigImpl.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/devfile/ComponentImpl.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironment.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalEnvironmentFactory.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/InternalMachineConfig.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/convert/component/editor/EditorComponentToWorkspaceApplierTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/convert/component/plugin/PluginComponentToWorkspaceApplierTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/MachineConfigsValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/editor_plugin_component/devfile_editor_plugins.yaml
Labels: kind/enhancement, status/code-review

#15468 Tests E2E: Update E2E test 'InstallCheByOperatorHub' according to changes on UI
  dockerfiles/e2e/README.md
  tests/e2e/TestConstants.ts
  tests/e2e/driver/ContainerInitializer.ts
  tests/e2e/index.ts
  tests/e2e/inversify.types.ts
  tests/e2e/package.json
  tests/e2e/pageobjects/login/MultiUserLoginPage.ts
  tests/e2e/pageobjects/login/OcpLoginByTempAdmin.ts
  tests/e2e/pageobjects/login/RegularUserOcpCheLoginPage.ts
  tests/e2e/pageobjects/openshift/CheLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpWebConsolePage.ts
  tests/e2e/tests/e2e_install_che_operatorhub/InstallCheByOperatorHub.spec.ts
Labels: kind/task, status/code-review, team/che-qe

#15474 Fix Vert.x - default project changed in devfile registry.
  tests/e2e/tests/e2e/JavaVertx.spec.ts
Labels: kind/bug, status/code-review

#15449 Add additional diagnostic for failure when K8s pronounces a pod running
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
Labels: kind/enhancement, status/code-review

#15451 Load test - typescript part
  dockerfiles/e2e/Dockerfile
  dockerfiles/e2e/entrypoint.sh
  tests/e2e/TestConstants.ts
  tests/e2e/driver/CheReporter.ts
  tests/e2e/index.ts
  tests/e2e/inversify.types.ts
  tests/e2e/package.json
  tests/e2e/pageobjects/dashboard/Workspaces.ts
  tests/e2e/tests/load_test/LoadTest.spec.ts
  tests/e2e/utils/workspace/ITestWorkspaceUtil.ts
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/task, status/code-review

#15426 Add Jenkins pipelines for pre-release and nightly testing
  tests/.infra/crw-ci/master/k8s/Jenkinsfile
  tests/.infra/crw-ci/nightly/k8s/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/.infra/crw-ci/pre-release-testing/k8s/Jenkinsfile
Labels: kind/task, status/code-review

#15450 Adding load tests.
  tests/performance/README.md
  tests/performance/create_users.sh
  tests/performance/ftp-server.yaml
  tests/performance/ftp-service.yaml
  tests/performance/load-tests.sh
  tests/performance/pod.yaml
  tests/performance/process-logs.sh
  tests/performance/pvc.yaml
  tests/performance/report-tree.png
  tests/performance/report-user.png
Labels: kind/task, status/code-review

#13364 Enable to set the value `che.workspace.plugin_broker.wait_timeout_min`
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: area/install, status/code-review

#15475 [Selenium] Fix unstable selenium tests from dashboard and organizations packages
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/ProjectSourcePage.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceOverview.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceShare.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceOwnerTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
Labels: kind/task, status/code-review, team/che-qe

#15491 Moving from Codenvy CI to the CentOS CI: Add sripts for CI Jobs
  .ci/cico_build.sh
  .ci/cico_build_nightly.sh
  .ci/cico_build_release.sh
  .ci/cico_common.sh
Labels: status/code-review

#15505 Deploy in one thread
  .ci/cico_common.sh
Labels: status/code-review

#15499 Add cloud-shell to list servers with liveness probes
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/task, status/code-review

#15498 Add spec.selector field in che-jaeger deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/deployment.yaml
Labels: kind/bug, status/code-review

#15516 Fix 'Unknown error has happened, try to reload page' while trying to re-open a workspace
  dashboard/src/app/ide/ide.service.ts
  workspace-loader/package.json
  workspace-loader/src/json-rpc/che-json-rpc-api-service.ts
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/json-rpc/json-rpc-client.ts
  workspace-loader/src/json-rpc/websocket-client.ts
  workspace-loader/src/workspace-loader.ts
  workspace-loader/yarn.lock
Labels: kind/bug, status/code-review

#15067 Added monaco and YAML support to devfile editor
  dashboard/gulp/scripts.js
  dashboard/gulp/styles.js
  dashboard/gulp/unit-tests.js
  dashboard/karma.conf.js
  dashboard/package.json
  dashboard/src/app/factories/create-factory/template-tab/factory-from-template.styl
  dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.ts
  dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
  dashboard/src/app/stacks/stack-details/stack.styl
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.styl
  dashboard/src/app/workspaces/workspace-details/config-import/workspace-config-import.controller.ts
  dashboard/src/app/workspaces/workspace-details/config-import/workspace-config-import.styl
  dashboard/src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.controller.ts
  dashboard/src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.styl
  dashboard/src/app/workspaces/workspace-details/environments/environments.controller.ts
  dashboard/src/app/workspaces/workspace-details/environments/environments.html
  dashboard/src/app/workspaces/workspace-details/environments/environments.styl
  dashboard/src/app/workspaces/workspace-details/export-workspace/dialog/export-tab-dialog.html
  dashboard/src/app/workspaces/workspace-details/export-workspace/dialog/export-workspace-dialog.controller.ts
  dashboard/src/app/workspaces/workspace-details/export-workspace/dialog/export-workspace-dialog.styl
  dashboard/src/app/workspaces/workspace-details/workspace-details.styl
  dashboard/src/app/workspaces/workspace-details/workspace-machines/edit-machine-dialog/edit-machine-dialog.styl
  dashboard/src/app/workspaces/workspaces.styl
  dashboard/src/components/api/che-api-config.ts
  dashboard/src/components/api/che-api.factory.ts
  dashboard/src/components/api/che-devfile.factory.ts
  dashboard/src/components/attribute/attribute-config.ts
  dashboard/src/components/attribute/codemirror/codemirror.directive.ts
  dashboard/src/components/attribute/monaco/monaco.directive.ts
  dashboard/src/components/typings/che.d.ts
  dashboard/src/components/widget/codemirror/codemirror.styl
  dashboard/src/components/widget/editor/che-editor.controller.ts
  dashboard/src/components/widget/editor/che-editor.directive.ts
  dashboard/src/components/widget/editor/che-editor.styl
  dashboard/src/index.ts
  dashboard/src/monaco-env-setup.ts
  dashboard/src/monaco-languages-setup.ts
  dashboard/yarn.lock
Labels: kind/enhancement, status/code-review

#15536 Fix conditional block not properly closed in helm chart template
  deploy/kubernetes/helm/che/templates/configmap.yaml
Labels: kind/bug, status/code-review

#15537 Cherrypick fix to helm chart template
  deploy/kubernetes/helm/che/templates/configmap.yaml
Labels: kind/bug, status/code-review, target/branch

#15538 Set the right plugin registry version in helm chart template
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/values.yaml
Labels: kind/bug, status/code-review, target/branch

#15530 Fix authentication error when non-root path requested
  assembly/assembly-root-war/src/main/webapp/_app/loader.js
Labels: kind/bug, status/code-review

#15535 Fix 'Open IDE' link
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-item/project-item.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-projects/project-item/project-item.html
Labels: kind/bug, status/code-review

#15544 Fix pre-release Jenkinsfile to be compatible with 7.6.0
  tests/.infra/crw-ci/pre-release-testing/k8s/Jenkinsfile
Labels: kind/task, status/code-review

#15553 [Happy Path] Check application readiness before opening the link by the "DialogWindow.waitDialogAndOpenLink" method
  tests/e2e/pageobjects/ide/DialogWindow.ts
Labels: kind/task, status/code-review, team/che-qe

#15550 Update variables in 'TestConstant' file
  tests/e2e/TestConstants.ts
  tests/e2e/driver/ChromeDriver.ts
  tests/e2e/driver/ContainerInitializer.ts
  tests/e2e/index.ts
  tests/e2e/tests/e2e_install_che_operatorhub/InstallCheByOperatorHub.spec.ts
Labels: kind/enhancement, status/code-review

#15549 Fix restarting a workspace from iframe in single-user mode
  dashboard/src/app/ide/ide-iframe/ide-iframe.service.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
Labels: kind/bug, status/code-review

#15573 Fix scripts for release and nightly builds on ci.centos.org
  .ci/cico_build_nightly.sh
  .ci/cico_build_release.sh
  .ci/cico_common.sh
  .ci/set_tag_version_images_linux.sh
  .ci/set_tag_version_images_macos.sh
Labels: kind/bug, status/code-review

#15575 Tests E2E: Update e2e test 'InstallCheByOperatorHub'
  tests/e2e/tests/e2e_install_che_operatorhub/InstallCheByOperatorHub.spec.ts
Labels: kind/task, status/code-review, team/che-qe

#15580 [TS_SELENIUM] Resolve a problem with lose focus during invoking suggestion container inside of the editor
  tests/e2e/pageobjects/ide/Editor.ts
Labels: kind/enhancement, status/code-review, team/che-qe
