Repository eclipse-che/che, pull requests merged in 2020-06, with the labels that each got.

#16358 Create e2e test for checking Openshift plugin
  tests/e2e/TestConstants.ts
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/mocha-connector.opts
  tests/e2e/package.json
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/ide/DialogWindow.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/pageobjects/ide/LeftToolBar.ts
  tests/e2e/pageobjects/ide/OpenDialogWidget.ts
  tests/e2e/pageobjects/ide/OpenWorkspaceWidget.ts
  tests/e2e/pageobjects/ide/OpenshiftPlugin.ts
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/pageobjects/ide/QuickOpenContainer.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: status/code-review

#16895 Add secret provisioner mounted as file or env variable
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesSecrets.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SecretAsContainerResourceProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SecretAsContainerResourceProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
Labels: kind/enhancement, status/code-review

#16763 Lang fixes of log messages.
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/ApiInfoProvider.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequest.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonRequest.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/ContentTypeGuesser.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/FileCleaner.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/UnixProcessManager.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/websocket/impl/BasicWebSocketEndpoint.java
  core/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImpl.java
  core/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplClientTemplate.java
  core/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java
  core/che-core-api-dto/src/test/java/org/eclipse/che/dto/ServerDtoTest.java
  core/che-core-db/src/main/java/org/eclipse/che/core/db/DBTermination.java
  core/che-core-db/src/main/java/org/eclipse/che/core/db/schema/impl/flyway/CustomSqlMigrationResolver.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/FileStoresMeterBinder.java
  core/che-core-metrics-core/src/main/java/org/eclipse/che/core/metrics/MetricsServletModule.java
  core/commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/CheBootstrap.java
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/IoUtil.java
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/execution/ExecutorServiceBuilder.java
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/execution/OutputReader.java
  core/commons/che-core-commons-lang/src/test/java/org/eclipse/che/commons/lang/execution/ExecutorServiceBuilderTest.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/MailSessionProvider.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/CountedRejectedExecutionHandler.java
  core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/CountedThreadFactory.java
  core/commons/che-core-commons-test/src/main/java/org/eclipse/che/commons/test/AssertRetry.java
  core/commons/che-core-commons-xml/src/main/java/org/eclipse/che/commons/xml/Element.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatch.java
Labels: kind/bug, status/code-review

#17093 Adding Quarkus devfile tests
  tests/e2e/tests/devfiles/Quarkus.spec.ts
Labels: kind/task, status/code-review

#17103 Have a common place for QE scripts used in multiple repositories (to avoid duplication)
  tests/.infra/centos-ci/common-qe/README.md
  tests/.infra/centos-ci/common-qe/che-cert-generation.sh
  tests/.infra/centos-ci/common-qe/che-util.sh
  tests/.infra/centos-ci/common-qe/common-qe-configuration.conf
  tests/.infra/centos-ci/common-qe/common-util.sh
  tests/.infra/centos-ci/common-qe/downloader.sh
  tests/.infra/centos-ci/common-qe/installation-util.sh
  tests/e2e/package-lock.json
Labels: kind/task, kind/technical-debt, status/code-review

#17128 Fix the cache forcing filter for UD
  assembly/assembly-dashboard-war/src/main/webapp/WEB-INF/web.xml
Labels: kind/bug, status/code-review

#17137 Skip quarkus
  tests/e2e/tests/devfiles/Quarkus.spec.ts
Labels: status/code-review

#17139 Adding VIDEO_RECORDING=false parameter for load test.
  tests/performance/pod.yaml
Labels: kind/enhancement, status/code-review

#17158 Fix "Happy path" tests failed on "Run application" step because test application was unable to access spring-petclinic-2.3.0.BUILD_SNAPSHOT.jar
  tests/e2e/files/happy-path/happy-path-workspace.yaml
Labels: kind/bug, status/code-review

#17044 Read self-signed certiicate from dedicated secret
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/task, status/code-review

#17161 Backport: Read self-signed certiicate from dedicated secret (to be consistent with operator installer)
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/task, status/code-review, target/branch

#16649 Migration of the che server codebase to Java 11
  .ci/cico_common.sh
  assembly/assembly-che-tomcat8/src/assembly/bin/setenv.sh
  deploy/kubernetes/helm/che/templates/configmap.yaml
  dockerfiles/che/Dockerfile
  pom.xml
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/task, status/code-review

#16810 moved some jsonrpc and websocket logging to TRACE level
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcMessageReceiver.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/RequestDispatcher.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/GsonJsonRpcQualifier.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/websocket/impl/BasicWebSocketEndpoint.java
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/websocket/impl/BasicWebSocketMessageTransmitter.java
Labels: status/code-review

#17160 Add Jenkinsfile for user creation
  tests/.infra/crw-ci/load-tests/JenkinsfileUsers
Labels: kind/enhancement, status/code-review

#17168 mount secrets with subpaths
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SecretAsContainerResourceProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SecretAsContainerResourceProvisionerTest.java
Labels: kind/enhancement, status/code-review

#17195 Added check that controls endpoint name duplication in devfile
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileIntegrityValidator.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileIntegrityValidatorTest.java
Labels: kind/bug, status/code-review

#17193 set read timeout to URLFetcher so it does not hang
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/URLFetcher.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/URLFetcherTest.java
Labels: kind/bug, status/code-review

#17206 fixes #16976 - fix ContainerLogWatch flaky test
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatchTest.java
Labels: kind/bug, status/code-review

#17190 fix typescriptdto test when running with podman
  core/che-core-typescript-dto-maven-plugin/src/it/java/org/eclipse/che/plugin/typescript/dto/TypeScriptDTOGeneratorMojoITest.java
Labels: kind/bug, status/code-review

#17194 Forces to use sources compatible with java8 and runtime java 11
  pom.xml
Labels: status/code-review

#17207 Apache Tomcat upgrade to 8.5.56
  pom.xml
Labels: status/code-review

#17112 Add parts for running Openshift plugin test nightly
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/cico-openshift-connector-test.sh
  tests/e2e/TestConstants.ts
  tests/e2e/pageobjects/ide/OpenshiftPlugin.ts
  tests/e2e/pageobjects/ide/Terminal.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
Labels: kind/task, status/code-review

#17214 Enhance report of load tests
  tests/performance/load-tests.sh
  tests/performance/process-logs.sh
Labels: status/code-review

#17223 Restore default image
  tests/.infra/centos-ci/functional_tests_utils.sh
Labels: status/code-review

#17080 Adding test of Factory URL to devfile test suite.
  tests/e2e/mocha-all-devfiles.opts
Labels: kind/enhancement, status/code-review

#17245 Hotfix missing arg in load tests
  tests/performance/process-logs.sh
Labels: kind/bug, status/code-review

#17227 Che devfile
  devfile.yaml
Labels: kind/enhancement, status/code-review

#17172 Fixing Quarkus devfile tests flakyness
  tests/e2e/tests/devfiles/Quarkus.spec.ts
Labels: kind/bug, status/code-review

#17167 Per-component override of secret mounts and paths
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/devfile/Component.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SecretAsContainerResourceProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/EnvironmentVariableSecretApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/FileSecretApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/KubernetesSecretApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/SecretAsContainerResourceProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/EnvironmentVariableSecretApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/FileSecretApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/SecretAsContainerResourceProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/devfile/ComponentDto.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileIntegrityValidator.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/devfile/ComponentImpl.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/tck/WorkspaceDaoTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/component/devfile_component_with_automount_secrets.yaml
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/7.16.0/1__add_devfile_component_automount_workspace_secrets.sql
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/TestObjectsFactory.java
Labels: kind/task, status/code-review

#17281 Load test - throw error if workspace is not stopped
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: status/code-review
