Repository eclipse-che/che, pull requests merged in 2020-12, with the labels that each got.

#18435 Switch che-e2e:nighlty image to selenium/standalone-chrome:86.0
  dockerfiles/e2e/Dockerfile
Labels: kind/bug, status/code-review

#18425 Allow to replace backslash in usernames during first login
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitializationFilter.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitializationFilterTest.java
Labels: kind/bug, status/code-review

#16616 Enable infrastructure request logging
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
  pom.xml
Labels: lifecycle/frozen, status/code-review

#18505 link to release guide section 2 - manual...
  .github/ISSUE_TEMPLATE/release.md
Labels: status/code-review

#18519 Fix exception if no data in certs config map
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/KubernetesTrustedCAProvisioner.java
Labels: kind/bug, status/code-review

#18506 Adding support for Keycloak admin secret and endpoint-watcher image configuration
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/values.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/enhancement, status/code-review

#18374 Fix git plus ssh test according to latest changes in Theia
  tests/.infra/crw-ci/nightly/k8s/multi-host/Jenkinsfile
  tests/e2e/pageobjects/ide/GitPlugin.ts
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: kind/bug, status/code-review

#17306 Improve git +ssh test
  tests/e2e/utils/VCS/github/GitHubUtil.ts
Labels: kind/task, status/code-review

#18487 Fix JavaSpringboot build task timeout
  tests/e2e/driver/CheReporter.ts
  tests/e2e/tests/devfiles/JavaSpringBoot.spec.ts
Labels: area/qe, kind/bug, kind/periodic-e2e-test, status/code-review, team/che-qe

#18527 fix container cpu resource conversion
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Containers.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/KubernetesSize.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/ContainersTest.java
Labels: kind/bug, status/code-review

#18525 Fixing NPE in the 'KeycloakSettings'
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettings.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettingsTest.java
Labels: kind/bug, status/code-review

#18486 Add possibility to run tests maximized
  tests/e2e/TestConstants.ts
  tests/e2e/driver/ChromeDriver.ts
  tests/e2e/tests/login/Login.spec.ts
  tests/e2e/utils/DriverHelper.ts
Labels: area/qe, kind/enhancement, status/code-review, team/che-qe

#18531 Rework the "ProjectTree.waitProjectImported" method for avoiding project import rejecting
  tests/e2e/TimeoutConstants.ts
  tests/e2e/pageobjects/ide/ProjectTree.ts
Labels: status/code-review

#18528 Adding support for CHE_LIMITS_USER_WORKSPACES_RUN_COUNT and CHE_WORKSPACE_POD_NODE__SELECTOR in helm chart
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/bug, status/code-review

#18423 Bitbucket public repo factories support
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  pom.xml
  wsmaster/che-core-api-factory-bitbucket-server/pom.xml
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerFactoryParametersResolver.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketURLParser.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUrl.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerFactoryParametersResolverTest.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketURLParserTest.java
  wsmaster/pom.xml
Labels: kind/task, status/code-review

#18410 Used images that moved from docker hub to quay for db integration testing
  multiuser/integration-tests/che-multiuser-mysql-tck/pom.xml
  multiuser/integration-tests/che-multiuser-postgresql-tck/pom.xml
  pom.xml
  wsmaster/integration-tests/mysql-tck/pom.xml
  wsmaster/integration-tests/postgresql-tck/pom.xml
Labels: kind/bug, status/code-review

#18551 add cpu and memory request for jwtproxy
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/AbstractJwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/PassThroughProxyProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/PassThroughProxyProvisionerTest.java
Labels: kind/enhancement, status/code-review

#18574 Add missing internal API urls
  deploy/kubernetes/helm/che/templates/configmap.yaml
Labels: kind/bug, status/code-review

#18584 Fix OpenShift plugin test after latest changes
  tests/.infra/centos-ci/nightly/cico-openshift-connector-test.sh
  tests/e2e/TestConstants.ts
  tests/e2e/TimeoutConstants.ts
  tests/e2e/pageobjects/ide/OpenshiftPlugin.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
Labels: area/qe, kind/enhancement, kind/task, status/code-review

#18504 Import all certificates from propagated bundle
  dockerfiles/che/entrypoint.sh
  dockerfiles/che/rhel.Dockerfile
  dockerfiles/keycloak/kc_realm_user.sh
Labels: kind/bug, status/code-review

#18599 [Selenium] Set TS_SELENIUM_HEADLESS property to false
  tests/.infra/centos-ci/nightly/cico-openshift-connector-test.sh
Labels: area/qe, kind/task, status/code-review

#18592 Gh17540 memory request dockerimage
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplierTest.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/dockerimage_component/devfile_dockerimage_component.yaml
Labels: kind/enhancement, status/code-review

#18601 Fix Che server entrypoint script for case of commonly trusted certificate
  dockerfiles/che/entrypoint.sh
Labels: kind/bug, status/code-review

#18600 Added checksums to configmaps to enable pod restart on configmap change.
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/templates/deployment.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
Labels: kind/enhancement, status/code-review

#18603 Revert "Added checksums to configmaps to enable pod restart on config map change
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/templates/deployment.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
Labels: status/code-review

#18608 Added new test constant for workspace stop timeout, 30s by default
  tests/e2e/TimeoutConstants.ts
  tests/e2e/pageobjects/dashboard/Workspaces.ts
Labels: kind/bug, kind/fringe-issue, kind/periodic-e2e-test, status/code-review

#18611 Added checksums to configmaps to enable pod restart on configmap change.
  deploy/kubernetes/helm/che/templates/deployment.yaml
Labels: kind/enhancement, status/code-review

#18563 Fix che-server when used external oidc provider.
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakJwkProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakProfileRetriever.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClient.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettings.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfo.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClientTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettingsTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProviderTest.java
  multiuser/keycloak/che-multiuser-keycloak-user-remover/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakUserRemover.java
  pom.xml
Labels: kind/task, status/code-review

#18631 Fix failing Che when used external OIDC provider. Port to 7.23.x
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakJwkProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakProfileRetriever.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClient.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettings.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfo.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakModule.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClientTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettingsTest.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProviderTest.java
  multiuser/keycloak/che-multiuser-keycloak-user-remover/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakUserRemover.java
  pom.xml
Labels: kind/task, status/code-review, target/branch

#18639 Rename root artifactId id to che-server
  assembly/pom.xml
  core/pom.xml
  infrastructures/pom.xml
  multiuser/pom.xml
  pom.xml
  tests/legacy-e2e/pom.xml
Labels: kind/task, status/code-review

#18629 Setup Sonar check for master and Github pull requests
  .github/workflows/sonar.yaml
  pom.xml
  tests/legacy-e2e/pom.xml
Labels: kind/task, status/code-review

#18612 fix(async-pv): There is only one tag of the image which is latest so there should not be any nightly plug-in
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#18642 fix(async-pv): Avoid to use latest as tag as it may change a lot
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#18585 fix(typo) in README file
  dockerfiles/e2e/README.md
Labels: kind/bug, status/code-review

#18646 🔨 Fix e2e docker image (log output & crooked screencast)
  dockerfiles/e2e/Dockerfile
  dockerfiles/e2e/entrypoint.sh
Labels: kind/bug, status/code-review

#18651 Fix external helm charts links
  deploy/kubernetes/helm/che/requirements.yaml
Labels: kind/bug, status/code-review

#18652 Fix external helm charts links
  deploy/kubernetes/helm/che/requirements.yaml
Labels: kind/bug, status/code-review, target/branch

#18655 Align app, component labels in helm chart and openshift templates
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/ingress.yaml
  deploy/kubernetes/helm/che/custom-charts/che-gateway/templates/role.yaml
  deploy/kubernetes/helm/che/custom-charts/che-gateway/templates/rolebinding.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/ingress.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/endpoints-monitor-role.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/endpoints-monitor-rolebinding.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/ingress.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/keycloak-data-claim.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/keycloak-log-claim.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/service.yaml
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/templates/ingress.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/postgres-data-claim.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/service.yaml
  deploy/kubernetes/helm/che/templates/cluster-role-binding.yaml
  deploy/kubernetes/helm/che/templates/dashboard-ingress.yaml
  deploy/kubernetes/helm/che/templates/exec-role.yaml
  deploy/kubernetes/helm/che/templates/ingress.yaml
  deploy/kubernetes/helm/che/templates/registry-pull-secret.yaml
  deploy/kubernetes/helm/che/templates/workspace-exec-role-binding.yaml
  deploy/kubernetes/helm/che/templates/workspace-service-account.yaml
  deploy/kubernetes/helm/che/templates/workspace-view-role-binding.yaml
  deploy/kubernetes/helm/che/templates/workspace-view-role.yaml
  deploy/openshift/templates/che-devfile-registry.yml
  deploy/openshift/templates/che-plugin-registry.yml
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/che-workspace-service-account.yaml
  deploy/openshift/templates/https/che-route-tls.yaml
  deploy/openshift/templates/https/keycloak-route-tls.yaml
  deploy/openshift/templates/multi/keycloak-template.yaml
  deploy/openshift/templates/multi/postgres-template.yaml
  deploy/openshift/templates/pvc/che-server-pvc.yaml
Labels: kind/task, status/code-review

#18656 Remove sleshchenko from codeowner for some components
  .github/CODEOWNERS
Labels: status/code-review

#18620 Make all configmaps unique in same namespace
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitConfigProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/KubernetesTrustedCAProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SshKeysProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/UniqueNamesProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/GitCredentialStorageFileSecretApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitConfigProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SshKeySecretProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/GitCredentialStorageFileSecretApplierTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
Labels: status/code-review

#18562 Make che update Images from registries at startup
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/configmap.yaml
  deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/templates/configmap.yaml
  deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/templates/deployment.yaml
  deploy/kubernetes/helm/che/templates/configmap.yaml
Labels: kind/question, status/code-review

#18687 [Selenium] Stabilize OpenshiftConnector and GitSsh typescript tests
  tests/e2e/tests/e2e/GitSsh.spec.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
Labels: area/qe, kind/task, status/code-review

#18714 Tests E2E: Update and delete unused files in 'e2e' folder
  tests/e2e/TestConstants.ts
  tests/e2e/TimeoutConstants.ts
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/mocha-che-operatorhub.opts
  tests/e2e/mocha-che-subscribe-operator.opts
  tests/e2e/package.json
  tests/e2e/pageobjects/openshift/OcpWebConsolePage.ts
  tests/e2e/tests/e2e_install_che_operatorhub/InstallCheByOperatorHub.spec.ts
  tests/e2e/tests/e2e_subscribe_che_operatorhub/SubscribeCheByOperatorHub.spec.ts
  tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe
