Repository eclipse-che/che, pull requests merged in 2020-05, with the labels that each got.

#16826 Fix: [InjectOnMemberAndConstructor] Members shouldn't be annotated with @Inject if constructor is already annotated @Inject
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/git/GitReset.java
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
Labels: kind/bug, status/code-review

#16804 che #15906 setting 'che.workspace.stop.role.enabled' to true
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#16829 Adapt automated E2E pre-release tests to check already released Che
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/rc/cico-rc-multiuser-happy-path-test.sh
  tests/.infra/centos-ci/rc/cico-rc-multiuser-integration-tests.sh
  tests/.infra/centos-ci/rc/cico-rc-ocp-oauth-test.sh
  tests/.infra/centos-ci/rc/cico-rc-rolling-strategy-test.sh
  tests/.infra/centos-ci/rc/rc_function_util.sh
  tests/.infra/crw-ci/master/k8s/Jenkinsfile
  tests/.infra/crw-ci/nightly/k8s/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/.infra/crw-ci/pre-release-testing/k8s/Jenkinsfile
Labels: kind/task, status/code-review, target/branch

#16831 Update the "DialogWindow.waitDialog" method
  tests/e2e/files/happy-path/happy-path-workspace.yaml
  tests/e2e/pageobjects/ide/DialogWindow.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/task, status/code-review

#16841 Remove rhopp as code owner from most of directories.
  .github/CODEOWNERS
Labels: status/code-review

#16847 Update the "DialogWindow.waitDialog" method
  tests/e2e/pageobjects/ide/DialogWindow.ts
Labels: kind/task, status/code-review

#16849 [Helm] Make Keycloak admin username and password configurable
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/values.yaml
Labels: kind/enhancement, status/code-review

#16843 setting 'che.workspace.stop.role.enabled' to true
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review, target/branch

#16497 Rebalancing maven module execution order
  assembly/assembly-che-tomcat8/pom.xml
  assembly/assembly-dashboard-war/pom.xml
  assembly/assembly-main/pom.xml
  assembly/assembly-root-war/pom.xml
  assembly/assembly-swagger-war/pom.xml
  assembly/assembly-workspace-loader-war/pom.xml
  assembly/assembly-wsmaster-war/pom.xml
  core/che-core-api-core/pom.xml
  core/che-core-api-dto-maven-plugin/pom.xml
  core/che-core-api-dto/pom.xml
  core/che-core-api-model/pom.xml
  core/che-core-db-vendor-h2/pom.xml
  core/che-core-db-vendor-mysql/pom.xml
  core/che-core-db-vendor-postgresql/pom.xml
  core/che-core-db/pom.xml
  core/che-core-logback/pom.xml
  core/che-core-logback/src/main/java/org/eclipse/che/commons/logback/EnvironmentVariablesLogLevelPropagator.java
  core/che-core-logback/src/main/java/org/eclipse/che/commons/logback/filter/IdentityIdLoggerFilter.java
  core/che-core-logback/src/main/java/org/eclipse/che/commons/logback/filter/RequestIdLoggerFilter.java
  core/che-core-metrics-core/pom.xml
  core/che-core-tracing-core/pom.xml
  core/che-core-tracing-metrics/pom.xml
  core/che-core-tracing-web/pom.xml
  core/che-core-typescript-dto-maven-plugin/pom.xml
  core/commons/pom.xml
  core/pom.xml
  infrastructures/infrastructure-distributed/pom.xml
  infrastructures/infrastructure-distributed/src/main/java/org/eclipse/che/multiuser/api/distributed/JGroupsServiceTermination.java
  infrastructures/infrastructure-distributed/src/main/java/org/eclipse/che/multiuser/api/distributed/WorkspaceStopPropagator.java
  infrastructures/infrastructure-distributed/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/JGroupsWorkspaceStatusCache.java
  infrastructures/infrastructure-distributed/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/ReplicatedMapNotificationAdapter.java
  infrastructures/infrastructure-distributed/src/main/java/org/eclipse/che/multiuser/api/distributed/cache/StatusChangeListener.java
  infrastructures/infrastructure-distributed/src/main/java/org/eclipse/che/multiuser/api/distributed/lock/JGroupsWorkspaceLockService.java
  infrastructures/infrastructure-distributed/src/main/java/org/eclipse/che/multiuser/api/distributed/subscription/DistributedRemoteSubscriptionStorage.java
  infrastructures/infrastructure-distributed/src/test/resources/logback-test.xml
  infrastructures/infrastructure-permission/pom.xml
  infrastructures/infrastructure-permission/src/main/java/org/eclipse/che/multiuser/permission/workspace/infra/kubernetes/BrokerServicePermissionFilter.java
  infrastructures/infrastructure-permission/src/test/java/org/eclipse/che/multiuser/permission/workspace/infra/kubernetes/BrokerServicePermissionFilterTest.java
  infrastructures/infrastructure-permission/src/test/resources/logback-test.xml
  infrastructures/kubernetes/pom.xml
  infrastructures/openshift/pom.xml
  infrastructures/pom.xml
  multiuser/api/pom.xml
  multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
  multiuser/permission/pom.xml
  pom.xml
  wsmaster/che-core-api-factory/pom.xml
  wsmaster/che-core-api-workspace-activity/pom.xml
  wsmaster/pom.xml
Labels: status/code-review

#16839 Make possible to mount not only 'vcs' ssh key but also other type of managed ssh keys
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Warnings.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SshKeysProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SshKeySecretProvisionerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
Labels: status/code-review

#16874 [Selenium] Set Keycloak admin password to 'admin'
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/.infra/centos-ci/nightly/cico-devfiles-test.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-all-tests.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-hot-update-tests.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-stable-selenium-tests.sh
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
  tests/.infra/centos-ci/nightly/ocp-oauth-test.sh
  tests/.infra/centos-ci/rc/rc_function_util.sh
Labels: area/qe, kind/task, status/code-review, team/che-qe

#16880 Used version docker-maven-plugin:0.22.1 that is defined in parent-pom
  multiuser/integration-tests/che-multiuser-postgresql-tck/pom.xml
Labels: kind/bug, status/code-review

#16898 Use new version of Plugin Broker: 3.2.0
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: status/code-review

#16802 Use docker images instead of maven artifact to deliver che-dashboard && che-workspace-loader
  assembly/assembly-dashboard-war/pom.xml
  assembly/assembly-main/pom.xml
  assembly/assembly-main/src/assembly/assembly.xml
  assembly/assembly-workspace-loader-war/pom.xml
  dockerfiles/che/Dockerfile
  dockerfiles/che/Dockerfile.centos
  dockerfiles/che/Dockerfile.openj9
Labels: kind/task, status/code-review

#16921 Remove centos image build from release scripts
  .ci/cico_common.sh
Labels: status/code-review

#16922 Fix devfile tests - use Get Started page
  dockerfiles/e2e/Dockerfile
  dockerfiles/e2e/entrypoint.sh
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/mocha-java-vertx.opts
  tests/e2e/pageobjects/dashboard/GetStarted.ts
  tests/e2e/pageobjects/dashboard/NewWorkspace.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/PythonDjango.spec.ts
  tests/e2e/tests/e2e/GitSsh.spec.ts
  tests/e2e/tests/e2e/WorkspaceCreationAndLsInitialization.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/load_test/LoadTest.spec.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
  tests/e2e/testsLibrary/WorksapceHandlingTests.ts
  tests/e2e/utils/DriverHelper.ts
  tests/e2e/utils/WorkspaceNameHandler.ts
Labels: kind/bug, status/code-review

#16941 Removing waiting for LS initialization to stabilize the tests.
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
Labels: status/code-review

#16901 Adapt automated E2E pre-release tests to verify released Che version
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/rc/cico-rc-multiuser-happy-path-test.sh
  tests/.infra/centos-ci/rc/cico-rc-multiuser-integration-tests.sh
  tests/.infra/centos-ci/rc/cico-rc-ocp-oauth-test.sh
  tests/.infra/centos-ci/rc/cico-rc-rolling-strategy-test.sh
  tests/.infra/centos-ci/rc/rc_function_util.sh
  tests/.infra/crw-ci/master/k8s/Jenkinsfile
  tests/.infra/crw-ci/nightly/k8s/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/.infra/crw-ci/pre-release-testing/k8s/Jenkinsfile
Labels: kind/task, status/code-review

#16947 Switching workspace readyness logic over to preloader
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: status/code-review

#16964 Disable http2 by default for java8
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
Labels: kind/bug, status/code-review

#16948 Implementing test for Golang devfile
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/utils/PreferencesHandler.ts
Labels: kind/task, status/code-review

#16917 [Selenium] Update java selenium tests
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/CreateWorkspaceHelper.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/NewWorkspace.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaIde.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/AccountTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateAndDeleteProjectsTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/CreateWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteRunningWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteStoppingWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportMavenProjectFromGitTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/RenameWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AdminOfParentOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AdminOfSubOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/CreateRootOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationByBulkTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationInListTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/FilterOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/MemberOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/OrganizationMembersTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/RenameOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceMemberTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceOwnerTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/SystemAdminOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/UserEmptyOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/NewWorkspacePageTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsProjectsTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/recreate/RecreateUpdateStrategyTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithEditorTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithStartedWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithWorkspacesStartStopTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/site/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/CheckStoppingWsByTimeoutTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java
  tests/legacy-e2e/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml
  tests/legacy-e2e/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: area/qe, kind/task, status/code-review, team/che-qe

#16979 Change locators according to latest changes in Theia
  tests/e2e/pageobjects/ide/GitPlugin.ts
Labels: kind/bug, status/code-review

#16985 [Selenium] Remove AccountTest from UNDER_REPAIR group
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/AccountTest.java
Labels: area/qe, kind/task, team/che-qe

#16982 Configure separate CPU limit for JWTProxy container;
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/AbstractJwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/PassThroughProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/factory/PassThroughProxyProvisionerFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/PassThroughProxyProvisionerTest.java
Labels: kind/bug, status/code-review

#16986 Remove access tokens and refresh tokens from response logging
  tests/e2e/utils/requestHandlers/CheApiRequestHandler.ts
Labels: status/code-review

#16995 Tests E2E: Update ''OcpLoginPage' to provide login both OCP and OSD
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#16955 Enable to overwrite the organization of che-dashboard and che-workspace-loader.
  dockerfiles/che/Dockerfile
Labels: kind/enhancement, status/code-review

#17006 Implementing NodeJS devfile test
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/NodeJS.spec.ts
  tests/e2e/tests/devfiles/PythonDjango.spec.ts
Labels: kind/task, status/code-review

#16992 Load tests Jenkins job
  dockerfiles/e2e/entrypoint.sh
  tests/.infra/crw-ci/load-tests/Jenkinsfile
  tests/performance/pod.yaml
Labels: status/code-review

#17019 Add NODE_TLS_REJECT_UNAUTHORIZED parameter for a load tests.
  tests/performance/pod.yaml
Labels: kind/enhancement, status/code-review

#17022 Apply var for log level
  tests/.infra/crw-ci/load-tests/Jenkinsfile
Labels: status/code-review

#17011 [Selenium] Change workspace limit for hotupdate tests Jenkins job
  tests/.infra/centos-ci/nightly/cico-multiuser-hot-update-tests.sh
Labels: area/qe, status/code-review, team/che-qe

#16949 update release issue template for...
  RELEASE.md
Labels: area/ci, area/productization, kind/enhancement, status/code-review

#16999 Add test for testing workspace creation via factory URL.
  tests/e2e/mocha-factory.opts
  tests/e2e/package.json
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/tests/e2e/FactoryUrl.spec.ts
Labels: kind/task, status/code-review

#17038 Disable CPU limits by default, allow to disable any type of default limits/requests.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/ContainerResourceProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/KubernetesSize.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/ContainerResourceProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/KubernetesSizeTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/ResourceLimitAttributesProvisioner.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/ResourceLimitAttributesProvisionerTest.java
Labels: kind/bug, status/code-review
