Repository eclipse-che/che, pull requests merged in 2020-01, with the labels that each got.

#15596 [TS_SELENIUM] Update methods for waiting application readiness inside of workspace
  tests/e2e/pageobjects/ide/DialogWindow.ts
  tests/e2e/pageobjects/ide/Ide.ts
Labels: kind/enhancement, team/che-qe

#15386 Refactor plugin brokering process
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesArtifactsBrokerApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarToolingProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/KubernetesBrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesArtifactsBrokerApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/SidecarToolingProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/wsplugins/brokerphases/OpenshiftBrokerEnvironmentFactory.java
Labels: kind/epic, kind/task, status/code-review

#15569 Move to the quay.io
  dashboard/devfile.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/deployment.yaml
  deploy/kubernetes/helm/che/custom-charts/che-keycloak/values.yaml
  deploy/kubernetes/helm/che/custom-charts/che-postgres/values.yaml
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
  deploy/openshift/deploy_che.sh
  deploy/openshift/templates/che-server-template.yaml
  deploy/openshift/templates/multi/keycloak-template.yaml
  deploy/openshift/templates/multi/postgres-template.yaml
  devfile.yaml
  dockerfiles/che/Dockerfile.centos
  dockerfiles/che/Dockerfile.openj9
  workspace-loader/devfile.yaml
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/kubernetes_openshift_component/devfile_kubernetes_component_reference_and_content_as_block.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/kubernetes_openshift_component/devfile_openshift_component_reference_and_content_as_block.yaml
Labels: status/code-review

#15227 Update prometheus and grafana version in requirement.yaml file to be compatible with k8s v1.16
  deploy/kubernetes/helm/che/requirements.yaml
Labels: kind/bug, status/code-review

#15642 Implemented the 'Get Started' page for UD
  dashboard/src/app/dashboard/dashboard-config.ts
  dashboard/src/app/dashboard/last-workspaces/last-workspaces.controller.spec.ts
  dashboard/src/app/dashboard/last-workspaces/last-workspaces.directive.spec.ts
  dashboard/src/app/demo-components/demo-components.controller.ts
  dashboard/src/app/demo-components/demo-components.html
  dashboard/src/app/get-started/get-started-config.ts
  dashboard/src/app/get-started/template-list/template-list.controller.ts
  dashboard/src/app/get-started/template-list/template-list.html
  dashboard/src/app/get-started/template-list/template-list.styl
  dashboard/src/app/get-started/template/template.directive.ts
  dashboard/src/app/get-started/template/template.html
  dashboard/src/app/get-started/template/template.styl
  dashboard/src/app/index.module.ts
  dashboard/src/app/navbar/navbar.controller.ts
  dashboard/src/app/navbar/navbar.html
  dashboard/src/app/stacks/list-stacks/list-stacks.controller.ts
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.styl
  dashboard/src/app/workspaces/list-workspaces/list-workspaces.controller.ts
  dashboard/src/app/workspaces/list-workspaces/list-workspaces.html
  dashboard/src/components/utils/random.service.ts
  dashboard/src/components/widget/list/che-list-header.html
  dashboard/src/components/widget/list/che-list-header.styl
  dashboard/src/components/widget/toolbar/che-toolbar.styl
  dashboard/yarn.lock
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/DashboardFactories.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceShare.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/WorkspacesListTest.java
Labels: status/code-review

#15692 [Happy Path] Add checking of the deployed application readiness in the "Happy Path" scenario
  tests/e2e/index.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/pageobjects/ide/PreviewWidget.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/enhancement, team/che-qe

#15706 Fix icon links for UD
  dashboard/src/app/get-started/template-list/template-list.controller.ts
  dashboard/src/app/stacks/list-stacks/list-stacks.controller.ts
Labels: kind/bug, status/code-review

#15677 Add ability to set up Che workspace and postgress pvc class names using helm.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/postgres-data-claim.yaml
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/enhancement, status/code-review

#15725 The "PreviewWidget.waitUrl" method has locator not applicable for all stacks
  tests/e2e/pageobjects/ide/PreviewWidget.ts
Labels: kind/enhancement, status/code-review

#15619 Extracting common test methods
  tests/e2e/driver/CheReporter.ts
  tests/e2e/generateIndex.sh
  tests/e2e/index.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
  tests/e2e/testsLibrary/LsTests.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
  tests/e2e/testsLibrary/WorksapceHandlingTests.ts
Labels: status/code-review

#15688 Don't fail in `deleteIfManaged` when the namespace/project is not managed
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectTest.java
Labels: kind/bug, status/code-review

#15689 Fix the update validation error while stopping an idling workspace.
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/K8sInfraNamespaceWsAttributeValidator.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/K8sInfraNamespaceWsAttributeValidatorTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceAttributeValidator.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceValidator.java
Labels: kind/bug, status/code-review

#15754 [TS_SELENIUM] Create a method for expanding project tree according to the provided path
  tests/e2e/pageobjects/ide/ProjectTree.ts
Labels: kind/enhancement, status/code-review, team/che-qe

#15414 Update CentOS dockerfile
  dockerfiles/che/Dockerfile.centos
Labels: kind/bug, status/code-review

#15767 Replace hardcoded prometheus datasource with template
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
Labels: status/code-review

#15704 [UD] view and change target kubernetes namespace when creating a new workspace
  dashboard/src/app/factories/load-factory/load-factory.controller.ts
  dashboard/src/app/get-started/template-list/template-list.controller.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.controller.ts
  dashboard/src/app/workspaces/create-workspace/create-workspace.html
  dashboard/src/app/workspaces/create-workspace/create-workspace.service.ts
  dashboard/src/app/workspaces/create-workspace/devfile-change-event-data.ts
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.controller.ts
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.directive.ts
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.html
  dashboard/src/app/workspaces/create-workspace/kubernetes-namespace-selector/kubernetes-namespace-selector.controller.ts
  dashboard/src/app/workspaces/create-workspace/kubernetes-namespace-selector/kubernetes-namespace-selector.directive.ts
  dashboard/src/app/workspaces/create-workspace/kubernetes-namespace-selector/kubernetes-namespace-selector.html
  dashboard/src/app/workspaces/create-workspace/kubernetes-namespace-selector/kubernetes-namespace-selector.styl
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.controller.ts
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.directive.ts
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.html
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.html
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.styl
  dashboard/src/app/workspaces/workspaces-config.ts
  dashboard/src/components/api/che-api-config.ts
  dashboard/src/components/api/che-api.factory.ts
  dashboard/src/components/api/che-kubernetes-namespace.factory.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  dashboard/src/components/typings/che.d.ts
  dashboard/src/components/widget/filter-selector/che-filter-selector.controller.ts
Labels: kind/enhancement, status/code-review

#15774 Fix the URL to devfile doc
  dashboard/src/components/branding/che-branding.factory.ts
Labels: kind/bug, status/code-review

#15765 Set current GitHub repository URL and branch into devfile projects if they're missing or didn't match
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubSourceStorageBuilder.java
  wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java
Labels: kind/enhancement, status/code-review

#15768 Set default organization to 'quay.io/eclipse' instead of 'eclipse'
  dockerfiles/build.include
  tests/.infra/crw-ci/nightly/k8s/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/.infra/crw-ci/pre-release-testing/k8s/Jenkinsfile
  tests/legacy-e2e/che-selenium-test/src/test/resources/projects/nodejs-with-yaml/deployment.yaml
Labels: status/code-review

#15784 Fix workspaces for UD
  dashboard/src/app/get-started/template-list/template-list.controller.ts
  dashboard/src/app/get-started/template-list/template-list.html
  dashboard/src/app/get-started/template-list/template-list.styl
  dashboard/src/app/navbar/navbar.controller.ts
  dashboard/src/app/navbar/navbar.html
  dashboard/src/app/navbar/recent-workspaces/recent-workspaces.controller.ts
  dashboard/src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.controller.ts
  dashboard/src/app/workspaces/list-workspaces/list-workspaces.controller.ts
  dashboard/src/app/workspaces/list-workspaces/list-workspaces.html
  dashboard/src/app/workspaces/list-workspaces/workspace-item/workspace-item.controller.ts
  dashboard/src/app/workspaces/list-workspaces/workspace-item/workspace-item.html
  dashboard/src/app/workspaces/workspace-details/workspace-details-config.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.styl
  dashboard/src/components/api/che-factory.factory.ts
  dashboard/src/components/api/test/che-http-backend.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  dashboard/src/components/api/workspace/che-workspace.spec.ts
  dashboard/src/components/widget/footer/che-footer.styl
  dashboard/src/components/widget/list/che-list-item.styl
Labels: kind/bug, status/code-review

#15775 Propagate default value for persistVolumes for clients
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/task, status/code-review

#15813 Fix nightly build on CentOS CI
  .ci/cico_common.sh
Labels: kind/bug, status/code-review

#15777 [UD] Added ability to disable some menu items and corresponding routes
  dashboard/README.md
  dashboard/src/app/administration/administration-config.service.ts
  dashboard/src/app/administration/administration-config.ts
  dashboard/src/app/dashboard/dashboard-config.ts
  dashboard/src/app/factories/factories-config.ts
  dashboard/src/app/factories/factory-config.service.ts
  dashboard/src/app/factories/factory-details/factory-details-config.ts
  dashboard/src/app/get-started/get-started-config.service.ts
  dashboard/src/app/get-started/get-started-config.ts
  dashboard/src/app/navbar/navbar.controller.ts
  dashboard/src/app/navbar/navbar.html
  dashboard/src/app/organizations/organizations-config.service.spec.ts
  dashboard/src/app/organizations/organizations-config.service.ts
  dashboard/src/app/organizations/organizations-config.ts
  dashboard/src/app/stacks/stacks-config.service.ts
  dashboard/src/app/stacks/stacks-config.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
  dashboard/src/components/branding/che-branding-config.ts
  dashboard/src/components/branding/che-branding.factory.ts
  dashboard/src/components/branding/che-dashboard-configuration.service.ts
  dashboard/src/components/typings/che.d.ts
Labels: kind/task, status/code-review

#15823 E2E: Update e2e java selenium tests according new behaviour on UD
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/Workspaces.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceMemberTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/recreate/RecreateUpdateStrategyTest.java
Labels: area/qe, kind/task, status/code-review, team/che-qe

#15832 Resolve relative links to icons on Create Workspace page
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/devfile-selector/devfile-selector.controller.ts
Labels: kind/enhancement, status/code-review

#15827 [TS_SELENIUM] Simplify "inversify" modules binding
  tests/e2e/driver/ContainerInitializer.ts
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
Labels: kind/enhancement, status/code-review, team/che-qe

#15843 Work around start test workspace failure in Happy path tests
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/e2e/TestConstants.ts
Labels: kind/bug, status/code-review

#15807 Update plugin brokers to version 3.1.0
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: area/plugin-broker, kind/enhancement, status/code-review

#15432 Ingress/Route per plugin endpoint
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/ServerConfig.java
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/runtime/Server.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/PreviewUrlExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/DefaultHostExternalServiceExposureStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServiceExposureStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/MultiHostExternalServiceExposureStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/SingleHostExternalServiceExposureStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/DefaultSecureServersFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/SecureServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/DefaultHostExternalServiceExposureStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/MultiHostExternalServiceExposureStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftExternalServerExposer.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftServerExposureStrategy.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftExternalServerExposerTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/InternalRuntime.java
Labels: kind/enhancement, kind/task, status/code-review, team/platform

#15828 Prevent session already invalidated error when re-logging in with different user
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/filter/MultiUserEnvironmentInitializationFilter.java
  multiuser/api/che-multiuser-api-authentication-commons/src/test/java/org/eclipse/che/multiuser/api/authentication/commons/filter/MultiUserEnvironmentInitializationFilterTest.java
Labels: kind/bug, status/code-review

#15793 Try to recover from invalid namespace names
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/K8sInfraNamespaceWsAttributeValidator.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/NamespaceNameValidator.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/NamespaceNameValidatorTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategyTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfrastructure.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/RuntimeInfrastructure.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
Labels: kind/bug, status/code-review

#15830 Refactor upstream tests to allow easier devfile implementation
  tests/e2e/pageobjects/ide/DialogWindow.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/task, status/code-review

#15668 Provides RELEASE.md file with the release instructions.
  RELEASE.md
Labels: status/code-review

#15833 Fix resolving the User Dashboard route
  dashboard/src/app/dashboard/dashboard-config.ts
  dashboard/src/app/navbar/navbar.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details-config.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/AddWorkspaceToOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceMemberTest.java
Labels: kind/bug, status/code-review

#15757 Given a URL plugin reference in CHE_WORKSPACE_DEFAULT__EDITOR_PLUGINS, resolve and install it
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/DefaultEditorProvisioner.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/convert/DefaultEditorProvisionerTest.java
Labels: kind/enhancement, status/code-review

#15818 Add the ephemeral mode toggle to create workspace screen
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.controller.ts
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.html
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.styl
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/project-source-selector/project-source-selector.controller.ts
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.controller.ts
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.html
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.styl
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.html
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  dashboard/src/components/typings/che.d.ts
Labels: kind/task, status/code-review

#15861 #15860 release process issue...
  RELEASE.md
Labels: status/code-review

#15429 Add a configuration property to the helm chart to not define probes
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/enhancement, status/code-review

#15879 Fix CI release script
  .ci/set_tag_version_images_linux.sh
Labels: kind/bug, status/code-review

#15896 Moving from Codenvy CI to the CentOS CI: add script for devtools-che-che-pullrequest-test project
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/.infra/centos-ci/functional_tests_utils.sh
Labels: status/code-review, team/che-qe
