Repository eclipse-che/che, pull requests merged in 2020-03, with the labels that each got.

#16162 watch mkdir logs
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/LogWatcher.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/WorkspaceVolumesStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/PrepareStorage.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/LogWatcherTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelperTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategyTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/UniqueWorkspacePVCStrategyTest.java
Labels: kind/enhancement, status/code-review

#15977 Add ability to set CPU limits/requests on the plugin containers
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/MachineConfig.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/ContainerResourceProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/RamLimitRequestProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Containers.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/KubernetesSize.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverBuilder.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesEnvironmentProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/ContainerResourceProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/ContainersTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolverTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisioner.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftEnvironmentProvisionerTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactoryTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/MemoryAttributeProvisioner.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/environment/ResourceLimitAttributesProvisioner.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheContainer.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/MemoryAttributeProvisionerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/environment/ResourceLimitAttributesProvisionerTest.java
Labels: kind/enhancement, status/code-review

#16128 Change the default jwtproxy image to the latest one.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#16203 Fix Java based devfile tests.
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/testsLibrary/LsTests.ts
  tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts
Labels: kind/bug, status/code-review

#16037 fix owners of stages; explain stage...
  RELEASE.md
Labels: area/ci, area/productization, kind/bug, status/code-review

#16213 Create "Get Started" page object in E2E typescript selenium tests
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/dashboard/GetStarted.ts
Labels: kind/task, status/code-review

#16207 Fix: The termination grace period is set to maximum explicitly defined values, otherwise, it is set to null.
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/PodMerger.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/PodMergerTest.java
Labels: kind/bug, status/code-review

#15963 Apply OpenShift OAuth provider
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  deploy/kubernetes/helm/che/templates/configmap.yaml
  deploy/kubernetes/helm/che/values.yaml
  deploy/openshift/templates/che-server-template.yaml
  pom.xml
  wsmaster/che-core-api-auth-openshift/pom.xml
  wsmaster/che-core-api-auth-openshift/src/main/java/org/eclipse/che/security/oauth/OpenShiftOAuthAuthenticator.java
  wsmaster/che-core-api-auth-openshift/src/main/java/org/eclipse/che/security/oauth/OpenShiftOAuthModule.java
  wsmaster/pom.xml
Labels: kind/task, status/code-review

#16006 Add an ability to add public key certificate to Java trust store
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
  dockerfiles/che/entrypoint.sh
Labels: kind/task, status/code-review

#16108 Fix latest image tag for release
  .ci/cico_common.sh
Labels: kind/bug, status/code-review

#16223 (7.9.x)Fix factories routes for UD
  dashboard/src/app/factories/factories-config.ts
Labels: kind/bug, status/code-review, target/branch

#16226 [TS_SELENIUM] Create method for clicking to "Get Started" button on dashboard.
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/dashboard/GetStarted.ts
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts
Labels: kind/enhancement, kind/task, status/code-review

#16238 Fix template styles
  dashboard/src/app/get-started/template/template.styl
Labels: kind/enhancement, status/code-review

#16242 Fix template styles
  dashboard/src/app/get-started/template/template.styl
Labels: kind/enhancement, status/code-review, target/branch

#16257 [TS_SELENIUM] Rework a "Terminal.getText" method for avoiding fails
  tests/e2e/pageobjects/ide/Terminal.ts
Labels: kind/task, status/code-review

#16279 Tests E2E: Update pageobjects to login page both OCP 4.3 and OCP 4.4
  tests/e2e/index.ts
  tests/e2e/pageobjects/login/OcpUserLoginPage.ts
  tests/e2e/pageobjects/login/RegularUserOcpCheLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
  tests/e2e/tests/e2e_subscribe_che_operatorhub/SubscribeCheByOperatorHub.spec.ts
Labels: kind/task, status/code-review, team/che-qe

#16276 Fix incorrect link to devfile docs in the dashboard
  dashboard/src/assets/branding/product.json
Labels: kind/bug, status/code-review

#16210 count workspace starts in debug mode
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceStartAttemptsMeterBinder.java
  wsmaster/che-core-api-metrics/src/test/java/org/eclipse/che/api/metrics/WorkspaceStartAttemptsMeterBinderTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/event/WorkspaceStatusEvent.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
Labels: kind/enhancement, status/code-review

#16263 Runtme log metrics
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/RuntimeLogMeterBinder.java
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WsMasterMetricsModule.java
Labels: kind/enhancement, status/code-review

#16295 Workaround to run E2E Happy path tests pipelines against Eclipse Che without TLS support
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/.infra/crw-ci/pre-release-testing/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#16294 Fallback to firstTimestamp if lastTimestamp is not set when handling event
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
Labels: kind/bug, status/code-review

#16289 Generate broker container names more sensibly
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java
Labels: kind/bug, status/code-review

#16290 Cherry-pick #16289 to 7.9.x release branch
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java
Labels: status/code-review, target/branch

#16222 Fix factories routes for UD
  dashboard/README.md
  dashboard/src/app/factories/factories-config.ts
Labels: kind/bug, status/code-review

#16285 Logwatchers metrics
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
  infrastructures/infrastructure-metrics/pom.xml
  infrastructures/infrastructure-metrics/src/main/java/org/eclipse/che/workspace/infrastructure/metrics/CurrentLogwatchersMeterBinder.java
  infrastructures/infrastructure-metrics/src/main/java/org/eclipse/che/workspace/infrastructure/metrics/InfrastructureMetricsModule.java
  infrastructures/infrastructure-metrics/src/test/java/org/eclipse/che/workspace/infrastructure/metrics/CurrentLogwatchersMeterBinderTest.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatch.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/LogWatcher.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/event/WatchLogStartedEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/event/WatchLogStoppedEvent.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/RuntimeEventsPublisher.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatchTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/LogWatcherTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelperTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBrokerTest.java
  infrastructures/pom.xml
  pom.xml
Labels: kind/enhancement, status/code-review

#16324 Disable Eclipse Che TLS mode in E2E tests on ci.centos
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-all-tests.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-hot-update-tests.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-stable-selenium-tests.sh
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
  tests/.infra/centos-ci/nightly/ocp-oauth-test.sh
  tests/.infra/centos-ci/rc/rc_function_util.sh
  tests/.infra/crw-ci/master/k8s/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/.infra/crw-ci/pre-release-testing/k8s/Jenkinsfile
Labels: kind/task, status/code-review

#16332 Fix refreshing of token after workspace start
  workspace-loader/src/workspace-loader.ts
Labels: kind/bug, status/code-review

#16319 [UD] Avoid unnecessary redirection while checking if user is authorized
  dashboard/src/app/index.module.ts
Labels: kind/bug, status/code-review

#16333 Cherry-pick: Fix refreshing of token after workspace start
  workspace-loader/src/workspace-loader.ts
Labels: kind/bug, status/code-review, target/branch

#16334 cherry-pick: [UD] Avoid unnecessary redirection while checking if user is authorized
  dashboard/src/app/index.module.ts
Labels: status/code-review, target/branch

#16339 fix race-condition sensitive logwatcher test
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatchTest.java
Labels: kind/bug, status/code-review

#16351 Workspace loader moved to individual Github repository
  pom.xml
  workspace-loader/.dockerignore
  workspace-loader/.gitignore
  workspace-loader/Dockerfile
  workspace-loader/assembly.xml
  workspace-loader/devfile.yaml
  workspace-loader/package.json
  workspace-loader/pom.xml
  workspace-loader/src/custom.d.ts
  workspace-loader/src/index.html
  workspace-loader/src/index.ts
  workspace-loader/src/json-rpc/che-json-rpc-api-service.ts
  workspace-loader/src/json-rpc/che-json-rpc-master-api.ts
  workspace-loader/src/json-rpc/json-rpc-client.ts
  workspace-loader/src/json-rpc/util.ts
  workspace-loader/src/json-rpc/websocket-client.ts
  workspace-loader/src/keycloak-loader.ts
  workspace-loader/src/loader/loader.ts
  workspace-loader/src/style.css
  workspace-loader/src/workspace-loader.ts
  workspace-loader/test/mock.js
  workspace-loader/test/preprocessor.js
  workspace-loader/test/test.spec.ts
  workspace-loader/tsconfig.json
  workspace-loader/tsfmt.json
  workspace-loader/tslint.json
  workspace-loader/webpack.common.js
  workspace-loader/webpack.dev.js
  workspace-loader/webpack.prod.js
  workspace-loader/yarn.lock
Labels: kind/task, status/code-review

#16297 Adding more logging levels to the utils/Logger class
  tests/e2e/utils/Logger.ts
Labels: kind/enhancement, status/code-review

#16357 Removing duplicate method Ide.waitIdeFrameAndSwitchOnIy
  tests/e2e/pageobjects/ide/Ide.ts
Labels: status/code-review

#16293 Fix the self-signed certificate error page
  dashboard/src/app/index.module.ts
  dashboard/src/app/index.styl
  dashboard/src/assets/branding/che-logo.svg
Labels: kind/task, status/code-review

#16369 Test E2E: Delete redundant steps from 'InstallCheByOperatorHub' test
  tests/e2e/pageobjects/openshift/OcpWebConsolePage.ts
  tests/e2e/tests/e2e_install_che_operatorhub/InstallCheByOperatorHub.spec.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#16347 Handle numeric versions for referenced plugins
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/PluginFQNParser.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/wsplugins/PluginFQNParserTest.java
Labels: kind/bug, status/code-review

#16376 Remove deploy.sh
  deploy/openshift/Readme.md
  deploy/openshift/deploy_che.sh
  deploy/openshift/ocp.sh
Labels: kind/task, status/code-review

#16378 Added fallback in case if firstTimestamp and lastTimeStamp both null
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
Labels: kind/bug, status/code-review

#16388 Improve the error messages thrown when we fail to determine whether a namespace/project is managed.
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
Labels: kind/bug, status/code-review

#16157 Revamped Get Started page
  dashboard/gulp/build.js
  dashboard/package.json
  dashboard/src/app/get-started/get-started-config.ts
  dashboard/src/app/get-started/get-started.controller.ts
  dashboard/src/app/get-started/get-started.html
  dashboard/src/app/get-started/get-started.styl
  dashboard/src/app/get-started/sample-card/sample-card.directive.ts
  dashboard/src/app/get-started/sample-card/sample-card.html
  dashboard/src/app/get-started/sample-card/sample-card.styl
  dashboard/src/app/get-started/template-list/template-list.controller.ts
  dashboard/src/app/get-started/template-list/template-list.html
  dashboard/src/app/get-started/template-list/template-list.styl
  dashboard/src/app/get-started/template/template.styl
  dashboard/src/app/get-started/toolbar/get-started-toolbar.component.ts
  dashboard/src/app/get-started/toolbar/get-started-toolbar.controller.ts
  dashboard/src/app/get-started/toolbar/get-started-toolbar.html
  dashboard/src/app/get-started/toolbar/get-started-toolbar.styl
  dashboard/src/components/branding/branding.constant.ts
  dashboard/src/components/branding/che-branding.ts
  dashboard/src/components/che-pf-widget/button/che-pf-secondary-button.directive.ts
  dashboard/src/components/che-pf-widget/button/che-pf-secondary-button.html
  dashboard/src/components/che-pf-widget/che-pf-widget.config.ts
  dashboard/src/components/che-pf-widget/input/che-pf-input.ts
  dashboard/src/components/che-pf-widget/masthead/che-pf-masthead.directive.ts
  dashboard/src/components/che-pf-widget/masthead/che-pf-masthead.html
  dashboard/src/components/che-pf-widget/masthead/che-pf-masthead.styl
  dashboard/src/components/che-pf-widget/page-main-area/che-pf-page-main-area.directive.ts
  dashboard/src/components/che-pf-widget/page-main-area/che-pf-page-main-area.html
  dashboard/src/components/che-pf-widget/page-main-area/che-pf-page-main-area.styl
  dashboard/src/components/che-pf-widget/page-main-section/che-pf-page-main-section.directive.ts
  dashboard/src/components/che-pf-widget/switch/che-pf-switch.directive.ts
  dashboard/src/components/che-pf-widget/switch/che-pf-switch.html
  dashboard/src/components/che-pf-widget/text-input/che-pf-text-input.directive.ts
  dashboard/src/components/che-pf-widget/text-input/che-pf-text-input.html
  dashboard/src/components/che-pf-widget/text-input/che-pf-text-input.spec.ts
  dashboard/src/components/components-config.ts
  dashboard/src/components/typings/che.d.ts
  dashboard/src/components/utils/register.ts
  dashboard/src/index.html
  dashboard/yarn.lock
Labels: kind/task, status/code-review

#16394 Update jwtproxy tag to include loopback fix
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#16380 [UD] Detect self-signed certificate issue with Plugin/Devfile Registries
  dashboard/src/app/index.module.ts
  dashboard/src/components/api/test/che-http-backend.ts
  dashboard/src/components/service/global-warning-banner.service.ts
  dashboard/src/components/service/registry-checking.service.ts
  dashboard/src/components/service/service-config.ts
  dashboard/src/components/typings/che.d.ts
  dashboard/src/components/widget/global-warning-banner/global-warning-banner.directive.ts
  dashboard/src/components/widget/global-warning-banner/global-warning-banner.html
  dashboard/src/components/widget/global-warning-banner/global-warning-banner.styl
  dashboard/src/components/widget/widget-config.ts
  dashboard/src/index.html
Labels: kind/enhancement, status/code-review

#16327 Restart workspaces in debug mode after startup failure
  dashboard/src/app/ide/ide.controller.ts
  dashboard/src/app/ide/ide.service.ts
  dashboard/src/app/navbar/recent-workspaces/recent-workspaces.controller.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
Labels: kind/enhancement, status/code-review

#16406 Add a possibility to set product version from the product.json
  dashboard/src/components/branding/branding.constant.ts
  dashboard/src/components/branding/che-branding.ts
  dashboard/src/index.html
Labels: kind/task, status/code-review, target/branch

#16405 Add a possibility to set product version from the product.json
  dashboard/src/components/branding/branding.constant.ts
  dashboard/src/components/branding/che-branding.ts
  dashboard/src/index.html
Labels: kind/task, status/code-review

#16420 gitignore dashboard war overlays folder
  .gitignore
Labels: status/code-review

#16419 Sync Dockerfiles format with che-plugin-broker repository
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: status/code-review

#16386 Add volumes support in cheEditor/chePlugin components
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/editor_plugin_component/devfile_editor_plugins.yaml
Labels: kind/enhancement, status/code-review

#16424 Referencing to che-dev@eclipse.org in the CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: kind/bug, status/code-review

#16430 Update CONTRIBUTING.md with new location of dashboard and workspace loader
  CONTRIBUTING.md
Labels: kind/enhancement, status/code-review

#16345 Upgrade kubernetes-client to 4.9.0
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/PodMerger.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesObjectUtil.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesWorkspaceServiceAccount.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PerWorkspacePVCStrategy.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/AbstractJwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Containers.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/ContainersTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftEnvironmentFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftWorkspaceServiceAccount.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
Labels: kind/task, status/code-review

#16438 fix logwatch flaky tests
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatchTest.java
Labels: kind/bug, status/code-review

#16443 [Selenium] Login to Che by Openshift OAuth
  tests/e2e/pageobjects/login/RegularUserOcpCheLoginPage.ts
  tests/e2e/pageobjects/openshift/CheLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
Labels: kind/task, status/code-review, team/che-qe

#16444 Add warning notifier for non-TLS installation mode
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/NonTlsDistributedClusterModeNotifier.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
Labels: kind/bug, status/code-review

#16459 Propagate component's RegistryURL via DTO
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java
Labels: kind/bug, status/code-review

#16447 feat(dockerfile): Bump openjdk version to latest
  dockerfiles/che/Dockerfile
  dockerfiles/che/Dockerfile.centos
Labels: status/code-review

#16460 Validate uniqueness of environment variable names in devfile components;
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileIntegrityValidator.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileIntegrityValidatorTest.java
Labels: kind/bug, status/code-review

#16467 Remove Factory and Dashboard menu checks from Dashboard.ts
  tests/e2e/pageobjects/dashboard/Dashboard.ts
Labels: kind/task, status/code-review

#16440 fix workspace count metric
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/InmemoryWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/JpaWorkspaceActivityDao.java
  wsmaster/che-core-api-workspace-activity/src/test/java/org/eclipse/che/api/workspace/activity/spi/tck/WorkspaceActivityDaoTest.java
  wsmaster/che-core-sql-schema/src/main/resources/che-schema/7.11.0/1__update_inconsistent_stopped_workspace_activities.sql
Labels: kind/bug, status/code-review

#16433 Add release script to enable automation of certain release steps
  .ci/cico_common.sh
  .ci/set_tag_version_images_linux.sh
  RELEASE.md
  make-release.sh
Labels: kind/enhancement, status/code-review

#16468 Add vscode-task and vscode-launch as command type example
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
Labels: kind/bug, status/code-review

#16449 Allow configuring ImagePullPolicy for some workspace components
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelperTest.java
  infrastructures/kubernetes/src/test/resources/devfile/petclinic.yaml
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/devfile/OpenshiftComponentToWorkspaceApplier.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/devfile/OpenshiftComponentToWorkspaceApplierTest.java
Labels: kind/task, status/code-review

#16486 Update plugin brokers to v3.1.2
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#16492 (7.9.x)Fix the self-signed certificate error page
  dashboard/src/app/index.module.ts
  dashboard/src/app/index.styl
  dashboard/src/assets/branding/che-logo.svg
Labels: kind/task, status/code-review, target/branch

#16493 Fix build result link in readme file
  README.md
Labels: kind/bug, status/code-review

#16495 [Selenium] Use TS_OCP_LOGIN_PAGE_PROVIDER_TITLE constant for identity provider name
  tests/e2e/pageobjects/login/RegularUserOcpCheLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
Labels: kind/task, status/code-review, team/che-qe
