Repository eclipse-che/che, pull requests merged in 2020-02, with the labels that each got.

#15889 [UD] Added ability to pre-fetch resources defined in configuration
  dashboard/README.md
  dashboard/src/app/index.module.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
  dashboard/src/components/branding/che-branding.factory.ts
  dashboard/src/components/service/resource-fetcher/resource-fetcher.service.ts
  dashboard/src/components/service/service-config.ts
Labels: kind/task, status/code-review

#15875 clean up release issue template
  RELEASE.md
Labels: status/code-review

#15883 Update RELEASE.md
  RELEASE.md
Labels: kind/enhancement, status/code-review

#15909 [TS_SELENIUM] Create the "NotificationCenter" pageobject
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/pageobjects/ide/NotificationCenter.ts
Labels: kind/enhancement, status/code-review

#15886 Turn on E2E tests which check restore of browser's tabs
  tests/.infra/crw-ci/nightly/k8s/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
Labels: kind/bug, status/code-review

#15508 Provision environment variables for initContainers of chePlugin/cheEditor
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/EnvVars.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/KubernetesPluginsToolingApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
Labels: kind/enhancement, status/code-review

#15894 Recover runtimes in multi-thread friendly manner
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
Labels: kind/bug, status/code-review

#15933 reset EnvironmentContext between test to avoid influence one test on another
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
Labels: status/code-review

#15948 [TS_SELENIUM] Fix the logical mistake in the "Editor.ts" pageobject leads to "StaleElementReference" error
  tests/e2e/pageobjects/ide/Editor.ts
Labels: kind/task, status/code-review

#15941 Create script for launching java selenium OCP OAuth test
  tests/.infra/centos-ci/nightly/ocp-oauth-test.sh
Labels: status/code-review

#15935 Add script for the launching nightly job with HappyPath scenario
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
Labels: kind/enhancement, status/code-review

#15905 [Selenium] stabilize selenium tests
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/.infra/centos-ci/functional_tests_utils.sh
Labels: status/code-review, team/che-qe

#15950 Use che-bot GitHub token when starting minishift to prevent GitHub AP…
  tests/.infra/centos-ci/functional_tests_utils.sh
Labels: status/code-review

#15734 Update testNG to more actual version (7.0.0)
  multiuser/api/che-multiuser-api-resource/src/test/java/org/eclipse/che/multiuser/resource/api/type/AbstractExhaustibleResourceTest.java
  tests/legacy-e2e/pom.xml
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
Labels: kind/enhancement, status/code-review

#15938 Add script for launching all scope of java selenium nightly tests
  tests/.infra/centos-ci/nightly/cico-multiuser-all-tests.sh
Labels: kind/enhancement, status/code-review

#15937 Add script for launching stable selenium nightly tests
  tests/.infra/centos-ci/nightly/cico-multiuser-stable-selenium-tests.sh
Labels: kind/enhancement, status/code-review

#15955 Ensure cascade removal is working correctly in JpaKubernetesMachineCache and JpaKubernetesRuntimeStateCache
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/jpa/JpaKubernetesRuntimeStateCache.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/KubernetesMachinesCacheTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/cache/tck/KubernetesRuntimeStateCacheTest.java
  wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
Labels: kind/bug, status/code-review

#15907 [UD] Make some features togglable, add optional FAQ button
  dashboard/README.md
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.controller.ts
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.html
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.controller.ts
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.html
  dashboard/src/app/workspaces/workspace-details/workspace-details.directive.spec.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.service.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.html
  dashboard/src/components/branding/che-branding.factory.ts
  dashboard/src/components/branding/che-dashboard-configuration.service.ts
  dashboard/src/components/widget/footer/che-footer.controller.ts
  dashboard/src/components/widget/footer/che-footer.directive.ts
  dashboard/src/components/widget/footer/che-footer.html
  dashboard/src/index.html
Labels: kind/task, status/code-review

#15965 Add '--fail-script-on-failed-tests' option to java selenium tests
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/.infra/centos-ci/nightly/ocp-oauth-test.sh
  tests/legacy-e2e/che-selenium-core/bin/webdriver.sh
  tests/legacy-e2e/che-selenium-test/README.md
Labels: kind/task, status/code-review

#15984 Update load tests
  tests/e2e/mocha-load.opts
  tests/performance/load-tests.sh
  tests/performance/pod.yaml
Labels: kind/enhancement, status/code-review

#15892 Adding functionality to switch user terminal to dom.
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/utils/PreferencesHandler.ts
  tests/e2e/utils/requestHandlers/CheApiRequestHandler.ts
  tests/e2e/utils/requestHandlers/headers/CheMultiuserAuthorizationHeaderHandler.ts
  tests/e2e/utils/requestHandlers/headers/CheSingleUserAuthorizationHeaderHandler.ts
  tests/e2e/utils/requestHandlers/headers/IAuthorizationHeaderHandler.ts
  tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts
  tests/e2e/utils/requestHandlers/tokens/ITokenHandler.ts
Labels: kind/enhancement, status/code-review

#16001 Exclude GitHub oauth depended tests
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/ImportProjectFromGitHubTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/AuthorizeOnGithubFromDashboardTest.java
Labels: status/code-review

#15964 Adapt rolling update tests according to deploy CHE with operator
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/executor/hotupdate/HotUpdateUtil.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithEditorTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithStartedWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithWorkspacesStartStopTest.java
Labels: kind/task, status/code-review

#16010 Setup envs to test
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
Labels: kind/task, status/code-review

#16011 Make several attempts to reach desired values in multi-thread dependent tests
  core/commons/che-core-commons-observability/pom.xml
  core/commons/che-core-commons-observability/src/test/java/io/micrometer/core/instrument/internal/TimedCronExecutorServiceTest.java
  core/commons/che-core-commons-observability/src/test/java/org/eclipse/che/commons/observability/MeteredExecutorServiceWrapperTest.java
  core/commons/che-core-commons-test/src/main/java/org/eclipse/che/commons/test/AssertRetry.java
  core/commons/che-core-commons-test/src/test/java/org/eclipse/che/commons/test/AssertRetryTest.java
Labels: status/code-review

#16005 [TS_SELENIUM] Update code owners list of the "e2e" project
  .github/CODEOWNERS
Labels: kind/task, status/code-review

#16013 Fix Centos CI build to be green if java selenium tests passed
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-all-tests.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-stable-selenium-tests.sh
  tests/.infra/centos-ci/nightly/ocp-oauth-test.sh
Labels: kind/task, status/code-review

#16026 Add "build" PR check.
  .ci/cico_build_pullrequest.sh
  .ci/cico_common.sh
Labels: kind/enhancement, status/code-review

#15972 Add script for the launching devfiles testsuite
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/cico-devfiles-test.sh
Labels: kind/enhancement, status/code-review

#16031 [TS_SELENIUM] Fix E2E tests failed on "Language server validation" step
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review

#16025 [TS_SELENIUM] Add methods for receiving and waiting text from the DOM based terminal.
  tests/e2e/pageobjects/ide/Terminal.ts
  tests/e2e/utils/PreferencesHandler.ts
Labels: kind/task, status/code-review

#16034 Fix expected status bar message in devfile e2e tests
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/e2e/WorkspaceCreationAndLsInitialization.spec.ts
Labels: kind/bug, status/code-review

#16036 Ignore ssl certificate errors in e2e tests
  tests/e2e/driver/ChromeDriver.ts
Labels: kind/task, status/code-review

#16016 [UD] Add Temporary Storage toggle button to Get Started page
  dashboard/src/app/get-started/template-list/template-list.controller.ts
  dashboard/src/app/get-started/template-list/template-list.html
  dashboard/src/app/get-started/template-list/template-list.styl
Labels: kind/task, status/code-review

#16033 Find solution for the correct behavior of CentOS job for checking devfile
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/cico-devfiles-test.sh
Labels: status/code-review

#16035 Fix storing artifacts for happy-path-test
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
Labels: kind/task, status/code-review

#16023 [Selenium] Stabilize selenium tests
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/organization/OrganizationListPage.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/RenameOrganizationTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceMemberTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/Che7PreviewDevfileStartTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java
  tests/legacy-e2e/che-selenium-test/src/test/resources/suites/CheSuite.xml
Labels: status/code-review, team/che-qe

#15951 Improved messages for self-signed cert issues
  dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.ts
  dashboard/src/app/index.module.ts
  dashboard/src/app/index.styl
  dashboard/src/app/navbar/recent-workspaces/recent-workspaces.controller.spec.ts
  dashboard/src/app/navbar/recent-workspaces/recent-workspaces.controller.ts
  dashboard/src/app/organizations/organizations-config.service.spec.ts
  dashboard/src/app/organizations/organizations-config.service.ts
  dashboard/src/app/workspaces/create-workspace/import-custom-stack/import-custom-stack.controller.ts
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/project-source-selector/add-import-project/import-github-project/import-github-project.controller.ts
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/ready-to-go-stacks.controller.ts
  dashboard/src/app/workspaces/list-workspaces/list-workspaces.controller.ts
  dashboard/src/app/workspaces/list-workspaces/workspace-item/workspace-item.controller.ts
  dashboard/src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.controller.ts
  dashboard/src/app/workspaces/workspace-details/workspace-details.service.ts
  dashboard/src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.controller.ts
  dashboard/src/assets/branding/product.json
  dashboard/src/components/api/che-service.factory.ts
  dashboard/src/components/api/workspace/che-workspace.factory.ts
  dashboard/src/components/branding/branding.constant.ts
  dashboard/src/components/branding/che-branding-config.ts
  dashboard/src/components/branding/che-branding.factory.ts
  dashboard/src/components/branding/che-branding.ts
  dashboard/src/components/branding/che-dashboard-configuration.service.ts
  dashboard/src/components/service/resource-fetcher/resource-fetcher.service.ts
  dashboard/src/components/validator/unique-project-name-validator.spec.ts
  dashboard/src/components/widget/footer/che-footer.controller.ts
Labels: kind/bug, status/code-review

#15890 Inject pods into other deployments
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironment.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/PodMerger.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/CertificateProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitConfigProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeysProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSslCertificateProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/DefaultSecureServersFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/SecureServerExposer.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/PodMergerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/CertificateProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitConfigProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeySecretProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSslCertificateProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxySecureServerExposerTest.java
  infrastructures/kubernetes/src/test/resources/jwtproxy-confg.yaml
Labels: kind/task, status/code-review

#16027 Do not recover runtime if environment factory is no longer available
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
Labels: kind/bug, status/code-review

#16044 Add '--insecure-skip-tls-verify' option when login to minishift in ci.centos test scripts
  tests/.infra/centos-ci/functional_tests_utils.sh
Labels: kind/enhancement, status/code-review

#16055 [Selenium] Stabilize selenium tests on Centos CI
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-all-tests.sh
  tests/.infra/centos-ci/nightly/cico-multiuser-stable-selenium-tests.sh
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/theia/TheiaProjectTree.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/ShareWorkspaceMemberTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromDevfileUrl.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithKeepDirectoryTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithRootFolderTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java
Labels: status/code-review, team/che-qe

#16046 Update plugin brokers to v3.1.1
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: area/plugin-broker, area/plugins, kind/enhancement, status/code-review

#16082 Store events in JSON format to get more info.
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: status/code-review

#16039 Add scripts to launch 'che-rc' jobs on the 'centos-ci'
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/rc/cico-rc-multiuser-happy-path-test.sh
  tests/.infra/centos-ci/rc/cico-rc-multiuser-integration-tests.sh
  tests/.infra/centos-ci/rc/cico-rc-ocp-oauth-test.sh
  tests/.infra/centos-ci/rc/cico-rc-rolling-strategy-test.sh
  tests/.infra/centos-ci/rc/rc_function_util.sh
Labels: area/qe, kind/task, status/code-review

#15831 Implement Python Django devfile test
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/e2e/pageobjects/ide/DialogWindow.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/PythonDjango.spec.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/task, status/code-review

#16095 Fix release scripts to update endpoint-watcher tag
  .ci/set_tag_version_images_linux.sh
Labels: kind/bug, status/code-review

#16106 [Selenium] Fix storing selenium tests results to artifacts.ci.centos.org
  tests/.infra/centos-ci/cico_pr_test.sh
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
Labels: area/qe, kind/bug, status/code-review

#16099 genclass package typo
  multiuser/api/che-multiuser-api-permission/pom.xml
Labels: status/code-review

#15705 Make embedded OAuth authentication model default for both singe and multiuser che && allow to get OAuth token with machine token
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  dashboard/src/app/workspaces/create-workspace/ready-to-go-stacks/project-source-selector/add-import-project/import-github-project/import-github-project.controller.ts
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java
Labels: kind/task, status/code-review

#16118 Tests E2E: Get rid of temporal admin in test which checks installation by OperatorHub
  tests/e2e/TestConstants.ts
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/pageobjects/login/OcpUserLoginPage.ts
  tests/e2e/pageobjects/login/RegularUserOcpCheLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#16116 [ TS_SELENIUM ] Use 80.0 Chrome driver in typescript selenium tests
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/enhancement, status/code-review

#15878 Remove selfSignedCertSecretName property
  deploy/kubernetes/helm/che/templates/deployment.yaml
  deploy/kubernetes/helm/che/values.yaml
Labels: kind/task, status/code-review

#16136 Fix the get starting page title
  dashboard/src/app/get-started/template-list/template-list.html
Labels: kind/bug, status/code-review

#16144 Move cert-manager related templates into Che repository
  deploy/cert-manager/ca-cert-generator-role-binding.yml
  deploy/cert-manager/ca-cert-generator-role.yml
  deploy/cert-manager/che-certificate.yml
  deploy/cert-manager/che-cluster-issuer.yml
Labels: area/chectl, status/code-review

#16147 Cleanup nightly/pre-release/master tests Jenkins pipelines
  tests/.infra/crw-ci/master/k8s/Jenkinsfile
  tests/.infra/crw-ci/nightly/k8s/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/.infra/crw-ci/pre-release-testing/k8s/Jenkinsfile
Labels: kind/enhancement, status/code-review

#16123 Fix accepting factory with git suffixed repository URL
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java
  wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java
Labels: kind/bug, status/code-review

#16143 Update bug_report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: kind/enhancement, status/code-review

#16148 Fix of memory leak that happened in EventService
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/StartSynchronizer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/StartSynchronizerTest.java
Labels: kind/bug, status/code-review

#16142 Switch application.confirmExit in tests to never by default
  tests/e2e/driver/CheReporter.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
  tests/e2e/utils/PreferencesHandler.ts
Labels: kind/bug, status/code-review

#16126 Watch and provide startup logs (workspace + broker pods)
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatch.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/LogWatchTimeouts.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/LogWatcher.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/PodLogHandler.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/PodLogToEventPublisher.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/PluginBrokerManager.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/SidecarToolingProvisioner.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/SidecarToolingProvisionerTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatchTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/LogWatcherTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/PodLogToEventPublisherTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBrokerTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectTest.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilterTest.java
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/enhancement, status/code-review

#16146 [Selenium] Set application.confirmExit property to 'never' by default
  tests/legacy-e2e/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestUserPreferencesServiceClient.java
  tests/legacy-e2e/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/factory/TestFactoryInitializer.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/CheMultiuserAdminDashboard.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/Dashboard.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
Labels: kind/task, status/code-review, team/che-qe

#16155 [TS_SELENIUM] Change bindings scope of the "e2e" project
  tests/e2e/inversify.config.ts
  tests/e2e/package-lock.json
  tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts
Labels: kind/task, status/code-review

#16173 [TS_SELENIUM] Move "@eclipse-che/api" from "devDependencies" to "dependencies" in the "e2e" project
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/task, status/code-review

#16175 fix UD branding
  dashboard/src/components/branding/che-branding.ts
Labels: kind/bug, status/code-review
