Repository eclipse-che/che, pull requests merged in 2020-04, with the labels that each got.

#16353 Ffmpeg recording
  dockerfiles/e2e/Dockerfile
  dockerfiles/e2e/entrypoint.sh
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/e2e/TestConstants.ts
Labels: status/code-review

#16498 cleanup before workspace start
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
Labels: kind/bug, status/code-review

#16526 [Selenium] Fix problem with login to Che by Openshift OAuth with 'admin' user
  tests/e2e/pageobjects/login/RegularUserOcpCheLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
Labels: kind/task, status/code-review, team/che-qe

#16505 Support for volumes in K8S/Openshift type components
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/resources/devfile/petclinic.yaml
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/kubernetes_openshift_component/devfile_kubernetes_component.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/kubernetes_openshift_component/devfile_openshift_component.yaml
Labels: kind/task, status/code-review

#16528 Prevent ArrayIndexOutOfBoundsException in HeaderRequestTokenExtractor
  multiuser/api/che-multiuser-api-authentication-commons/src/main/java/org/eclipse/che/multiuser/api/authentication/commons/token/HeaderRequestTokenExtractor.java
  multiuser/api/che-multiuser-api-authentication-commons/src/test/java/org/eclipse/che/multiuser/api/authentication/commons/token/HeaderRequestTokenExtractorTest.java
Labels: kind/bug, status/code-review

#16536 Make logger less verbose on OpenShift 4.x
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
Labels: status/code-review

#16525 Remove che-workspace-loader developer workflow
  CONTRIBUTING.md
Labels: kind/task, status/code-review

#16548 Fix the "E2E typescript selenium tests are failing after update to new ChromeDriver 80.0.2" issue
  tests/e2e/package.json
Labels: kind/bug, status/code-review

#16540 Explicitly marked cascade deletion as Foreground
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesConfigsMaps.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesIngresses.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPersistentVolumeClaims.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesSecrets.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesServices.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesSecretsTest.java
Labels: kind/bug, status/code-review

#16551 Update load tests
  tests/e2e/tests/e2e/GitSsh.spec.ts
  tests/e2e/tests/load_test/LoadTest.spec.ts
  tests/performance/create_users.sh
  tests/performance/load-tests.sh
  tests/performance/sum_up_failures.sh
Labels: kind/enhancement, status/code-review

#16561 Typescript tests - fix removing workspace
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/dashboard/Workspaces.ts
Labels: kind/bug, status/code-review

#16488 Apply web application that can make authentication requests with user token
  assembly/assembly-root-war/src/main/webapp/_app/keycloackLoader.js
  assembly/assembly-root-war/src/main/webapp/_app/loader.html
  assembly/assembly-root-war/src/main/webapp/_app/loader.js
  assembly/assembly-root-war/src/main/webapp/_app/oauth.html
  assembly/assembly-root-war/src/main/webapp/_app/oauthLoader.js
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java
Labels: kind/enhancement, status/code-review

#16564 [Selenium] Confirm workspace deletion, add project state java tests to UNDER_REPAIR group
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteRunningWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteStoppingWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRefreshTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java
Labels: kind/task, status/code-review, team/che-qe

#16391 Add Container Lifecycle support
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolver.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/CheContainer.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/Exec.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/Handler.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/Lifecycle.java
Labels: kind/enhancement, status/code-review

#16582 [TS_SELENIUM] Unexpected url after using the "PreviewWidget.typeAndApplyUrl" method
  tests/e2e/pageobjects/ide/PreviewWidget.ts
Labels: kind/task, status/code-review

#16586 7.11.1 cherry-pick - Explicitly marked cascade deletion as Foreground (#16540)
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesConfigsMaps.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesIngresses.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPersistentVolumeClaims.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesSecrets.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesServices.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesSecretsTest.java
Labels: kind/bug, status/code-review, target/branch

#16580 Prevent & log NPE in KubernetesRuntime;
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java
Labels: kind/bug, status/code-review

#16595 Fix workspace deletion in typescript tests
  tests/e2e/pageobjects/dashboard/Workspaces.ts
Labels: kind/bug, status/code-review

#16600 Make it possible to set CPU limits to dockerimage type components;
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplierTest.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/dockerimage_component/devfile_dockerimage_component.yaml
Labels: kind/enhancement, status/code-review

#16441 fix(security): fix minimist issue
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/bug, status/code-review

#16598 [Selenium] Wait for 'confirm workspace deletion' checkbox is enabled
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/organization/OrganizationListPage.java
  tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceDetails.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteRunningWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/DeleteStoppingWorkspaceTest.java
  tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization/DeleteOrganizationTest.java
Labels: kind/bug, kind/task, status/code-review, team/che-qe

#16619 Fix rolebinding issues in infras
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesWorkspaceServiceAccount.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftWorkspaceServiceAccount.java
Labels: kind/bug, status/code-review

#16479 update release template for 7.11
  RELEASE.md
Labels: kind/enhancement, status/code-review

#16617 Minimal quick fix for the CRW-811 critical bug
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
Labels: kind/bug, status/code-review, target/branch

#16445 Add Axios request and response interceptors
  tests/e2e/driver/CheReporter.ts
  tests/e2e/utils/requestHandlers/CheApiRequestHandler.ts
Labels: kind/enhancement, status/code-review

#16527 Make sure we always handle the "Failed" pod container event.
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/UnrecoverablePodEventListener.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/UnrecoverablePodEventListenerTest.java
Labels: kind/bug, status/code-review

#16529 Support `endpoints` for components of type kubernetes/openshift
  core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/ServerConfig.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplier.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplierTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposerTest.java
  infrastructures/kubernetes/src/test/resources/devfile/petclinicPods.yaml
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/ServerConfigImpl.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/model/impl/ServerConfigImplTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/kubernetes_openshift_component/devfile_k8s_openshift_component_with_endpoints.yaml
Labels: kind/task, status/code-review

#16640 [Metric] Total workspace count
  deploy/openshift/templates/monitoring/che-monitoring.yaml
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/spi/jpa/MultiuserJpaWorkspaceDao.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/jpa/MultiuserJpaWorkspaceDaoTest.java
  wsmaster/che-core-api-metrics/pom.xml
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceMeterBinder.java
  wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WsMasterMetricsModule.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/jpa/JpaWorkspaceDao.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/WorkspaceImpl.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/WorkspaceDao.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/spi/tck/WorkspaceDaoTest.java
Labels: kind/task, status/code-review

#16632 Don't use the label to designate managed namespaces.
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectTest.java
Labels: kind/bug, status/code-review

#16669 Gh15126 plugin endpoints
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolver.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/MachineResolverTest.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/editor_plugin_component/devfile_editor_plugins.yaml
Labels: kind/task, status/code-review

#16676 Fix indentation that prevents oc apply with an absolute path
  deploy/openshift/templates/monitoring/grafana-dashboards.yaml
Labels: kind/bug, status/code-review

#16532 Add a role allowing che SA to stop workspaces
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/environment/OpenShiftCheInstallationLocation.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/provision/OpenShiftStopWorkspaceRoleProvisioner.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/provision/OpenShiftStopWorkspaceRoleProvisionerTest.java
Labels: kind/bug, status/code-review

#16692 create ingress only for matching services of secure servers
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposerTest.java
Labels: kind/bug, status/code-review

#16725 che #15906 Disabling 'che.workspace.stop.role.enabled' by default
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#16706 [Selenium] Fix scripts for nightly jobs on ci.centos
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/cico-devfiles-test.sh
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
Labels: kind/task, status/code-review, team/che-qe

#16680 Allow preferences to be an array of serializable values.
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/PreferencesDeserializer.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/SerializableConverter.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/PreferencesDeserializerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/SerializableConverterTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/editor_plugin_component/devfile_plugin_components_with_preferences.yaml
Labels: kind/enhancement, status/code-review

#16729 delete k8s objects with Background propagation policy
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesConfigsMaps.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesIngresses.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPersistentVolumeClaims.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesSecrets.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesServices.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesSecretsTest.java
Labels: kind/bug, status/code-review

#16772 Remove unnecessary import
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: status/code-review

#15669 Add CI information to the README.md file
  README.md
Labels: kind/enhancement, status/code-review

#16786 [Selenium] Stabilize 'devtools-che-nightly-devfiles-test' test job
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/cico-devfiles-test.sh
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
Labels: area/qe, kind/task, status/code-review, team/che-qe

#16774 Update bug template to specific the exact command to deploy Eclipse Che
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: kind/enhancement, status/code-review

#16785 Fixing incorrect xpath strings in DialogWindow class
  tests/e2e/pageobjects/ide/DialogWindow.ts
Labels: kind/bug, status/code-review

#16735 Do not provision the stop workspace role if there is no OS OAuth identitty provider
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
Labels: kind/bug, status/code-review

#16803 Do not provision the stop workspace role if there is no oauth identity provider configured.
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
Labels: status/code-review, target/branch

#16782 Move dependency management pom to che repo
  pom.xml
  tests/legacy-e2e/pom.xml
  wsmaster/che-core-api-auth/pom.xml
  wsmaster/che-core-api-factory-github/pom.xml
  wsmaster/che-core-api-factory/pom.xml
  wsmaster/che-core-api-ssh/pom.xml
Labels: kind/task, status/code-review

#16778 Do not create internal servers for public endpoints
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposer.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerExposerTest.java
Labels: kind/bug, status/code-review

#16781 Remove docs from che-server build...
  assembly/assembly-main/pom.xml
  assembly/assembly-main/src/assembly/assembly.xml
  pom.xml
Labels: status/code-review
