Repository eclipse-che/che, pull requests merged in 2021-09, with the labels that each got.

#20374 chore(happy-path-tests): confirm trust git repository authors when necessary
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/pageobjects/ide/ContextMenu.ts
  tests/e2e/pageobjects/ide/DebugView.ts
  tests/e2e/pageobjects/ide/DialogWindow.ts
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/pageobjects/ide/LeftToolBar.ts
  tests/e2e/pageobjects/ide/NotificationCenter.ts
  tests/e2e/pageobjects/ide/OpenDialogWidget.ts
  tests/e2e/pageobjects/ide/OpenWorkspaceWidget.ts
  tests/e2e/pageobjects/ide/PreviewWidget.ts
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/pageobjects/ide/QuickOpenContainer.ts
  tests/e2e/pageobjects/ide/Terminal.ts
  tests/e2e/pageobjects/ide/plugins/GitHubPullRequestPlugin.ts
  tests/e2e/pageobjects/ide/plugins/GitPlugin.ts
  tests/e2e/pageobjects/ide/plugins/KubernetesPlugin.ts
  tests/e2e/pageobjects/ide/plugins/OpenshiftPlugin.ts
  tests/e2e/pageobjects/ide/plugins/PluginsView.ts
  tests/e2e/tests/e2e/GitPublishBranch.spec.ts
  tests/e2e/tests/e2e/GitSelfSignCert.spec.ts
  tests/e2e/tests/e2e/GitSsh.spec.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts
  tests/e2e/tsconfig.json
  tests/e2e/utils/Sanitizer.ts
Labels: kind/enhancement, status/code-review, target/branch

#20384 Hotfix linting project for dockerimage build fix
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/utils/Sanitizer.ts
  tests/e2e/utils/ScreenCatcher.ts
Labels: kind/bug, status/code-review, target/branch

#20371 Removing CI section from the README since it points to che-server
  README.md
Labels: status/code-review, target/branch

#20406 test: fix name of the project for the dew workspace DevWorkspaceHappyPath
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: kind/bug, status/code-review, target/branch

#20405 Fix single host load tests
  tests/performance/load-tests.sh
Labels: kind/bug, status/code-review, target/branch

#20419 Update plugin tests for the author trust notification confirmation
  tests/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: status/code-review, kind/task, target/branch

#20427 Added wait to avoid interacting with outdated dom
  tests/e2e/testsLibrary/LanguageServerTests.ts
Labels: kind/bug, status/code-review, target/branch

#20453 Fix the issue: The "VscodeYamlPlugin" fails on the openshift CI nightly job
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: status/code-review, kind/task, target/branch

#20458 Hotfix linting project for dockerimage build fix (#20384)
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/utils/Sanitizer.ts
  tests/e2e/utils/ScreenCatcher.ts
Labels: kind/bug, status/code-review, target/branch

#20484 Fix the issue: The "TypescriptPlugin" test unexpectedly fails on the nightly CI job
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: status/code-review, kind/task, target/branch

#20480 Hotfix linting project for dockerimage build fix
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/utils/ScreenCatcher.ts
Labels: kind/bug, status/code-review, target/branch

#20483 Hotfix linting project for dockerimage build fix
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/utils/ScreenCatcher.ts
Labels: kind/bug, status/code-review, target/branch

#20493 Add preferences setup check for the VscodeYamlPlugin test
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: status/code-review, kind/task, target/branch

#20476 Adapt testsuites of the Language server validation and build features for DevWorkspaceHappyPath
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#20502 Fix confirmation dialog issue in testsLibrary
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: kind/bug, status/code-review, target/branch

#20503 Cherry-pick 20502 for main
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: status/code-review, target/branch

#20511 Rework the VscodeYamlPlugin test to use UI for preferences setup
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
  tests/e2e/utils/PreferencesHandler.ts
Labels: status/code-review, kind/task, target/branch
