Repository eclipse-che/che, pull requests merged in 2021-10, with the labels that each got.

#20562 QuickOpenContainer and NotificationCenter locator fix
  tests/e2e/pageobjects/ide/NotificationCenter.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/bug, status/code-review, target/branch

#20570 Crw 2295 fix quick open container locator change 7.36.x cherry pick
  tests/e2e/pageobjects/ide/NotificationCenter.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/bug, status/code-review, target/branch

#20579 Build quay.io/eclipse/che-e2e on top of selenium/standalone-chrome:94.0
  dockerfiles/e2e/Dockerfile
Labels: status/code-review, kind/task, target/branch

#20584 Reverting locator change for 7.36.x in favor of downstream tests
  tests/e2e/pageobjects/ide/NotificationCenter.ts
Labels: status/code-review, target/branch

#20575 chore: Update release template
  .github/ISSUE_TEMPLATE/release.md
Labels: status/code-review, target/branch
