Repository eclipse-che/che, pull requests merged in 2021-03, with the labels that each got.

#19181 [Selenium] Increase number of timeout to stabilize 'OpenshiftConnector' e2e test
  tests/e2e/TimeoutConstants.ts
Labels: area/qe, e2e-test/failure, kind/task, status/code-review, team/che-qe

#19148 Hostname configuration of workspace routes
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/openshift/pom.xml
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/server/RouteServerExposer.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftExternalServerExposerTest.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/server/OpenShiftPreviewUrlExposerTest.java
Labels: status/code-review

#19193 Include che.devworkspaces.enabled property
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/task, status/code-review

#19209 Added documentation team as codeowners for the property description review.
  .github/CODEOWNERS
Labels: status/code-review

#19211 https://github.com/eclipse/che/issues/17177 create a GH release every time we release...
  .github/workflows/release.yml
Labels: status/code-review

#19217 Create the "xml" and "yaml" plugins tests
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: kind/task, status/code-review

#18894 Fix bugs - constant and error throwing
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: kind/bug, status/code-review

#19249 Fix bugs - constant and error throwing (#18894)
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: kind/bug, status/code-review, target/branch

#19252 Fixing error messages
  tests/e2e/pageobjects/ide/Ide.ts
Labels: kind/bug, status/code-review

#19261 Create tests for the vale plugin
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/pageobjects/ide/Terminal.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
Labels: kind/task, status/code-review

#19233 Property descriptions
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
Labels: kind/bug, status/code-review

#19272 add MM message
  .github/workflows/release.yml
Labels: kind/enhancement, status/code-review

#18970 Remove workspace loader from Che Server
  .github/ISSUE_TEMPLATE/release.md
  .repositories.yaml
  CONTRIBUTING.md
  RELEASE.md
  assembly/assembly-main/pom.xml
  assembly/assembly-main/src/assembly/assembly.xml
  assembly/assembly-workspace-loader-war/pom.xml
  assembly/assembly-workspace-loader-war/src/main/java/org/eclipse/che/WSLoaderController.java
  assembly/assembly-workspace-loader-war/src/main/webapp/WEB-INF/web.xml
  assembly/pom.xml
  dockerfiles/che/Dockerfile
  pom.xml
Labels: kind/task, status/code-review

#19278 Disable broken repo from Che Happy path tests pipeline
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#19267 generate changelog and include in GH...
  .github/workflows/release-changelog.yml
Labels: status/code-review

#19280 Fixing tests
  tests/e2e/index.ts
  tests/performance/pod-oauth.yaml
Labels: kind/bug, status/code-review

#19253 Properties script
  .github/workflows/build-pr-check.yml
  check_properties_description.sh
Labels: kind/bug, status/code-review

#19293 Stabilize PR Happy path testing pipelines
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/cico-openshift-connector-test.sh
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#19245 Gitlab public repo support in factory URL
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  pom.xml
  wsmaster/che-core-api-factory-gitlab/pom.xml
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolver.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabFileContentProvider.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java
  wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabFileContentProviderTest.java
  wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParserTest.java
  wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlTest.java
  wsmaster/pom.xml
Labels: kind/task, status/code-review

#19336 Stabilize installation of dependencies in PR check Happy path testing pipelines
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/task, status/code-review

#19285 Add documentation to monitoring and openID
  multiuser/keycloak/che-multiuser-keycloak-server/authenticating-to-the-che-server-using-openid.adoc
  wsmaster/che-core-api-metrics/extending-che-monitoring-metrics.adoc
Labels: kind/task, status/code-review

#19333 Update environment list to accommodate workspaces.openshift.com
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: kind/enhancement, status/code-review

#19332 feat(machine-exec): Remove default machine-exec component as it is provided by che-theia meta/devfile now
  .ci/set_tag_version_images.sh
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
  wsmaster/che-core-api-factory/pom.xml
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/DefaultEditorProvisioner.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/convert/DefaultEditorProvisionerTest.java
Labels: kind/task, status/code-review

#19343 Add variability for test suite to load tests
  dockerfiles/e2e/entrypoint.sh
  tests/e2e/TestConstants.ts
  tests/e2e/driver/CheReporter.ts
  tests/performance/load-tests.sh
  tests/performance/pod-oauth.yaml
Labels: kind/enhancement, status/code-review

#19353 Replace eclipse on eclipse-che organization for che-operator and che-machine-exec repositories
  .github/ISSUE_TEMPLATE/release.md
  .repositories.yaml
  CONTRIBUTING.md
  RELEASE.md
Labels: kind/task, status/code-review

#19362 Decrease minikube resources in PR Happy path tests
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#19356 Make it possible to run all plugins tests
  tests/e2e/inversify.types.ts
  tests/e2e/mocha-all-plugins.opts
  tests/e2e/package.json
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/utils/workspace/ITestWorkspaceUtil.ts
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/task, status/code-review

#19384 [Selenium] Update DevWorkspaceHappyPath test sample name
  tests/e2e/mocha-devworkspace-happy-path.opts
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: area/qe, kind/task, status/code-review

#19392 Send MM notification on release failure
  .github/workflows/release.yml
Labels: kind/bug, status/code-review

#19395 Bump version during release in the beginning
  make-release.sh
Labels: status/code-review

#19399 Get rid of the "Buffer" deprecation warning in the test logs
  tests/e2e/driver/CheReporter.ts
  tests/e2e/utils/ScreenCatcher.ts
Labels: kind/task, status/code-review

#19406 Adapt tests to multi-root workspaces related changes
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/task, status/code-review

#19432 Update the references to a new Che-Theia repository
  .repositories.yaml
  CONTRIBUTING.md
Labels: kind/task, status/code-review

#19446 Create E2E test for checking the "Java11" plugin
  tests/e2e/files/devfiles/plugins/Java11PluginTest.yaml
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
Labels: status/code-review

#19452 add DWO and DWCO to issue template; clean up...
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/release.yml
Labels: kind/enhancement, status/code-review

#19447 use :no_entry_sign: or :white_check_mark:...
  .github/workflows/release.yml
Labels: status/code-review
