Repository eclipse-che/che, pull requests merged in 2021-11, with the labels that each got.

#20721 fix: git config --global pull.rebase...
  .github/workflows/release.yml
Labels: kind/bug, status/code-review, target/branch

#20747 Re-implemented workaround for 19887, missing debug configuration
  tests/e2e/testsLibrary/LanguageServerTests.ts
Labels: kind/bug, status/code-review, target/branch

#20746 Re-implemented workaround for 19887, missing debug configuration
  tests/e2e/testsLibrary/LanguageServerTests.ts
Labels: kind/bug, status/code-review, target/branch

#20745 docs: Removing archived sidecar related repositories
  .repositories.yaml
  CONTRIBUTING.md
Labels: status/code-review, target/branch

#20755 Update chromedriver version to 95.0.0
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/enhancement, status/code-review, target/branch

#20753 Update the chromedriver version to 95.0.0
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/enhancement, status/code-review, target/branch

#20764 Updated plugin scripts to fetch the workspace name from url
  tests/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts
  tests/e2e/tests/plugins/InstallPluginUsingUI.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#20723 chore: Have proper versioning of Che e2e project
  make-release.sh
  tests/e2e/package.json
  tests/e2e/tsconfig.json
Labels: status/code-review, target/branch

#20826 Fix error highlighting line coordinate locator
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
  tests/e2e/testsLibrary/LanguageServerTests.ts
  tests/e2e/utils/DriverHelper.ts
Labels: kind/bug, status/code-review, target/branch

#19565 chore: should also include new features in...
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: status/code-review, target/branch, lifecycle/stale

#20825 Fix error highlighting line coordinate locator main cherrypick
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
  tests/e2e/testsLibrary/LanguageServerTests.ts
  tests/e2e/utils/DriverHelper.ts
Labels: kind/bug, status/code-review, target/branch

#20846 fix: release script must update npm project version
  make-release.sh
Labels: status/code-review, kind/task, target/branch

#20849 Add rollout for the oauth-openshift
  tests/devworkspace-happy-path/launch.sh
Labels: kind/enhancement, status/code-review, target/branch
