Repository eclipse-che/che, pull requests merged in 2021-08, with the labels that each got.

#20231 Updating PythonDjango.spec.ts
  tests/e2e/tests/devfiles/PythonDjango.spec.ts
Labels: kind/bug, status/code-review, target/branch

#20204 chore: Adapt Happy Path tests to the changes related to the Monaco upgrade
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/pageobjects/ide/QuickOpenContainer.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/task, status/code-review, target/branch

#20213 Update readme to launch test
  tests/e2e/README.md
  tests/e2e/mocha.opts
Labels: kind/enhancement, status/code-review, target/branch

#20248 [Selenium] Remove Centos CI scripts
  tests/.infra/centos-ci/common-qe/README.md
  tests/.infra/centos-ci/common-qe/che-cert-generation.sh
  tests/.infra/centos-ci/common-qe/che-util.sh
  tests/.infra/centos-ci/common-qe/common-qe-configuration.conf
  tests/.infra/centos-ci/common-qe/common-util.sh
  tests/.infra/centos-ci/common-qe/downloader.sh
  tests/.infra/centos-ci/common-qe/installation-util.sh
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/cico-devfiles-test.sh
  tests/.infra/centos-ci/nightly/cico-openshift-connector-test.sh
  tests/.infra/centos-ci/nightly/nightly-happypath-test.sh
Labels: area/qe, kind/task, status/code-review

#20238 chore(github): Introduce form templates
  .github/ISSUE_TEMPLATE/a_question.md
  .github/ISSUE_TEMPLATE/a_question.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/task.yaml
Labels: status/code-review, target/branch

#20268 [Selenium] fix Editor view-lines locator
  tests/e2e/pageobjects/ide/Editor.ts
Labels: status/code-review, sprint/current, area/qe

#20285 ci: label release as being Che E2E Tests,...
  .github/workflows/release.yml
Labels: status/code-review, target/branch

#20293 Fix the che-plugin-registry nightly tests
  tests/e2e/pageobjects/ide/plugins/KubernetesPlugin.ts
  tests/e2e/pageobjects/third-parties/GitOauthAppsSettings.ts
  tests/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
Labels: status/code-review, kind/task, target/branch

#20301 Fix the che-plugin-registry nightly tests
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
Labels: status/code-review, kind/task, target/branch

#20309 Fix the issue "The "TypescriptPlugin" test fails because can't connect to the debug session"
  tests/e2e/files/devfiles/plugins/TypescriptNodeDebug2PluginTest.yaml
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/utils/BrowserTabsUtil.ts
Labels: status/code-review, kind/task, target/branch

#20319 Update load tests
  tests/performance/load-tests.sh
  tests/performance/pod-oauth.yaml
  tests/performance/pod.yaml
Labels: kind/enhancement, status/code-review, target/branch

#20344 Fix the VscodeKubernetesPlugin test
  tests/e2e/pageobjects/ide/OpenDialogWidget.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
Labels: status/code-review, kind/task, target/branch

#20349 Added fix for debug configuration
  tests/e2e/testsLibrary/LanguageServerTests.ts
Labels: kind/bug, status/code-review, target/branch

#20346 Fixed verifyRunningApplication method
  tests/e2e/pageobjects/ide/PreviewWidget.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/bug, status/code-review, target/branch

#20348 Cherry-pick #20346 for main branch
  tests/e2e/pageobjects/ide/PreviewWidget.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: status/code-review, target/branch

#20355 Port Sanetizer changes to main
  tests/e2e/driver/CheReporter.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/utils/Sanitizer.ts
  tests/e2e/utils/ScreenCatcher.ts
Labels: kind/enhancement, status/code-review, target/branch

#20354 Implement sanetizer to fix random crashes in screencaster and reporter
  tests/e2e/driver/CheReporter.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/utils/Sanitizer.ts
  tests/e2e/utils/ScreenCatcher.ts
Labels: kind/enhancement, status/code-review, target/branch

#20358 Fix issue: The "VscodeValePlugin" unexpectedly fails on the openshift-ci
  tests/e2e/files/devfiles/plugins/VscodeValePlugin.yaml
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
Labels: status/code-review, kind/task, target/branch
