Repository eclipse-che/che, pull requests merged in 2021-12, with the labels that each got.

#20868 fix: cd down two dirs, but only cd back one:...
  .github/workflows/release.yml
  make-release.sh
Labels: kind/bug, status/code-review, target/branch

#20890 chore: move release-changelog.yml from...
  .github/workflows/release-changelog.yml
Labels: status/code-review, target/branch

#20864 feature: Publish E2E tests to npmjs for dev builds
  .github/workflows/next-build.yml
  .github/workflows/typescript-publish.yml
  tests/e2e/build/dockerfiles/Dockerfile
  tests/e2e/build/dockerfiles/README.md
  tests/e2e/build/dockerfiles/entrypoint.sh
  tests/e2e/build/dockerfiles/google-chrome.repo
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: status/code-review, kind/task, target/branch

#20891 [Typescript] Delete SSH key added to github account automatically by GitPublishBranch typescript test
  tests/e2e/utils/VCS/github/GitHubUtil.ts
Labels: status/in-progress, kind/task, sprint/current, target/branch, area/qe

#20894 [Typescript] Delete SSH key added to github account automatically by GitPublishBranch typescript test(7.38.x branch))
  tests/e2e/utils/VCS/github/GitHubUtil.ts
Labels: status/code-review, kind/task, sprint/current, target/branch, area/qe

#20905 fix: fix release workflow
  .github/workflows/release.yml
  make-release.sh
Labels: kind/bug, status/code-review, target/branch

#20881 Added logic for getting terminal input textarea using the div ID inst…
  tests/e2e/pageobjects/ide/Terminal.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
Labels: status/code-review, target/branch

#20882 Added logic for getting terminal input textarea using the div ID inst…
  tests/e2e/pageobjects/ide/Terminal.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#20903 Fix running DevWorkspaceHappyPath test on PROW ci
  tests/devworkspace-happy-path/resources/cluster-oauth-patch.json
  tests/devworkspace-happy-path/resources/pod-che-happy-path.yaml
  tests/devworkspace-happy-path/resources/users.htpasswd
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: status/code-review, kind/task, target/branch

#20918 fix: publish che-e2e@next-7.y.x npm package on '7.y.x' branch commit
  .github/workflows/typescript-publish.yml
Labels: status/code-review, kind/task, target/branch

#20892 updated mocha version and fixed relevant files
  tests/e2e/mocha-all-devfiles.json
  tests/e2e/mocha-all-devfiles.opts
  tests/e2e/mocha-all-factories.json
  tests/e2e/mocha-all-factories.opts
  tests/e2e/mocha-all-plugins.json
  tests/e2e/mocha-all-plugins.opts
  tests/e2e/mocha-connector.json
  tests/e2e/mocha-connector.opts
  tests/e2e/mocha-devworkspace-happy-path.json
  tests/e2e/mocha-devworkspace-happy-path.opts
  tests/e2e/mocha-factory.json
  tests/e2e/mocha-factory.opts
  tests/e2e/mocha-git-publish-branch.json
  tests/e2e/mocha-git-publish-branch.opts
  tests/e2e/mocha-git-self-sign-cert.json
  tests/e2e/mocha-git-self-sign-cert.opts
  tests/e2e/mocha-git-ssh.json
  tests/e2e/mocha-git-ssh.opts
  tests/e2e/mocha-happy-path.json
  tests/e2e/mocha-happy-path.opts
  tests/e2e/mocha-java-vertx.json
  tests/e2e/mocha-java-vertx.opts
  tests/e2e/mocha-load.json
  tests/e2e/mocha-load.opts
  tests/e2e/mocha-single-devfile.json
  tests/e2e/mocha-single-devfile.opts
  tests/e2e/mocha-wkspc-creation-and-ls.json
  tests/e2e/mocha-wkspc-creation-and-ls.opts
  tests/e2e/mocha.intelij.json
  tests/e2e/mocha.intelij.opts
  tests/e2e/mocha.json
  tests/e2e/mocha.ocp.link.json
  tests/e2e/mocha.ocp.link.opts
  tests/e2e/mocha.opts
  tests/e2e/mocha.single.plugin.json
  tests/e2e/mocha.single.plugin.opts
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/bug, status/code-review, target/branch

#20930 disable auto-trigger of changelog; keep...
  .github/workflows/release-changelog.yml
Labels: kind/enhancement, status/code-review, target/branch

#20927 Replaced npm install with npm ci appropriately
  tests/e2e/README.md
  tests/e2e/build/dockerfiles/entrypoint.sh
  tests/e2e/initDevfileTests.sh
Labels: status/code-review, target/branch

#20924 Include checking of the debug fuctionality into happy path test
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: status/code-review, target/branch

#20932 Replaced npm install with npm ci appropriately
  tests/e2e/README.md
  tests/e2e/build/dockerfiles/entrypoint.sh
  tests/e2e/initDevfileTests.sh
Labels: status/code-review, target/branch

#20931 updated mocha version and fixed relevant files
  tests/e2e/mocha-all-devfiles.json
  tests/e2e/mocha-all-devfiles.opts
  tests/e2e/mocha-all-factories.json
  tests/e2e/mocha-all-factories.opts
  tests/e2e/mocha-all-plugins.json
  tests/e2e/mocha-all-plugins.opts
  tests/e2e/mocha-connector.json
  tests/e2e/mocha-connector.opts
  tests/e2e/mocha-devworkspace-happy-path.json
  tests/e2e/mocha-devworkspace-happy-path.opts
  tests/e2e/mocha-factory.json
  tests/e2e/mocha-factory.opts
  tests/e2e/mocha-git-publish-branch.json
  tests/e2e/mocha-git-publish-branch.opts
  tests/e2e/mocha-git-self-sign-cert.json
  tests/e2e/mocha-git-self-sign-cert.opts
  tests/e2e/mocha-git-ssh.json
  tests/e2e/mocha-git-ssh.opts
  tests/e2e/mocha-happy-path.json
  tests/e2e/mocha-happy-path.opts
  tests/e2e/mocha-java-vertx.json
  tests/e2e/mocha-java-vertx.opts
  tests/e2e/mocha-load.json
  tests/e2e/mocha-load.opts
  tests/e2e/mocha-single-devfile.json
  tests/e2e/mocha-single-devfile.opts
  tests/e2e/mocha-wkspc-creation-and-ls.json
  tests/e2e/mocha-wkspc-creation-and-ls.opts
  tests/e2e/mocha.intelij.json
  tests/e2e/mocha.intelij.opts
  tests/e2e/mocha.json
  tests/e2e/mocha.ocp.link.json
  tests/e2e/mocha.ocp.link.opts
  tests/e2e/mocha.opts
  tests/e2e/mocha.single.plugin.json
  tests/e2e/mocha.single.plugin.opts
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/bug, status/code-review, target/branch

#20942 fix: fix github release npmjs publishing
  .github/workflows/release.yml
Labels: kind/bug, status/code-review, target/branch

#20943 chore: as in plugin reg, add notes about...
  .github/workflows/release.yml
Labels: status/code-review, target/branch

#20948 Change names and strategy for avoiding potentials conflicts
  tests/devworkspace-happy-path/launch.sh
Labels: kind/enhancement, status/code-review, target/branch

#20970 Fix up 'GitSsh' E2E test related to last changes
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: status/code-review, kind/task, target/branch, team/che-qe, area/qe
