Repository eclipse-che/che, pull requests merged in 2021-04, with the labels that each got.

#19433 refactor(e2e Dashboard): fix Get Started button name
  tests/e2e/pageobjects/dashboard/Dashboard.ts
Labels: kind/bug, status/code-review

#19474 Create tests for the "Typescript" and "Node-debug2" plugins
  .gitignore
  tests/e2e/files/devfiles/plugins/TypescriptNodeDebug2PluginTest.yaml
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/utils/BrowserTabsUtil.ts
  tests/e2e/utils/DriverHelper.ts
Labels: kind/task, status/code-review

#19482 Fixing workspace stopping with new dashboard
  tests/e2e/pageobjects/dashboard/Workspaces.ts
Labels: kind/bug, status/code-review

#19481 Fix workspace stopping with new Dashboard - backport to 7.28
  tests/e2e/pageobjects/dashboard/Workspaces.ts
Labels: kind/task, status/code-review, target/branch

#19471 Upgrade guava and related dependencies to fix potential security issues
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  core/commons/che-core-commons-mail/pom.xml
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/Attachment.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/EmailBean.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/MailSender.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/MailSessionProvider.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/SendMailException.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/template/ST/STTemplateProcessorImpl.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/template/Template.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/template/TemplateProcessor.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/template/exception/TemplateException.java
  core/commons/che-core-commons-mail/src/main/java/org/eclipse/che/mail/template/exception/TemplateNotFoundException.java
  core/commons/che-core-commons-mail/src/test/java/org/eclipse/che/mail/MailSenderTest.java
  core/commons/che-core-commons-mail/src/test/resources/logback-test.xml
  core/commons/pom.xml
  multiuser/api/che-multiuser-api-organization/pom.xml
  multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/OrganizationApiModule.java
  multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/notification/OrganizationEmailNotifications.java
  multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/notification/OrganizationNotificationEmailSender.java
  multiuser/api/che-multiuser-api-organization/src/test/java/org/eclipse/che/multiuser/organization/api/notification/OrganizationEmailNotificationsTest.java
  multiuser/api/che-multiuser-api-organization/src/test/java/org/eclipse/che/multiuser/organization/api/notification/OrganizationNotificationEmailSenderTest.java
  pom.xml
  wsmaster/che-core-api-system/src/main/java/org/eclipse/che/api/system/server/JvmManager.java
Labels: kind/bug, status/code-review

#19501 Update tomcat to the latest bugfix version 8.5.64
  pom.xml
Labels: kind/bug, status/code-review

#19509 Disable selenium tests
  pom.xml
Labels: kind/task, status/code-review

#19496 Add @Katka92 and @ScrewTSW to code owners of /tests/e2e
  .github/CODEOWNERS
Labels: kind/enhancement, status/code-review

#19409 Deprecate namespace strategies other than 'per user'
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/pom.xml
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
Labels: kind/task, status/code-review

#19533 Enable the Vale plugin test
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
Labels: kind/task, status/code-review

#19552 Include JSON schema for devfile 2.1.0-alpha
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/Constants.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/2.1.0-alpha/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-1-0-alpha_just_schemaVersion.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-1-0-alpha_simple-devfile.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-1-0-alpha_unsupported_schemaVersion.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-1-0-alpha_with_invalid_plugin_definition.yaml
Labels: kind/task, status/code-review

#19558 Fix e2e tests after GetStarted -> CreateWorkspace
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/dashboard/CreateWorkspace.ts
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/tests/devfiles/CSlashCPlusPlus.spec.ts
  tests/e2e/tests/devfiles/DevfileSmoke.spec.ts
  tests/e2e/tests/devfiles/DotNetCore.spec.ts
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaSpringBoot.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/NodeJS.spec.ts
  tests/e2e/tests/devfiles/PHPSimple.spec.ts
  tests/e2e/tests/devfiles/Python.spec.ts
  tests/e2e/tests/devfiles/PythonDjango.spec.ts
  tests/e2e/tests/devfiles/Quarkus.spec.ts
  tests/e2e/tests/devfiles/Scala.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithKeepDirectoryTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithRootFolderTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithSpecificBranchTest.spec.ts
  tests/e2e/tests/e2e/FactoryUrl.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
Labels: kind/bug, status/code-review

#19553 Update to traefik 2.3.2 using new quay.io image
  deploy/kubernetes/helm/che/custom-charts/che-gateway/values.yaml
Labels: kind/enhancement, status/code-review

#19195 Added support for s390x in che.properties for workspace
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#19510 Create test for covering the "Php" and "Php-debug" plugins
  tests/e2e/files/devfiles/plugins/PhpPluginTest.yaml
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
Labels: kind/task, status/code-review

#19497 Create E2E test for checking the "python" plugin
  tests/e2e/files/devfiles/plugins/PythonPluginTest.yaml
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
Labels: kind/task, status/code-review

#19535 [E2E test] Do fix up 'OpenshiftConnector' e2e test according to last changes
  tests/e2e/pageobjects/ide/OpenWorkspaceWidget.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
Labels: area/qe, e2e-test/failure, kind/bug, status/code-review, team/che-qe

#19511 [Selenium] Do workaround in 'GitSsh' E2E test
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: area/qe, e2e-test/failure, kind/task, status/code-review

#19263 Language review on che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: status/code-review

#19587 Remove deployment to Nexus of Maven artifacts
  .github/workflows/release.yml
  make-release.sh
Labels: kind/task, status/code-review

#19560 Update README.md and RELEASE.md
  README.md
  RELEASE.md
Labels: kind/enhancement, status/code-review

#19600 Restore defaults of `che.factory.default_editor` property
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/bug, status/code-review

#19561 explicitly specify jre dockerimage registry
  dockerfiles/che/Dockerfile
Labels: status/code-review

#19608 Rework "plugins" tests for using devfiles from the "Che" repository
  tests/e2e/files/devfiles/plugins/VscodeKubernetesPlugin.yaml
  tests/e2e/files/devfiles/plugins/VscodeShellcheckPlugin.yaml
  tests/e2e/files/devfiles/plugins/VscodeValePlugin.yaml
  tests/e2e/files/devfiles/plugins/VscodeXmlPlugin.yaml
  tests/e2e/files/devfiles/plugins/VscodeYamlPlugin.yaml
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: kind/task, status/code-review

#19629 if we re-release Che server, we should NOT...
  .github/workflows/release.yml
Labels: status/code-review

#19615 Update dependencies versions
  dockerfiles/e2e/Dockerfile
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/enhancement, status/code-review

#19616 Che server configuration integrity test
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties
  assembly/assembly-wsmaster-war/src/test/java/org/eclipse/che/integration/IntegrityConfigurationTest.java
  core/che-core-db/src/main/java/org/eclipse/che/core/db/schema/impl/flyway/FlywaySchemaInitializer.java
  multiuser/api/che-multiuser-api-authorization/pom.xml
  multiuser/api/che-multiuser-api-authorization/src/main/java/org/eclipse/che/multiuser/api/permission/server/HttpPermissionCheckerImpl.java
  multiuser/api/che-multiuser-api-workspace-activity/pom.xml
  multiuser/api/che-multiuser-api-workspace-activity/src/main/java/org/eclipse/che/multiuser/api/workspace/activity/MultiUserWorkspaceActivityManager.java
  wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth1/BitbucketServerOAuthAuthenticatorProvider.java
Labels: status/code-review

#19518 Validation of Bitbucket personal access token before usage
  infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java
  infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManagerTest.java
  wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth1/NoopOAuthAuthenticator.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticator.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/AuthorizationHeaderSupplier.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/BitbucketServerApiClient.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/HttpBitbucketServerApiClient.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/NoopBitbucketServerApiClient.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/security/oauth1/BitbucketServerApiProvider.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/security/oauth1/BitbucketServerOAuth1AuthorizationHeaderSupplier.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcherTest.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/security/oauth1/BitbucketServerOAuth1AuthorizationHeaderSupplierTest.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenFetcher.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenManager.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/ScmPersonalAccessTokenFetcher.java
Labels: kind/bug, status/code-review

#19655 Temporary disables test to fix issues on CI.
  core/che-core-typescript-dto-maven-plugin/src/it/java/org/eclipse/che/plugin/typescript/dto/TypeScriptDTOGeneratorMojoTST.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
Labels: kind/bug, status/code-review

#19635 Include Typescript DTO into release process
  make-release.sh
  typescript-dto/build.sh
  typescript-dto/dto-pom.xml
Labels: status/code-review

#19676 Send notification in Mattermost when nightly build fails
  .github/workflows/nightly-build.yml
Labels: status/code-review

#19521 Gitlab factory authentication using OAuth 2 flow
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  wsmaster/che-core-api-factory-gitlab/pom.xml
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabApiClient.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProvider.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabModule.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOauthTokenInfo.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUser.java
  wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabApiClientTest.java
  wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcherTest.java
  wsmaster/che-core-api-factory-gitlab/src/test/resources/__files/gitlab/rest/api/v4/user/response.json
  wsmaster/che-core-api-factory-gitlab/src/test/resources/__files/gitlab/rest/api/v4/user/token_info.json
  wsmaster/che-core-api-factory-gitlab/src/test/resources/__files/gitlab/rest/api/v4/user/token_info_lack_scopes.json
  wsmaster/che-core-api-factory-gitlab/src/test/resources/logback-test.xml
Labels: kind/task, status/code-review

#19681 Upgrade commons io to latest 2.8.0
  pom.xml
Labels: status/code-review

#19694 Upgrade swagger to latest 1.6.2
  pom.xml
Labels: kind/bug, status/code-review

#19620 Improving flow when user denies Bitbucket access to Che
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticationException.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticationService.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticator.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/UserDeniedOAuthAuthenticationException.java
Labels: kind/task, status/code-review

#19701 Fix broken nightly job
  .github/workflows/nightly-build.yml
Labels: kind/task, status/code-review

#19606 Adapt dashboard tests to moving dashboard to a separate deployment
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
Labels: kind/task, status/code-review

#19712 Set petclinic version to 2.4.5 in Happy path tests
  tests/e2e/files/happy-path/happy-path-workspace.yaml
Labels: status/code-review

#19713 Sync java version between CI and che-server image and set to java 11.0.11_9
  .github/workflows/build-pr-check.yml
  .github/workflows/nightly-build.yml
  .github/workflows/release.yml
  .github/workflows/sonar.yaml
  dockerfiles/che/Dockerfile
Labels: kind/bug, status/code-review

#19725 feat(vscode-extensions): Add vscode-commons as default plug-in
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/task, status/code-review
