Repository eclipse-che/che, pull requests merged in 2021-05, with the labels that each got.

#19715 Removed SCM user name from git credential secret name
  infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManager.java
  infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManagerTest.java
Labels: status/code-review

#19723 Tests for oauth flow improvement with bitbucket
  wsmaster/che-core-api-auth/pom.xml
  wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth1/OAuthAuthenticationServiceTest.java
  wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth1/OAuthAuthenticatorTest.java
Labels: kind/task, status/code-review

#19748 Added missing unit for che.limits.workspace.idle.timeout che-server's property
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
Labels: kind/enhancement, status/code-review

#19651 Add role for metrics
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/AbstractWorkspaceServiceAccount.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
Labels: kind/bug, status/code-review

#19747 Refactor testsLibs to use classes and add them to inversify
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/tests/devfiles/CSlashCPlusPlus.spec.ts
  tests/e2e/tests/devfiles/DevfileSmoke.spec.ts
  tests/e2e/tests/devfiles/DotNetCore.spec.ts
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaSpringBoot.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/NodeJS.spec.ts
  tests/e2e/tests/devfiles/PHPSimple.spec.ts
  tests/e2e/tests/devfiles/Python.spec.ts
  tests/e2e/tests/devfiles/PythonDjango.spec.ts
  tests/e2e/tests/devfiles/Quarkus.spec.ts
  tests/e2e/tests/devfiles/Scala.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithKeepDirectoryTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithRootFolderTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithSpecificBranchTest.spec.ts
  tests/e2e/tests/e2e/FactoryUrl.spec.ts
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
  tests/e2e/testsLibrary/LanguageServerTests.ts
  tests/e2e/testsLibrary/LsTests.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
  tests/e2e/utils/requestHandlers/CheApiRequestHandler.ts
Labels: area/qe, kind/enhancement, severity/P1, status/code-review, team/che-qe

#19759 [Selenium] Remove workaround from 'GitSsh' E2E test
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#19761 Remove TS_SELENIUM_MULTIUSER variable.
  tests/e2e/TestConstants.ts
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/pageobjects/login/SingleUserLoginPage.ts
  tests/e2e/utils/requestHandlers/headers/CheSingleUserAuthorizationHeaderHandler.ts
Labels: status/code-review

#19768 [Selenium] Update 'GitSsh' E2E test to expand cloned project
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#19766 Automate testing Plugins view from the IDE
  tests/e2e/TimeoutConstants.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/ide/TopMenu.ts
  tests/e2e/pageobjects/ide/plugins/PluginsView.ts
  tests/e2e/tests/plugins/InstallPluginUsingUI.spec.ts
Labels: kind/task, status/code-review

#19785 Rework plugin tests for the openshift CI
  tests/e2e/TestConstants.ts
  tests/e2e/package.json
  tests/e2e/pageobjects/ide/plugins/PluginsView.ts
  tests/e2e/tests/plugins/InstallPluginUsingUI.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: kind/task, status/code-review

#19763 Remove code that supports namespace strategies other than per-user
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/AsyncStorageModeValidator.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/AsyncStoragePodWatcher.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/AsyncStorageModeValidatorTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/AsyncStoragePodWatcherTest.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfrastructure.java
  infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
  infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
  multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilter.java
  multiuser/permission/che-multiuser-permission-workspace/src/test/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilterTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/RuntimeInfrastructure.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/task, status/code-review

#19791 use dynamic port for tests using WireMockServer
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProviderTest.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java
  wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabApiClientTest.java
  wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcherTest.java
Labels: status/code-review

#19794 [Selenium] Do workaround related to open 'Find Command' container
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: e2e-test/failure, kind/bug, status/code-review, team/che-qe

#19752 Fixup SCM URL matching sometimes fails
  infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManager.java
  infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java
  infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManagerTest.java
  infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManagerTest.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/security/oauth1/BitbucketServerApiProvider.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/security/oauth1/BitbucketServerApiClientProviderTest.java
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUrl.java
  wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java
  wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcherTest.java
Labels: kind/bug, status/code-review

#19798 [Selenium] Update 'happy-path' files to run 'Happy-path' E2E test on Che 'single-host'
  tests/e2e/files/happy-path/happy-path-workspace.yaml
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: area/qe, e2e-test/failure, kind/task, status/code-review, team/che-qe

#19801 [Selenium] Update path to che-dashboard Dockerfile
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
Labels: area/qe, status/code-review

#19802 [Selenium] Fix Dockerfile path in che-dashboard Jenkinsfile
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
Labels: area/qe, kind/bug, status/code-review

#19443 Move CRW Jenkins CI testing pipelines to new CRW Jenkins CI repo
  .github/CODEOWNERS
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
  tests/.infra/crw-ci/master/k8s/Jenkinsfile
  tests/.infra/crw-ci/nightly/k8s/multi-host/Jenkinsfile
  tests/.infra/crw-ci/nightly/k8s/single-host/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/.infra/crw-ci/release-testing/k8s/Jenkinsfile
Labels: status/code-review

#19812 Fix e2e dashboard tests
  tests/e2e/pageobjects/dashboard/CreateWorkspace.ts
Labels: kind/bug, status/code-review

#19542 Drop dashboard resources from Che server image
  .github/workflows/nightly-build.yml
  assembly/assembly-dashboard-war/pom.xml
  assembly/assembly-dashboard-war/src/main/webapp/WEB-INF/web.xml
  assembly/assembly-main/pom.xml
  assembly/assembly-main/src/assembly/assembly.xml
  assembly/pom.xml
  dockerfiles/che/Dockerfile
  dockerfiles/dashboard-dev/Dockerfile
  dockerfiles/dashboard-dev/README.md
  dockerfiles/dashboard-dev/build.sh
  dockerfiles/dashboard-dev/src/entrypoint.sh
  make-release.sh
  pom.xml
  tests/.infra/centos-ci/functional_tests_utils.sh
Labels: kind/task, status/code-review

#19826 [Selenium] Create a test for 'git self sign cert' test case
  tests/e2e/mocha-git-self-sign-cert.opts
  tests/e2e/package.json
  tests/e2e/tests/e2e/GitSelfSignCert.spec.ts
Labels: area/qe, kind/task, status/code-review, target/branch

#19830 feat(devfile): Update devfile 2.1 schema to the revision used by DevWorkspace Operator
  wsmaster/che-core-api-workspace/src/main/resources/schema/2.1.0-alpha/devfile.json
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-1-0-alpha_simple-devfile.yaml
Labels: status/code-review

#19842 Restore files that were removed by mistake
  .repositories-update-contributing.sh
  .repositories.yaml
Labels: status/code-review

#19787 Migrated debug logic from downstream, add missing logic and refactored happy-path
  tests/e2e/TestConstants.ts
  tests/e2e/driver/CheReporter.ts
  tests/e2e/index.ts
  tests/e2e/mocha-happy-path.opts
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/tests/devfiles/CSlashCPlusPlus.spec.ts
  tests/e2e/tests/devfiles/DotNetCore.spec.ts
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaSpringBoot.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/NodeJS.spec.ts
  tests/e2e/tests/devfiles/PHPSimple.spec.ts
  tests/e2e/tests/devfiles/Python.spec.ts
  tests/e2e/tests/devfiles/Quarkus.spec.ts
  tests/e2e/tests/devfiles/Scala.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/login/Login.spec.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
  tests/e2e/testsLibrary/LanguageServerTests.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
Labels: kind/enhancement, severity/P1, status/code-review, target/branch

#19849 Update README.md
  README.md
Labels: kind/enhancement, status/code-review, target/branch

#19848 Cherry-pick 19787 to che 7.30.x
  tests/e2e/TestConstants.ts
  tests/e2e/driver/CheReporter.ts
  tests/e2e/index.ts
  tests/e2e/mocha-happy-path.opts
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/tests/devfiles/CSlashCPlusPlus.spec.ts
  tests/e2e/tests/devfiles/DotNetCore.spec.ts
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaSpringBoot.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/NodeJS.spec.ts
  tests/e2e/tests/devfiles/PHPSimple.spec.ts
  tests/e2e/tests/devfiles/Python.spec.ts
  tests/e2e/tests/devfiles/Quarkus.spec.ts
  tests/e2e/tests/devfiles/Scala.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/login/Login.spec.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
  tests/e2e/testsLibrary/LanguageServerTests.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
Labels: kind/enhancement, severity/P1, status/code-review, target/branch

#19857 Fixing incorrect import in index.ts
  tests/e2e/index.ts
Labels: kind/bug, severity/blocker, status/code-review, target/branch

#19865 Fix e2e dashboard create workspace page objects
  tests/e2e/pageobjects/dashboard/CreateWorkspace.ts
Labels: kind/bug, status/code-review, target/branch

#19844 docs: Fix links after repository move
  .github/ISSUE_TEMPLATE/release.md
  .repositories.yaml
  CONTRIBUTING.md
  tests/e2e/README.md
Labels: kind/task, status/code-review, target/branch

#19863 Create automated test for the GitHub PR plugin
  tests/e2e/TestConstants.ts
  tests/e2e/files/devfiles/plugins/GitHubPullRequestPlugin.yaml
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/ide/plugins/GitHubPullRequestPlugin.ts
  tests/e2e/pageobjects/third-parties/GitLoginPage.ts
  tests/e2e/pageobjects/third-parties/GitOauthAppsSettings.ts
  tests/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts
  tests/e2e/utils/KeycloackUrlHandler.ts
  tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts
Labels: status/code-review, target/branch

#19862 Move e2e dockerfiles back to eclipse/che repository
  dockerfiles/e2e/Dockerfile
  dockerfiles/e2e/README.md
  dockerfiles/e2e/build.sh
  dockerfiles/e2e/entrypoint.sh
  dockerfiles/e2e/google-chrome.repo
Labels: status/code-review, target/branch

#19876 Add release workflow
  .github/workflows/release.yml
  make-release.sh
Labels: kind/enhancement, status/code-review, target/branch

#19884 The nightly che-plugin-registry job fails on the "InstallPluginUsingUI" test
  tests/e2e/files/devfiles/plugins/InstallPluginUsingUI.yaml
  tests/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts
  tests/e2e/tests/plugins/InstallPluginUsingUI.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: status/code-review, target/branch
