Repository eclipse-che/che, pull requests merged in 2021-07, with the labels that each got.

#20062 Reload page if there is no debug configuration in Happy path test
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review, target/branch

#20079 The "TypescriptPlugin" fails because of no debug config displays
  tests/e2e/TimeoutConstants.ts
  tests/e2e/files/devfiles/plugins/TypescriptNodeDebug2PluginTest.yaml
  tests/e2e/pageobjects/ide/DebugView.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
Labels: kind/task, status/code-review, target/branch

#20091 [Selenium] Add GitSelfSignCert typescript test to 7.32.x branch
  tests/e2e/TestConstants.ts
  tests/e2e/mocha-git-self-sign-cert.opts
  tests/e2e/package.json
  tests/e2e/tests/e2e/GitSelfSignCert.spec.ts
Labels: area/qe, status/code-review, target/branch

#20102 Update Go.spec.ts
  tests/e2e/tests/devfiles/Go.spec.ts
Labels: kind/bug, status/code-review, target/branch

#20103 ci: Remove nightly images build
  .github/workflows/next-build.yml
  .github/workflows/nightly-build.yml
Labels: kind/epic, kind/task, status/code-review, target/branch

#20141 Fix workspace creation and debug profiles for devsandbox periodic tests
  tests/e2e/pageobjects/dashboard/CreateWorkspace.ts
  tests/e2e/testsLibrary/LanguageServerTests.ts
Labels: kind/bug, status/code-review, target/branch

#20179 chore: Fix some lint issues for tests
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
Labels: kind/bug, status/code-review, target/branch

#20214 chore: Update Mattermost GH Action to 1.1.0 version
  .github/workflows/next-build.yml
  .github/workflows/release.yml
Labels: kind/release, kind/task, status/code-review, target/branch

#20206 [Selenium] Create test for check git with self sign certs
  tests/e2e/TestConstants.ts
  tests/e2e/mocha-git-self-sign-cert.opts
  tests/e2e/package.json
  tests/e2e/tests/e2e/GitSelfSignCert.spec.ts
Labels: area/qe, kind/task, sprint/current, status/code-review, target/branch
