Repository eclipse-che/che, pull requests merged in 2021-02, with the labels that each got.

#18893 Don't use a custom requestbody impl when resending the data to k8s
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/DirectKubernetesAPIAccessHelper.java
Labels: kind/bug, status/code-review

#18868 Gh18838 factory devfile2
  multiuser/permission/che-multiuser-permission-devfile/src/test/java/org/eclipse/che/multiuser/permission/devfile/server/filters/UserDevfilePermissionsFilterTest.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileServiceTest.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolver.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolverTest.java
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
  wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java
  wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/dto/FactoryDevfileV2Dto.java
  wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/dto/FactoryDto.java
  wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/dto/FactoryMetaDto.java
  wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/dto/FactoryVisitor.java
  wsmaster/che-core-api-factory/pom.xml
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolver.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryAcceptValidator.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryLinksHelper.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryParametersResolver.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/impl/FactoryAcceptValidatorImpl.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/impl/FactoryBaseValidator.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolverTest.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileParser.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileVersionDetector.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidator.java
  wsmaster/che-core-api-workspace/src/main/resources/schema/2.0.0/devfile.json
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/DevfileVersionTest.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2_invalid_schemaVersion.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2_just_schemaVersion.yaml
  wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2_unsupported_schemaVersion.yaml
Labels: kind/task, status/code-review

#18909 Add release workflow for che parent and server
  .github/workflows/release.yml
  make-release.sh
Labels: kind/task, status/code-review

#18949 don't run sonar on PRs as it is not working
  .github/workflows/sonar.yaml
Labels: status/code-review

#18997 Set ProxyAuthenticator during workspace start up checks
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/HttpConnectionServerChecker.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/hc/HttpConnectionServerCheckerTest.java
Labels: status/code-review

#18996 include default editor and plugins in /workspace/settings
  wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/Constants.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
Labels: kind/enhancement, status/code-review

#18983 The "Happy Path" test fails on the "Wait error highlighting" step
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review

#18915 che #18914 Adding 'ReplicaSetCreateError' to the list of the unrecoverable events
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
Labels: kind/enhancement, status/code-review

#18836 tweaks to readme links
  README.md
Labels: status/code-review

#18985 Quick fix for Quarkus CLI until the devfile itself is fixed
  tests/e2e/tests/devfiles/Quarkus.spec.ts
Labels: kind/bug, status/code-review

#18988 Fix release workflow
  .github/workflows/release.yml
  make-release.sh
Labels: kind/bug, status/code-review

#19032 Temporarily disabling Scala:sbt test to allow more stable pre-release suite
  tests/e2e/tests/devfiles/Scala.spec.ts
Labels: kind/bug, status/code-review

#19009 Register custom keystore in all cases;
  dockerfiles/che/entrypoint.sh
Labels: kind/bug, status/code-review

#19010 update justify library to 3.1.0
  pom.xml
  wsmaster/che-core-api-workspace/pom.xml
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidator.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
Labels: kind/bug, status/code-review

#19043 /devfile version parameter to provide concrete schema version
  core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/IoUtil.java
  multiuser/permission/che-multiuser-permission-devfile/src/test/java/org/eclipse/che/multiuser/permission/devfile/server/filters/UserDevfilePermissionsFilterTest.java
  wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/DevfileService.java
  wsmaster/che-core-api-devfile/src/test/java/org/eclipse/che/api/devfile/server/DevfileServiceTest.java
  wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/schema/DevfileSchemaProvider.java
  wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/schema/DevfileSchemaProviderTest.java
Labels: kind/enhancement, status/code-review

#19048 Fix E2E Happy path tests to pass debug verification step
  tests/e2e/files/happy-path/containers-happy-path.yaml
  tests/e2e/pageobjects/ide/DebugView.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review

#19046 [backport] Register custom keystore in all cases;
  dockerfiles/che/entrypoint.sh
Labels: kind/bug, status/code-review, target/branch

#18717 Remove customizing section
  dockerfiles/README.md
Labels: kind/enhancement, status/code-review

#19031 Do not mount ssh keys as secrets if the name is not a valid Kubernetes config map key name
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Warnings.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesObjectUtil.java
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SshKeysProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesObjectUtilTest.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/SshKeySecretProvisionerTest.java
Labels: kind/bug, status/code-review

#19005 [Selenium] Add factories typescript selenium tests
  tests/e2e/mocha-all-factories.opts
  tests/e2e/package.json
  tests/e2e/tests/e2e/DirectUrlFactoryWithKeepDirectoryTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithRootFolderTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithSpecificBranchTest.spec.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: area/qe, kind/task, status/code-review

#19086 Fix release parameters
  .github/workflows/release.yml
  make-release.sh
Labels: kind/bug, status/code-review

#19077 [Selenium] Update 'GitSsh' E2E typescript test
  tests/e2e/TimeoutConstants.ts
  tests/e2e/pageobjects/ide/DebugView.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/tests/e2e/GitSsh.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#19047 Correct response codes and messages related to private factory flow
  core/che-core-api-core/src/main/java/org/eclipse/che/api/core/ErrorCodes.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/workspace/ErrorCodes.java
  multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/workspace/LimitExceededException.java
  wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth1/BitbucketServerOAuthAuthenticator.java
  wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth1/NoopOAuthAuthenticator.java
  wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticator.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolver.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/BitbucketServerApiClient.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/HttpBitbucketServerApiClient.java
  wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/security/oauth1/BitbucketServerOAuth1AuthorizationHeaderSupplier.java
  wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcherTest.java
  wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolver.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryParametersResolver.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/exception/ScmUnauthorizedException.java
  wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
  wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
Labels: kind/task, status/code-review

#19068 Work around error highlighting and run application failures in Happy path tests
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
  tests/e2e/TimeoutConstants.ts
  tests/e2e/files/happy-path/happy-path-workspace.yaml
  tests/e2e/pageobjects/ide/DebugView.ts
  tests/e2e/pageobjects/ide/Ide.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review

#19094 Fix build of Eclipse Che in PR Happy path tests
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#19095 Fix build of Eclipse Che in Dashboard Next happy path tests
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
Labels: kind/bug, status/code-review

#19103 Improve fixup of Eclipse Che build in PR Happy path tests
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#19096 Set public url for public keycloak endpoints
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProviderTest.java
Labels: status/code-review

#19108 Set public url for public keycloak endpoints (#19096)
  multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProvider.java
  multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProviderTest.java
Labels: status/code-review, target/branch

#19113 [Selenium] Stabilize 'GitSsh' E2E test to downstream project
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: area/qe, kind/task, status/code-review, target/branch, team/che-qe

#19117 [Selenium] Fix up 'GitSsh' to waiting start workspace
  tests/e2e/pageobjects/ide/DebugView.ts
  tests/e2e/tests/e2e/GitSsh.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#19118 [Selenium] Update 'OpenshiftConnector' E2E typescript test
  tests/e2e/TimeoutConstants.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#19075 Change cert-manager api version
  deploy/cert-manager/che-certificate.yml
  deploy/cert-manager/che-cluster-issuer.yml
Labels: kind/enhancement, status/code-review

#19063 add che-docs step; refactor table to drop...
  .github/ISSUE_TEMPLATE/release.md
Labels: kind/enhancement, status/code-review

#19017 Fix error message when workspace has invalid async storage config
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/AsyncStorageProvisioner.java
  infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/AsyncStorageProvisionerTest.java
Labels: kind/bug, status/code-review

#18998 [helm chart] Add RBAC templates for the resource-monitor.
  deploy/kubernetes/helm/che/templates/resource-monitor-role-binding.yaml
  deploy/kubernetes/helm/che/templates/resource-monitor-role.yaml
Labels: kind/enhancement, status/code-review

#19087 Fix pod watching manner to prevent events from other pods to cancel the waiting
  infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
Labels: kind/bug, status/code-review

#19132 jackson-databind update version to 2.10.5.1
  pom.xml
Labels: status/code-review

#19138 [Selenium] Update 'GitSsh' E2E test according to last changes
  tests/e2e/tests/e2e/GitSsh.spec.ts
Labels: area/qe, kind/task, status/code-review, team/che-qe

#19139 Cover the "Kubernetes" plugin by the e2e test
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/mocha.single.plugin.opts
  tests/e2e/package.json
  tests/e2e/pageobjects/ide/LeftToolBar.ts
  tests/e2e/pageobjects/ide/RightToolBar.ts
  tests/e2e/pageobjects/ide/TopMenu.ts
  tests/e2e/pageobjects/ide/plugins/KubernetesPlugin.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/utils/PreferencesHandler.ts
Labels: kind/enhancement, kind/task, status/code-review

#19152 [Selenium] Add DevWorkspaceHappyPath e2e typescript test
  tests/e2e/TestConstants.ts
  tests/e2e/mocha-devworkspace-happy-path.opts
  tests/e2e/package.json
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: area/qe, kind/task, status/code-review

#19144 Push che-server/che-dashboard images to quay.io/crw_pr when run Happy path PR tests
  tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
  tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
Labels: kind/bug, status/code-review

#19164 [Selenium] Fixup comment in the 'DevWorkspaceHappyPath' test
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: area/qe, e2e-test/failure, kind/task, status/code-review, team/che-qe
