Repository eclipse-che/che, pull requests merged in 2021-06, with the labels that each got.

#19904 Fix release workflow
  .github/workflows/release.yml
  dockerfiles/e2e/build.sh
  make-release.sh
Labels: kind/bug, status/code-review, target/branch

#19907 Add nightly and next builds for e2e image
  .github/workflows/next-build.yml
  .github/workflows/nightly-build.yml
Labels: kind/task, status/code-review, target/branch

#19913 ci: Fix nightly & next container image build & push jobs
  .github/workflows/next-build.yml
  .github/workflows/nightly-build.yml
Labels: kind/bug, status/code-review, target/branch

#19928 [Selenium] Add devworkspace happy-path test yaml file
  tests/.infra/openshift-ci/pod-che-happy-path.yaml
Labels: area/qe, kind/task, status/code-review, target/branch

#19909 Stabilize check of build and run application in Happy path tests
  tests/.infra/centos-ci/common-qe/README.md
  tests/.infra/centos-ci/common-qe/che-util.sh
  tests/.infra/centos-ci/common-qe/common-qe-configuration.conf
  tests/.infra/centos-ci/common-qe/downloader.sh
  tests/.infra/centos-ci/functional_tests_utils.sh
  tests/.infra/centos-ci/nightly/cico-openshift-connector-test.sh
  tests/e2e/TimeoutConstants.ts
  tests/e2e/pageobjects/ide/PreviewWidget.ts
  tests/e2e/pageobjects/ide/TopMenu.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
Labels: kind/bug, status/code-review, target/branch

#19963 Rework the "GitHubPullRequestPlugin" test to make PR instead of checking existing one
  tests/e2e/TimeoutConstants.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/ide/TopMenu.ts
  tests/e2e/pageobjects/ide/plugins/GitHubPullRequestPlugin.ts
  tests/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts
  tests/e2e/utils/AnimationChecker.ts
Labels: kind/task, status/code-review, target/branch

#19919 Fixing workspace deletion logic to enable parallel test run
  tests/e2e/TestConstants.ts
  tests/e2e/driver/CheReporter.ts
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/tests/devfiles/CSlashCPlusPlus.spec.ts
  tests/e2e/tests/devfiles/DevfileSmoke.spec.ts
  tests/e2e/tests/devfiles/DotNetCore.spec.ts
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaSpringBoot.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/NodeJS.spec.ts
  tests/e2e/tests/devfiles/PHPSimple.spec.ts
  tests/e2e/tests/devfiles/Python.spec.ts
  tests/e2e/tests/devfiles/PythonDjango.spec.ts
  tests/e2e/tests/devfiles/Quarkus.spec.ts
  tests/e2e/tests/devfiles/Scala.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithKeepDirectoryTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithRootFolderTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithSpecificBranchTest.spec.ts
  tests/e2e/tests/e2e/FactoryUrl.spec.ts
  tests/e2e/tests/e2e/GitPublishBranch.spec.ts
  tests/e2e/tests/e2e/GitSsh.spec.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/intelij/IntelijOpenWorkspace.spec.ts
  tests/e2e/tests/load_test/LoadTest.spec.ts
  tests/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts
  tests/e2e/tests/plugins/InstallPluginUsingUI.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
  tests/e2e/utils/AnimationChecker.ts
  tests/e2e/utils/WorkspaceNameHandler.ts
  tests/e2e/utils/workspace/ITestWorkspaceUtil.ts
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/bug, status/in-progress, target/branch

#19974 Backporting workspace name handler and workspace deletion fix
  tests/e2e/TestConstants.ts
  tests/e2e/driver/CheReporter.ts
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/tests/devfiles/CSlashCPlusPlus.spec.ts
  tests/e2e/tests/devfiles/DevfileSmoke.spec.ts
  tests/e2e/tests/devfiles/DotNetCore.spec.ts
  tests/e2e/tests/devfiles/Go.spec.ts
  tests/e2e/tests/devfiles/JavaMaven.spec.ts
  tests/e2e/tests/devfiles/JavaSpringBoot.spec.ts
  tests/e2e/tests/devfiles/JavaVertx.spec.ts
  tests/e2e/tests/devfiles/NodeJS.spec.ts
  tests/e2e/tests/devfiles/PHPSimple.spec.ts
  tests/e2e/tests/devfiles/Python.spec.ts
  tests/e2e/tests/devfiles/PythonDjango.spec.ts
  tests/e2e/tests/devfiles/Quarkus.spec.ts
  tests/e2e/tests/devfiles/Scala.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithKeepDirectoryTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithRootFolderTest.spec.ts
  tests/e2e/tests/e2e/DirectUrlFactoryWithSpecificBranchTest.spec.ts
  tests/e2e/tests/e2e/FactoryUrl.spec.ts
  tests/e2e/tests/e2e/GitPublishBranch.spec.ts
  tests/e2e/tests/e2e/GitSsh.spec.ts
  tests/e2e/tests/e2e/OpenshiftConnector.spec.ts
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
  tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts
  tests/e2e/tests/intelij/IntelijOpenWorkspace.spec.ts
  tests/e2e/tests/load_test/LoadTest.spec.ts
  tests/e2e/tests/plugins/JavaPlugin.spec.ts
  tests/e2e/tests/plugins/PhpPlugin.spec.ts
  tests/e2e/tests/plugins/PythonPlugin.spec.ts
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeKubernetesPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeShellcheckPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/tests/plugins/VscodeXmlPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
  tests/e2e/utils/WorkspaceNameHandler.ts
  tests/e2e/utils/workspace/ITestWorkspaceUtil.ts
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/bug, status/code-review, target/branch

#19994 Cherry-picking WorkspaceTestUtil fix from 7.30.x to main
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/bug, status/code-review, target/branch

#19993 Refactored stop workspace request
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: status/code-review, target/branch

#20002 refactor: Update Che-Theia's `master` branch mentioning to `main`
  .github/ISSUE_TEMPLATE/release.md
  .repositories.yaml
  CONTRIBUTING.md
Labels: kind/task, status/code-review, target/branch

#20015 Hotfix for Editor getLineYCoordinates
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/pageobjects/ide/PreviewWidget.ts
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/bug, status/code-review, target/branch

#20016 [BACKPORT] Hotfix for Editor getLineYCoordinates
  tests/e2e/pageobjects/ide/Editor.ts
  tests/e2e/pageobjects/ide/PreviewWidget.ts
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/bug, status/code-review, target/branch

#20012 fix: move dashboard contributing to its repo
  CONTRIBUTING.md
Labels: kind/task, status/code-review, target/branch

#20030 Fix e2e dashboard create workspace page objects
  tests/e2e/pageobjects/dashboard/CreateWorkspace.ts
Labels: kind/bug, status/code-review, target/branch

#20039 Fix Terminal.waitIconSuccess log spam in TRACE mode
  tests/e2e/index.ts
  tests/e2e/pageobjects/ide/Terminal.ts
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/enhancement, status/code-review, target/branch

#20047 Backporting fix by vbahdano
  tests/e2e/index.ts
  tests/e2e/pageobjects/ide/Terminal.ts
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/enhancement, status/code-review, target/branch

#20048 Fixed logic errors regarding obtaining the preview widget URL
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/bug, status/code-review, target/branch

#20050 Fixed logic errors regarding obtaining the preview widget URL
  tests/e2e/pageobjects/ide/PreviewWidget.ts
  tests/e2e/testsLibrary/CodeExecutionTests.ts
Labels: kind/bug, status/code-review, target/branch

#20051 Fixed logic errors regarding obtaining the preview widget URL
  tests/e2e/testsLibrary/CodeExecutionTests.ts
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/bug, status/code-review, target/branch
