Repository eclipse-che/che, pull requests merged in 2022-11, with the labels that each got.

#21830 docs: Add a link to the git-srv repository
  CONTRIBUTING.md
Labels: status/code-review, kind/task, target/branch

#21842 Updating typescript-publish.yml
  .github/workflows/typescript-publish.yml
Labels: status/code-review, target/branch

#21843 Fixing initDefaultValues.sh and initDevfileTests.sh scripts
  tests/e2e/initDefaultValues.sh
  tests/e2e/initDevfileTests.sh
Labels: kind/bug, status/code-review, target/branch

#21847 Changing folder names to match EditorType.CHE_CODE
  tests/e2e/tests/devfiles/che-code/EmptyWorkspace.spec.ts
Labels: status/code-review, target/branch

#21839 Make it possible to chose editor when create workspace from Dashboard sample in e2e GUI typescript tests
  tests/e2e/TestConstants.ts
  tests/e2e/pageobjects/dashboard/CreateWorkspace.ts
  tests/e2e/tests/devfiles/theia/JavaMaven.spec.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
  tests/e2e/tslint.json
Labels: status/code-review, target/branch
