Repository eclipse-che/che, pull requests merged in 2022-01, with the labels that each got.

#20988 Fix project tree breaking workspace readiness
  tests/e2e/TimeoutConstants.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/ide/OpenEditors.ts
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/tests/plugins/VscodeValePlugin.spec.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: kind/bug, status/code-review, target/branch

#21012 Fix project tree breaking workspace readiness - 7.42.x cherry-pick
  tests/e2e/TimeoutConstants.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/ide/OpenEditors.ts
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: kind/bug, status/code-review, target/branch

#20989 Fix project tree breaking workspace readiness - main cherry-pick
  tests/e2e/TimeoutConstants.ts
  tests/e2e/inversify.config.ts
  tests/e2e/inversify.types.ts
  tests/e2e/pageobjects/ide/OpenEditors.ts
  tests/e2e/pageobjects/ide/ProjectTree.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: kind/bug, status/code-review, target/branch

#21046 update axios npm version w.r.to "npm audit fix"
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/bug, status/code-review, target/branch

#21048 update axios version based on npm audit
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/enhancement, status/code-review, target/branch

#21047 update axios npm version w.r.to npm audit fix
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/bug, status/code-review, target/branch

#21050 Revert "update axios version based on npm audit (#21048)"
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: status/code-review, target/branch

#21051 Fixed undefined objects error
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/utils/requestHandlers/CheApiRequestHandler.ts
Labels: kind/bug, status/code-review, target/branch

#21053 Hotfix balaji axios update 7.40.x cherry pick
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/utils/requestHandlers/CheApiRequestHandler.ts
Labels: kind/bug, status/code-review, target/branch

#21052 Hotfix balaji axios update 7.42.x cherry pick
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/utils/requestHandlers/CheApiRequestHandler.ts
Labels: kind/bug, status/code-review, target/branch

#21060 Update dex login page details
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/pageobjects/openshift/CheLoginPage.ts
Labels: kind/enhancement, status/code-review, target/branch

#21084 Add data from the responce when breakpoin is not activated
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: status/code-review, kind/task, target/branch
