Repository eclipse-che/che, pull requests merged in 2022-02, with the labels that each got.

#21101 docs: Add che-code repository
  .repositories.yaml
  CONTRIBUTING.md
Labels: status/code-review, target/branch

#21169 Change name of the command for maven build
  tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#21170 Plugin-registry openshift-ci PR check should be adapted to the Dev Workspace engine
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: status/in-progress, kind/task, target/branch, area/qe

#21192 Set yamlSchema in VscodeYamlPlugin test
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
Labels: status/in-progress, severity/P1, target/branch, area/qe

#21202 [Typescript] Check that settings.json content is valid
  tests/e2e/package.json
  tests/e2e/utils/PreferencesHandler.ts
Labels: status/in-progress, kind/task, target/branch, team/che-qe, area/qe

#21204 test: Add workspace readiness function for devworkspace tests
  tests/e2e/tests/plugins/TypescriptPlugin.spec.ts
  tests/e2e/tests/plugins/VscodeYamlPlugin.spec.ts
  tests/e2e/testsLibrary/ProjectAndFileTests.ts
Labels: status/code-review, target/branch, team/che-qe, area/qe
