Repository eclipse-che/che, pull requests merged in 2023-03, with the labels that each got.

#22023 Added getLoaderAlert() method and getAllCreatedWorkspacesNames() into page objects
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/dashboard/Workspaces.ts
Labels: status/code-review, kind/planning, target/branch

#22016 chore: remove unused buildx configuration
  .github/workflows/release.yml
Labels: status/code-review, kind/task, target/branch, kind/release

#22055 Fixed small typos
  tests/performance/README.md
Labels: kind/bug, status/code-review, target/branch

#22056 Fixed error message incorrectly listing available editors on nonexisting `USERSTORY` in initDevFileTests
  tests/e2e/initDevfileTests.sh
Labels: kind/bug, status/code-review, target/branch

#22084 Fix logic for setting the editor
  tests/e2e/configs/sh-scripts/initDevfileTests.sh
Labels: kind/bug, status/code-review, target/branch

#22087 Updated launch.sh and startHappyPathTest()
  tests/devworkspace-happy-path/launch.sh
Labels: kind/enhancement, status/code-review, target/branch

#22085 Implement SmokeTest utilizing Quarkus REST API
  tests/e2e/configs/mocharc.ts
  tests/e2e/package-lock.json
  tests/e2e/pageobjects/dashboard/CreateWorkspace.ts
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/specs/SmokeTest.spec.ts
  tests/e2e/tests-library/WorkspaceHandlingTests.ts
  tests/e2e/utils/CheReporter.ts
  tests/e2e/utils/vsc/GitUtil.ts
Labels: status/code-review, kind/task, target/branch

#22113 fix: lint issues
  tests/e2e/configs/inversify.types.ts
  tests/e2e/constants/TestConstants.ts
  tests/e2e/constants/TimeoutConstants.ts
  tests/e2e/driver/ChromeDriver.ts
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/dashboard/Workspaces.ts
  tests/e2e/pageobjects/dashboard/workspace-details/WorkspaceDetails.ts
  tests/e2e/pageobjects/git-providers/OauthPage.ts
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/pageobjects/login/OcpUserLoginPage.ts
  tests/e2e/pageobjects/login/RedHatLoginPage.ts
  tests/e2e/pageobjects/login/RegularUserOcpCheLoginPage.ts
  tests/e2e/pageobjects/openshift/CheLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
  tests/e2e/specs/MochaHooks.ts
  tests/e2e/specs/SmokeTest.spec.ts
  tests/e2e/specs/devfiles/Quarkus.spec.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/specs/miscellaneous/PredefinedNamespace.spec.ts
  tests/e2e/tslint.json
  tests/e2e/utils/BrowserTabsUtil.ts
  tests/e2e/utils/CheReporter.ts
  tests/e2e/utils/DriverHelper.ts
  tests/e2e/utils/Logger.ts
  tests/e2e/utils/ScreenCatcher.ts
  tests/e2e/utils/request-handlers/headers/CheMultiuserAuthorizationHeaderHandler.ts
  tests/e2e/utils/vsc/GitUtil.ts
  tests/e2e/utils/workspace/ApiUrlResolver.ts
  tests/e2e/utils/workspace/TestWorkspaceUtil.ts
Labels: kind/bug, status/code-review, target/branch
