Repository eclipse-che/che, pull requests merged in 2023-11, with the labels that each got.

#22623 Fix up and update 'Factory' E2E flow components
  tests/e2e/constants/FACTORY_TEST_CONSTANTS.ts
  tests/e2e/pageobjects/git-providers/OauthPage.ts
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/tests-library/ProjectAndFileTests.ts
Labels: status/code-review, kind/task, target/branch

#22662 [Test] Fix lint errors in WebTerminalTest test
  tests/e2e/specs/web-terminal/WebTerminalTest.spec.ts
Labels: kind/bug, status/code-review, target/branch, area/qe

#22663 Fix: 22646, replace hub with gh
  make-release.sh
Labels: status/code-review, kind/task, target/branch, kind/release

#22672 [CRW-5013] Fix up factory E2E test to avoid 'Restricted' mode
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/tests-library/ProjectAndFileTests.ts
Labels: kind/bug, status/code-review, target/branch, area/qe

#22677 Improve and fix problems for running DevFile API tests
  tests/e2e/constants/API_TEST_CONSTANTS.ts
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/utils/DevfilesRegistryHelper.ts
  tests/e2e/utils/KubernetesCommandLineToolsExecutor.ts
Labels: kind/bug, status/code-review, target/branch

#22692 Сhange the setting up for k8s namespaces
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/utils/KubernetesCommandLineToolsExecutor.ts
Labels: status/code-review, target/branch

#22693 Fix and rework PredefinedNamespace test
  tests/e2e/specs/miscellaneous/PredefinedNamespace.spec.ts
Labels: kind/bug, status/code-review, target/branch
