Repository eclipse-che/che, pull requests merged in 2023-04, with the labels that each got.

#22121 Ignore 'undefined' name when obtain workspace name
  tests/e2e/tests-library/WorkspaceHandlingTests.ts
Labels: status/code-review, target/branch

#22123 Merge TS_SELENIUM_USERNAME/PASSOWRD with TS_SELENIUM_OCP_USERNAME/PASSWORD
  tests/e2e/build/dockerfiles/entrypoint.sh
  tests/e2e/configs/sh-scripts/initDefaultValues.sh
  tests/e2e/constants/TestConstants.ts
  tests/e2e/package-lock.json
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/login/RedHatLoginPage.ts
  tests/e2e/specs/miscellaneous/PredefinedNamespace.spec.ts
  tests/e2e/utils/CheReporter.ts
Labels: status/code-review, kind/task, target/branch

#22127 [Test] Estimate time of java project build and run inside Che Code Editor in performance tests
  tests/performance/api-load-tests.sh
  tests/performance/api-pod.yaml
  tests/performance/api-process-logs.sh
  tests/performance/api-tests/api-test-cpp.sh
  tests/performance/api-tests/api-test-lombok.sh
  tests/performance/api-tests/api-test-php.sh
  tests/performance/api-tests/api-test-python.sh
  tests/performance/api-tests/api-test-quarkus.sh
  tests/performance/api-tests/api-utils.sh
Labels: status/code-review, target/branch, area/qe

#22129 CRW-3566: Empty workspace project export API test: added CloneGitRepoAPI.spec.ts, OpenshiftHelper
  tests/e2e/README.md
  tests/e2e/configs/sh-scripts/initDevfileTests.sh
  tests/e2e/constants/TestConstants.ts
  tests/e2e/driver/ChromeDriver.ts
  tests/e2e/index.ts
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/specs/MochaHooks.ts
  tests/e2e/specs/api/CloneGitRepoAPI.spec.ts
  tests/e2e/specs/dashboard-samples/EmptyWorkspace.spec.ts
  tests/e2e/specs/dashboard-samples/Quarkus.spec.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/utils/CheReporter.ts
  tests/e2e/utils/DriverHelper.ts
  tests/e2e/utils/OpenshiftClientExecutor.ts
  tests/e2e/utils/vsc/GitUtil.ts
Labels: status/code-review, target/branch

#22144 Recommended extensions GUI test
  tests/e2e/constants/TimeoutConstants.ts
  tests/e2e/specs/dashboard-samples/RecomendedExtentions.spec.ts
  tests/e2e/tests-library/WorkspaceHandlingTests.ts
Labels: status/code-review, target/branch

#22151 Added new dependency, switched ffmpeg to use libvpx-vp8 instead
  tests/e2e/build/dockerfiles/Dockerfile
  tests/e2e/build/dockerfiles/entrypoint.sh
Labels: kind/enhancement, status/code-review, target/branch

#22152 Add TS_SAMPLE_LIST constant
  tests/e2e/constants/TestConstants.ts
  tests/e2e/specs/dashboard-samples/RecomendedExtentions.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#22168 Add an ability to execute commands on K8s (minikube) using Kubectl
  tests/e2e/constants/TestConstants.ts
  tests/e2e/index.ts
  tests/e2e/specs/api/CloneGitRepoAPI.spec.ts
  tests/e2e/utils/KubernetesCommandLineToolsExecutor.ts
  tests/e2e/utils/OpenshiftClientExecutor.ts
  tests/e2e/utils/ShellExecutor.ts
Labels: kind/enhancement, status/code-review, target/branch

#22174 Fix 'Recommended extensions' test: timeouts and installed extension menu item
  tests/e2e/constants/TimeoutConstants.ts
  tests/e2e/pageobjects/dashboard/Workspaces.ts
  tests/e2e/specs/dashboard-samples/RecomendedExtentions.spec.ts
  tests/e2e/utils/CheReporter.ts
Labels: kind/bug, status/code-review, target/branch

#22178 [Test] Correctly delete workspaces in performance tests
  tests/performance/api-tests/api-test-cpp.sh
  tests/performance/api-tests/api-test-lombok.sh
  tests/performance/api-tests/api-test-php.sh
  tests/performance/api-tests/api-test-python.sh
  tests/performance/api-tests/api-test-quarkus.sh
  tests/performance/api-tests/api-utils.sh
Labels: status/code-review, target/branch, area/qe

#22180 fix: wait dashboard after login
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/login/RedHatLoginPage.ts
  tests/e2e/tests-library/LoginTests.ts
Labels: kind/bug, status/code-review, target/branch
