Repository eclipse-che/che, pull requests merged in 2023-05, with the labels that each got.

#22187 [Test] Correctly patch DevSpaces sample devfiles
  tests/performance/Dockerfile
  tests/performance/README.md
  tests/performance/api-pod.yaml
  tests/performance/api-tests/api-test-cpp.sh
  tests/performance/api-tests/api-test-lombok.sh
  tests/performance/api-tests/api-test-php.sh
  tests/performance/api-tests/api-test-python.sh
  tests/performance/api-tests/api-test-quarkus.sh
  tests/performance/api-tests/api-utils.sh
Labels: status/code-review, target/branch, area/qe

#22189 [Test] Update performance Readme.md file
  tests/performance/README.md
Labels: status/code-review, target/branch, area/qe

#22195 Pod and container overrides via attribute API tests
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/resources/container-overrides.yaml
  tests/e2e/resources/pod-overrides.yaml
  tests/e2e/specs/api/ContainerOverridesAPI.spec.ts
  tests/e2e/specs/api/PodOverridesAPI.spec.ts
  tests/e2e/tests-library/ProjectAndFileTests.ts
  tests/e2e/utils/KubernetesCommandLineToolsExecutor.ts
  tests/e2e/utils/ShellExecutor.ts
Labels: status/code-review, target/branch

#22224 Refactoring CloneGitRepoAPI.spec.ts to work with DevWorkspace generator tool
  tests/e2e/constants/TestConstants.ts
  tests/e2e/specs/api/CloneGitRepoAPI.spec.ts
  tests/e2e/specs/api/DevfileAcceptanceTestAPI.spec.ts
  tests/e2e/specs/api/EmptyWorkspaceAPI.spec.ts
  tests/e2e/utils/DevWorkspaceConfigurationHelper.ts
Labels: status/code-review, kind/task, target/branch

#22255 remove --silent from npm install
  tests/e2e/build/dockerfiles/Dockerfile
Labels: status/code-review, target/branch

#22256 Set che-devworkspace-generator version to 0.0.1-602dcb4
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: status/code-review, target/branch

#22257 Exclude devworkspace-generator from the sed
  make-release.sh
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: status/code-review, target/branch
