Repository eclipse-che/che, pull requests merged in 2023-09, with the labels that each got.

#22466 Standardization of "che" test automation framework classes
  tests/e2e/.eslintrc.js
  tests/e2e/CODE_STYLE.md
  tests/e2e/configs/inversify.config.ts
  tests/e2e/configs/inversify.types.ts
  tests/e2e/constants/CHROME_DRIVER_CONSTANTS.ts
  tests/e2e/driver/ChromeDriver.ts
  tests/e2e/index.ts
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/pageobjects/dashboard/CreateWorkspace.ts
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/dashboard/Workspaces.ts
  tests/e2e/pageobjects/dashboard/workspace-details/WorkspaceDetails.ts
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/pageobjects/login/interfaces/ICheLoginPage.ts
  tests/e2e/pageobjects/login/interfaces/IOcpLoginPage.ts
  tests/e2e/pageobjects/login/kubernetes/DexLoginPage.ts
  tests/e2e/pageobjects/login/openshift/OcpLoginPage.ts
  tests/e2e/pageobjects/login/openshift/OcpRedHatLoginPage.ts
  tests/e2e/pageobjects/login/openshift/OcpUserLoginPage.ts
  tests/e2e/pageobjects/login/openshift/RedHatLoginPage.ts
  tests/e2e/pageobjects/login/openshift/RegularUserOcpCheLoginPage.ts
  tests/e2e/pageobjects/openshift/OcpApplicationPage.ts
  tests/e2e/pageobjects/openshift/OcpImportFromGitPage.ts
  tests/e2e/pageobjects/openshift/OcpMainPage.ts
  tests/e2e/specs/MochaHooks.ts
  tests/e2e/specs/SmokeTest.spec.ts
  tests/e2e/specs/api/ContainerOverridesAPI.spec.ts
  tests/e2e/specs/api/DevfileAcceptanceTestAPI.spec.ts
  tests/e2e/specs/api/EmptyWorkspaceAPI.spec.ts
  tests/e2e/specs/api/PodOverridesAPI.spec.ts
  tests/e2e/specs/dashboard-samples/EmptyWorkspace.spec.ts
  tests/e2e/specs/dashboard-samples/Quarkus.spec.ts
  tests/e2e/specs/dashboard-samples/RecommendedExtensions.spec.ts
  tests/e2e/specs/devconsole-intergration/DevConsoleIntegration.spec.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/specs/miscellaneous/PredefinedNamespace.spec.ts
  tests/e2e/tests-library/LoginTests.ts
  tests/e2e/tests-library/WorkspaceHandlingTests.ts
  tests/e2e/utils/BrowserTabsUtil.ts
  tests/e2e/utils/CheReporter.ts
  tests/e2e/utils/DevWorkspaceConfigurationHelper.ts
  tests/e2e/utils/DevfilesRegistryHelper.ts
  tests/e2e/utils/DriverHelper.ts
  tests/e2e/utils/IContextParams.ts
  tests/e2e/utils/IKubernetesCommandLineToolsExecutor.ts
  tests/e2e/utils/KubernetesCommandLineToolsExecutor.ts
  tests/e2e/utils/ShellExecutor.ts
  tests/e2e/utils/StringUtil.ts
Labels: status/code-review, kind/task, target/branch

#22494 fix: fix DW generator dependency version
  .github/workflows/release.yml
  make-release.sh
Labels: kind/bug, status/code-review, target/branch

#22495 fix incorrect jq synthax during release
  make-release.sh
Labels: kind/bug, status/code-review, target/branch

#22500 chore: remove che-theia as it's...
  .repositories-update-contributing.sh
  .repositories.yaml
  CONTRIBUTING.md
Labels: status/code-review, target/branch

#22504 CRW-582 Added MOCHA_CONSTANTS file to setup mocharc.ts config with ENVs
  tests/e2e/configs/mocharc.ts
  tests/e2e/constants/MOCHA_CONSTANTS.ts
Labels: status/code-review, target/branch

#22503 [Test] Create automated test for "Existing workspace found" scenario
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/constants/TIMEOUT_CONSTANTS.ts
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/specs/miscellaneous/CreateWorkspaceWithExistedName.spec.ts
  tests/e2e/tests-library/WorkspaceHandlingTests.ts
Labels: status/code-review, kind/task, target/branch, area/qe

#22471 Fix project import failures on che-dashboard prcheck
  tests/e2e/constants/MONACO_CONSTANTS.ts
  tests/e2e/pageobjects/dashboard/Workspaces.ts
  tests/e2e/specs/SmokeTest.spec.ts
Labels: kind/bug, status/code-review, target/branch

#22516 Fixed project import logic and dashboard locator
  tests/e2e/pageobjects/dashboard/Workspaces.ts
  tests/e2e/specs/SmokeTest.spec.ts
  tests/e2e/utils/StringUtil.ts
Labels: kind/bug, status/code-review, target/branch

#22506 Create a test for checking a workspace with parent functionality
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/specs/miscellaneous/WorkpaseUsingParent.spec.ts
  tests/e2e/tests-library/ProjectAndFileTests.ts
Labels: status/code-review, target/branch

#22508 change snapshot to next for dev versioning
  .github/workflows/typescript-publish.yml
  VERSION
  make-release.sh
  tests/e2e/package.json
  tests/e2e/specs/miscellaneous/CreateWorkspaceWithExistedName.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#22532 Revert "Fixed project import logic and dashboard locator"
  tests/e2e/pageobjects/dashboard/Workspaces.ts
  tests/e2e/specs/SmokeTest.spec.ts
  tests/e2e/utils/StringUtil.ts
Labels: kind/bug, status/code-review, target/branch

#22514 Fix: timeouts of waiting on extensions complete installation RecommendedExtensions test
  tests/e2e/.eslintrc.js
  tests/e2e/README.md
  tests/e2e/configs/mocharc.ts
  tests/e2e/configs/reporters-config.json
  tests/e2e/constants/PLUGIN_TEST_CONSTANTS.ts
  tests/e2e/constants/TIMEOUT_CONSTANTS.ts
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/specs/MochaHooks.ts
  tests/e2e/specs/dashboard-samples/RecommendedExtensions.spec.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/tests-library/ProjectAndFileTests.ts
  tests/e2e/tests-library/WorkspaceHandlingTests.ts
  tests/e2e/tsconfig.json
  tests/e2e/utils/DriverHelper.ts
Labels: status/code-review, kind/task, target/branch

#22540 Rename WorkpaseUsingParent.spec.ts to WorkspaceWithParent.spec.ts
  tests/e2e/specs/miscellaneous/WorkspaceWithParent.spec.ts
Labels: status/code-review, target/branch

#22544 Refactoring test codebase accordind to recomendations
  tests/e2e/specs/miscellaneous/WorkspaceWithParent.spec.ts
  tests/e2e/tests-library/ProjectAndFileTests.ts
  tests/e2e/utils/ShellExecutor.ts
Labels: status/code-review, target/branch, kind/technical-debt

#22554 Hotfix fix cookie policy approval
  tests/e2e/pageobjects/login/openshift/OcpRedHatLoginPage.ts
  tests/e2e/pageobjects/login/openshift/RedHatLoginPage.ts
Labels: kind/bug, status/code-review, target/branch

#22555 Hotfix fix cookie policy approval
  tests/e2e/pageobjects/login/openshift/OcpRedHatLoginPage.ts
  tests/e2e/pageobjects/login/openshift/RedHatLoginPage.ts
Labels: kind/bug, status/code-review, target/branch

#22559 fix: fix incorrect version in release script
  make-release.sh
Labels: kind/bug, status/code-review, target/branch

#22567 Update make-release.sh to install npm dependencies
  make-release.sh
Labels: kind/enhancement, status/code-review, target/branch

#22566 [Che#22564] Update the alert message
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#22565 CRW-4864 Make 'Check the project files were imported' test in Che test framework not use view section name
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/specs/SmokeTest.spec.ts
  tests/e2e/specs/dashboard-samples/Quarkus.spec.ts
  tests/e2e/specs/dashboard-samples/RecommendedExtensions.spec.ts
  tests/e2e/specs/devconsole-intergration/DevConsoleIntegration.spec.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/specs/miscellaneous/CreateWorkspaceWithExistedName.spec.ts
  tests/e2e/specs/miscellaneous/KubedockPodmanTest.spec.ts
  tests/e2e/specs/miscellaneous/WorkspaceWithParent.spec.ts
  tests/e2e/tests-library/ProjectAndFileTests.ts
Labels: status/code-review, target/branch
