Repository eclipse-che/che, pull requests merged in 2023-01, with the labels that each got.

#21906 Eliminate lint errors; fix build of quay.io/eclipse/che-e2e
  tests/e2e/build/dockerfiles/Dockerfile
  tests/e2e/tslint.json
Labels: status/code-review, kind/task, target/branch

#21874 Update GH actions to use tasks using Node 16
  .github/workflows/contributing-repositories-check.yml
  .github/workflows/next-build.yml
  .github/workflows/release-changelog.yml
  .github/workflows/release.yml
  .github/workflows/typescript-publish.yml
Labels: status/code-review, kind/task, target/branch

#21910 chore: #21763 - bump to latest Adopt JDK...
  .github/workflows/next-build.yml
Labels: status/code-review, kind/task, target/branch

#21918 chore: Allow to configure HappyPath test suite
  tests/devworkspace-happy-path/launch.sh
  tests/devworkspace-happy-path/resources/pod-che-happy-path.yaml
  tests/e2e/mocha-empty-workspace-devworkspace-happy-path-che-code.json
  tests/e2e/package.json
Labels: kind/bug, status/code-review, target/branch, kind/release

#21919 fix: EmtpyWorkspace test path
  tests/e2e/mocha-empty-workspace-devworkspace-happy-path-che-code.json
Labels: kind/bug, status/code-review, target/branch, kind/release

#21920 chore: EmtpyWorkspace test path
  tests/e2e/mocha-empty-workspace-devworkspace-happy-path-che-code.json
Labels: kind/bug, status/code-review, target/branch, kind/release

#21928 Fix workspace obtaining logic main cherry pick
  tests/e2e/driver/CheReporter.ts
  tests/e2e/package-lock.json
  tests/e2e/tests/MochaHooks.ts
  tests/e2e/tests/e2e_happy_path/theia/DevWorkspaceHappyPath.spec.ts
  tests/e2e/tests/e2e_happy_path/theia/HappyPath.spec.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
  tests/e2e/utils/DriverHelper.ts
Labels: kind/bug, status/code-review, target/branch

#21929 Fix workspace obtaining logic 7.58.x cherry pick
  tests/e2e/driver/CheReporter.ts
  tests/e2e/package-lock.json
  tests/e2e/tests/MochaHooks.ts
  tests/e2e/tests/e2e_happy_path/theia/DevWorkspaceHappyPath.spec.ts
  tests/e2e/tests/e2e_happy_path/theia/HappyPath.spec.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
  tests/e2e/tslint.json
  tests/e2e/utils/DriverHelper.ts
Labels: kind/bug, status/code-review, target/branch

#21930 Fix workspace obtaining logic
  tests/e2e/build/dockerfiles/Dockerfile
  tests/e2e/driver/CheReporter.ts
  tests/e2e/package-lock.json
  tests/e2e/pageobjects/ide/theia/OpenEditors.ts
  tests/e2e/tests/MochaHooks.ts
  tests/e2e/tests/devfiles/theia/DotNetCore.spec.ts
  tests/e2e/tests/e2e/theia/FactoryUrl.spec.ts
  tests/e2e/tests/e2e/theia/factories/DirectUrlFactoryWithKeepDirectoryTest.spec.ts
  tests/e2e/tests/e2e/theia/factories/DirectUrlFactoryWithRootFolderTest.spec.ts
  tests/e2e/tests/e2e/theia/factories/DirectUrlFactoryWithSpecificBranchTest.spec.ts
  tests/e2e/tests/e2e_happy_path/theia/DevWorkspaceHappyPath.spec.ts
  tests/e2e/tests/e2e_happy_path/theia/HappyPath.spec.ts
  tests/e2e/testsLibrary/WorkspaceHandlingTests.ts
  tests/e2e/testsLibrary/theia/LanguageServerTestsTheia.ts
  tests/e2e/testsLibrary/theia/ProjectAndFileTestsTheia.ts
  tests/e2e/tslint.json
  tests/e2e/utils/DriverHelper.ts
  tests/e2e/utils/workspace/ApiUrlResolver.ts
  tests/e2e/utils/workspace/ITestWorkspaceUtil.ts
Labels: kind/bug, status/code-review, target/branch

#21946 Fix upstream happy path test execution
  tests/e2e/inversify.config.ts
  tests/e2e/package-lock.json
  tests/e2e/tests/MochaHooks.ts
Labels: kind/bug, status/code-review, target/branch

#21947 Fix upstream happy path test execution 7.58.x cherry pick
  tests/e2e/inversify.config.ts
  tests/e2e/package-lock.json
  tests/e2e/tests/MochaHooks.ts
Labels: kind/bug, status/code-review, target/branch

#21952 Fix upstream happy path test execution 7.59.x cherry pick
  tests/e2e/index.ts
  tests/e2e/inversify.config.ts
  tests/e2e/package-lock.json
  tests/e2e/tests/MochaHooks.ts
Labels: kind/bug, status/code-review, target/branch

#21955 Set buildx version to v0.9.1 in release.yml
  .github/workflows/release.yml
Labels: status/code-review, kind/task, target/branch

#21966 Crw 3902 fix workspace readiness missing timeouts
  tests/e2e/package-lock.json
  tests/e2e/testsLibrary/che-code/ProjectAndFileTestsCheCode.ts
Labels: status/code-review, kind/task, target/branch

#21968 Crw 3902 fix workspace readiness missing timeouts 7.58.x cherry pick
  tests/e2e/package-lock.json
  tests/e2e/testsLibrary/che-code/ProjectAndFileTestsCheCode.ts
Labels: status/code-review, kind/task, target/branch

#21967 Crw 3902 fix workspace readiness missing timeouts 7.60.x cerry-pick
  tests/e2e/package-lock.json
  tests/e2e/testsLibrary/che-code/ProjectAndFileTestsCheCode.ts
Labels: status/code-review, kind/task, target/branch
