Repository eclipse-che/che, pull requests merged in 2023-12, with the labels that each got.

#22713 Add namespace context for exec command in the test
  tests/e2e/specs/miscellaneous/WorkspaceWithParent.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#22720 [Test] Update WebTerminalTest test to work correctly with new `Initialize terminal` changes
  tests/e2e/pageobjects/openshift/OcpMainPage.ts
Labels: status/in-progress, target/branch, area/qe, team/B

#22717 Update the locator of 'workspace current status' according the changes on Dashboard UI
  tests/e2e/pageobjects/dashboard/Workspaces.ts
Labels: status/code-review, kind/task, target/branch

#22724 Fix README links
  .devfile.yaml
  .github/ISSUE_TEMPLATE/a_question.yaml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/task.yaml
  .repositories.yaml
  CONTRIBUTING.md
  README.md
Labels: kind/bug, status/code-review, target/branch

#22734 [Test] Create page object for User Preferences page on Dashboard
  tests/e2e/configs/inversify.config.ts
  tests/e2e/configs/inversify.types.ts
  tests/e2e/pageobjects/dashboard/UserPreferences.ts
  tests/e2e/specs/miscellaneous/UserPreferencesTest.spec.ts
Labels: status/code-review, kind/task, target/branch, area/qe
