Repository eclipse-che/che, pull requests merged in 2023-10, with the labels that each got.

#22526 feat: collect har file on test fail
  tests/e2e/CheReporter.js
  tests/e2e/driver/ChromeDriver.ts
  tests/e2e/report2/The_SmokeTest_userstory_Create_workspace_from_factory-https-++github.com+che-incubator+quarkus-api-example.git_Check_a_project_folder_has_been_created/har-Check_a_project_folder_has_been_created.har
  tests/e2e/utils/CheReporter.ts
Labels: status/code-review, kind/task, target/branch

#22552 [Test] Automate `Workspace stopping by idle timeout` test-case
  tests/e2e/specs/miscellaneous/WorkspaceIdleTimeout.spec.ts
Labels: status/code-review, kind/task, target/branch, area/qe

#22588 Update E2E 'factory' tests according new UI changes
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
Labels: kind/enhancement, status/code-review, target/branch

#22595 fix: redact headers, cookies, url params in har file
  tests/e2e/utils/CheReporter.ts
  tests/e2e/utils/StringUtil.ts
Labels: kind/bug, status/code-review, target/branch

#22602 Fix return type error in 'CheCodeLocatorLoader'
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/specs/miscellaneous/WorkspaceIdleTimeout.spec.ts
Labels: kind/bug, status/code-review, target/branch

#22591 feat: added test suites
  tests/e2e/CODE_STYLE.md
  tests/e2e/configs/inversify.config.ts
  tests/e2e/configs/mocharc.ts
  tests/e2e/configs/sh-scripts/runFunctionalTests.sh
  tests/e2e/constants/API_TEST_CONSTANTS.ts
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/constants/MOCHA_CONSTANTS.ts
  tests/e2e/package.json
  tests/e2e/specs/MochaHooks.ts
  tests/e2e/specs/api/ContainerOverridesAPI.spec.ts
  tests/e2e/specs/api/DevfileAcceptanceTestAPI.spec.ts
  tests/e2e/specs/api/EmptyWorkspaceAPI.spec.ts
  tests/e2e/specs/api/InbuiltApplicationDevWorkspacesAPI.spec.ts
  tests/e2e/specs/api/PodOverridesAPI.spec.ts
  tests/e2e/specs/dashboard-samples/Documentation.spec.ts
  tests/e2e/specs/dashboard-samples/EmptyWorkspace.spec.ts
  tests/e2e/specs/dashboard-samples/Quarkus.spec.ts
  tests/e2e/specs/dashboard-samples/RecommendedExtensions.spec.ts
  tests/e2e/specs/devconsole-intergration/DevConsoleIntegration.spec.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/specs/miscellaneous/CreateWorkspaceWithExistedName.spec.ts
  tests/e2e/specs/miscellaneous/KubedockPodmanTest.spec.ts
  tests/e2e/specs/miscellaneous/PredefinedNamespace.spec.ts
  tests/e2e/specs/miscellaneous/WorkspaceWithParent.spec.ts
  tests/e2e/specs/web-terminal/WebTerminalTest.spec.ts
  tests/e2e/suites/disconnected-ocp/APITest.suite.ts
  tests/e2e/suites/disconnected-ocp/DynamicallyGeneratingAPITest.suite.ts
  tests/e2e/suites/disconnected-ocp/UITest.suite.ts
  tests/e2e/suites/online-ocp/APITest.suite.ts
  tests/e2e/suites/online-ocp/DynamicallyGeneratingAPITest.suite.ts
  tests/e2e/suites/online-ocp/UITest.suite.ts
  tests/e2e/tests-library/LoginTests.ts
  tests/e2e/utils/DevWorkspaceConfigurationHelper.ts
  tests/e2e/utils/DevfilesRegistryHelper.ts
  tests/e2e/utils/IKubernetesCommandLineToolsExecutor.ts
  tests/e2e/utils/KubernetesCommandLineToolsExecutor.ts
Labels: status/code-review, kind/task, target/branch

#22590 Generate E2E typescript test report for ReportPortal
  tests/e2e/configs/mocharc.ts
  tests/e2e/configs/reporters-config.json
  tests/e2e/configs/reporters.config.js
  tests/e2e/configs/sh-scripts/runFunctionalTests.sh
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/constants/MOCHA_CONSTANTS.ts
  tests/e2e/constants/REPORTER_CONSTANTS.ts
  tests/e2e/constants/TIMEOUT_CONSTANTS.ts
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/specs/MochaHooks.ts
  tests/e2e/specs/SmokeTest.spec.ts
  tests/e2e/specs/api/EmptyWorkspaceAPI.spec.ts
  tests/e2e/tests-library/LoginTests.ts
  tests/e2e/tsconfig.json
  tests/e2e/utils/DevWorkspaceConfigurationHelper.ts
  tests/e2e/utils/KubernetesCommandLineToolsExecutor.ts
Labels: status/code-review, kind/task, target/branch

#22624 fix: devfile-acceptance-test-suite command
  tests/e2e/configs/sh-scripts/runDevfileAcceptanceTests.sh
  tests/e2e/package.json
  tests/e2e/specs/api/DevfileAcceptanceTestAPI.spec.ts
  tests/e2e/suites/devfile-acceptance-test-suite/DynamicallyGeneratingAPITest.suite.ts
  tests/e2e/utils/DevfilesRegistryHelper.ts
Labels: kind/bug, status/code-review, target/branch

#22634 feat: added test run url as reporter attribute
  tests/e2e/configs/reporters.config.js
  tests/e2e/constants/REPORTER_CONSTANTS.ts
Labels: status/code-review, kind/task, target/branch

#22636 feat: change Login, Logout, Stop and delete workspace tests to be hooks (suileSetup, suiteTeardown)
  tests/e2e/configs/sh-scripts/runFunctionalTests.sh
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/pageobjects/dashboard/workspace-details/WorkspaceDetails.ts
  tests/e2e/specs/MochaHooks.ts
  tests/e2e/specs/SmokeTest.spec.ts
  tests/e2e/specs/dashboard-samples/Documentation.spec.ts
  tests/e2e/specs/dashboard-samples/EmptyWorkspace.spec.ts
  tests/e2e/specs/dashboard-samples/Quarkus.spec.ts
  tests/e2e/specs/dashboard-samples/RecommendedExtensions.spec.ts
  tests/e2e/specs/devconsole-intergration/DevConsoleIntegration.spec.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/specs/miscellaneous/CreateWorkspaceWithExistedName.spec.ts
  tests/e2e/specs/miscellaneous/KubedockPodmanTest.spec.ts
  tests/e2e/specs/miscellaneous/PredefinedNamespace.spec.ts
  tests/e2e/specs/miscellaneous/WorkspaceIdleTimeout.spec.ts
  tests/e2e/specs/miscellaneous/WorkspaceWithParent.spec.ts
  tests/e2e/suites/disconnected-ocp/UITest.suite.ts
  tests/e2e/suites/online-ocp/UITest.suite.ts
  tests/e2e/tests-library/LoginTests.ts
  tests/e2e/tests-library/WorkspaceHandlingTests.ts
  tests/e2e/utils/BrowserTabsUtil.ts
  tests/e2e/utils/Logger.ts
  tests/e2e/utils/workspace/ITestWorkspaceUtil.ts
Labels: status/code-review, kind/task, target/branch
