Repository eclipse-che/che, pull requests merged in 2023-02, with the labels that each got.

#21996 Mask sensitive test data in DriverHelper.ts
  tests/e2e/pageobjects/openshift/OcpLoginPage.ts
  tests/e2e/utils/DriverHelper.ts
Labels: status/code-review, target/branch

#22019 Fixing error message if editor variable not set
  tests/e2e/initDevfileTests.sh
Labels: kind/bug, status/code-review, target/branch

#22020 Added getLoaderAlert() method and getAllCreatedWorkspacesNames() into page objects.
  tests/e2e/pageobjects/dashboard/Dashboard.ts
  tests/e2e/pageobjects/dashboard/Workspaces.ts
Labels: status/code-review, kind/planning, target/branch
