Repository eclipse-che/che, pull requests merged in 2024-02, with the labels that each got.

#22815 [Test] Dev Spaces load tests based on `kubect apply`
  tests/performance/load-tests/README.md
  tests/performance/load-tests/load-test.sh
Labels: status/code-review, kind/task, sprint/current, target/branch, area/qe

#22824 Update 'login' method in 'OcpUserLoginPage' class
  tests/e2e/pageobjects/login/openshift/OcpUserLoginPage.ts
Labels: status/code-review, kind/task, target/branch

#22829 [Test] Update RevokeOauth test to work correctly with github service status after revoking
  tests/e2e/pageobjects/dashboard/UserPreferences.ts
Labels: status/code-review, kind/task, target/branch, area/qe

#22855 [Test] Use local devfile.yaml for workspace creation in load-test script
  tests/performance/load-tests/devfile.yaml
  tests/performance/load-tests/load-test.sh
Labels: status/code-review, kind/task, area/qe

#22857 Increase kubectl wait timeout to 360 in load-test
  tests/performance/load-tests/load-test.sh
Labels: status/code-review, kind/task, area/qe
