Repository eclipse-che/che, pull requests merged in 2024-03, with the labels that each got.

#22282 Devtools week che dogfooding test development
  .che/che-editor.yaml
  .devfile.yaml
Labels: status/code-review, kind/task, target/branch

#22860 [Test] Update load-tests script
  tests/performance/load-tests/README.md
  tests/performance/load-tests/devworkspace.yaml
  tests/performance/load-tests/load-test.sh
Labels: status/code-review, kind/task, area/qe

#22861 Fix up E2E tests related to factory test flow
  tests/e2e/configs/mocharc.ts
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/specs/MochaHooks.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/utils/DevWorkspaceConfigurationHelper.ts
Labels: status/code-review, area/qe, team/A

#22874 [Test] Fix logs folder not found error in load-tests script
  tests/performance/load-tests/load-test.sh
Labels: status/code-review, kind/task, area/qe

#22885 [Test] Check existed buttons in `Your workspace stopped by timeout` dialog
  tests/e2e/specs/miscellaneous/WorkspaceIdleTimeout.spec.ts
Labels: status/code-review, kind/task, area/qe

#22888 [Test] Save events from failed workspaces in load-tests script
  tests/performance/load-tests/load-test.sh
Labels: status/code-review, kind/task, area/qe

#22890 [Test] Add argument that allows to use downloaded devworkspace file load-tests script
  tests/performance/load-tests/README.md
  tests/performance/load-tests/example.yaml
  tests/performance/load-tests/load-test.sh
Labels: status/code-review, kind/task, area/qe

#22893 [Test] Get workspace starting time in threads in load-tests script, simplify devworkspace yaml
  tests/performance/load-tests/example.yaml
  tests/performance/load-tests/load-test.sh
Labels: status/code-review, e2e-test/failure, area/qe
