Repository eclipse-che/che, pull requests merged in 2024-01, with the labels that each got.

#22748 Rewrite test userstory for WTO under admin
  tests/e2e/configs/inversify.config.ts
  tests/e2e/configs/inversify.types.ts
  tests/e2e/constants/REPORTER_CONSTANTS.ts
  tests/e2e/index.ts
  tests/e2e/pageobjects/openshift/OcpMainPage.ts
  tests/e2e/pageobjects/webterminal/WebTerminalPage.ts
  tests/e2e/specs/web-terminal/WebTerminalTest.spec.ts
  tests/e2e/specs/web-terminal/WebTerminalUnderAdmin.spec.ts
Labels: status/code-review, target/branch

#22754 update chrome driver to v.120.0
  tests/e2e/build/dockerfiles/Dockerfile
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: kind/enhancement, status/code-review, target/branch

#22761 Fix Java sample titles/paths in tests; fix Documentation test
  tests/e2e/constants/PLUGIN_TEST_CONSTANTS.ts
  tests/e2e/specs/dashboard-samples/Documentation.spec.ts
  tests/e2e/specs/dashboard-samples/Quarkus.spec.ts
  tests/performance/api-tests/api-test-lombok.sh
  tests/performance/api-tests/api-test-quarkus.sh
Labels: kind/bug, status/code-review, target/branch

#22770 fix: remove unsupported theia badge
  README.md
Labels: kind/bug, status/code-review, target/branch

#22779 chore: remove Nick and Tibor as code owners;...
  .github/CODEOWNERS
Labels: status/code-review, target/branch

#22795 Fix WorkspaceWithParent test
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/specs/miscellaneous/WorkspaceWithParent.spec.ts
Labels: kind/bug, status/code-review, target/branch
