Repository eclipse-che/che, pull requests merged in 2025-02, with the labels that each got.

#23341 [Test] Add "Trust Author popup" checking to WorkspaceWithParent e2e test
  tests/e2e/specs/miscellaneous/WorkspaceWithParent.spec.ts
Labels: status/code-review, area/qe

#23336 [Test] Update 'Factory' E2E test
  tests/e2e/constants/BASE_TEST_CONSTANTS.ts
  tests/e2e/specs/factory/Factory.spec.ts
Labels: area/qe

#23349 [Test] Add "Trust Author popup" checking to factories e2e tests
  tests/e2e/specs/devconsole-intergration/DevConsoleIntegration.spec.ts
  tests/e2e/specs/factory/FactoryWithGitRepoOptions.spec.ts
  tests/e2e/specs/miscellaneous/CreateWorkspaceWithExistedName.spec.ts
Labels: status/code-review, area/qe

#23360 [Test] fix: click workspaces button in WorkspaceIdleTimeout E2E typescript test
  tests/e2e/specs/miscellaneous/WorkspaceIdleTimeout.spec.ts
Labels: area/qe

#23361 [Test] Add 'Restricted Mode' button handler to switch on 'Trust Mode' in IDE in E2E tests
  tests/e2e/CODE_STYLE.md
  tests/e2e/README.md
  tests/e2e/configs/inversify.config.ts
  tests/e2e/configs/inversify.types.ts
  tests/e2e/index.ts
  tests/e2e/pageobjects/ide/CheCodeLocatorLoader.ts
  tests/e2e/pageobjects/ide/RestrictedModeButton.ts
  tests/e2e/specs/dashboard-samples/RecommendedExtensions.spec.ts
  tests/e2e/specs/factory/Factory.spec.ts
  tests/e2e/specs/factory/NoSetupRepoFactory.spec.ts
  tests/e2e/specs/factory/RefusedOAuthFactory.spec.ts
  tests/e2e/tests-library/ProjectAndFileTests.ts
Labels: area/qe, team/A, team/B
